
CREATE VIEW VW_D_ForeCast_Sales
AS

WITH CTE_SKU (FACILITY_ID_IFS, GEN_PART_NO, ITEM_NAME, DATE) AS (
SELECT
	Z.FACILITY_ID_IFS
	, Z.GEN_PART_NO
	, CASE WHEN D.ITEM_NAME IS NULL THEN Z.GEN_PART_NO ELSE D.ITEM_NAME END AS ITEM_NAME
	, Z.DATE
FROM (
	SELECT
		X.FACILITY_ID_IFS
		, X.GEN_PART_NO
		, MAX(X.DATE) AS DATE
	FROM (
		SELECT
			OL.FACILITY_ID_IFS
			, OL.FACILITY_ID_WMS
			, CASE 
				WHEN LEFT(IC.ITEM_NAME, 3)='LFD'  THEN 'Label'
				WHEN LEFT(IC.ITEM_NAME, 3)='PDF'  THEN 'PDF'
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,6)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,6)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,5)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,5)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,4)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,4)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,3)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,3)  
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,5)) = 1 THEN RIGHT(IC.ITEM_NAME,5)
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,4)) = 1 THEN RIGHT(IC.ITEM_NAME,4)
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,3)) = 1 THEN RIGHT(IC.ITEM_NAME,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,4),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,4),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,8),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,8),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,3)
				ELSE IC.ITEM_NAME
			END AS  GEN_PART_NO
			, IC.ITEM_NAME
			, MAX(OD.CREATED_DTTM) AS DATE
		FROM		MANH.ORDERS AS OD
		INNER JOIN	dbo.VW_T_LPN AS LP
		ON			LP.ORDER_ID = OD.ORDER_ID
		AND			LP.ActInd = 'Y'
		INNER JOIN	MANH.LPN_DETAIL AS LD
		ON			LD.LPN_ID = LP.LPN_ID
		AND			LD.ActInd = 'Y'
		INNER JOIN	FORECAST.Office_Facility AS OL
		ON			OL.FACILITY_ID_WMS = OD.BILL_FACILITY_ALIAS_ID
		AND			OL.ActInd = 'Y'
		INNER JOIN	MANH.ITEM_CBO IC
		ON			IC.ITEM_ID = LD.ITEM_ID
		AND			IC.ActInd = 'Y'
		WHERE		OD.ActInd = 'Y'
		AND			OD.BILL_FACILITY_ALIAS_ID IS NOT NULL
		GROUP BY
			OL.FACILITY_ID_IFS
			, OL.FACILITY_ID_WMS
			, CASE 
				WHEN LEFT(IC.ITEM_NAME, 3)='LFD'  THEN 'Label'
				WHEN LEFT(IC.ITEM_NAME, 3)='PDF'  THEN 'PDF'
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,6)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,6)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,5)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,5)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,4)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,4)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,3)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,3)  
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,5)) = 1 THEN RIGHT(IC.ITEM_NAME,5)
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,4)) = 1 THEN RIGHT(IC.ITEM_NAME,4)
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,3)) = 1 THEN RIGHT(IC.ITEM_NAME,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,4),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,4),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,8),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,8),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,3)
				ELSE IC.ITEM_NAME
			END
			, IC.ITEM_NAME
	) X
	GROUP BY
		X.FACILITY_ID_IFS
		, X.GEN_PART_NO
) Z
LEFT JOIN (SELECT
			OL.FACILITY_ID_IFS
			, OL.FACILITY_ID_WMS
			, CASE 
				WHEN LEFT(IC.ITEM_NAME, 3)='LFD'  THEN 'Label'
				WHEN LEFT(IC.ITEM_NAME, 3)='PDF'  THEN 'PDF'
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,6)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,6)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,5)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,5)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,4)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,4)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,3)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,3)  
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,5)) = 1 THEN RIGHT(IC.ITEM_NAME,5)
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,4)) = 1 THEN RIGHT(IC.ITEM_NAME,4)
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,3)) = 1 THEN RIGHT(IC.ITEM_NAME,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,4),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,4),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,8),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,8),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,3)
				ELSE IC.ITEM_NAME
			END AS  GEN_PART_NO
			, IC.ITEM_NAME
			, MAX(OD.CREATED_DTTM) AS DATE
		FROM		MANH.ORDERS AS OD
		INNER JOIN	dbo.VW_T_LPN AS LP
		ON			LP.ORDER_ID = OD.ORDER_ID
		AND			LP.ActInd = 'Y'
		INNER JOIN	MANH.LPN_DETAIL AS LD
		ON			LD.LPN_ID = LP.LPN_ID
		AND			LD.ActInd = 'Y'
		INNER JOIN	FORECAST.Office_Facility AS OL
		ON			OL.FACILITY_ID_WMS = OD.BILL_FACILITY_ALIAS_ID
		AND			OL.ActInd = 'Y'
		INNER JOIN	MANH.ITEM_CBO IC
		ON			IC.ITEM_ID = LD.ITEM_ID
		AND			IC.ActInd = 'Y'
		WHERE		OD.ActInd = 'Y'
		AND			OD.BILL_FACILITY_ALIAS_ID IS NOT NULL
		GROUP BY
			OL.FACILITY_ID_IFS
			, OL.FACILITY_ID_WMS
			, CASE 
				WHEN LEFT(IC.ITEM_NAME, 3)='LFD'  THEN 'Label'
				WHEN LEFT(IC.ITEM_NAME, 3)='PDF'  THEN 'PDF'
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,6)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,6)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,5)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,5)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,4)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,4)
				WHEN IsNumeric(SUBSTRING(IC.ITEM_NAME,1,3)) = 1 THEN SUBSTRING(IC.ITEM_NAME,1,3)  
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,5)) = 1 THEN RIGHT(IC.ITEM_NAME,5)
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,4)) = 1 THEN RIGHT(IC.ITEM_NAME,4)
				WHEN IsNUmeric(RIGHT(IC.ITEM_NAME,3)) = 1 THEN RIGHT(IC.ITEM_NAME,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,4),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,4),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,5),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,6),1,3)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,8),1,4)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,8),1,4)
				WHEN IsNUmeric(SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,3)) =1 THEN SUBSTRING(RIGHT(IC.ITEM_NAME,7),1,3)
				ELSE IC.ITEM_NAME
			END
			, IC.ITEM_NAME
) AS D
ON Z.FACILITY_ID_IFS = D.FACILITY_ID_IFS
AND Z.GEN_PART_NO = D.GEN_PART_NO
AND Z.DATE = D.DATE
)

SELECT DISTINCT
	OL.FACILITY_ID_IFS		AS ForeCast_Sales_Customer
	, OL.OFFICE_CODE		AS ForeCast_Sales_Office
	, RS.PROCESSYEAR		AS ForeCast_Sales_Year
	, RS.PROCESSMONTH		AS ForeCast_Sales_Month
	, CASE 
		WHEN CS.ITEM_NAME IS NULL 
		THEN RS.PRODUCTNUM 
		ELSE CASE 
				WHEN CS.ITEM_NAME = '015SAK-BK' THEN '015UK'
				WHEN CS.ITEM_NAME = '034SAK-BK' THEN '034UK'
				WHEN CS.ITEM_NAME = '077SAK-BK' THEN '077UK'
				WHEN CS.ITEM_NAME = '196SAK-BK' THEN '196UK'
				ELSE CS.ITEM_NAME
			END 
	END AS ForeCast_Sales_Part_No
	, RS.PRODUCTNUM			AS ForeCast_Sales_Gen_Part_No
	, RS.Quantity			AS ForeCast_Sales_Eaches
FROM		FORECAST.Realize_Sales AS RS
INNER JOIN	FORECAST.Office_Facility AS OL
ON			OL.OFFICE_CODE = RS.OFFICE_CODE
AND			OL.ActInd = 'Y'
AND			OL.FACILITY_ID_IFS <> '0'
AND			OL.FACILITY_ID_WMS IS NOT NULL
LEFT JOIN	CTE_SKU AS CS
ON			CS.FACILITY_ID_IFS = OL.FACILITY_ID_IFS
AND			CS.GEN_PART_NO = RS.PRODUCTNUM
WHERE		RS.ActInd = 'Y'