
CREATE VIEW VW_ODS_Parcel
AS

SELECT * FROM (
SELECT
	OD.TC_ORDER_ID						AS ParcelOrderID
	, LP.TC_LPN_ID						AS ParcelLPNID
	, CAST(FD.FORWARDER_SHIPMENT_REF AS NVARCHAR(50)) AS ParcelLPNTrackingCode	
	, REPLACE(TU.TransporterURL_Link,'portal.foreverdirect.local','portal.foreverdirect.eu') + FD.FORWARDER_SHIPMENT_REF
			+ CASE WHEN TU.TransporterURL_Link2 IS NOT NULL THEN TU.TransporterURL_Link2 ELSE '' END 
			+ CASE
				-- Strip B- or L- from zipcode and and country code for NL03
				WHEN TU.TransporterURL_Zipcode = 1 AND OD.DSG_SHIP_VIA = 'NL03' AND LEN(OD.D_POSTAL_CODE) > 4 AND SUBSTRING(OD.D_POSTAL_CODE,1,1) = 'L' THEN N'-LU-' + SUBSTRING(OD.D_POSTAL_CODE,3,4)
				WHEN TU.TransporterURL_Zipcode = 1 AND OD.DSG_SHIP_VIA = 'NL03' AND LEN(OD.D_POSTAL_CODE) > 4 AND SUBSTRING(OD.D_POSTAL_CODE,1,1) = 'B' THEN N'-BE-' + SUBSTRING(OD.D_POSTAL_CODE,3,4)
				WHEN TU.TransporterURL_Zipcode = 1 AND OD.DSG_SHIP_VIA = 'NL12' AND LEN(OD.D_POSTAL_CODE) > 4 THEN SUBSTRING(OD.D_POSTAL_CODE,3,4)
				WHEN TU.TransporterURL_Zipcode = 1 AND OD.DSG_SHIP_VIA = 'NL13' AND LEN(OT.NOTE) > 1 THEN SUBSTRING(SUBSTRING(SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1),CHARINDEX(';',SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1))+1,LEN(SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1))+1),0,CHARINDEX(';',SUBSTRING(SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1),CHARINDEX(';',SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1))+1,LEN(SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1))+1)))
				WHEN TU.TransporterURL_Zipcode = 1 AND OD.DSG_SHIP_VIA = 'NL14' AND LEN(OD.D_POSTAL_CODE) > 4 AND DW.REF_FIELD_2 LIKE 'PNP%' THEN SUBSTRING(SUBSTRING(SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1),CHARINDEX(';',SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1))+3,LEN(SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1))+1),1,CHARINDEX(';',SUBSTRING(SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1),CHARINDEX(';',SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1))+3,LEN(SUBSTRING(OT.NOTE,CHARINDEX(';',OT.NOTE)+1,LEN(OT.NOTE)+1))+1))-1)
				WHEN TU.TransporterURL_Zipcode = 1 AND OD.DSG_SHIP_VIA = 'NL14' AND LEN(OD.D_POSTAL_CODE) > 4 THEN SUBSTRING(OD.D_POSTAL_CODE,3,4) 
				WHEN TU.TransporterURL_Zipcode = 1 AND OD.DSG_SHIP_VIA = 'NL15' AND LEN(OD.D_POSTAL_CODE) > 4 THEN SUBSTRING(OD.D_POSTAL_CODE,3,4)
				WHEN TU.TransporterURL_Zipcode = 1 THEN OD.D_POSTAL_CODE
				ELSE '' 
			END							AS ParcelLPNTrackingLink
	, LP.WEIGHT							AS ParcelLPNWeight
	, LP.ESTIMATED_WEIGHT				AS ParcelLPNEstimatedWeight
	, LP.ESTIMATED_VOLUME/1000			AS ParcelLPNVolume
	, LP.TOTAL_LPN_QTY					AS ParcelLPNQuantity
	, CASE 
		WHEN CO.CODE_DESC IS NULL 
		THEN LP.CONTAINER_SIZE
		ELSE CO.CODE_DESC
	END									AS ParcelLPNBoxSize
	, P2.PLT_ID							AS ParcelLPNPalletID
	, FA.FACILITY_ALIAS_ID				AS ParcelFacilityCode
	, ROW_NUMBER() OVER (PARTITION BY LP.TC_LPN_ID ORDER BY LP.CREATED_DTTM DESC) AS RN
FROM		MANH.ORDERS OD
INNER JOIN	MANH.DO_WMPROCESSINFO DW
ON			DW.ORDER_ID = OD.ORDER_ID
AND			DW.ActInd = 'Y'
LEFT JOIN	MANH.ORDER_NOTE OT
ON			OT.ORDER_ID = OD.ORDER_ID
AND			OT.ActInd = 'Y'
AND			OT.NOTE_TYPE = 'FD'
INNER JOIN	MANH.LPN_OUTBOUND LP
ON			LP.ORDER_ID = OD.ORDER_ID
AND			LP.ActInd = 'Y'
AND			LP.LPN_FACILITY_STATUS < 99
INNER JOIN	MANH.FACILITY_ALIAS AS FA 
ON			FA.FACILITY_ALIAS_ID = OD.BILL_FACILITY_ALIAS_ID 
AND			FA.ActInd = 'Y'
LEFT JOIN	WEB.TransporterURL AS TU 
ON			TU.TransporterURL_ShipVia = CASE WHEN OD.DSG_SHIP_VIA = 'NL14' AND DW.REF_FIELD_2 LIKE 'LD-01%' THEN 'NL14K' ELSE OD.DSG_SHIP_VIA END --Exception NL14 can be postnl or kariboo
AND			TU.ActInd = 'Y'
LEFT JOIN	MANH.SYS_CODE CO 
ON			CO.CODE_ID = ISNULL(LP.CONTAINER_SIZE, '000') 
AND			CO.REC_TYPE = 'C' 
AND			CO.CODE_TYPE = 'STU' 
AND			CO.ActInd = 'Y'
LEFT JOIN(
			SELECT
				MAX(P1.PROD_TRKG_TRAN_ID) AS PROD_TRKG_TRAN_ID
				, P1.CNTR_NBR
            FROM		MANH.PROD_TRKG_TRAN AS P1
            WHERE		P1.MENU_OPTN_NAME IN (N'RF Anchor oLPN Pltz', 'Pltz oLPN', 'PackCD', 'RF QA incomplete', 'Pack Cubed Directed', 'Weigh and Manifest oLPN', 'Pck Cubed Dir CP Conveyable', 'TASK Pck Cubed Dir Bulk Repl') -- Some parcels are palletized Pltz oLPN
			AND			P1.FROM_LOCN IS NULL
            GROUP BY	P1.CNTR_NBR
) AS PT		ON PT.CNTR_NBR = LP.TC_LPN_ID 
LEFT JOIN	MANH.PROD_TRKG_TRAN AS P2 
ON			P2.CNTR_NBR = PT.CNTR_NBR
AND			P2.PROD_TRKG_TRAN_ID = PT.PROD_TRKG_TRAN_ID
LEFT JOIN (
	SELECT
		SHIPPER_SHIPMENT_REF
		, MAX(STATUS_DATE_DL) AS STATUS_DATE_DL
		, MAX(STATUS_DATE_IN) AS STATUS_DATE_IN
		, MAX(STATUS_DATE_SH) AS STATUS_DATE_SH
		, MAX(STATUS_DATE_AT) AS STATUS_DATE_AT
		, MAX(FORWARDER_SHIPMENT_REF) AS FORWARDER_SHIPMENT_REF 
	FROM (
	SELECT	  
		'TPX5' AS SORT
		, F1.SHIPPER_SHIPMENT_REF
		, MAX(CASE WHEN F1.STATUS_CATEGORY = 'DELIVERED' THEN F1.STATUS_DATE  END) AS STATUS_DATE_DL
		, MAX(CASE WHEN F1.STATUS_CATEGORY = 'INTRANSIT' THEN F1.STATUS_DATE END) AS STATUS_DATE_IN
		, MAX(CASE WHEN F1.STATUS_CATEGORY = 'SHIP_CONFIRM' THEN F1.STATUS_DATE END) AS STATUS_DATE_SH
		, MAX(CASE WHEN F1.STATUS_CATEGORY = 'ATTEMPT' THEN F1.STATUS_DATE END) AS STATUS_DATE_AT
		, MAX(F1.FORWARDER_SHIPMENT_REF) AS FORWARDER_SHIPMENT_REF 
	FROM TRANS.FORWARDER_STATUS AS F1
	GROUP BY F1.SHIPPER_SHIPMENT_REF

	UNION ALL

	SELECT	  
		'TPX7' AS SORT
		, F1.SHIPPER_SHIPMENT_REF
		, MAX(CASE WHEN F1.SHIPMENT_STATUS = 'DELIVERED' THEN F1.SHIPMENT_EVENT_TS  END) AS STATUS_DATE_DL
		, MAX(CASE WHEN F1.SHIPMENT_STATUS = 'INTRANSIT' THEN F1.SHIPMENT_EVENT_TS END) AS STATUS_DATE_IN
		, MAX(CASE WHEN F1.SHIPMENT_STATUS = 'SHIP_CONFIRM' THEN F1.SHIPMENT_EVENT_TS END) AS STATUS_DATE_SH
		, MAX(CASE WHEN F1.SHIPMENT_STATUS = 'ATTEMPT' THEN F1.SHIPMENT_EVENT_TS END) AS STATUS_DATE_AT
		, MAX(F2.FORWARDER_REFERENCE) AS FORWARDER_SHIPMENT_REF 
	FROM TPX7.VW_FORWARDER_STATUS AS F1
	LEFT JOIN TPX7.VW_SHIPMENT F2 ON F2.SHIPMENT_ID = F1.SHIPMENT_ID
	GROUP BY F1.SHIPPER_SHIPMENT_REF
) X
GROUP BY
  SHIPPER_SHIPMENT_REF
		  ) AS FD 
ON			FD.SHIPPER_SHIPMENT_REF = LP.TC_LPN_ID
WHERE		OD.ActInd = 'Y'
AND			OD.Eff_Date >= GETDATE()-365
) A WHERE A.RN = 1