
CREATE VIEW VW_ODS_Facility
AS

SELECT
  FA.FACILITY_ALIAS_ID			AS Facility_ID
  , FA.FACILITY_NAME			AS Facility_Name
  , RTRIM(SUBSTRING(SC.MISC_FLAGS,11,30)) AS Facility_Country
FROM			MANH.FACILITY_ALIAS FA
INNER JOIN		MANH.SYS_CODE SC
ON				SC.CODE_ID = FA.FACILITY_ALIAS_ID
AND				SC.CODE_TYPE = 'Z04'
AND				SC.REC_TYPE = 'C'
AND				SC.ActInd = 'Y'
WHERE			FA.ActInd = 'Y'