
CREATE VIEW VW_ODS_Order
AS


SELECT
	OD.TC_ORDER_ID					AS OrderID
	, LP.TC_SHIPMENT_ID				AS OrderShipmentID
	--, TS.dosvlg						AS OrderDossierID
	, FA.FACILITY_ALIAS_ID			AS OrderFacilityCode
	, CASE WHEN OD.EXT_PURCHASE_ORDER IS NULL THEN OD.TC_ORDER_ID ELSE OD.EXT_PURCHASE_ORDER END AS OrderPosNumber
	, OD.CREATED_DTTM				AS OrderCreateDate
	, OD.ORDER_TYPE					AS OrderType 
	, OD.D_NAME						AS CustomerName
	, OD.D_ADDRESS_1				AS CustomerAddress1
	, OD.D_ADDRESS_2				AS CustomerAddress2
	, OD.D_CITY						AS CustomerCity
	, OD.D_COUNTRY_CODE				AS CustomerCountryCode
	, OD.D_POSTAL_CODE				AS CustomerPostalCode
	, OD.D_STATE_PROV				AS CustomerState
	, LP.Number_Of_Parcels			AS StatisticNumberOfParcels
FROM		MANH.ORDERS OD
INNER JOIN	MANH.SHIP_VIA AS SV 
ON			SV.SHIP_VIA = OD.DSG_SHIP_VIA 
AND			SV.ActInd = 'Y' 
INNER JOIN	MANH.CARRIER_CODE AS CC 
ON			CC.CARRIER_ID = SV.CARRIER_ID 
AND			CC.ActInd = 'Y' 
INNER JOIN	MANH.SYS_CODE AS S1 
ON			S1.CODE_ID = OD.DO_STATUS 
AND			S1.CODE_TYPE = '501' 
AND			S1.REC_TYPE = 'S' 
AND			S1.ActInd = 'Y' 
INNER JOIN	MANH.FACILITY_ALIAS AS FA 
ON			FA.FACILITY_ALIAS_ID = OD.BILL_FACILITY_ALIAS_ID 
AND			FA.ActInd = 'Y'
INNER JOIN  (
			SELECT	  
				LP.TC_ORDER_ID				AS TC_ORDER_ID
				, MAX(LP.TC_SHIPMENT_ID)	AS TC_SHIPMENT_ID
				,COUNT(1)					AS Number_Of_Parcels
			FROM	 MANH.LPN_OUTBOUND AS LP
			WHERE	 ActInd = 'Y'
			AND		 LPN_FACILITY_STATUS <> 99
			GROUP BY 
				TC_ORDER_ID
			) LP
ON			OD.TC_ORDER_ID = LP.TC_ORDER_ID
/*
LEFT JOIN	DWH.KEWILL.tsdsmd TS
ON			TS.ActInd = 'Y'
AND			TS.afd = 'outb'
AND			
			(
				(TS.ref01 = 'OF' + SUBSTRING(LP.TC_SHIPMENT_ID,1,8) OR TS.ref01 = 'BK' + SUBSTRING(LP.TC_SHIPMENT_ID,1,8)) AND	TS.ref02 = SUBSTRING(LP.TC_SHIPMENT_ID,9,2) 
				OR
				(TS.ref01 = 'BK' + SUBSTRING(OD.TC_ORDER_ID,1,8) AND TS.ref02 = SUBSTRING(OD.TC_ORDER_ID,9,1) )			
			)
*/
WHERE		OD.ActInd = 'Y'
AND			OD.Eff_Date >= GETDATE()-365