
CREATE VIEW VW_ODS_ParcelDetail
AS

SELECT 
  LP.TC_LPN_ID						AS ParcelDetailLPNID
  , LD.LPN_DETAIL_ID				AS ParcelDetailLPNDetailId
  , LD.ITEM_ID						AS ParcelDetailItemID
  , LD.BATCH_NBR					AS ParcelDetailLotID
  , LD.SIZE_VALUE					AS ParcelDetailQuantity
  , OL.CUSTOMER_ITEM				AS ParcelDetailItemName
  , OL.DESCRIPTION					AS ParcelDetailItemDescription
FROM			MANH.ORDERS OD
INNER JOIN		MANH.LPN_OUTBOUND AS LP 
ON				LP.ORDER_ID = OD.ORDER_ID
AND				LP.LPN_FACILITY_STATUS <> 99
AND				LP.ActInd = 'Y'
INNER JOIN		MANH.ORDER_LINE_ITEM OL 
ON				OL.ORDER_ID = OD.ORDER_ID
AND				OL.ActInd = 'Y'
INNER JOIN		MANH.ALLOC_INVN_DTL AI 
ON				AI.LINE_ITEM_ID = OL.LINE_ITEM_ID 
AND				AI.CARTON_NBR = LP.TC_LPN_ID
AND				AI.STAT_CODE < 99
AND				AI.ActInd = 'Y'
INNER JOIN		MANH.LPN_DETAIL	AS LD
ON				LD.LPN_ID = LP.LPN_ID 
AND				LD.LPN_DETAIL_ID = AI.CARTON_SEQ_NBR
AND				LD.ActInd = 'Y'
WHERE			OD.ActInd = 'Y'
AND				OD.Eff_Date >= GETDATE()-365
GROUP BY
LP.TC_LPN_ID
  , LD.LPN_DETAIL_ID
  , LD.ITEM_ID
  , LD.BATCH_NBR
  , LD.SIZE_VALUE
  , OL.CUSTOMER_ITEM
  , OL.DESCRIPTION