CREATE TABLE [MANH].[PIX_TRAN] (
    [TRAN_TYPE]              NVARCHAR (3)    NOT NULL,
    [TRAN_CODE]              NVARCHAR (3)    NOT NULL,
    [TRAN_NBR]               INT             NOT NULL,
    [PIX_SEQ_NBR]            INT             NOT NULL,
    [PROC_STAT_CODE]         SMALLINT        NOT NULL,
    [WHSE]                   NVARCHAR (3)    NULL,
    [CASE_NBR]               NVARCHAR (50)   NULL,
    [SEASON]                 NVARCHAR (16)   NULL,
    [SEASON_YR]              NVARCHAR (4)    NULL,
    [STYLE]                  NVARCHAR (50)   NULL,
    [STYLE_SFX]              NVARCHAR (8)    NULL,
    [COLOR]                  NVARCHAR (50)   NULL,
    [COLOR_SFX]              NVARCHAR (8)    NULL,
    [SEC_DIM]                NVARCHAR (50)   NULL,
    [QUAL]                   NVARCHAR (1)    NULL,
    [SIZE_DESC]              NVARCHAR (50)   NULL,
    [SIZE_RANGE_CODE]        NVARCHAR (50)   NULL,
    [SIZE_REL_POSN_IN_TABLE] NVARCHAR (2)    NULL,
    [INVN_TYPE]              NVARCHAR (1)    NULL,
    [PROD_STAT]              NVARCHAR (3)    NULL,
    [BATCH_NBR]              NVARCHAR (15)   NULL,
    [SKU_ATTR_1]             NVARCHAR (10)   NULL,
    [SKU_ATTR_2]             NVARCHAR (10)   NULL,
    [SKU_ATTR_3]             NVARCHAR (10)   NULL,
    [SKU_ATTR_4]             NVARCHAR (10)   NULL,
    [SKU_ATTR_5]             NVARCHAR (10)   NULL,
    [CNTRY_OF_ORGN]          NVARCHAR (4)    NULL,
    [INVN_ADJMT_QTY]         NUMERIC (13, 5) NOT NULL,
    [INVN_ADJMT_TYPE]        NVARCHAR (1)    NULL,
    [WT_ADJMT_QTY]           NUMERIC (13, 5) NOT NULL,
    [WT_ADJMT_TYPE]          NVARCHAR (1)    NULL,
    [UOM]                    NVARCHAR (10)   NULL,
    [REF_WHSE]               NVARCHAR (3)    NULL,
    [RSN_CODE]               NVARCHAR (3)    NULL,
    [RCPT_VARI]              NVARCHAR (1)    NULL,
    [RCPT_CMPL]              NVARCHAR (1)    NULL,
    [CASES_SHPD]             INT             NOT NULL,
    [UNITS_SHPD]             NUMERIC (15, 5) NOT NULL,
    [CASES_RCVD]             INT             NOT NULL,
    [UNITS_RCVD]             NUMERIC (15, 5) NOT NULL,
    [ACTN_CODE]              NVARCHAR (3)    NULL,
    [CUSTOM_REF]             NVARCHAR (30)   NULL,
    [DATE_PROC]              DATETIME2 (7)   NULL,
    [SYS_USER_ID]            NVARCHAR (15)   NULL,
    [ERROR_CMNT]             NVARCHAR (25)   NULL,
    [REF_CODE_ID_1]          NVARCHAR (3)    NULL,
    [REF_FIELD_1]            NVARCHAR (75)   NULL,
    [REF_CODE_ID_2]          NVARCHAR (3)    NULL,
    [REF_FIELD_2]            NVARCHAR (75)   NULL,
    [REF_CODE_ID_3]          NVARCHAR (3)    NULL,
    [REF_FIELD_3]            NVARCHAR (75)   NULL,
    [REF_CODE_ID_4]          NVARCHAR (3)    NULL,
    [REF_FIELD_4]            NVARCHAR (75)   NULL,
    [REF_CODE_ID_5]          NVARCHAR (3)    NULL,
    [REF_FIELD_5]            NVARCHAR (75)   NULL,
    [REF_CODE_ID_6]          NVARCHAR (3)    NULL,
    [REF_FIELD_6]            NVARCHAR (75)   NULL,
    [REF_CODE_ID_7]          NVARCHAR (3)    NULL,
    [REF_FIELD_7]            NVARCHAR (75)   NULL,
    [REF_CODE_ID_8]          NVARCHAR (3)    NULL,
    [REF_FIELD_8]            NVARCHAR (75)   NULL,
    [REF_CODE_ID_9]          NVARCHAR (3)    NULL,
    [REF_FIELD_9]            NVARCHAR (75)   NULL,
    [REF_CODE_ID_10]         NVARCHAR (3)    NULL,
    [REF_FIELD_10]           NVARCHAR (75)   NULL,
    [XML_GROUP_ID]           NVARCHAR (10)   NULL,
    [CREATE_DATE_TIME]       DATETIME2 (7)   NULL,
    [MOD_DATE_TIME]          DATETIME2 (7)   NULL,
    [USER_ID]                NVARCHAR (15)   NULL,
    [ITEM_ID]                BIGINT          NULL,
    [TC_COMPANY_ID]          INT             NULL,
    [PIX_TRAN_ID]            INT             NOT NULL,
    [WM_VERSION_ID]          INT             NOT NULL,
    [FACILITY_ID]            INT             NULL,
    [COMPANY_CODE]           NVARCHAR (10)   NULL,
    [ITEM_NAME]              NVARCHAR (100)  NULL,
    [ESIGN_USER_NAME]        NVARCHAR (255)  NULL,
    [BatchID]                BIGINT          NULL,
    [ProcessLogID]           BIGINT          NULL,
    CONSTRAINT [PK_MANH_PIX_TRAN] PRIMARY KEY CLUSTERED ([PIX_TRAN_ID] ASC) ON [DWH_MANH]
) ON [DWH_MANH];








GO
CREATE NONCLUSTERED INDEX [NI_MANH_PIX_TRAN_TYPE_CODE_ACTION_REF1]
    ON [MANH].[PIX_TRAN]([TRAN_TYPE] ASC, [TRAN_CODE] ASC, [ACTN_CODE] ASC, [REF_FIELD_1] ASC)
    INCLUDE([BATCH_NBR], [ITEM_ID]);

