CREATE TABLE [MANH].[PKT_DTL] (
    [PKT_CTRL_NBR]           NVARCHAR (10)   NOT NULL,
    [PKT_SEQ_NBR]            BIGINT          NOT NULL,
    [INVN_TYPE]              NVARCHAR (1)    NULL,
    [PROD_STAT]              NVARCHAR (3)    NULL,
    [BATCH_NBR]              NVARCHAR (15)   NULL,
    [SKU_ATTR_1]             NVARCHAR (10)   NULL,
    [SKU_ATTR_2]             NVARCHAR (10)   NULL,
    [SKU_ATTR_3]             NVARCHAR (10)   NULL,
    [SKU_ATTR_4]             NVARCHAR (10)   NULL,
    [SKU_ATTR_5]             NVARCHAR (10)   NULL,
    [CNTRY_OF_ORGN]          NVARCHAR (4)    NULL,
    [ORIG_ORD_LINE_NBR]      INT             NOT NULL,
    [ORIG_PKT_LINE_NBR]      INT             NOT NULL,
    [PICK_LOCN_ID]           NVARCHAR (10)   NULL,
    [PO_NBR]                 NVARCHAR (20)   NULL,
    [ORIG_ORD_QTY]           NUMERIC (9, 2)  NOT NULL,
    [ORIG_PKT_QTY]           NUMERIC (9, 2)  NOT NULL,
    [PKT_QTY]                NUMERIC (9, 2)  NOT NULL,
    [BACK_ORD_QTY]           NUMERIC (13, 4) NOT NULL,
    [CANCEL_QTY]             NUMERIC (9, 2)  NOT NULL,
    [TO_BE_PIKD]             NUMERIC (9, 2)  NOT NULL,
    [TO_BE_VERF_AS_PAKD]     NUMERIC (9, 2)  NOT NULL,
    [VERF_AS_PAKD]           NUMERIC (9, 2)  NOT NULL,
    [UNITS_PIKD]             NUMERIC (9, 2)  NOT NULL,
    [UNITS_PAKD]             NUMERIC (9, 2)  NOT NULL,
    [STD_BUNDL_QTY]          NUMERIC (9, 2)  NOT NULL,
    [STD_SUB_PACK_QTY]       NUMERIC (9, 2)  NOT NULL,
    [STD_PACK_QTY]           NUMERIC (9, 2)  NOT NULL,
    [STD_CASE_QTY]           NUMERIC (9, 2)  NOT NULL,
    [STD_PLT_QTY]            NUMERIC (9, 2)  NOT NULL,
    [CUBE_MULT_QTY]          NUMERIC (9, 2)  NOT NULL,
    [STD_CASE_WT]            NUMERIC (13, 4) NOT NULL,
    [STD_CASE_VOL]           NUMERIC (13, 4) NOT NULL,
    [UNIT_WT]                NUMERIC (13, 4) NOT NULL,
    [UNIT_VOL]               NUMERIC (13, 4) NOT NULL,
    [CUST_SKU]               NVARCHAR (20)   NULL,
    [PPACK_GRP_CODE]         NVARCHAR (2)    NULL,
    [ASSORT_NBR]             NVARCHAR (12)   NULL,
    [PPACK_QTY]              NUMERIC (9, 2)  NOT NULL,
    [PLT_TYPE]               NVARCHAR (3)    NULL,
    [CARTON_TYPE]            NVARCHAR (3)    NULL,
    [CARTON_SIZE]            NVARCHAR (3)    NULL,
    [CARTON_BREAK_ATTR]      NVARCHAR (3)    NULL,
    [CRITCL_DIM_1]           NUMERIC (7, 2)  NOT NULL,
    [CRITCL_DIM_2]           NUMERIC (7, 2)  NOT NULL,
    [CRITCL_DIM_3]           NUMERIC (7, 2)  NOT NULL,
    [SNGL_ITEM_CARTON_FLAG]  NVARCHAR (1)    NULL,
    [UOM]                    NVARCHAR (2)    NULL,
    [PRE_CUBE_FLAG]          NVARCHAR (1)    NULL,
    [LINE_ITEM_STAT]         NVARCHAR (2)    NULL,
    [RSN_CODE]               NVARCHAR (2)    NULL,
    [UPC_PRE_DIGIT]          NVARCHAR (1)    NULL,
    [UPC_VENDOR_CODE]        NVARCHAR (5)    NULL,
    [UPC_SRL_PROD_NBR]       NVARCHAR (5)    NULL,
    [UPC_POST_DIGIT]         NVARCHAR (1)    NULL,
    [PRICE]                  NUMERIC (9, 2)  NOT NULL,
    [RETAIL_PRICE]           NUMERIC (9, 2)  NOT NULL,
    [STAT_CODE]              INT             NOT NULL,
    [CUSTOM_TAG]             NVARCHAR (8)    NULL,
    [FRT_CLASS]              NVARCHAR (5)    NULL,
    [PICK_RATE]              NUMERIC (9, 4)  NOT NULL,
    [PACK_RATE]              NUMERIC (9, 4)  NOT NULL,
    [OVRSZ_LEN]              INT             NOT NULL,
    [ALLOC_TYPE]             NVARCHAR (3)    NULL,
    [PICK_LOCN_ASSIGN_TYPE]  NVARCHAR (3)    NULL,
    [I2O5_PACK_QTY_REF]      NVARCHAR (1)    NULL,
    [I2O5_CASE_QTY_REF]      NVARCHAR (1)    NULL,
    [I2O5_TIER_QTY_REF]      NVARCHAR (1)    NULL,
    [WAVE_PROC_TYPE]         INT             NOT NULL,
    [REPL_PROC_TYPE]         INT             NOT NULL,
    [LINE_TYPE]              NVARCHAR (1)    NULL,
    [TEMP_ZONE]              NVARCHAR (1)    NULL,
    [PKT_CONSOL_ATTR]        NVARCHAR (3)    NULL,
    [SHELF_DAYS]             INT             NOT NULL,
    [DISTRO_NBR]             NVARCHAR (12)   NULL,
    [DISTRO_TYPE]            NVARCHAR (1)    NULL,
    [SKU_SUB_CODE_ID]        NVARCHAR (3)    NULL,
    [SKU_SUB_CODE_VALUE]     NVARCHAR (20)   NULL,
    [STORE_NBR]              NVARCHAR (16)   NULL,
    [SHPMT_NBR]              NVARCHAR (20)   NULL,
    [MERCH_TYPE]             NVARCHAR (3)    NULL,
    [MERCH_GRP]              NVARCHAR (3)    NULL,
    [STORE_DEPT]             NVARCHAR (3)    NULL,
    [EVENT_CODE]             NVARCHAR (10)   NULL,
    [IN_STORE_DATE]          DATETIME2 (7)   NULL,
    [PACK_ZONE]              NVARCHAR (4)    NULL,
    [DISTRO_W_CTRL_NBR]      NVARCHAR (30)   NULL,
    [TICKET_TYPE]            NVARCHAR (3)    NULL,
    [DISTRO_BREAK_ATTR]      NVARCHAR (4)    NULL,
    [WAVE_NBR]               NVARCHAR (12)   NULL,
    [SHIP_WAVE_NBR]          NVARCHAR (12)   NULL,
    [PARTL_FILL]             NVARCHAR (1)    NULL,
    [RTL_TO_BE_DISTROED_QTY] NUMERIC (9, 2)  NOT NULL,
    [SPL_INSTR_CODE_1]       NVARCHAR (2)    NULL,
    [SPL_INSTR_CODE_2]       NVARCHAR (2)    NULL,
    [SPL_INSTR_CODE_3]       NVARCHAR (2)    NULL,
    [SPL_INSTR_CODE_4]       NVARCHAR (2)    NULL,
    [SPL_INSTR_CODE_5]       NVARCHAR (2)    NULL,
    [CREATE_DATE_TIME]       DATETIME2 (7)   NOT NULL,
    [MOD_DATE_TIME]          DATETIME2 (7)   NULL,
    [USER_ID]                NVARCHAR (15)   NULL,
    [SKU_BREAK_ATTR]         NVARCHAR (15)   NULL,
    [ORD_TYPE]               NVARCHAR (2)    NULL,
    [VAS_PROC_TYPE]          NVARCHAR (1)    NULL,
    [BATCH_REQMT_TYPE]       NVARCHAR (1)    NULL,
    [CHUTE_ASSIGN_TYPE]      NVARCHAR (3)    NULL,
    [SNGL_UNIT_FLAG]         NVARCHAR (1)    NULL,
    [SRL_NBR_REQD_FLAG]      NVARCHAR (1)    NULL,
    [SRL_NBR_REQD]           NVARCHAR (1)    NULL,
    [TMS_PO_SEQ]             NVARCHAR (25)   NULL,
    [DISTRO_PLAN_LOAD_NBR]   NVARCHAR (20)   NULL,
    [DISTRO_TMS_FLAG]        NVARCHAR (1)    NULL,
    [REF_FIELD_1]            NVARCHAR (25)   NULL,
    [REF_FIELD_2]            NVARCHAR (25)   NULL,
    [REF_FIELD_3]            NVARCHAR (25)   NULL,
    [PO_SIZE_UOM]            NVARCHAR (2)    NULL,
    [PO_SIZE_VALUE]          NUMERIC (13, 4) NOT NULL,
    [PO_READY_TO_SHIP_FLAG]  NVARCHAR (1)    NULL,
    [BUDGET_COST]            NUMERIC (13, 2) NOT NULL,
    [CURR_CODE]              NVARCHAR (10)   NULL,
    [DISTRO_PLAN_SHPMT_NBR]  NVARCHAR (20)   NULL,
    [DISTRO_TMS_STAT_CODE]   INT             NOT NULL,
    [DISTRO_TMS_TO_ID]       NVARCHAR (50)   NULL,
    [TMS_TO_LINE_NBR]        INT             NOT NULL,
    [TMS_PO_PKT]             NVARCHAR (10)   NULL,
    [DISTRO_PLAN_BOL]        NVARCHAR (20)   NULL,
    [PRICE_TKT_TYPE]         NVARCHAR (3)    NULL,
    [PKG_TYPE_INSTANCE]      NVARCHAR (100)  NULL,
    [PKG_TYPE]               NVARCHAR (255)  NULL,
    [PARENT_LINE_ITEM_ID]    NVARCHAR (25)   NULL,
    [UN_NBR]                 NVARCHAR (16)   NULL,
    [COMMODITY_CODE]         NVARCHAR (35)   NULL,
    [MONETARY_VALUE]         NUMERIC (13, 2) NOT NULL,
    [MV_CURRENCY_CODE]       NVARCHAR (3)    NULL,
    [UNIT_MONETARY_VALUE]    NUMERIC (13, 2) NOT NULL,
    [MV_SIZE_UOM]            NVARCHAR (3)    NULL,
    [IS_HAZMAT_FLAG]         NVARCHAR (1)    NULL,
    [EXP_INFO_CODE]          NVARCHAR (2)    NULL,
    [MINOR_PKT_CTRL_NBR]     NVARCHAR (10)   NULL,
    [ITEM_ID]                BIGINT          NOT NULL,
    [PKT_DTL_ID]             BIGINT          NOT NULL,
    [PKT_HDR_ID]             BIGINT          NULL,
    [WM_VERSION_ID]          INT             NOT NULL,
    [ORIGINAL_LINE_ITEM_ID]  BIGINT          NULL,
    [REFERENCE_LINE_ITEM_ID] BIGINT          NULL,
    [ORIGINAL_ORDER_ID]      BIGINT          NULL,
    [REFERENCE_ORDER_ID]     BIGINT          NULL,
    [CHUTE_ID]               NVARCHAR (10)   NULL,
    [PKT_GRP_CODE]           NVARCHAR (3)    NULL,
    [PACK_WAVE_NBR]          NVARCHAR (15)   NULL,
    [WAVE_STAT_CODE]         INT             NOT NULL,
    [WAVE_SEQ_NBR]           INT             NOT NULL,
    [IS_CONSOLIDATED]        INT             NOT NULL,
    [ORIG_ITEM_ID]           BIGINT          NULL,
    [QTY_UOM_ID_BASE]        INT             NULL,
    [QTY_UOM_ID]             INT             NULL,
    [QTY_CONV_FACTOR]        NUMERIC (13, 4) NOT NULL,
    [ACTUAL_COST]            NUMERIC (13, 4) NOT NULL,
    [Eff_Date]               DATE            NOT NULL,
    [End_Date]               DATE            NULL,
    [ActInd]                 CHAR (1)        NULL,
    [IsDeleted]              CHAR (1)        NULL,
    [BatchID]                BIGINT          NULL,
    [ProcessLogID]           BIGINT          NULL,
    [TC_ORDER_LINE_ID]       NVARCHAR (30)   NULL,
    CONSTRAINT [PK_MANH_PKT_DTL] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [PKT_DTL_ID] ASC) ON [DWH_MANH]
) ON [DWH_MANH];



