CREATE TABLE [MANH].[UN_NUMBER] (
    [UN_NUMBER_ID]             BIGINT         NOT NULL,
    [TC_COMPANY_ID]            INT            NOT NULL,
    [UN_NUMBER_VALUE]          NVARCHAR (16)  NOT NULL,
    [UN_NUMBER_DESCRIPTION]    NVARCHAR (255) NOT NULL,
    [UNN_CLASS_DIV]            NVARCHAR (255) NULL,
    [UNN_SUB_RISK]             NVARCHAR (255) NULL,
    [UNN_HAZARD_LABEL]         NVARCHAR (255) NULL,
    [UNN_PG]                   NVARCHAR (255) NULL,
    [UNN_SP]                   NVARCHAR (255) NULL,
    [UNN_AIR_BOTH_INST_LTD]    NVARCHAR (255) NULL,
    [UNN_AIR_BOTH_QTY_LTD]     NVARCHAR (255) NULL,
    [UNN_AIR_BOTH_INST]        NVARCHAR (255) NULL,
    [UNN_AIR_BOTH_QTY]         NVARCHAR (255) NULL,
    [UNN_AIR_CARGO_INST]       NVARCHAR (255) NULL,
    [UNN_AIR_CARGO_QTY]        NVARCHAR (255) NULL,
    [UN_NUMBER]                BIGINT         NULL,
    [RQ_FIELD_1]               NVARCHAR (40)  NULL,
    [RQ_FIELD_2]               NVARCHAR (40)  NULL,
    [RQ_FIELD_3]               NVARCHAR (40)  NULL,
    [RQ_FIELD_4]               NVARCHAR (40)  NULL,
    [RQ_FIELD_5]               NVARCHAR (40)  NULL,
    [HZC_FIELD_1]              NVARCHAR (40)  NULL,
    [HZC_FIELD_2]              NVARCHAR (40)  NULL,
    [HZC_FIELD_3]              NVARCHAR (40)  NULL,
    [HZC_FIELD_4]              NVARCHAR (40)  NULL,
    [HZC_FIELD_5]              NVARCHAR (40)  NULL,
    [MARK_FOR_DELETION]        SMALLINT       NOT NULL,
    [CREATED_SOURCE_TYPE]      SMALLINT       NULL,
    [CREATED_SOURCE]           NVARCHAR (50)  NULL,
    [CREATED_DTTM]             DATETIME2 (7)  NOT NULL,
    [LAST_UPDATED_SOURCE_TYPE] SMALLINT       NULL,
    [LAST_UPDATED_SOURCE]      NVARCHAR (50)  NULL,
    [LAST_UPDATED_DTTM]        DATETIME2 (7)  NOT NULL,
    [Eff_Date]                 DATE           NOT NULL,
    [End_Date]                 DATE           NULL,
    [ActInd]                   CHAR (1)       NULL,
    [IsDeleted]                CHAR (1)       NULL,
    [BatchID]                  BIGINT         NULL,
    [ProcessLogID]             BIGINT         NULL,
    CONSTRAINT [PK_MANH_UN_NUMBER] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [UN_NUMBER_ID] ASC)
);

