CREATE TABLE [WEB_ARC].[Complaints] (
    [ID]                      BIGINT          NOT NULL,
    [Datum]                   DATE            NULL,
    [Pos_Nr]                  NVARCHAR (50)   NULL,
    [Order_Nr]                NVARCHAR (50)   NULL,
    [Complaint]               NVARCHAR (255)  NULL,
    [Complaint_Details]       NVARCHAR (4000) NULL,
    [Item_Ordered]            NVARCHAR (50)   NULL,
    [Item_Received]           NVARCHAR (50)   NULL,
    [Quantity_Ordered]        INT             NULL,
    [Quantity_Received]       INT             NULL,
    [Complaint_nr]            NVARCHAR (50)   NULL,
    [Facility_ID]             NVARCHAR (50)   NULL,
    [Olpn_Nr]                 NVARCHAR (50)   NULL,
    [Customer_Nr]             NVARCHAR (50)   NULL,
    [Item_Ordered_Reported]   NVARCHAR (50)   NULL,
    [Item_Received_Reported]  NVARCHAR (50)   NULL,
    [Batch_Ordered]           NVARCHAR (50)   NULL,
    [Credit_Note]             NVARCHAR (255)  NULL,
    [Service_order]           NVARCHAR (255)  NULL,
    [CarrierDamage]           NVARCHAR (255)  NULL,
    [TrackandTrace]           NVARCHAR (255)  NULL,
    [CustomerServiceOperator] NVARCHAR (255)  NULL,
    [Conterminator]           NVARCHAR (50)   NULL,
    [Pos_Nr_Orig]             NVARCHAR (50)   NULL,
    [Order_Nr_orig]           NVARCHAR (50)   NULL,
    [TrackandTrace_Nr_Orig]   NVARCHAR (50)   NULL,
    [Item_Ordered_Orig]       NVARCHAR (50)   NULL,
    [Complaint_Orig]          NVARCHAR (50)   NULL,
    [Checked]                 CHAR (1)        NULL,
    [Incomplete]              CHAR (1)        NULL,
    [Created_Date]            DATETIME2 (7)   NULL,
    [Created_By]              NVARCHAR (255)  NULL,
    [Updated_Date]            DATETIME2 (7)   NULL,
    [Updated_By]              NVARCHAR (255)  NULL,
    [Eff_Date]                DATE            NOT NULL,
    [End_Date]                DATE            NULL,
    [ActInd]                  CHAR (1)        NULL,
    [IsDeleted]               CHAR (1)        NULL,
    [BatchID]                 BIGINT          NULL,
    [ProcessLogID]            BIGINT          NULL,
    CONSTRAINT [PK_Complaints] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [ID] ASC) ON [DWH_WEB_ARC]
) ON [DWH_WEB_ARC];

