CREATE TABLE [RT].[Activity_tracking] (
    [Tran_Type]         NVARCHAR (3)    NULL,
    [Tran_Code]         NVARCHAR (3)    NULL,
    [LPN]               NVARCHAR (50)   NULL,
    [Wave]              NVARCHAR (12)   NULL,
    [Work_Type]         NVARCHAR (3)    NULL,
    [#_of_Units]        NUMERIC (13, 5) NULL,
    [From_Location]     NVARCHAR (15)   NULL,
    [To_Location]       NVARCHAR (15)   NULL,
    [RF_Module]         NVARCHAR (10)   NULL,
    [RF_Menu_option]    NVARCHAR (40)   NULL,
    [Create_date]       DATETIME2 (7)   NULL,
    [Datum]             DATE            NULL,
    [Picker]            NVARCHAR (15)   NULL,
    [Item]              NVARCHAR (100)  NULL,
    [Reference_code_1]  NVARCHAR (3)    NULL,
    [Reference_field_1] NVARCHAR (50)   NULL,
    [Reference_code_2]  NVARCHAR (3)    NULL,
    [Reference_field_2] NVARCHAR (50)   NULL,
    [Reference_code_3]  NVARCHAR (3)    NULL,
    [Reference_field_3] NVARCHAR (50)   NULL,
    [Reference_code_4]  NVARCHAR (3)    NULL,
    [Reference_field_4] NVARCHAR (50)   NULL,
    [Reference_code_5]  NVARCHAR (3)    NULL,
    [Reference_field_5] NVARCHAR (50)   NULL,
    [Task_ID]           INT             NULL,
    [Pallet_ID]         NVARCHAR (50)   NULL,
    [Request_ID]        BIGINT          NULL,
    [BatchID]           BIGINT          NULL,
    [ProcessLogID]      BIGINT          NULL
);

