CREATE TABLE [RT].[Obsolescense] (
    [DateKey]                            VARCHAR (30)    NULL,
    [Contract]                           NVARCHAR (5)    NULL,
    [RN]                                 BIGINT          NULL,
    [SKU_Name]                           NVARCHAR (25)   NULL,
    [Purchase_SKU_Code]                  NVARCHAR (100)  NULL,
    [Lot_Code]                           NVARCHAR (20)   NULL,
    [SKU_Description]                    NVARCHAR (65)   NULL,
    [Inventory_Netto_QTY]                DECIMAL (32, 3) NULL,
    [Percentage]                         DECIMAL (32, 3) NULL,
    [Sum_Netto_Qty]                      DECIMAL (32, 3) NULL,
    [Inventory_Cost_Price]               DECIMAL (32, 3) NULL,
    [Inventory_Netto_Value]              DECIMAL (32, 3) NULL,
    [Order_Type]                         VARCHAR (2)     NULL,
    [Criteria]                           INT             NULL,
    [Days_to_Expire]                     INT             NULL,
    [Expiration_Date]                    VARCHAR (30)    NULL,
    [Lock_Date]                          VARCHAR (30)    NULL,
    [Days_Until_Lockdate]                INT             NULL,
    [Locken]                             VARCHAR (6)     NULL,
    [Number_Of_Units_PMND]               DECIMAL (32, 3) NULL,
    [Number_Of_Units_PD]                 DECIMAL (32, 2) NULL,
    [Days_To_Sell_Stock]                 DECIMAL (32, 2) NULL,
    [Days_To_Sell_Stock_SUM]             DECIMAL (32)    NULL,
    [Projection_OOS]                     VARCHAR (30)    NULL,
    [Lock_VS_Projection_OOS]             VARCHAR (30)    NULL,
    [Calc_Date]                          VARCHAR (30)    NULL,
    [Last_batch_vs_lock_date_next_batch] INT             NULL,
    [Expected_Obsolete]                  VARCHAR (7)     NULL,
    [Expected_Obsolete_Stock]            DECIMAL (32, 2) NULL,
    [Value_Obsolete_Stock]               DECIMAL (32, 2) NULL,
    [Request_ID]                         BIGINT          NULL,
    [BatchID]                            BIGINT          NULL,
    [ProcessLogID]                       BIGINT          NULL
);



