CREATE TABLE [MANH].[ALLOC_INVN_DTL] (
    [ALLOC_INVN_DTL_ID] INT           NOT NULL,
    [MOD_DATE_TIME]     DATETIME2 (7) NULL,
    [BatchID]           BIGINT        NULL,
    [ProcessLogID]      BIGINT        NULL,
    [Issue]             TINYINT       NULL,
    CONSTRAINT [PK_MANH_ALLOC_INVN_DTL] PRIMARY KEY CLUSTERED ([ALLOC_INVN_DTL_ID] ASC)
);

