CREATE TABLE [MANH].[BATCH_MASTER] (
    [BATCH_MASTER_ID] INT           NOT NULL,
    [MOD_DATE_TIME]   DATETIME2 (7) NULL,
    [BatchID]         BIGINT        NULL,
    [ProcessLogID]    BIGINT        NULL,
    [Issue]           TINYINT       NULL,
    CONSTRAINT [PK_MANH_BATCH_MASTER] PRIMARY KEY CLUSTERED ([BATCH_MASTER_ID] ASC)
);

