CREATE TABLE [MANH].[CNT_INVN_DTL] (
    [CNT_INVN_DTL_ID] INT           NOT NULL,
    [MOD_DATE_TIME]   DATETIME2 (7) NULL,
    [BatchID]         BIGINT        NULL,
    [ProcessLogID]    BIGINT        NULL,
    [Issue]           TINYINT       NULL,
    CONSTRAINT [PK_MANH_CNT_INVN_DTL] PRIMARY KEY CLUSTERED ([CNT_INVN_DTL_ID] ASC)
);

