CREATE TABLE [MANH].[ILM_YARD_ACTIVITY] (
    [ACTIVITY_ID]   INT           NOT NULL,
    [ACTIVITY_DTTM] DATETIME2 (7) NOT NULL,
    [BatchID]       BIGINT        NULL,
    [ProcessLogID]  BIGINT        NULL,
    [Issue]         TINYINT       NULL,
    CONSTRAINT [PK_MANH_ILM_YARD_ACTIVITY] PRIMARY KEY CLUSTERED ([ACTIVITY_ID] ASC)
);

