CREATE TABLE [MANH].[INVN_VARI_HDR] (
    [INVN_VARI_HDR_ID] INT           NOT NULL,
    [MOD_DATE_TIME]    DATETIME2 (7) NULL,
    [BatchID]          BIGINT        NULL,
    [ProcessLogID]     BIGINT        NULL,
    [Issue]            TINYINT       NULL,
    CONSTRAINT [PK_MANH_INVN_VARI_HDR] PRIMARY KEY CLUSTERED ([INVN_VARI_HDR_ID] ASC)
);

