CREATE TABLE [MANH].[ITEM_FACILITY_MAPPING_WMS] (
    [ITEM_FACILITY_MAPPING_ID] BIGINT        NOT NULL,
    [AUDIT_LAST_UPDATED_DTTM]  DATETIME2 (7) NULL,
    [BatchID]                  BIGINT        NULL,
    [ProcessLogID]             BIGINT        NULL,
    [Issue]                    TINYINT       NULL,
    CONSTRAINT [PK_MANH_ITEM_FACILITY_MAPPING_WMS] PRIMARY KEY CLUSTERED ([ITEM_FACILITY_MAPPING_ID] ASC)
);

