CREATE TABLE [MANH].[PHYS_INVN_HDR] (
    [PHYS_INVN_HDR_ID] INT           NOT NULL,
    [MOD_DATE_TIME]    DATETIME2 (7) NULL,
    [BatchID]          BIGINT        NULL,
    [ProcessLogID]     BIGINT        NULL,
    [Issue]            TINYINT       NULL,
    CONSTRAINT [PK_MANH_PHYS_INVN_HDR] PRIMARY KEY CLUSTERED ([PHYS_INVN_HDR_ID] ASC)
);

