CREATE TABLE [MANH].[PKT_DTL] (
    [PKT_DTL_ID]    BIGINT        NOT NULL,
    [MOD_DATE_TIME] DATETIME2 (7) NULL,
    [BatchID]       BIGINT        NULL,
    [ProcessLogID]  BIGINT        NULL,
    [Issue]         TINYINT       NULL,
    CONSTRAINT [PK_MANH_PKT_DTL] PRIMARY KEY CLUSTERED ([PKT_DTL_ID] ASC)
);

