CREATE TABLE [MANH].[PKT_CONSOL_LOCN] (
    [PKT_CONSOL_LOCN_ID] BIGINT        NOT NULL,
    [MOD_DATE_TIME]      DATETIME2 (7) NULL,
    [BatchID]            BIGINT        NULL,
    [ProcessLogID]       BIGINT        NULL,
    [Issue]              TINYINT       NULL,
    CONSTRAINT [PK_MANH_PKT_CONSOL_LOCN] PRIMARY KEY CLUSTERED ([PKT_CONSOL_LOCN_ID] ASC)
);

