CREATE TABLE [MANH].[SHIPMENT] (
    [SHIPMENT_ID]       BIGINT        NOT NULL,
    [LAST_UPDATED_DTTM] DATETIME2 (7) NOT NULL,
    [BatchID]           BIGINT        NULL,
    [ProcessLogID]      BIGINT        NULL,
    [Issue]             TINYINT       NULL,
    CONSTRAINT [PK_MANH_SHIPMENT] PRIMARY KEY CLUSTERED ([SHIPMENT_ID] ASC)
);

