CREATE TABLE [MANH].[TASK_PARM] (
    [TASK_PARM_ID]  INT           NOT NULL,
    [MOD_DATE_TIME] DATETIME2 (7) NULL,
    [BatchID]       BIGINT        NULL,
    [ProcessLogID]  BIGINT        NULL,
    [Issue]         TINYINT       NULL,
    CONSTRAINT [PK_MANH_TASK_PARM] PRIMARY KEY CLUSTERED ([TASK_PARM_ID] ASC)
);

