CREATE TABLE [MANH].[WAVE_TASK_CRIT] (
    [WAVE_TASK_CRIT_ID] INT           NOT NULL,
    [MOD_DATE_TIME]     DATETIME2 (7) NULL,
    [BatchID]           BIGINT        NULL,
    [ProcessLogID]      BIGINT        NULL,
    [Issue]             TINYINT       NULL,
    CONSTRAINT [PK_MANH_WAVE_TASK_CRIT] PRIMARY KEY CLUSTERED ([WAVE_TASK_CRIT_ID] ASC)
);

