CREATE TABLE [MANH].[WAVE_PARM] (
    [WAVE_PARM_ID]  INT           NOT NULL,
    [MOD_DATE_TIME] DATETIME2 (7) NULL,
    [BatchID]       BIGINT        NULL,
    [ProcessLogID]  BIGINT        NULL,
    [Issue]         TINYINT       NULL,
    CONSTRAINT [PK_MANH_WAVE_PARM] PRIMARY KEY CLUSTERED ([WAVE_PARM_ID] ASC)
);

