CREATE TABLE [PROJWMS].[ACCOUNTING_GROUP] (
    [ACCOUNTING_GROUP] NVARCHAR (5)    NOT NULL,
    [DESCRIPTION]      NVARCHAR (35)   NULL,
    [OBJID]            NVARCHAR (4000) NULL,
    [OBJVERSION]       NVARCHAR (2000) NULL,
    [BatchID]          BIGINT          NULL,
    [ProcessLogID]     BIGINT          NULL,
    CONSTRAINT [PK_ACCOUNTING_GROUP] PRIMARY KEY CLUSTERED ([ACCOUNTING_GROUP] ASC)
);

