CREATE VIEW FDV.FD_INVENTORY_PART_VALUE 
as
with cte_0 as
(SELECT IPIS.CONTRACT as CONTRACT,  
       IPIS.PART_NO as PART_NO,  
       IPIS.LOT_BATCH_NO AS LOT_BATCH_NO,  
	   SUM(cast(IPIS.QTY_ONHAND as DECIMAL(11,2))) as INVENTORY_QTY,
       MAX(cast(IPUC.INVENTORY_VALUE AS DECIMAL(11,2))) as INVENTORY_PRICE,
       SUM(cast(IPIS.QTY_ONHAND as DECIMAL(11,2))) * MAX(cast(IPUC.INVENTORY_VALUE AS DECIMAL(11,2))) as INVENTORY_VALUE 
FROM IFS.INVENTORY_PART_IN_STOCK IPIS  
LEFT OUTER JOIN IFS.INVENTORY_PART_UNIT_COST_SUM IPUC  
  ON IPIS.CONTRACT=IPUC.CONTRACT  
 AND IPIS.PART_NO=IPUC.PART_NO  
 AND IPUC.LOT_BATCH_NO=IPIS.LOT_BATCH_NO  
 AND IPUC.ActInd='Y'
WHERE IPIS.QTY_ONHAND>0
and IPIS.ActInd='Y' 
and IPIS.CONTRACT='FD01' --nieuw
GROUP BY IPIS.CONTRACT,  
       IPIS.PART_NO,  
       IPIS.LOT_BATCH_NO)


select 
c0.CONTRACT
,c0.PART_NO
,c0.LOT_BATCH_NO
,max(c0.INVENTORY_PRICE) INVENTORY_UNIT_COST
,sum(c0.INVENTORY_VALUE) INVENTORY_VALUE
,sum(c0.INVENTORY_QTY) INVENTORY_QTY
from cte_0 c0
join IFS.LOT_BATCH_MASTER LBM
on
c0.PART_NO=LBM.PART_NO
and
c0.LOT_BATCH_NO=LBM.LOT_BATCH_NO
group by 
c0.CONTRACT
,c0.PART_NO
,c0.LOT_BATCH_NO
,c0.INVENTORY_PRICE

union all

SELECT V1.CONTRACT,  
       V1.PART_NO,
       V1.LOT_BATCH_NO,
       CAST(MAX(V1.INVENTORY_PRICE) AS DECIMAL(11,2)) INVENTORY_COST,
       CAST(SUM(V1.INVENTORY_VALUE) AS DECIMAL(11,2)) INVENTORY_VALUE,  
       SUM(V1.INVENTORY_QTY) INVENTORY_QTY
FROM IFS.LOT_BATCH_MASTER LBM
LEFT OUTER JOIN  
(  
SELECT IPIS.CONTRACT,  
       IPIS.PART_NO,  
       IPIS.LOT_BATCH_NO,  
       SUM(IPIS.QTY_ONHAND) INVENTORY_QTY,  
       MAX(ITH.COST) INVENTORY_PRICE,  
       0 INVENTORY_VALUE  
FROM IFS.INVENTORY_PART_IN_STOCK IPIS  
LEFT OUTER JOIN (SELECT 'FD01' CONTRACT,  
				YEAR(ITH2.DATE_APPLIED) YEAR, 
				ITH2.PART_NO, 
				ITH2.LOT_BATCH_NO, 
				ITH2.TRANSACTION_CODE, 
				MAX(ITH2.COST) COST 
				FROM IFS.INVENTORY_TRANSACTION_HIST ITH2 
				where YEAR(ITH2.DATE_APPLIED)<=YEAR(GETDATE())
				and ITH2.ActInd='Y'   
				GROUP BY ITH2.CONTRACT
				,YEAR(ITH2.DATE_APPLIED)
				,ITH2.PART_NO
				,ITH2.LOT_BATCH_NO
				,ITH2.TRANSACTION_CODE
                ) ITH
  ON IPIS.CONTRACT=ITH.CONTRACT  
 AND IPIS.PART_NO=ITH.PART_NO  
 AND IPIS.LOT_BATCH_NO=ITH.LOT_BATCH_NO  
 AND IPIS.ActInd='Y'

WHERE IPIS.QTY_ONHAND=0  
GROUP BY IPIS.CONTRACT,  
       IPIS.PART_NO,  
       IPIS.LOT_BATCH_NO  
) V1
 ON V1.PART_NO=LBM.PART_NO
AND V1.LOT_BATCH_NO=LBM.LOT_BATCH_NO  
WHERE (V1.INVENTORY_QTY IS NOT NULL
       OR V1.INVENTORY_QTY=0)
GROUP BY V1.CONTRACT,  
       V1.PART_NO,
       V1.LOT_BATCH_NO,
       V1.INVENTORY_PRICE