




CREATE VIEW [FDV].[VW_D_Vas_Lane] 
AS

SELECT 
      distinct([MFG_LINE]) AS Vas_Lane_Code
	  ,CASE WHEN [MFG_LINE]='OP' THEN 'OMPAK' 
	        WHEN [MFG_LINE]='LB' THEN 'HANDMATIG LABELEN' 
	        WHEN [MFG_LINE]='LS' THEN 'SPOED'
			WHEN [MFG_LINE] in ('LG','KG') THEN 'MACHINE1 LABELING'
			WHEN [MFG_LINE]='LF' THEN 'MACHINE2 LABELING'
			WHEN [MFG_LINE]='LE' THEN 'MACHINE3 LABELING'
			WHEN [MFG_LINE]='LD' THEN 'MACHINE4 LABELING'
			WHEN [MFG_LINE] in ('LC','KC') THEN 'MACHINE5 LABELING'
			WHEN [MFG_LINE]='LL' THEN 'MACHINE6 LABELING'
			WHEN [MFG_LINE]='KRIMP' THEN 'MACHINE7 KRIMP TUNNEL'
			WHEN [MFG_LINE]='LK' THEN 'MACHINE8 LABELING'
		    WHEN [MFG_LINE]='KH' THEN 'TPA TRIPAK'
			WHEN [MFG_LINE]='KK' THEN 'KLEINE KITTING'
			WHEN [MFG_LINE]='KT' THEN 'KITTING'
			WHEN [MFG_LINE]='LH' THEN 'SINGLE PAK'
			WHEN [MFG_LINE]='UP' THEN 'UITPAK'
			ELSE 'UNKNOWN'
   		    END AS Vas_Lane_Description
      
  FROM [MANH].[WORK_ORD_HDR]
  WHERE ActInd='Y'