





CREATE VIEW [FDV].[VW_D_Lot]
AS


SELECT
	SKU_Code
	, Lot_Code
	, Status_Code
	, Status_Description
	, Received_Date
	, Expire_Date
	, Expire_Flag
	, Cost_Price
FROM (
		SELECT 
			BM.ITEM_ID AS SKU_Code
			, BM.BATCH_NBR AS Lot_Code
			, BM.STAT_CODE AS Status_Code
			, SC.CODE_DESC AS Status_Description
			, BM.RCVD_DATE AS Received_Date
			, BM.XPIRE_DATE AS Expire_Date
			, BM.XPIRE_FLAG AS Expire_Flag
			, cast(IP.INVENTORY_VALUE as decimal (22,5)) AS Cost_Price
			, ROW_NUMBER() OVER (PARTITION BY BM.ITEM_ID, BM.BATCH_NBR ORDER BY BM.MOD_DATE_TIME) KEYNR
			FROM MANH.BATCH_MASTER AS BM 
			LEFT OUTER JOIN MANH.SYS_CODE AS SC ON BM.STAT_CODE = SC.CODE_ID AND SC.CODE_TYPE = '305' AND SC.REC_TYPE = 'S' AND SC.ActInd = 'Y'
			LEFT OUTER JOIN MANH.ITEM_CBO AS IC ON IC.ITEM_ID = BM.ITEM_ID AND IC.ActInd = 'Y'
			LEFT OUTER JOIN IFS.INVENTORY_PART_UNIT_COST_SUM AS IP ON IP.PART_NO = IC.ITEM_NAME /*AND IP.LOT_BATCH_NO = BM.BATCH_NBR*/ AND IP.ActInd = 'Y'
			WHERE (BM.ActInd = 'Y')
			and BM.XPIRE_DATE<>'0006-10-10 00:00:00.0000000'
) A
WHERE  KEYNR = 1
UNION
SELECT  - 1, '-1', NULL, 'Unknown', NULL, NULL, NULL, NULL