






CREATE VIEW [FDV].[VW_D_IFS_Bulk_Orderline_Events]
AS
with CTE_1 as
(SELECT  
	 OL.PART_NO as SKU_Name
	,LA.OLD_VALUE as Old_Value
	,LA.NEW_VALUE as New_Value
	,substring(KEYS,CHARINDEX('=',KEYS)+1,CHARINDEX('^',KEYS)-CHARINDEX('=',KEYS)-1) as Line_Item_NO
	,cast(substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)-1) as numeric) as Line_NO
	,substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)-1) as Order_NO 
	,substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)+1)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1)-1) as REL_NO
	,dateadd(hh,7,[TIME_STAMP]) as Time_Stamp
	,L.[USERNAME] as UserName
	,L.HISTORY_TYPE as History_Type
    ,LA.[OBJVERSION] as Object_Version
	,row_number() over (partition by substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)-1)
									   ,cast(substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)-1) as numeric)
									   ,substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)+1)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1)-1)
									    order by LA.OBJVERSION asc) as RN
      																																				
  FROM [IFS].[HISTORY_LOG] L
  join [IFS].[HISTORY_LOG_ATTRIBUTE] LA
  on L.LOG_ID=LA.LOG_ID
  join IFS.CUSTOMER_ORDER_LINE OL
  on
  OL.ORDER_NO=substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)-1)
  and
  OL.LINE_NO=cast(substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)-1) as numeric)
  and 
  OL.LINE_ITEM_NO=substring(KEYS,CHARINDEX('=',KEYS)+1,CHARINDEX('^',KEYS)-CHARINDEX('=',KEYS)-1)
  and 
  OL.REL_NO=substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)+1)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1)-1)
  and
  OL.ActInd='Y'

  where upper([MODULE])='ORDER'
  and upper(LU_NAME)='CUSTOMERORDERLINE'
  and substring(KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)+1,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS,CHARINDEX('^',KEYS)+1)+1)-CHARINDEX('=',KEYS,CHARINDEX('=',KEYS,CHARINDEX('=',KEYS)+1)+1)-1)like 'B%')

  SELECT C1.Order_NO 
  ,C1.Line_NO
  ,C1.Line_Item_NO
  ,C1.REL_NO
  ,C1.SKU_Name
  ,C1.Old_Value
  ,C1.New_Value
  ,C1.UserName
  ,C1.History_Type
  ,C1.Object_Version
  ,C1.Time_Stamp
  ,C1.RN
  
  from CTE_1 C1
 
UNION ALL

SELECT        '-1', '-1', '-1', '-1', NULL, NULL, NULL, NULL, NULL, NULL, NULL,'-1'