






CREATE VIEW [FDV].[VW_D_Order_Details]
AS
select
OD.TC_ORDER_ID as Order_ID
,OL.IS_CANCELLED as IS_CANCELLED
,sum(OL.ORDER_QTY) as ORDER_QTY
,ISNULL(OL.ITEM_NAME, '-1') as SKU_Name
from MANH.ORDER_LINE_ITEM as OL
join MANH.ORDERS as OD
on 
OD.ORDER_ID=OL.ORDER_ID
and OD.ActInd = 'Y'
and OL.ActInd = 'Y'
and YEAR(OL.CREATED_DTTM) > YEAR(GETDATE())-3
group by
OD.TC_ORDER_ID,OL.IS_CANCELLED,OL.ITEM_NAME 

UNION ALL

SELECT '-1','-1',NULL,'-1';