

CREATE VIEW [FDV].[VW_D_Cost_Bucked3]
AS


SELECT PCB.CONTRACT                       CONTRACT,
       PCB.PART_NO                        PART_NO,
       PCB.COST_SET                       COST_SET,
       PCB.ALTERNATIVE_NO                 ALTERNATIVE_NO,
       PCB.ROUTING_ALTERNATIVE_NO         ROUTING_ALTERNATIVE_NO,
       PCB.BUCKET_LEVEL                   BUCKET_LEVEL,
       PCB.BUCKET_SEQ                     BUCKET_SEQ,
       PCB.TOP_LEVEL_PART_NO              TOP_LEVEL_PART_NO,
       PCB.TOP_ALTERNATIVE_NO             TOP_ALTERNATIVE_NO,
       PCB.TOP_ROUTING_NO                 TOP_ROUTING_NO,
       PCB.PARENT_PART_NO                 PARENT_PART_NO,
       PCB.PARENT_BUCKET_SEQ              PARENT_BUCKET_SEQ,
       PCB.CALCULATION_DATE               CALCULATION_DATE,
       SUM(PCB.BUCKET_LEVEL_COST)         BUCKET_LEVEL_COST,
       SUM(PCB.BUCKET_ACCUM_COST)         BUCKET_ACCUM_COST,
       MAX(PCB.QTY_PER_ASSEMBLY)          QTY_PER_ASSEMBLY,
       MAX(PCB.CUMM_QTY_PER_ASSEMBLY)     CUMM_QTY_PER_ASSEMBLY,
       MAX(PCB.SPLIT_QTY_PER_ASSEMBLY)    SPLIT_QTY_PER_ASSEMBLY,
       MAX(PCB.COST_QTY_PER_ASSEMBLY)     COST_QTY_PER_ASSEMBLY
FROM   IFS.PART_COST_BUCKET PCB
INNER JOIN IFS.COST_BUCKET CB
	ON PCB.CONTRACT         = CB.CONTRACT AND    PCB.COST_BUCKET_ID   = CB.COST_BUCKET_ID 
AND   ISNULL(CB.COST_BUCKET_TYPE, 'DUMMY') != 'BUCKETS'
AND    PCB.COST_BUCKET_PUBLIC_TYPE != 'SALESOH'
GROUP BY PCB.CONTRACT, PCB.PART_NO, PCB.COST_SET, PCB.ALTERNATIVE_NO, PCB.ROUTING_ALTERNATIVE_NO,
         PCB.BUCKET_LEVEL, PCB.BUCKET_SEQ, PCB.TOP_LEVEL_PART_NO, PCB.TOP_ALTERNATIVE_NO,
         PCB.TOP_ROUTING_NO, PCB.PARENT_PART_NO, PCB.PARENT_BUCKET_SEQ, PCB.CALCULATION_DATE

UNION ALL

SELECT '-1','-1','NULL', 'NULL', 'NULL' , 'NULL', 'NULL', 'NULL' ,'NULL', 'NULL', 'NULL' , 'NULL', 'NULL', 'NULL', 'NULL', 'NULL' , 'NULL', 'NULL', 'NULL'