


















CREATE VIEW [FDV].[VW_D_Country]
AS

SELECT
	CC.COUNTRY_CODE                                  AS Country_Code
  , CC.COUNTRY_NAME                               AS Country_Name
  , CC.CNTRY_A3_CODE                AS Country_A3_Code
  , CC.ISO_CNTRY_CODE               AS Country_Iso_Code
  , CC.GEO_REGION_ID                 AS Geo_Region_Code
  , 
  CASE 
  WHEN CC.COUNTRY_CODE = 'AD' THEN 'EUROPE'
WHEN  CC.COUNTRY_CODE = 'MX' THEN 'SOUTH AMERICA'
WHEN CC.COUNTRY_CODE = 'AZ' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'DZ' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'IQ' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'IL' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'KZ' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'KG' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'MA' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'MQ' THEN 'EUROPE'
when CC.COUNTRY_CODE = 'YT' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'MU' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'RU' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'RE' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'TN' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'TR' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'GF' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'GE' THEN 'EUROPE'
WHEN CC.COUNTRY_CODE = 'RS' THEN 'EUROPE'
WHEN  CC.GEO_REGION_ID = 'SA' THEN 'SOUTH AMERICA'
WHEN CC.GEO_REGION_ID = 'AU' THEN 'AUSTRALIA'
WHEN  CC.GEO_REGION_ID  = 'AS'  THEN 'ASIA'
WHEN CC.GEO_REGION_ID = 'EU' THEN 'EUROPE'
WHEN CC.GEO_REGION_ID = 'AF' THEN 'AFRICA'
WHEN CC.GEO_REGION_ID = 'NA' THEN 'NORTH AMERICA'
WHEN CC.GEO_REGION_ID = 'CB' THEN 'CARIBBEAN'
WHEN CC.GEO_REGION_ID = 'ME' THEN 'MIDDLE-EAST'


ELSE CC.GEO_REGION_ID  END as FD_Region_Code,

CASE WHEN CC.CNTRY_A3_CODE = 'ROU' THEN 'ROM'
       WHEN CC.CNTRY_A3_CODE = 'IMN'THEN 'ILN'
		ELSE CC.CNTRY_A3_CODE END AS FD_Home_Country,
		
CASE WHEN CC.CNTRY_A3_CODE IN ('JOR', 'KWT','LBN','OMN', 'QAT', 'SAU' ) THEN 'ARE' 
				WHEN CC.CNTRY_A3_CODE IN ('BGR', 'MKD') THEN 'BGR'
				WHEN CC.CNTRY_A3_CODE IN ('BEN', 'BFA', 'CIV', 'NER', 'TGO') THEN 'CIV'
				WHEN CC.CNTRY_A3_CODE IN ('CMR', 'GBN') THEN 'CMR'
			   WHEN CC.CNTRY_A3_CODE IN ('COG', 'COD') THEN 'COD'
			   WHEN CC.CNTRY_A3_CODE IN ('AUT', 'DEU') THEN 'DEU'
			   WHEN CC.CNTRY_A3_CODE IN ( 'FRA', 'DZA', 'MAR', 'MUS' , 'REU', 'GUF', 'TUN', 'MYT')  THEN 'FRA'
			   WHEN CC.CNTRY_A3_CODE IN ( 'GHA', 'LBR' , 'SLE') THEN 'GHA'
			   WHEN CC.CNTRY_A3_CODE IN ( 'GRC' , 'CYP') THEN 'GRC'
				 WHEN CC.CNTRY_A3_CODE IN ( 'IMN' , 'IRL') THEN 'IRL'
         WHEN CC.CNTRY_A3_CODE IN ( 'MLT' , 'ITA') THEN 'ITA'
		 WHEN CC.CNTRY_A3_CODE IN ( 'BIH' , 'HUN', 'SVN', 'HRV' ) THEN 'HUN'
         WHEN CC.CNTRY_A3_CODE IN ( 'BDI' , 'KEN' , 'RWA' , 'TZA' , 'UGA') THEN 'KEN' 
         WHEN CC.CNTRY_A3_CODE IN ( 'BRN' , 'MYS' , 'SGP') THEN 'MYS' 
         WHEN CC.CNTRY_A3_CODE IN ( 'BEN' , 'NGA' ) THEN 'NGA' 
         WHEN CC.CNTRY_A3_CODE IN ( 'NLD' , 'BEL', 'LUX') THEN 'BNL'
         WHEN CC.CNTRY_A3_CODE IN ( 'ROU' , 'MDA') THEN 'ROM'
         WHEN CC.CNTRY_A3_CODE IN ( 'GIN', 'GMB' , 'GNB', 'MLI', 'MRT', 'SEN') THEN 'SEN'
         WHEN CC.CNTRY_A3_CODE IN ( 'DNK', 'SWE' , 'NOR', 'FIN') THEN 'SKA'  
           WHEN CC.CNTRY_A3_CODE IN ( 'TUR', 'AZE' , 'GEO', 'IRQ', 'KAZ', 'KGZ') THEN 'TUR'
                       WHEN CC.CNTRY_A3_CODE IN ( 'CAN' , 'USA') THEN 'USA'
                        WHEN CC.CNTRY_A3_CODE IN ( 'NAM' , 'ZAF' , 'ZMB' , 'ZWE') THEN 'ZAF'
                        ELSE CC.CNTRY_A3_CODE END AS FD_OP_Country,
-- Definition of CIM countries, used by CRS

CASE	WHEN CC.CNTRY_A3_CODE IN ('ARE' ) THEN 'ARE' 
		WHEN CC.CNTRY_A3_CODE IN ('CMR', 'GBN') THEN 'CMR'
		WHEN CC.CNTRY_A3_CODE IN ( 'FRA', 'GUF')  THEN 'FRA'
		WHEN CC.CNTRY_A3_CODE IN ( 'GHA',  'SLE') THEN 'GHA'
		WHEN CC.CNTRY_A3_CODE IN ( 'GRC' , 'CYP') THEN 'GRC'
		WHEN CC.CNTRY_A3_CODE IN ( 'IMN' , 'IRL') THEN 'IRL'
	    WHEN CC.CNTRY_A3_CODE IN ( 'MLT' , 'ITA') THEN 'ITA'
		WHEN CC.CNTRY_A3_CODE IN ( 'HUN', 'SVN' ) THEN 'HUN'
		WHEN CC.CNTRY_A3_CODE IN (  'MYS' , 'SGP') THEN 'MYS' 
		WHEN CC.CNTRY_A3_CODE IN ( 'NLD' , 'BEL', 'LUX') THEN 'BNL'
		WHEN CC.CNTRY_A3_CODE IN ( 'ROU' , 'MDA') THEN 'ROM'
        WHEN CC.CNTRY_A3_CODE IN (  'GMB' , 'SEN') THEN 'SEN'  
        WHEN CC.CNTRY_A3_CODE IN ( 'CAN' , 'USA') THEN 'USA'		
ELSE CC.CNTRY_A3_CODE END AS FD_CIM_Country_A3,
-- Country Name for CIM
CASE WHEN CC.CNTRY_A3_CODE IN ('ARE' ) THEN 'UAE' 
		WHEN CC.CNTRY_A3_CODE IN ('CMR', 'GBN') THEN 'CAMEROON'
		WHEN CC.CNTRY_A3_CODE IN ( 'FRA',   'GUF')  THEN 'FRANCE'
		WHEN CC.CNTRY_A3_CODE IN ( 'GHA',  'SLE') THEN 'GHANA'
		WHEN CC.CNTRY_A3_CODE IN ( 'GRC' , 'CYP') THEN 'GREECE'
        WHEN CC.CNTRY_A3_CODE IN ( 'IMN' , 'IRL') THEN 'IRELAND'
        WHEN CC.CNTRY_A3_CODE IN ( 'MLT' , 'ITA') THEN 'ITALY'
		WHEN CC.CNTRY_A3_CODE IN ( 'HUN', 'SVN' ) THEN 'HUNGARY'
        WHEN CC.CNTRY_A3_CODE IN (  'MYS' , 'SGP') THEN 'MALAYSIA' 
        WHEN CC.CNTRY_A3_CODE IN ( 'NLD' , 'BEL', 'LUX') THEN 'BENELUX'
        WHEN CC.CNTRY_A3_CODE IN ( 'ROU' , 'MDA') THEN 'ROMANIA'
        WHEN CC.CNTRY_A3_CODE IN (  'GMB' ,   'SEN') THEN 'SENEGAL'
		WHEN CC.CNTRY_A3_CODE IN ( 'AUT') THEN 'AUSTRIA'  
		WHEN CC.CNTRY_A3_CODE IN ( 'CAN' , 'USA') THEN 'USA'
		WHEN CC.CNTRY_A3_CODE IN ( 'DEU' ) THEN 'GERMANY'
		WHEN CC.CNTRY_A3_CODE IN ( 'GBR', 'JEY', 'GGY', 'ILN', 'FLK' ) THEN 'UK'
		WHEN CC.CNTRY_A3_CODE IN ( 'DNK' , 'SJM', 'ALA' , 'GRL'  ) THEN 'DENMARK'
		WHEN CC.CNTRY_A3_CODE IN ( 'ESP', 'PRT' ) THEN 'SPAIN'

ELSE UPPER(CC.COUNTRY_NAME) END AS FD_CIM_Full_Country,



CASE WHEN CC.CNTRY_A3_CODE IN ('JOR', 'KWT','LBN','OMN', 'QAT', 'SAU' ) THEN 'UAE GROUP' 
		WHEN CC.CNTRY_A3_CODE IN ('BGR', 'MKD') THEN 'BULGARIA GROUP'
		WHEN CC.CNTRY_A3_CODE IN ('BEN', 'BFA', 'CIV', 'NER', 'TGO') THEN 'IVORY COAST GROUP'
		WHEN CC.CNTRY_A3_CODE IN ('CMR', 'GBN') THEN 'CAMEROUN GROUP'
		WHEN CC.CNTRY_A3_CODE IN ('COG', 'COD') THEN 'DEM. REP OF CONGO GROUP'
		WHEN CC.CNTRY_A3_CODE IN ('AUT', 'DEU') THEN 'GERMANY GROUP'
		WHEN CC.CNTRY_A3_CODE IN ( 'FRA', 'MYT', 'DZA', 'MAR', 'MUS' , 'REU', 'GUF', 'TUN')  THEN 'FRANCE GROUP'
		WHEN CC.CNTRY_A3_CODE IN ( 'GHA', 'LBR' , 'SLE') THEN 'GHANA GROUP'
		WHEN CC.CNTRY_A3_CODE IN ( 'GRC' , 'CYP') THEN 'GREECE GROUP'
		WHEN CC.CNTRY_A3_CODE IN ( 'IMN' , 'IRL', 'GBR') THEN 'UK GROUP'
        WHEN CC.CNTRY_A3_CODE IN ( 'MLT' , 'ITA') THEN 'ITALY GROUP'
		WHEN CC.CNTRY_A3_CODE IN ( 'BIH' , 'HUN', 'SVN', 'HRV' ) THEN 'HUNGARY GROUP'
        WHEN CC.CNTRY_A3_CODE IN ( 'BDI' , 'KEN' , 'RWA' , 'TZA' , 'UGA') THEN 'EAST AFRICA GROUP' 
        WHEN CC.CNTRY_A3_CODE IN ( 'BRN' , 'MYS' , 'SGP') THEN 'MALYSIA GROUP' 
        WHEN CC.CNTRY_A3_CODE IN ( 'BEN' , 'NGA' ) THEN 'NIGERIA GROUP' 
        WHEN CC.CNTRY_A3_CODE IN ( 'NLD' , 'BEL', 'LUX') THEN 'BENELUX GROUP'
        WHEN CC.CNTRY_A3_CODE IN ( 'ROU' , 'MDA') THEN 'ROMENIA GROUP'
        WHEN CC.CNTRY_A3_CODE IN ( 'GIN', 'GMB' , 'GNB', 'MLI', 'MRT', 'SEN') THEN 'SENEGAL GROUP'
        WHEN CC.CNTRY_A3_CODE IN ( 'DNK', 'SWE' , 'NOR', 'FIN', 'SJM', 'ALA' , 'GRL' ) THEN 'SCANDINAVIA'  
        WHEN CC.CNTRY_A3_CODE IN ( 'TUR', 'AZE' , 'GEO', 'IRQ', 'KAZ', 'KGZ') THEN 'TURKEY GROUP'
        WHEN CC.CNTRY_A3_CODE IN ( 'CAN' , 'USA') THEN 'USA GROUP'
        WHEN CC.CNTRY_A3_CODE IN ( 'NAM' , 'ZAF' , 'ZMB' , 'ZWE') THEN 'SOUTH AFRICA GROUP'
		WHEN CC.CNTRY_A3_CODE IN ( 'ESP', 'PRT' ) THEN 'SPAIN'
        ELSE upper(CC.COUNTRY_NAME) END AS FD_Country_Group,


	CASE WHEN CC.CNTRY_A3_CODE = 'AGO' THEN 'ANGOLA' 
		 WHEN CC.CNTRY_A3_CODE = 'ARE'  THEN 'UAE'
		 WHEN CC.CNTRY_A3_CODE = 'AZE' THEN 'AZERBAIJAN'
		 WHEN CC.CNTRY_A2_CODE = 'BDI' THEN 'BURUNDI'
		 WHEN CC.CNTRY_A3_CODE = 'BEN' THEN 'BENIN'
		 WHEN CC.CNTRY_A3_CODE = 'BFA' THEN 'BURKINA FASO'
		 WHEN CC.CNTRY_A3_CODE = 'BGR' THEN 'BULGARIA'
		 WHEN CC.CNTRY_A3_CODE = 'BIH' THEN 'BOSNIA'
		 WHEN CC.CNTRY_A3_CODE = 'CHE' THEN 'SWITZERLAND'
		 WHEN CC.CNTRY_A3_CODE = 'CIV' THEN 'IVORY COAST'
		 WHEN CC.CNTRY_A3_CODE = 'CMR' THEN 'CAMEROON'
		 WHEN CC.CNTRY_A3_CODE = 'COD' THEN 'DEMOCRATIC REPUBLIC OF CONGO'
		 WHEN CC.CNTRY_A3_CODE = 'COG' THEN 'REPUBLIC OF CONGO'
		 WHEN CC.CNTRY_A3_CODE = 'CZE' THEN 'CZECH REP.'
		 WHEN CC.CNTRY_A3_CODE = 'DZA' THEN 'ALGERIA'
		 WHEN CC.CNTRY_A3_CODE = 'ESP' THEN 'SPAIN'
		 WHEN CC.CNTRY_A3_CODE = 'GAB' THEN 'GABON'
		 WHEN CC.CNTRY_A3_CODE = 'GBR' THEN 'UNITED KINGDOM'
		WHEN CC.CNTRY_A3_CODE = 'GHA' THEN 'GHANA'
		WHEN CC.CNTRY_A3_CODE = 'GAB' THEN 'GABON'
		WHEN CC.CNTRY_A3_CODE = 'GRC' THEN 'GREECE'
		WHEN CC.CNTRY_A3_CODE = 'GUF' THEN 'FRENCH GUIANA'
		WHEN CC.CNTRY_A3_CODE = 'HRV' THEN 'CROATIA'
		WHEN CC.CNTRY_A3_CODE = 'HUN' THEN 'HUNGARY'
		WHEN CC.CNTRY_A3_CODE = 'IRL' THEN 'IRELAND'
		WHEN CC.CNTRY_A3_CODE = 'IRQ' THEN 'IRAQ'
		WHEN CC.CNTRY_A3_CODE = 'ISL' THEN 'ICELAND'
		WHEN CC.CNTRY_A3_CODE = 'ISR' THEN 'ISRAEL'
		WHEN CC.CNTRY_A3_CODE = 'ITA' THEN 'ITALY'
		WHEN CC.CNTRY_A3_CODE = 'KAZ' THEN 'KAZAKHSTAN'
		WHEN CC.CNTRY_A3_CODE = 'KEN' THEN 'KENYA'
		WHEN CC.CNTRY_A3_CODE = 'KGZ' THEN 'KYRGYZSTAN'		
		WHEN CC.CNTRY_A3_CODE = 'LTU' THEN 'LITHUANIA'
		WHEN CC.CNTRY_A3_CODE = 'KGZ' THEN 'KYRGYZSTAN'
		WHEN CC.CNTRY_A3_CODE = 'LBR' THEN 'LIBERIA'
		WHEN CC.CNTRY_A3_CODE = 'MAR' THEN 'MOROCCO'
		WHEN CC.CNTRY_A3_CODE = 'MKD' THEN 'MACEDONIA'
		WHEN CC.CNTRY_A3_CODE = 'MLI' THEN 'MALI'
		WHEN CC.CNTRY_A3_CODE = 'MRT' THEN 'MAURITANIA'
		WHEN CC.CNTRY_A3_CODE = 'MTQ' THEN 'MARTINIQUE'
		WHEN CC.CNTRY_A3_CODE = 'MUS' THEN 'MAURITIUS'
		WHEN CC.CNTRY_A3_CODE = 'NAM' THEN 'NAMIBIA'
			WHEN CC.CNTRY_A3_CODE = 'MYT' THEN 'MAYOTTE'
		WHEN CC.CNTRY_A3_CODE = 'POL' THEN 'POLAND'
		WHEN CC.CNTRY_A3_CODE = 'REU' THEN 'REUNION'
		WHEN CC.CNTRY_A3_CODE = 'KGZ' THEN 'KYRGYZSTAN'
		WHEN CC.CNTRY_A3_CODE = 'ROM' THEN 'ROMANIA'
		WHEN CC.CNTRY_A3_CODE = 'RUS' THEN 'RUSSIA'
		WHEN CC.CNTRY_A3_CODE = 'RWA' THEN 'RWANDA'
		WHEN CC.CNTRY_A3_CODE = 'SEN' THEN 'SENEGAL'
		WHEN CC.CNTRY_A3_CODE = 'SLE' THEN 'SIERRA LEONE'
		WHEN CC.CNTRY_A3_CODE = 'SRB' THEN 'SERBIA'
		WHEN CC.CNTRY_A3_CODE = 'SVK' THEN 'SLOVAK REP'
		WHEN CC.CNTRY_A3_CODE = 'SVN' THEN 'SLOVENIA'
		WHEN CC.CNTRY_A3_CODE = 'TGO' THEN 'TOGO'
		WHEN CC.CNTRY_A3_CODE = 'TUN' THEN 'TUNISIA'
		WHEN CC.CNTRY_A3_CODE = 'TUR' THEN 'TURKEY'
		WHEN CC.CNTRY_A3_CODE = 'UGA' THEN 'UGANDA'
		WHEN CC.CNTRY_A3_CODE = 'UKR' THEN 'UKRAINE'
		WHEN CC.CNTRY_A3_CODE = 'ZAF' THEN 'SOUTH AFRICA'
		WHEN CC.CNTRY_A3_CODE = 'ZMB' THEN 'ZAMBIA'
		WHEN CC.CNTRY_A3_CODE = 'ZWE' THEN 'ZIMBABWE'
		WHEN CC.CNTRY_A3_CODE = 'NER' THEN 'NIGER'
		WHEN CC.CNTRY_A3_CODE = 'GIN' THEN 'GUINEA CONAKRY'
		WHEN CC.CNTRY_A3_CODE = 'QTR' THEN 'QATAR'
		WHEN CC.CNTRY_A3_CODE = 'QAT' THEN 'QATAR'
		WHEN CC.CNTRY_A3_CODE = 'OMN' THEN 'OMAN'
		WHEN CC.CNTRY_A3_CODE = 'KWT' THEN 'KUWAIT'
		WHEN CC.CNTRY_A3_CODE = 'JOR' THEN 'JORDAN'
		WHEN CC.CNTRY_A3_CODE = 'SAU' THEN 'SAUDI ARABIA'
		WHEN CC.CNTRY_A3_CODE = 'BHR' THEN 'BAHRAIN'
		WHEN CC.CNTRY_A3_CODE = 'GEO' THEN 'GEORGIA'
		WHEN CC.CNTRY_A2_CODE = 'LBN' THEN 'LEBANON'

		 
                        ELSE 'NA'
       END AS FLPI_Country,



   CASE WHEN  CC.COUNTRY_CODE in (
  'AT',
'BE',
'BG',
'CY',
'CZ',
'DE',
'DK',
'EE',
'ES',
'FI',
'FR',
'GB',
'UK',
'GG',
'GR',
'HR',
'HU',
'IE',
'IT',
'JE',
'LT',
'LU',
'LV',
'MT',
'NL',
'PL',
'PT',
'RO',
'SE',
'SI',
'YT',
'SK') then 'EU'      
     when  CC.COUNTRY_CODE in ( 
'NO') 
then 'EFTA_EU'
     when  CC.COUNTRY_CODE in ( 'CH',
'IS',
'LI') 
then 'EFTA'
       else 'NOT EU_EFTA'
       end
       as EU_FTA



FROM                  MANH.COUNTRY CC
WHERE                CC.ActInd = 'Y'

UNION ALL

SELECT
  '-1'
  , 'Unknown'
  , 'Unknown'
  , 'Unknown'
  , 'Unknown'
  , 'Unknown'
   , 'Unknown'
   , 'Unkown'
   , 'Unkown'
   , 'Unkown'
   , 'Unkown'
  , 'Unknown'
   , 'Unknown'
UNION ALL

select  'CW'
		, 'Curacau' 
		, 'CUW'
		, '531'	
		, 'SA'
		, 'SA'
		, 'CUR' 
		, 'CUR'
		, 'CUR' 
		, 'CURACAU'
		, 'CURACAU GROUP'
		, 'NA'
		, 'NOT EU_EFTA' 
--GO