
CREATE VIEW [FDV].[VW_F_Item_Usage]
AS
-- 4 Items Used

SELECT			
	CONVERT(CHAR, OD.ACTUAL_SHIPPED_DTTM, 112)		AS DateKey
	, ISNULL(OD.D_COUNTRY_CODE,'-1')				AS Country_Code
	, ISNULL(OD.DSG_SHIP_VIA,'-1')					AS Transporter_Ship_Via_Code
	, ISNULL(LP.TC_ORDER_ID,'-1')					AS Order_ID
	, ISNULL(LP.TC_LPN_ID,'-1')						AS OLPN_ID
	, ISNULL(LD.ITEM_ID,'-1')						AS SKU_Code1
	, ISNULL(LD.ITEM_ID,'-1')						AS SKU_Code2
	, ISNULL(INVP.CONTRACT,'-1')					AS Contract
	, ISNULL(LD.BATCH_NBR,'-1')						AS Lot_Code
	, ISNULL(OD.DWH_CUSTOMER_ID,'-1')				AS Customer_ID
	, ISNULL(BOM.BOM_ID,'-1')				        AS BOM_ID
	, ISNULL(INVP.PART_PRODUCT_FAMILY,'-1')			AS FAM_Prod_ID
	,BOM.QTY_Per_Assembley_Verkoop*LD.SIZE_VALUE	AS Number_Of_Items_Used
	, 0											    AS Number_Of_Items_Direct_Shipped_Bulk
	
FROM			MANH.LPN_DETAIL	AS LD
INNER JOIN		MANH.LPN_OUTBOUND AS LP 
ON				LP.LPN_ID = LD.LPN_ID
AND				LP.LPN_FACILITY_STATUS <> 99
AND				LP.ActInd = 'Y'
INNER JOIN		MANH.ORDERS AS OD 
ON				OD.ORDER_ID = LP.ORDER_ID 
AND				OD.ActInd = 'Y'
INNER JOIN		MANH.ITEM_CBO IC
ON				IC.ITEM_ID = LD.ITEM_ID
AND				IC.ActInd = 'Y'
INNER JOIN		IFS.INVENTORY_PART INVP
ON				INVP.PART_NO=IC.ITEM_NAME
AND				INVP.ActInd='Y'
AND				INVP.CONTRACT='FD01'
AND				IC.ActInd='Y'
LEFT JOIN		(SELECT
					OL.ORDER_ID
					, OL.ITEM_NAME
					, MAX(OL.CUSTOMER_ITEM) AS CUSTOMER_ITEM
				 FROM		MANH.ORDER_LINE_ITEM OL
				 WHERE 		OL.ActInd = 'Y' 
				 AND		OL.IS_CANCELLED = 0
				 GROUP BY
					OL.ORDER_ID
					, OL.ITEM_NAME
) OL ON			OL.ORDER_ID = OD.ORDER_ID
AND				OL.ITEM_NAME = IC.ITEM_NAME
INNER JOIN			[ForeverData01].[DM].[D_BOM_Explosie] BOM
ON
IC.ITEM_NAME=BOM.Sales_Part_Level_0
and BOM.IsDeleted='0'



LEFT JOIN		MANH.FACILITY_ALIAS	AS FA 
ON				FA.FACILITY_ALIAS_ID = OD.BILL_FACILITY_ALIAS_ID 
AND				FA.ActInd = 'Y'
WHERE			OD.DO_STATUS = '190' 
AND				LD.ActInd = 'Y'
AND				OD.ACTUAL_SHIPPED_DTTM >= DATEADD(yy, DATEDIFF(yy, 0, GETDATE()) - 1, 0)



UNION ALL
-- 5 Items_Direct_Shipped_Bulk
SELECT			
	CONVERT(CHAR, OD.ACTUAL_SHIPPED_DTTM, 112)		AS DateKey
	, ISNULL(OD.D_COUNTRY_CODE,'-1')				AS Country_Code
	, ISNULL(OD.DSG_SHIP_VIA,'-1')					AS Transporter_Ship_Via_Code
	, ISNULL(LP.TC_ORDER_ID,'-1')					AS Order_ID
	, ISNULL(LP.TC_LPN_ID,'-1')						AS OLPN_ID
	, ISNULL(LD.ITEM_ID,'-1')						AS SKU_Code1
	, ISNULL(LD.ITEM_ID,'-1')						AS SKU_Code2
	, ISNULL(INVP.CONTRACT,'-1')					AS Contract
	, ISNULL(LD.BATCH_NBR,'-1')						AS Lot_Code
	, ISNULL(OD.DWH_CUSTOMER_ID,'-1')				AS Customer_ID
	, '-1'											AS BOM_ID
	, ISNULL(INVP.PART_PRODUCT_FAMILY,'-1')			AS FAM_Prod_ID
	, 0												AS Number_Of_Items_Used
	,LD.SIZE_VALUE								    AS Number_Of_Items_Direct_Shipped_Bulk
	
FROM			MANH.LPN_DETAIL	AS LD
INNER JOIN		MANH.LPN_OUTBOUND AS LP 
ON				LP.LPN_ID = LD.LPN_ID
AND				LP.LPN_FACILITY_STATUS <> 99
AND				LP.ActInd = 'Y'
INNER JOIN		MANH.ORDERS AS OD 
ON				OD.ORDER_ID = LP.ORDER_ID 
AND				OD.ActInd = 'Y'
INNER JOIN		MANH.ITEM_CBO IC
ON				IC.ITEM_ID = LD.ITEM_ID
AND				IC.ActInd = 'Y'
LEFT JOIN		(SELECT
					OL.ORDER_ID
					, OL.ITEM_NAME
					, MAX(OL.CUSTOMER_ITEM) AS CUSTOMER_ITEM
				 FROM		MANH.ORDER_LINE_ITEM OL
				 WHERE 		OL.ActInd = 'Y' 
				 AND		OL.IS_CANCELLED = 0
				 GROUP BY
					OL.ORDER_ID
					, OL.ITEM_NAME
) OL ON			OL.ORDER_ID = OD.ORDER_ID
AND				OL.ITEM_NAME = IC.ITEM_NAME
INNER JOIN		IFS.INVENTORY_PART INVP
ON				INVP.PART_NO=IC.ITEM_NAME
AND				INVP.TYPE_CODE='Purchased (raw)'
AND				INVP.ActInd='Y'
AND				INVP.CONTRACT='FD01'
AND				IC.ActInd='Y'
LEFT JOIN		MANH.FACILITY_ALIAS	AS FA 
ON				FA.FACILITY_ALIAS_ID = OD.BILL_FACILITY_ALIAS_ID 
AND				FA.ActInd = 'Y'
WHERE			OD.DO_STATUS = '190' 
AND				LD.ActInd = 'Y'
AND				OD.ORDER_TYPE in ('BK', 'OF')
AND				OD.ACTUAL_SHIPPED_DTTM >= DATEADD(yy, DATEDIFF(yy, 0, GETDATE()) - 1, 0)