

CREATE VIEW [FDV].[VW_F_Parcel_Status]
AS

SELECT DISTINCT
			SHIPPER_SHIPMENT_REF		AS Parcel_Status_OLPN_ID
			, FS.STATUS					AS Parcel_Status_Code
			, FS.STATUS_DATE			AS Parcel_Status_Status_Date
			, FS.FORWARDER_STATUS_CODE  AS Parcel_Status_Forwarder_Code
			, FC.STATUS_CATEGORY		AS Parcel_Status_Category
			, FC.DESCRIPTION			AS Parcel_Status_Description
FROM        TRANS.FORWARDER_STATUS AS FS
LEFT JOIN	TRANS.HUB_FORWARDER AS HF
ON			FS.HUB_FORWARDER_ID	= HF.HUB_FORWARDER_ID
AND			HF.ActInd='Y'
LEFT JOIN	TRANS.FORWARDER_STATUS_CODE AS FC
ON			FS.FORWARDER_CODE = FC.FORWARDER_CODE
AND			FS.FORWARDER_STATUS_CODE = FC.FORWARDER_STATUS_CODE
AND			FC.ActInd = 'Y'

UNION ALL

SELECT DISTINCT
			SHIPPER_SHIPMENT_REF				AS Parcel_Status_OLPN_ID
			, FS.SHIPMENT_EVENT_DESCRIPTION		AS Parcel_Status_Code
			, FS.SHIPMENT_EVENT_TS				AS Parcel_Status_Status_Date
			, FS.FORWARDER_EVENT_CODE			AS Parcel_Status_Forwarder_Code
			, FS.SHIPMENT_STATUS				AS Parcel_Status_Category
			, FC.DESCRIPTION					AS Parcel_Status_Description
FROM        TPX7.VW_FORWARDER_STATUS AS FS
LEFT JOIN	TPX7.VW_FORWARDER AS HF
ON			FS.FORWARDER_CODE	= HF.FORWARDER_CODE
AND			HF.ActInd='Y'
LEFT JOIN	TPX7.VW_FORWARDER_EVENT AS FC
ON			FS.FORWARDER_CODE = FC.FORWARDER_CODE
AND			FS.FORWARDER_EVENT_CODE = FC.FORWARDER_EVENT_CODE
AND			FC.ActInd = 'Y'