CREATE TABLE [dbo].[Main_FLPSLS] (
    [OP-CO]     VARCHAR (50) NULL,
    [HOME-CO]   VARCHAR (50) NULL,
    [PROC-YR]   VARCHAR (50) NULL,
    [PROC-MO]   VARCHAR (50) NULL,
    [REGION]    VARCHAR (50) NULL,
    [PROD#]     VARCHAR (50) NULL,
    [PROD-DESC] VARCHAR (50) NULL,
    [AVA#]      VARCHAR (50) NULL,
    [AVA-DESC]  VARCHAR (50) NULL,
    [CAT#]      VARCHAR (50) NULL,
    [CAT-DESC]  VARCHAR (50) NULL,
    [QUANTITY]  VARCHAR (50) NULL,
    [CASE-CRED] VARCHAR (50) NULL
);

