CREATE TABLE [MANH_ARC].[ER_ITEM_FACILITY_MAPPING_WMS] (
    [ITEM_FACILITY_MAPPING_ID]       BIGINT          NULL,
    [LPN_PER_TIER]                   INT             NULL,
    [TIER_PER_PLT]                   INT             NULL,
    [CASE_SIZE_TYPE]                 NVARCHAR (3)    NULL,
    [PICK_RATE]                      NUMERIC (9, 4)  NULL,
    [WAGE_VALUE]                     NUMERIC (9, 4)  NULL,
    [PACK_RATE]                      NUMERIC (13, 4) NULL,
    [SPL_PROC_RATE]                  NUMERIC (9, 4)  NULL,
    [AUTO_SUB_CASE]                  NVARCHAR (1)    NULL,
    [ASSIGN_DYNAMIC_ACTV_PICK_SITE]  NVARCHAR (1)    NULL,
    [ASSIGN_DYNAMIC_CASE_PICK_SITE]  NVARCHAR (1)    NULL,
    [PICK_LOCN_ASSIGN_TYPE]          NVARCHAR (3)    NULL,
    [PUTWY_TYPE]                     NVARCHAR (3)    NULL,
    [DFLT_WAVE_PROC_TYPE]            INT             NULL,
    [XCESS_WAVE_NEED_PROC_TYPE]      INT             NULL,
    [ALLOC_TYPE]                     NVARCHAR (3)    NULL,
    [VIOLATE_FIFO_ALLOC_QTY_MATCH]   NVARCHAR (1)    NULL,
    [QV_ITEM_GRP]                    NVARCHAR (3)    NULL,
    [QUAL_INSPCT_ITEM_GRP]           NVARCHAR (3)    NULL,
    [MAX_UNITS_IN_DYNAMIC_ACTV]      NUMERIC (13, 5) NULL,
    [MAX_CASES_IN_DYNAMIC_ACTV]      INT             NULL,
    [MAX_UNITS_IN_DYNAMIC_CASE_PICK] NUMERIC (13, 5) NULL,
    [MAX_CASES_IN_DYNAMIC_CASE_PICK] INT             NULL,
    [CASE_CNT_DATE_TIME]             DATETIME2 (7)   NULL,
    [ACTV_CNT_DATE_TIME]             DATETIME2 (7)   NULL,
    [CASE_PICK_CNT_DATE_TIME]        DATETIME2 (7)   NULL,
    [VENDOR_CARTON_PER_TIER]         INT             NULL,
    [VENDOR_TIER_PER_PLT]            INT             NULL,
    [ORD_CARTON_PER_TIER]            INT             NULL,
    [ORD_TIER_PER_PLT]               INT             NULL,
    [DFLT_CATCH_WT_METHOD]           NVARCHAR (1)    NULL,
    [DFLT_DATE_MASK]                 NVARCHAR (11)   NULL,
    [CARTON_BREAK_ATTR]              NVARCHAR (3)    NULL,
    [MISC_SHORT_ALPHA_1]             NVARCHAR (3)    NULL,
    [MISC_SHORT_ALPHA_2]             NVARCHAR (3)    NULL,
    [MISC_ALPHA_1]                   NVARCHAR (10)   NULL,
    [MISC_ALPHA_2]                   NVARCHAR (10)   NULL,
    [MISC_ALPHA_3]                   NVARCHAR (10)   NULL,
    [MISC_NUMERIC_1]                 NUMERIC (9, 3)  NULL,
    [MISC_NUMERIC_2]                 NUMERIC (9, 3)  NULL,
    [MISC_NUMERIC_3]                 NUMERIC (9, 3)  NULL,
    [MISC_DATE_1]                    DATETIME2 (7)   NULL,
    [MISC_DATE_2]                    DATETIME2 (7)   NULL,
    [CHUTE_ASSIGN_TYPE]              NVARCHAR (3)    NULL,
    [ACTV_REPL_ORGN]                 NVARCHAR (1)    NULL,
    [UIN_NBR]                        NVARCHAR (57)   NULL,
    [FIFO_RANGE]                     INT             NULL,
    [PRTL_CASE_ALLOC_THRESH_UNITS]   NUMERIC (13, 4) NULL,
    [PRTL_CASE_PUTWY_THRESH_UNITS]   NUMERIC (13, 4) NULL,
    [VENDOR_TAGGED_EPC_FLAG]         NVARCHAR (1)    NULL,
    [ITEM_AVG_WT]                    NUMERIC (13, 4) NULL,
    [DFLT_MIN_FROM_PREV_LOCN_FLAG]   NVARCHAR (1)    NULL,
    [SLOT_MISC_1]                    NVARCHAR (15)   NULL,
    [SLOT_MISC_2]                    NVARCHAR (15)   NULL,
    [SLOT_MISC_3]                    NVARCHAR (15)   NULL,
    [SLOT_MISC_4]                    NVARCHAR (15)   NULL,
    [SLOT_MISC_5]                    NVARCHAR (15)   NULL,
    [SLOT_MISC_6]                    NVARCHAR (15)   NULL,
    [SLOT_ROTATE_EACHES_FLAG]        NVARCHAR (1)    NULL,
    [SLOT_ROTATE_INNERS_FLAG]        NVARCHAR (1)    NULL,
    [SLOT_ROTATE_BINS_FLAG]          NVARCHAR (1)    NULL,
    [SLOT_ROTATE_CASES_FLAG]         NVARCHAR (1)    NULL,
    [SLOT_3D_SLOTTING_FLAG]          NVARCHAR (1)    NULL,
    [SLOT_NEST_EACHES_FLAG]          NVARCHAR (1)    NULL,
    [SLOT_INCR_HT]                   NUMERIC (7, 2)  NULL,
    [SLOT_INCR_LEN]                  NUMERIC (7, 2)  NULL,
    [SLOT_INCR_WIDTH]                NUMERIC (7, 2)  NULL,
    [NBR_OF_DYN_ACTV_PICK_PER_ITEM]  INT             NULL,
    [NBR_OF_DYN_CASE_PICK_PER_ITEM]  INT             NULL,
    [AUDIT_CREATED_SOURCE]           NVARCHAR (100)  NULL,
    [AUDIT_CREATED_SOURCE_TYPE]      INT             NULL,
    [AUDIT_CREATED_DTTM]             DATETIME2 (7)   NULL,
    [AUDIT_LAST_UPDATED_SOURCE]      NVARCHAR (100)  NULL,
    [AUDIT_LAST_UPDATED_SOURCE_TYPE] INT             NULL,
    [AUDIT_LAST_UPDATED_DTTM]        DATETIME2 (7)   NULL,
    [MARK_FOR_DELETION]              INT             NULL,
    [ITEM_ID]                        INT             NULL,
    [FACILITY_ID]                    INT             NULL,
    [BUSINESS_PARTNER_ID]            NVARCHAR (10)   NULL,
    [AVERAGE_MOVEMENT]               NUMERIC (9, 2)  NULL,
    [ACTION]                         NVARCHAR (2)    NULL,
    [ESIGN_USER_ID]                  NVARCHAR (15)   NULL,
    [DB_SID]                         INT             NULL,
    [TRANSACTION_ID]                 INT             NULL,
    [EREC_CREATE_DATE_TIME]          DATETIME2 (7)   NULL,
    [DB_USERNAME]                    NVARCHAR (30)   NULL,
    [CLIENT_MACHINE_NAME]            NVARCHAR (64)   NULL,
    [CLIENT_OS_USER]                 NVARCHAR (30)   NULL,
    [CLIENT_MODULE]                  NVARCHAR (12)   NULL,
    [CLIENT_SQL]                     NVARCHAR (1000) NULL,
    [ER_ITEM_FACILITY_MAPPING_W_ID]  BIGINT          NULL,
    [BatchID]                        BIGINT          NULL,
    [ProcessLogID]                   BIGINT          NULL
)
WITH (DATA_COMPRESSION = PAGE);



