CREATE TABLE [MANH_ARC].[ER_RESV_LOCN_HDR] (
    [LOCN_ID]               NVARCHAR (10)   NULL,
    [LOCN_SIZE_TYPE]        NVARCHAR (3)    NULL,
    [LOCN_PUTAWAY_LOCK]     NVARCHAR (2)    NULL,
    [INVN_LOCK_CODE]        NVARCHAR (2)    NULL,
    [CURR_WT]               NUMERIC (13, 4) NULL,
    [DIRCT_WT]              NUMERIC (13, 4) NULL,
    [MAX_WT]                NUMERIC (13, 4) NULL,
    [CURR_VOL]              NUMERIC (13, 4) NULL,
    [DIRCT_VOL]             NUMERIC (13, 4) NULL,
    [MAX_VOL]               NUMERIC (13, 4) NULL,
    [CURR_UOM_QTY]          NUMERIC (9, 2)  NULL,
    [DIRCT_UOM_QTY]         NUMERIC (9, 2)  NULL,
    [MAX_UOM_QTY]           NUMERIC (15, 5) NULL,
    [CREATE_DATE_TIME]      DATETIME2 (7)   NULL,
    [MOD_DATE_TIME]         DATETIME2 (7)   NULL,
    [USER_ID]               NVARCHAR (15)   NULL,
    [DEDCTN_BATCH_NBR]      NVARCHAR (15)   NULL,
    [DEDCTN_PACK_QTY]       NUMERIC (9, 2)  NULL,
    [PACK_ZONE]             NVARCHAR (4)    NULL,
    [SORT_LOCN_FLAG]        INT             NULL,
    [INBD_STAGING_FLAG]     NVARCHAR (1)    NULL,
    [RESV_LOCN_HDR_ID]      INT             NULL,
    [WM_VERSION_ID]         INT             NULL,
    [DEDCTN_ITEM_ID]        INT             NULL,
    [LOCN_HDR_ID]           INT             NULL,
    [ACTION]                NVARCHAR (2)    NULL,
    [ESIGN_USER_ID]         NVARCHAR (15)   NULL,
    [DB_SID]                INT             NULL,
    [TRANSACTION_ID]        INT             NULL,
    [EREC_CREATE_DATE_TIME] DATETIME2 (7)   NULL,
    [DB_USERNAME]           NVARCHAR (30)   NULL,
    [CLIENT_MACHINE_NAME]   NVARCHAR (64)   NULL,
    [CLIENT_OS_USER]        NVARCHAR (30)   NULL,
    [CLIENT_MODULE]         NVARCHAR (12)   NULL,
    [CLIENT_SQL]            NVARCHAR (1000) NULL,
    [ER_RESV_LOCN_HDR_ID]   INT             NULL,
    [BatchID]               BIGINT          NULL,
    [ProcessLogID]          BIGINT          NULL
) ON [DWH_MANH_ARC];





