CREATE TABLE [MANH_ARC].[ILM_TASKS] (
    [TASK_ID]                  INT             NOT NULL,
    [TASK_TYPE]                INT             NOT NULL,
    [STATUS]                   INT             NOT NULL,
    [ASSIGNED_USER_ID]         NVARCHAR (32)   NULL,
    [CREATED_SOURCE]           NVARCHAR (32)   NOT NULL,
    [CREATED_DTTM]             DATETIME2 (7)   NOT NULL,
    [LAST_UPDATED_DTTM]        DATETIME2 (7)   NULL,
    [LAST_UPDATED_SOURCE]      NVARCHAR (32)   NULL,
    [PRIORITY]                 INT             NOT NULL,
    [COMPANY_ID]               INT             NULL,
    [REASON_CODE_ID]           INT             NULL,
    [PARENT_TASK_ID]           INT             NULL,
    [IS_USER_INITIATED]        NVARCHAR (1)    NULL,
    [TASK_DETAILS]             NVARCHAR (2000) NULL,
    [TASK_EXECUTION_DETAILS]   NVARCHAR (2000) NULL,
    [YARD_ID]                  INT             NULL,
    [TASK_START_TIME]          DATETIME2 (7)   NULL,
    [TASK_END_TIME]            DATETIME2 (7)   NULL,
    [TASK_RELEASE_TIME]        DATETIME2 (7)   NULL,
    [COMMENTS]                 NVARCHAR (500)  NULL,
    [CREATED_SOURCE_TYPE]      INT             NULL,
    [LAST_UPDATED_SOURCE_TYPE] INT             NULL,
    [TRAILER_ID]               INT             NULL,
    [DEST_LOCATION_ID]         INT             NULL,
    [SOURCE_LOCATION_ID]       INT             NULL,
    [LOAD_POSITION]            INT             NULL,
    [PARENT_LOCATION_ID]       INT             NULL,
    [DEST_LOCN_ID]             NVARCHAR (10)   NULL,
    [SOURCE_LOCN_ID]           NVARCHAR (10)   NULL,
    [SEAL_NUMBER]              NVARCHAR (100)  NULL,
    [FACILITY_ID]              INT             NULL,
    [Eff_Date]                 DATE            NOT NULL,
    [End_Date]                 DATE            NULL,
    [ActInd]                   CHAR (1)        NULL,
    [IsDeleted]                CHAR (1)        NULL,
    [BatchID]                  BIGINT          NULL,
    [ProcessLogID]             BIGINT          NULL,
    CONSTRAINT [PK_MANH_ILM_TASKS] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [TASK_ID] ASC) ON [DWH_MANH_ARC]
) ON [DWH_MANH_ARC];





