CREATE TABLE [MANH_ARC].[INVN_VARI_HDR] (
    [WHSE]                   NVARCHAR (3)    NOT NULL,
    [CASE_NBR]               NVARCHAR (20)   NULL,
    [BEF_BKG_CASE_STAT_CODE] SMALLINT        NOT NULL,
    [AFT_BKG_CASE_STAT_CODE] SMALLINT        NOT NULL,
    [FROZN_LOCN_ID]          NVARCHAR (10)   NULL,
    [CNT_LOCN_ID]            NVARCHAR (10)   NULL,
    [CMNT]                   NVARCHAR (255)  NULL,
    [FOLLOW_UP_REQD]         NVARCHAR (1)    NULL,
    [CREATE_DATE_TIME]       DATETIME2 (7)   NULL,
    [MOD_DATE_TIME]          DATETIME2 (7)   NULL,
    [USER_ID]                NVARCHAR (15)   NULL,
    [FROZN_PLT_ID]           NVARCHAR (20)   NULL,
    [CNT_PLT_ID]             NVARCHAR (20)   NULL,
    [INVN_TYPE]              NVARCHAR (1)    NULL,
    [PROD_STAT]              NVARCHAR (3)    NULL,
    [BATCH_NBR]              NVARCHAR (15)   NULL,
    [FROZN_INVN_QTY]         NUMERIC (13, 5) NOT NULL,
    [CNT_INVN_QTY]           NUMERIC (13, 5) NOT NULL,
    [PROD_TYPE]              NVARCHAR (1)    NULL,
    [CNT_PACK_QTY]           NUMERIC (9, 2)  NOT NULL,
    [FROZN_PACK_QTY]         NUMERIC (9, 2)  NOT NULL,
    [INVN_VARI_HDR_ID]       INT             NOT NULL,
    [WM_VERSION_ID]          INT             NOT NULL,
    [CASE_HDR_ID]            INT             NULL,
    [PHYS_INVN_HDR_ID]       INT             NULL,
    [STAT_CODE]              INT             NOT NULL,
    [PHYS_INVN_VARI_HDR_ID]  INT             NULL,
    [LPN_ID]                 BIGINT          NULL,
    [ITEM_ID]                INT             NULL,
    [ITEM_ATTR_1]            NVARCHAR (10)   NULL,
    [ITEM_ATTR_2]            NVARCHAR (10)   NULL,
    [ITEM_ATTR_3]            NVARCHAR (10)   NULL,
    [ITEM_ATTR_4]            NVARCHAR (10)   NULL,
    [ITEM_ATTR_5]            NVARCHAR (10)   NULL,
    [CNTRY_OF_ORGN]          NVARCHAR (4)    NULL,
    [RSN_CODE]               NVARCHAR (2)    NULL,
    [FROZN_INVN_CONFIG_ID]   INT             NOT NULL,
    [Eff_Date]               DATE            NOT NULL,
    [End_Date]               DATE            NULL,
    [ActInd]                 CHAR (1)        NULL,
    [IsDeleted]              CHAR (1)        NULL,
    [BatchID]                BIGINT          NULL,
    [ProcessLogID]           BIGINT          NULL,
    CONSTRAINT [PK_MANH_INVN_VARI_HDR] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [INVN_VARI_HDR_ID] ASC) ON [DWH_MANH_ARC]
) ON [DWH_MANH_ARC];

