CREATE TABLE [MANH_ARC].[OUTPT_ORDER_LINE_ITEM] (
    [ACTUAL_COST_CURRENCY_CODE]  NVARCHAR (3)    NULL,
    [ACTUAL_SHIPPED_DTTM]        DATETIME2 (7)   NULL,
    [ASSORT_NBR]                 NVARCHAR (30)   NULL,
    [BACK_ORD_QTY]               DECIMAL (13, 2) NULL,
    [BATCH_CTRL_NBR]             NVARCHAR (10)   NOT NULL,
    [BATCH_NBR]                  NVARCHAR (15)   NULL,
    [CNTRY_OF_ORGN]              NVARCHAR (4)    NULL,
    [COMMODITY_CLASS]            NVARCHAR (10)   NULL,
    [CREATED_DTTM]               DATETIME2 (7)   NOT NULL,
    [CREATED_SOURCE]             NVARCHAR (25)   NULL,
    [CREATED_SOURCE_TYPE]        INT             NOT NULL,
    [CUSTOMER_ITEM]              NVARCHAR (30)   NULL,
    [EXP_INFO_CODE]              NVARCHAR (2)    NULL,
    [GTIN]                       NVARCHAR (25)   NULL,
    [INVC_BATCH_NBR]             INT             NOT NULL,
    [INVN_TYPE]                  NVARCHAR (1)    NULL,
    [ITEM_ATTR_1]                NVARCHAR (10)   NULL,
    [ITEM_ATTR_2]                NVARCHAR (10)   NULL,
    [ITEM_ATTR_3]                NVARCHAR (10)   NULL,
    [ITEM_ATTR_4]                NVARCHAR (10)   NULL,
    [ITEM_ATTR_5]                NVARCHAR (10)   NULL,
    [ITEM_ID]                    INT             NULL,
    [LAST_UPDATED_DTTM]          DATETIME2 (7)   NOT NULL,
    [LAST_UPDATED_SOURCE]        NVARCHAR (25)   NULL,
    [LAST_UPDATED_SOURCE_TYPE]   INT             NOT NULL,
    [LINE_ITEM_ID]               INT             NOT NULL,
    [LINE_TYPE]                  NVARCHAR (1)    NULL,
    [MANUFACTURING_DTTM]         DATETIME2 (7)   NULL,
    [MISC_INSTR_10_BYTE_1]       NVARCHAR (10)   NULL,
    [MISC_INSTR_10_BYTE_2]       NVARCHAR (10)   NULL,
    [ORDER_QTY]                  DECIMAL (13, 4) NULL,
    [ORDER_QTY_UOM]              NVARCHAR (50)   NULL,
    [ORIG_ITEM_ID]               INT             NULL,
    [ORIG_ORDER_LINE_ITEM_ID]    INT             NULL,
    [ORIG_ORDER_QTY]             DECIMAL (13, 4) NULL,
    [ORIG_ORDER_QTY_UOM]         NVARCHAR (50)   NULL,
    [OUTPT_ORDER_LINE_ITEM_ID]   INT             NOT NULL,
    [PARENT_LINE_ITEM_ID]        INT             NULL,
    [PICKUP_END_DTTM]            DATETIME2 (7)   NULL,
    [PICKUP_REFERENCE_NUMBER]    NVARCHAR (30)   NULL,
    [PICKUP_START_DTTM]          DATETIME2 (7)   NULL,
    [PLANNED_QUANTITY]           DECIMAL (13, 4) NOT NULL,
    [PLANNED_QUANTITY_UOM]       NVARCHAR (50)   NULL,
    [PLANNED_SHIP_DATE]          DATETIME2 (7)   NULL,
    [PPACK_GRP_CODE]             NVARCHAR (8)    NULL,
    [PPACK_QTY]                  DECIMAL (13, 4) NOT NULL,
    [PRICE]                      DECIMAL (13, 4) NULL,
    [PRICE_TKT_TYPE]             NVARCHAR (3)    NULL,
    [PROC_DTTM]                  DATETIME2 (7)   NOT NULL,
    [PROC_STAT_CODE]             INT             NOT NULL,
    [PRODUCT_STATUS]             NVARCHAR (3)    NULL,
    [PURCHASE_ORDER_LINE_NUMBER] NVARCHAR (30)   NULL,
    [REASON_CODE]                NVARCHAR (2)    NULL,
    [REC_PROC_FLAG]              NVARCHAR (1)    NULL,
    [REC_XPANS_FIELD]            NVARCHAR (20)   NULL,
    [RETAIL_PRICE]               DECIMAL (16, 4) NULL,
    [SHIPPED_QTY]                DECIMAL (13, 4) NULL,
    [TC_COMPANY_ID]              INT             NULL,
    [UNIT_VOL]                   DECIMAL (16, 4) NULL,
    [UNIT_WT]                    DECIMAL (16, 4) NULL,
    [UOM]                        NVARCHAR (50)   NULL,
    [USER_CANCELED_QTY]          DECIMAL (13, 4) NULL,
    [VERSION_NBR]                INT             NOT NULL,
    [AISLE]                      NVARCHAR (4)    NULL,
    [AREA]                       NVARCHAR (4)    NULL,
    [BAY]                        NVARCHAR (4)    NULL,
    [LVL]                        NVARCHAR (4)    NULL,
    [POSN]                       NVARCHAR (4)    NULL,
    [ZONE]                       NVARCHAR (4)    NULL,
    [ITEM_COLOR]                 NVARCHAR (50)   NULL,
    [ITEM_COLOR_SFX]             NVARCHAR (8)    NULL,
    [ITEM_SEASON]                NVARCHAR (16)   NULL,
    [ITEM_SEASON_YEAR]           NVARCHAR (4)    NULL,
    [ITEM_SECOND_DIM]            NVARCHAR (50)   NULL,
    [ITEM_SIZE_DESC]             NVARCHAR (50)   NULL,
    [ITEM_QUALITY]               NVARCHAR (1)    NULL,
    [ITEM_STYLE]                 NVARCHAR (50)   NULL,
    [ITEM_STYLE_SFX]             NVARCHAR (8)    NULL,
    [SIZE_RANGE_CODE]            NVARCHAR (50)   NULL,
    [SIZE_REL_POSN_IN_TABLE]     NVARCHAR (2)    NULL,
    [SHELF_DAYS]                 INT             NULL,
    [TEMP_ZONE]                  INT             NULL,
    [ORIG_ITEM_COLOR]            NVARCHAR (50)   NULL,
    [ORIG_ITEM_COLOR_SFX]        NVARCHAR (8)    NULL,
    [ORIG_ITEM_SEASON]           NVARCHAR (16)   NULL,
    [ORIG_ITEM_SEASON_YEAR]      NVARCHAR (4)    NULL,
    [ORIG_ITEM_SECOND_DIM]       NVARCHAR (50)   NULL,
    [ORIG_ITEM_SIZE_DESC]        NVARCHAR (50)   NULL,
    [ORIG_ITEM_QUALITY]          NVARCHAR (1)    NULL,
    [ORIG_ITEM_STYLE]            NVARCHAR (50)   NULL,
    [ORIG_ITEM_STYLE_SFX]        NVARCHAR (8)    NULL,
    [TC_ORDER_ID]                NVARCHAR (50)   NOT NULL,
    [TC_PURCHASE_ORDERS_ID]      NVARCHAR (50)   NULL,
    [ITEM_NAME]                  NVARCHAR (100)  NULL,
    [ACTUAL_COST]                DECIMAL (13, 4) NULL,
    [TC_ORDER_LINE_ID]           NVARCHAR (30)   NULL,
    [PURCHASE_ORDER_NUMBER]      NVARCHAR (50)   NULL,
    [EXT_PURCHASE_ORDER]         NVARCHAR (50)   NULL,
    [Eff_Date]                   DATE            NOT NULL,
    [End_Date]                   DATE            NULL,
    [ActInd]                     CHAR (1)        NULL,
    [IsDeleted]                  CHAR (1)        NULL,
    [BatchID]                    BIGINT          NULL,
    [ProcessLogID]               BIGINT          NULL,
    CONSTRAINT [PK_MANH_OUTPT_ORDER_LINE_ITEM] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [OUTPT_ORDER_LINE_ITEM_ID] ASC) ON [DWH_MANH_ARC]
) ON [DWH_MANH_ARC];





