CREATE TABLE [MANH_ARC].[OUTPT_LPN] (
    [ACTUAL_CHARGE]                 DECIMAL (9, 2)  NULL,
    [ACTUAL_CHARGE_CURRENCY]        NVARCHAR (40)   NULL,
    [ACTUAL_MONETARY_VALUE]         DECIMAL (13, 4) NULL,
    [ACTUAL_VOLUME]                 DECIMAL (13, 4) NULL,
    [ADDNL_OPTION_CHARGE]           DECIMAL (9, 2)  NULL,
    [ADDNL_OPTION_CHARGE_CURRENCY]  NVARCHAR (40)   NULL,
    [ADF_TRANSMIT_FLAG]             NVARCHAR (1)    NULL,
    [AUDITOR_USERID]                NVARCHAR (15)   NULL,
    [BASE_CHARGE]                   DECIMAL (13, 4) NULL,
    [BASE_CHARGE_CURRENCY]          NVARCHAR (40)   NULL,
    [BILL_OF_LADING_NUMBER]         NVARCHAR (30)   NULL,
    [C_FACILITY_ALIAS_ID]           NVARCHAR (16)   NULL,
    [COD_AMOUNT]                    DECIMAL (13, 4) NULL,
    [COD_PAYMENT_METHOD]            INT             NULL,
    [CONTAINER_SIZE]                NVARCHAR (3)    NULL,
    [CONTAINER_TYPE]                NVARCHAR (3)    NULL,
    [CREATED_DTTM]                  DATETIME2 (7)   NOT NULL,
    [CREATED_SOURCE]                NVARCHAR (25)   NULL,
    [CREATED_SOURCE_TYPE]           INT             NOT NULL,
    [DECLARED_MONETARY_VALUE]       DECIMAL (13, 4) NULL,
    [DIST_CHARGE]                   DECIMAL (11, 2) NULL,
    [DIST_CHARGE_CURRENCY]          NVARCHAR (40)   NULL,
    [EPC_MATCH_FLAG]                NVARCHAR (1)    NULL,
    [ESTIMATED_WEIGHT]              DECIMAL (13, 4) NULL,
    [FINAL_DEST_FACILITY_ALIAS_ID]  NVARCHAR (16)   NULL,
    [FREIGHT_CHARGE]                DECIMAL (11, 2) NULL,
    [FREIGHT_CHARGE_CURRENCY]       NVARCHAR (40)   NULL,
    [INSUR_CHARGE]                  DECIMAL (9, 2)  NULL,
    [INSUR_CHARGE_CURRENCY]         NVARCHAR (40)   NULL,
    [INVC_BATCH_NBR]                INT             NOT NULL,
    [LAST_UPDATED_DTTM]             DATETIME2 (7)   NOT NULL,
    [LOADED_DTTM]                   DATETIME2 (7)   NULL,
    [LOADED_POSN]                   NVARCHAR (1)    NULL,
    [LPN_EPC]                       NVARCHAR (96)   NULL,
    [LPN_NBR_X_OF_Y]                INT             NULL,
    [MANIFEST_NBR]                  NVARCHAR (20)   NULL,
    [MASTER_BOL_NBR]                NVARCHAR (30)   NULL,
    [MISC_INSTR_CODE_1]             NVARCHAR (2)    NULL,
    [MISC_INSTR_CODE_2]             NVARCHAR (2)    NULL,
    [MISC_INSTR_CODE_3]             NVARCHAR (2)    NULL,
    [MISC_INSTR_CODE_4]             NVARCHAR (2)    NULL,
    [MISC_INSTR_CODE_5]             NVARCHAR (2)    NULL,
    [MISC_NUM_1]                    DECIMAL (9, 2)  NULL,
    [MISC_NUM_2]                    DECIMAL (9, 2)  NULL,
    [NON_INVENTORY_LPN_FLAG]        INT             NULL,
    [NON_MACHINEABLE]               INT             NULL,
    [OUTPT_LPN_ID]                  INT             NOT NULL,
    [PACKAGE_DESCRIPTION]           NVARCHAR (100)  NULL,
    [PACKER_USERID]                 NVARCHAR (15)   NULL,
    [PALLET_EPC]                    NVARCHAR (96)   NULL,
    [PALLET_MASTER_LPN_FLAG]        INT             NULL,
    [PARCEL_SERVICE_MODE]           NVARCHAR (100)  NULL,
    [PARCEL_SHIPMENT_NBR]           NVARCHAR (20)   NULL,
    [PICKER_USERID]                 NVARCHAR (15)   NULL,
    [PRE_BULK_ADD_OPT_CHR]          DECIMAL (9, 2)  NULL,
    [PRE_BULK_ADD_OPT_CHR_CURRENCY] NVARCHAR (40)   NULL,
    [PRE_BULK_BASE_CHARGE]          DECIMAL (9, 2)  NULL,
    [PROC_DTTM]                     DATETIME2 (7)   NOT NULL,
    [PROC_STAT_CODE]                INT             NOT NULL,
    [QTY_UOM]                       NVARCHAR (50)   NULL,
    [RATE_ZONE]                     NVARCHAR (25)   NULL,
    [RATED_WEIGHT]                  DECIMAL (13, 4) NULL,
    [RATED_WEIGHT_UOM]              NVARCHAR (50)   NULL,
    [SERVICE_LEVEL]                 NVARCHAR (50)   NULL,
    [SHIP_VIA]                      NVARCHAR (4)    NULL,
    [SHIPPED_DTTM]                  DATETIME2 (7)   NULL,
    [STATIC_ROUTE_ID]               INT             NULL,
    [TC_COMPANY_ID]                 INT             NOT NULL,
    [TC_LPN_ID]                     NVARCHAR (50)   NOT NULL,
    [TC_ORDER_ID]                   NVARCHAR (50)   NULL,
    [TC_PARENT_LPN_ID]              NVARCHAR (50)   NULL,
    [TC_SHIPMENT_ID]                NVARCHAR (50)   NULL,
    [TOTAL_LPN_QTY]                 DECIMAL (13, 4) NULL,
    [TRACKING_NBR]                  NVARCHAR (50)   NULL,
    [ALT_TRACKING_NBR]              NVARCHAR (50)   NULL,
    [VERSION_NBR]                   INT             NOT NULL,
    [VOLUME_UOM]                    NVARCHAR (50)   NULL,
    [WEIGHT]                        DECIMAL (13, 4) NULL,
    [WEIGHT_UOM]                    NVARCHAR (50)   NULL,
    [LOAD_SEQUENCE]                 INT             NULL,
    [TC_PURCHASE_ORDER_ID]          NVARCHAR (50)   NULL,
    [RETURN_TRACKING_NBR]           NVARCHAR (50)   NULL,
    [Eff_Date]                      DATE            NOT NULL,
    [End_Date]                      DATE            NULL,
    [ActInd]                        CHAR (1)        NULL,
    [IsDeleted]                     CHAR (1)        NULL,
    [BatchID]                       BIGINT          NULL,
    [ProcessLogID]                  BIGINT          NULL,
    CONSTRAINT [PK_MANH_OUTPT_LPN] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [OUTPT_LPN_ID] ASC) ON [DWH_MANH_ARC]
) ON [DWH_MANH_ARC];





