CREATE TABLE [MANH_ARC].[TRAN_MASTER] (
    [TRAN_ID]                  INT            NOT NULL,
    [TRAN_NAME]                NVARCHAR (40)  NULL,
    [TRAN_TYPE]                NVARCHAR (10)  NULL,
    [ICON_FILE_NAME]           NVARCHAR (255) NULL,
    [PGM_ID]                   NVARCHAR (200) NULL,
    [PGM_TYPE]                 NVARCHAR (4)   NULL,
    [CUST_ID]                  NVARCHAR (4)   NULL,
    [OPTN_ACCESS]              NVARCHAR (1)   NULL,
    [TASK_NAME]                NVARCHAR (15)  NULL,
    [TRK_PROD]                 NVARCHAR (1)   NULL,
    [PROMPT_FOR_PRTR_DEST]     NVARCHAR (1)   NULL,
    [ELS_ACTVTY_CODE]          NVARCHAR (15)  NULL,
    [CREATE_DATE_TIME]         DATETIME2 (7)  NULL,
    [MOD_DATE_TIME]            DATETIME2 (7)  NULL,
    [USER_ID]                  NVARCHAR (15)  NULL,
    [DISABLED_RF_CTRL_KEYS]    NVARCHAR (26)  NULL,
    [URL]                      NVARCHAR (300) NULL,
    [WORKINFO_INTERFACE]       NVARCHAR (1)   NULL,
    [WORKINFO_LOG]             NVARCHAR (1)   NULL,
    [TRAN_GRP]                 NVARCHAR (15)  NULL,
    [FORM_CUSTOMIZE_LEVEL]     INT            NOT NULL,
    [DISABLE_ROW_COUNT]        INT            NOT NULL,
    [FACTORY_NAME]             NVARCHAR (50)  NULL,
    [WM_VERSION_ID]            INT            NOT NULL,
    [TRAN_MASTER_ID]           INT            NOT NULL,
    [GET_EMP_PERF]             NVARCHAR (1)   NULL,
    [FO_TYPE]                  NVARCHAR (50)  NULL,
    [MHE_ENABLED]              NVARCHAR (1)   NULL,
    [REASON_CODE_ENABLED]      NVARCHAR (1)   NULL,
    [APP_ID]                   INT            NULL,
    [CREATED_SOURCE_TYPE]      INT            NOT NULL,
    [CREATED_SOURCE]           NVARCHAR (25)  NULL,
    [CREATED_DTTM]             DATETIME2 (7)  NOT NULL,
    [LAST_UPDATED_SOURCE_TYPE] INT            NOT NULL,
    [LAST_UPDATED_SOURCE]      NVARCHAR (25)  NULL,
    [LAST_UPDATED_DTTM]        DATETIME2 (7)  NOT NULL,
    [Eff_Date]                 DATE           NOT NULL,
    [End_Date]                 DATE           NULL,
    [ActInd]                   CHAR (1)       NULL,
    [IsDeleted]                CHAR (1)       NULL,
    [BatchID]                  BIGINT         NULL,
    [ProcessLogID]             BIGINT         NULL,
    CONSTRAINT [PK_MANH_TRAN_MASTER] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [TRAN_MASTER_ID] ASC) ON [DWH_MANH_ARC]
) ON [DWH_MANH_ARC];

