CREATE TABLE [MANH_ARC].[WAVE_RULE_PARM] (
    [WAVE_PARM_ID]                INT            NOT NULL,
    [RULE_ID]                     INT            NOT NULL,
    [WHSE]                        NVARCHAR (3)   NOT NULL,
    [RULE_PRTY]                   INT            NOT NULL,
    [WAVE_NBR]                    NVARCHAR (12)  NULL,
    [RULE_NAME]                   NVARCHAR (20)  NULL,
    [RULE_DESC]                   NVARCHAR (40)  NULL,
    [UNITS_CAPCTY]                INT            NOT NULL,
    [MAX_ORDERS]                  INT            NULL,
    [LABEL_PRTR_REQSTR]           NVARCHAR (255) NULL,
    [RPT_PRTR_REQSTR]             NVARCHAR (255) NULL,
    [NBR_OF_LABELS_PER_SPOOL]     INT            NOT NULL,
    [NBR_OF_LABELS_PER_ROW]       INT            NOT NULL,
    [MISC_INSTR_CODE_1]           NVARCHAR (2)   NULL,
    [MISC_INSTR_CODE_2]           NVARCHAR (2)   NULL,
    [STAT_CODE]                   INT            NOT NULL,
    [CREATE_DATE_TIME]            DATETIME2 (7)  NULL,
    [MOD_DATE_TIME]               DATETIME2 (7)  NULL,
    [USER_ID]                     NVARCHAR (15)  NULL,
    [WHEN_TO_PRT_CTN_CONTENT_LBL] NVARCHAR (1)   NULL,
    [WHEN_TO_PRT_CTN_SHIP_LBL]    NVARCHAR (1)   NULL,
    [PRINT_CONTENT_LABEL]         NVARCHAR (1)   NULL,
    [PRINT_SHIP_LABEL]            NVARCHAR (1)   NULL,
    [COLLATE_PRTR_REQSTR]         NVARCHAR (255) NULL,
    [WAVE_RULE_PARM_ID]           INT            NOT NULL,
    [SHIP_WAVE_PARM_ID]           INT            NULL,
    [RULE_HDR_ID]                 INT            NULL,
    [WM_VERSION_ID]               INT            NOT NULL,
    [MAX_ORDER_LINES]             INT            NOT NULL,
    [CREATED_DTTM]                DATETIME2 (7)  NOT NULL,
    [LAST_UPDATED_DTTM]           DATETIME2 (7)  NULL,
    [SEND_LABELS_TO_PANDA]        INT            NOT NULL,
    [Eff_Date]                    DATE           NOT NULL,
    [End_Date]                    DATE           NULL,
    [ActInd]                      CHAR (1)       NULL,
    [IsDeleted]                   CHAR (1)       NULL,
    [BatchID]                     BIGINT         NULL,
    [ProcessLogID]                BIGINT         NULL,
    CONSTRAINT [PK_MANH_WAVE_RULE_PARM] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [WAVE_RULE_PARM_ID] ASC) ON [DWH_MANH_ARC]
) ON [DWH_MANH_ARC];

