CREATE TABLE [MANH_ARC].[WORK_ORD_DTL] (
    [WORK_ORD_NBR]         NVARCHAR (12)   NULL,
    [SEQ_NBR]              NUMERIC (9)     NULL,
    [PARENT_SEQ_NBR]       NUMERIC (9)     NULL,
    [WAVE_PROC_TYPE]       NUMERIC (4)     NULL,
    [FROM_TO_CODE]         NVARCHAR (1)    NULL,
    [CMPL_SKU_SEQ_NBR]     NUMERIC (9)     NULL,
    [BACK_FLUSH_FLAG]      NVARCHAR (1)    NULL,
    [BOM_ITEM_FLAG]        NVARCHAR (1)    NULL,
    [CMPNT_TYPE]           NVARCHAR (1)    NULL,
    [INVN_TYPE]            NVARCHAR (1)    NULL,
    [PROD_STAT]            NVARCHAR (3)    NULL,
    [BATCH_NBR]            NVARCHAR (15)   NULL,
    [SKU_ATTR_1]           NVARCHAR (10)   NULL,
    [SKU_ATTR_2]           NVARCHAR (10)   NULL,
    [SKU_ATTR_3]           NVARCHAR (10)   NULL,
    [SKU_ATTR_4]           NVARCHAR (10)   NULL,
    [SKU_ATTR_5]           NVARCHAR (10)   NULL,
    [CNTRY_OF_ORGN]        NVARCHAR (4)    NULL,
    [ORG_REQD_QTY]         NUMERIC (9, 2)  NULL,
    [REQD_QTY]             NUMERIC (9, 2)  NULL,
    [TO_BE_PIKD_QTY]       NUMERIC (9, 2)  NULL,
    [PULLD_QTY]            NUMERIC (9, 2)  NULL,
    [IN_WORK_QTY]          NUMERIC (9, 2)  NULL,
    [CMPL_QTY]             NUMERIC (9, 2)  NULL,
    [USED_QTY]             NUMERIC (9, 2)  NULL,
    [RESDL_QTY]            NUMERIC (9, 2)  NULL,
    [SCRAP_QTY]            NUMERIC (9, 2)  NULL,
    [BULK_PULL_FLAG]       NVARCHAR (1)    NULL,
    [ALLOC_TYPE]           NVARCHAR (3)    NULL,
    [CREATE_DATE_TIME]     DATETIME        NULL,
    [MOD_DATE_TIME]        DATETIME        NULL,
    [USER_ID]              NVARCHAR (15)   NULL,
    [LOCN_ID]              NVARCHAR (10)   NULL,
    [ALLOC_CUTOFF]         NUMERIC (4)     NULL,
    [SKU_SUB]              NVARCHAR (1)    NULL,
    [ORG_SEQ_NBR]          NUMERIC (9)     NULL,
    [STAT_CODE]            NUMERIC (4)     NULL,
    [RATIO]                NUMERIC (16, 4) NULL,
    [RSN_CODE]             NVARCHAR (2)    NULL,
    [WORK_ORD_DTL_ID]      NUMERIC (9)     NOT NULL,
    [WORK_ORD_HDR_ID]      NUMERIC (9)     NULL,
    [WM_VERSION_ID]        NUMERIC (9)     NULL,
    [ITEM_ID]              NUMERIC (11)    NULL,
    [HAS_IMPORT_ERROR]     NUMERIC (1)     NULL,
    [HAS_SOFT_CHECK_ERROR] NUMERIC (1)     NULL,
    [Eff_Date]             DATE            NOT NULL,
    [End_Date]             DATE            NULL,
    [ActInd]               CHAR (1)        NULL,
    [IsDeleted]            CHAR (1)        NULL,
    [BatchID]              BIGINT          NULL,
    [ProcessLogID]         BIGINT          NULL,
    CONSTRAINT [PK_MANH_WORK_ORD_DTL] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [WORK_ORD_DTL_ID] ASC) ON [DWH_MANH_ARC]
) ON [DWH_MANH_ARC];





