CREATE TABLE [IFS_ARC].[COST_BUCKET] (
    [CONTRACT]                   NVARCHAR (5)    NOT NULL,
    [COST_BUCKET_ID]             NVARCHAR (5)    NOT NULL,
    [DESCRIPTION]                NVARCHAR (35)   NULL,
    [NOTE_TEXT]                  NVARCHAR (2000) NULL,
    [COST_BUCKET_TYPE]           NVARCHAR (4000) NULL,
    [COST_BUCKET_TYPE_DB]        NVARCHAR (20)   NULL,
    [SUNK_RELEVANT_COST]         NVARCHAR (4000) NULL,
    [SUNK_RELEVANT_COST_DB]      NVARCHAR (20)   NULL,
    [FIXED_VARIABLE_COST]        NVARCHAR (4000) NULL,
    [FIXED_VARIABLE_COST_DB]     NVARCHAR (20)   NULL,
    [DIRECT_INDIRECT_COST]       NVARCHAR (4000) NULL,
    [DIRECT_INDIRECT_COST_DB]    NVARCHAR (20)   NULL,
    [COST_BUCKET_PUBLIC_TYPE]    NVARCHAR (4000) NULL,
    [COST_BUCKET_PUBLIC_TYPE_DB] NVARCHAR (20)   NULL,
    [COST_ACTIVITY_ID]           NVARCHAR (5)    NULL,
    [LAST_ACTIVITY_DATE]         DATETIME2 (7)   NULL,
    [POSTING_GROUP_ID]           NVARCHAR (20)   NULL,
    [OBJID]                      NVARCHAR (4000) NULL,
    [OBJVERSION]                 NVARCHAR (2000) NULL,
    [Eff_Date]                   DATE            NOT NULL,
    [End_Date]                   DATE            NULL,
    [ActInd]                     CHAR (1)        NULL,
    [IsDeleted]                  CHAR (1)        NULL,
    [BatchID]                    BIGINT          NULL,
    [ProcessLogID]               BIGINT          NULL,
    CONSTRAINT [PK_COST_BUCKET] PRIMARY KEY CLUSTERED ([CONTRACT] ASC, [COST_BUCKET_ID] ASC) ON [DWH_IFS_ARC]
) ON [DWH_IFS_ARC];

