CREATE TABLE [IFS_ARC].[MANUF_STRUCTURE] (
    [CONTRACT]                    NVARCHAR (5)    NOT NULL,
    [PART_NO]                     NVARCHAR (25)   NOT NULL,
    [ENG_CHG_LEVEL]               NVARCHAR (2)    NOT NULL,
    [BOM_TYPE]                    NVARCHAR (200)  NULL,
    [BOM_TYPE_DB]                 NVARCHAR (20)   NOT NULL,
    [ALTERNATIVE_NO]              NVARCHAR (20)   NOT NULL,
    [LINE_ITEM_NO]                INT             NOT NULL,
    [LINE_SEQUENCE]               INT             NULL,
    [EFF_PHASE_IN_DATE]           DATETIME2 (7)   NULL,
    [EFF_PHASE_OUT_DATE]          DATETIME2 (7)   NULL,
    [QTY_PER_ASSEMBLY]            INT             NULL,
    [COMPONENT_SCRAP]             INT             NULL,
    [SHRINKAGE_FACTOR]            INT             NULL,
    [OPERATION_NO]                INT             NULL,
    [LEADTIME_OFFSET]             INT             NULL,
    [ISSUE_TO_LOC]                NVARCHAR (35)   NULL,
    [ENG_CHG_NO]                  NVARCHAR (10)   NULL,
    [NOTE_ID]                     INT             NULL,
    [NOTE_TEXT]                   NVARCHAR (2000) NULL,
    [SOURCE]                      NVARCHAR (25)   NULL,
    [CREATE_DATE]                 DATETIME2 (7)   NULL,
    [LAST_ACTIVITY_DATE]          DATETIME2 (7)   NULL,
    [CONSUMPTION_ITEM]            NVARCHAR (200)  NULL,
    [CONSUMPTION_ITEM_DB]         NVARCHAR (20)   NULL,
    [PHANTOM_CONSUME]             NVARCHAR (200)  NULL,
    [PHANTOM_CONSUME_DB]          NVARCHAR (20)   NULL,
    [CHARGED_ITEM]                NVARCHAR (200)  NULL,
    [CHARGED_ITEM_DB]             NVARCHAR (20)   NULL,
    [COMPONENT_PART]              NVARCHAR (25)   NULL,
    [PRINT_UNIT]                  NVARCHAR (30)   NULL,
    [PROMISE_PLANNED]             NVARCHAR (200)  NULL,
    [PROMISE_PLANNED_DB]          NVARCHAR (20)   NULL,
    [DRAW_POS_NO]                 NVARCHAR (10)   NULL,
    [MANUF_STRUCTURE_TYPE]        NVARCHAR (200)  NULL,
    [VALUE_ANALYSIS_FUNC_ID]      NVARCHAR (10)   NULL,
    [VALUE_ANALYSIS_FUNC_TYPE]    NVARCHAR (200)  NULL,
    [VALUE_ANALYSIS_FUNC_TYPE_DB] NVARCHAR (20)   NULL,
    [COMPONENT_CONTRACT]          NVARCHAR (5)    NULL,
    [WEIGHT_SHARE]                INT             NULL,
    [PROCEDURE_STEP]              INT             NULL,
    [FIXED_QTY_FLAG]              NVARCHAR (200)  NULL,
    [COMPONENT_USAGE_FACTOR]      INT             NULL,
    [PURCHASE_COMP_BACKFLUSH]     NVARCHAR (200)  NULL,
    [PURCHASE_COMP_BACKFLUSH_DB]  NVARCHAR (20)   NULL,
    [STD_PLANNED_ITEM]            INT             NULL,
    [GEN_OH_COST_DISTRIBUTION]    INT             NULL,
    [OPER_COST_DISTRIBUTION]      INT             NULL,
    [ROWTYPE]                     NVARCHAR (30)   NULL,
    [OBJID]                       NVARCHAR (100)  NULL,
    [OBJVERSION]                  BIGINT          NULL,
    [Eff_Date]                    DATE            NOT NULL,
    [End_Date]                    DATE            NULL,
    [ActInd]                      CHAR (1)        NULL,
    [IsDeleted]                   CHAR (1)        NULL,
    [BatchID]                     BIGINT          NULL,
    [ProcessLogID]                BIGINT          NULL,
    CONSTRAINT [PK_MANUF_STRUCTURE] PRIMARY KEY CLUSTERED ([ALTERNATIVE_NO] ASC, [BOM_TYPE_DB] ASC, [CONTRACT] ASC, [Eff_Date] ASC, [ENG_CHG_LEVEL] ASC, [LINE_ITEM_NO] ASC, [PART_NO] ASC) ON [DWH_IFS_ARC]
) ON [DWH_IFS_ARC];

