CREATE TABLE [IFS_ARC].[MIXED_PAYMENT] (
    [COMPANY]                  NVARCHAR (20)    NOT NULL,
    [MIXED_PAYMENT_ID]         INT              NOT NULL,
    [STATEMENT_NO]             NVARCHAR (20)    NULL,
    [MIXED_PAYMENT_DATE]       DATETIME2 (7)    NULL,
    [OPENING_BALANCE]          DECIMAL (18, 2)  NULL,
    [CLOSING_BALANCE]          DECIMAL (18, 2)  NULL,
    [OPEN_BAL_ACC_CURR]        DECIMAL (18, 2)  NULL,
    [CLOSE_BAL_ACC_CURR]       DECIMAL (18, 2)  NULL,
    [CALC_OPEN_BALANCE]        DECIMAL (18, 2)  NULL,
    [CURRENCY_RATE]            DECIMAL (18, 10) NULL,
    [DIV_FACTOR]               INT              NULL,
    [VOUCHER_NO_REF]           INT              NULL,
    [USER_GROUP_REF]           NVARCHAR (30)    NULL,
    [VOUCHER_DATE_REF]         DATETIME2 (7)    NULL,
    [VOUCHER_TYPE_REF]         NVARCHAR (3)     NULL,
    [VOUCHER_GROUP_REF]        NVARCHAR (1)     NULL,
    [ACCOUNTING_YEAR_REF]      INT              NULL,
    [SHORT_NAME_CURR]          NVARCHAR (4000)  NULL,
    [VOUCHER_TEXT]             NVARCHAR (200)   NULL,
    [BALANCE_METHOD]           NVARCHAR (4000)  NULL,
    [BALANCE_METHOD_DB]        NVARCHAR (20)    NULL,
    [CURRENCY]                 NVARCHAR (3)     NULL,
    [SHORT_NAME]               NVARCHAR (20)    NULL,
    [SHORT_NAME_FIXED_VOUCHER] NVARCHAR (4000)  NULL,
    [SHORT_NAME_VOUCHER_TYPE]  NVARCHAR (4000)  NULL,
    [BATCH_ID]                 INT              NULL,
    [NOTE]                     NVARCHAR (4000)  NULL,
    [OBJID]                    NVARCHAR (4000)  NULL,
    [OBJVERSION]               NVARCHAR (2000)  NULL,
    [OBJSTATE]                 NVARCHAR (30)    NULL,
    [OBJEVENTS]                NVARCHAR (253)   NULL,
    [STATE]                    NVARCHAR (253)   NULL,
    [Eff_Date]                 DATE             NOT NULL,
    [End_Date]                 DATE             NULL,
    [ActInd]                   CHAR (1)         NULL,
    [IsDeleted]                CHAR (1)         NULL,
    [BatchID]                  BIGINT           NULL,
    [ProcessLogID]             BIGINT           NULL,
    CONSTRAINT [PK_MIXED_PAYMENT] PRIMARY KEY CLUSTERED ([COMPANY] ASC, [MIXED_PAYMENT_ID] ASC) ON [DWH_IFS_ARC]
) ON [DWH_IFS_ARC];

