CREATE TABLE [IFS_ARC].[SHOP_ORDER_COST_OVERVIEW] (
    [ORDER_NO]                NVARCHAR (12)    NOT NULL,
    [RELEASE_NO]              NVARCHAR (4)     NOT NULL,
    [SEQUENCE_NO]             NVARCHAR (4)     NOT NULL,
    [CONTRACT]                NVARCHAR (5)     NOT NULL,
    [PART_NO]                 NVARCHAR (25)    NOT NULL,
    [STATE]                   NVARCHAR (4000)  NULL,
    [OBJSTATE]                NVARCHAR (30)    NULL,
    [CONFIGURATION_ID]        NVARCHAR (50)    NULL,
    [REVISED_START_DATE]      DATETIME2 (7)    NULL,
    [REVISED_DUE_DATE]        DATETIME2 (7)    NULL,
    [CLOSE_DATE]              DATETIME2 (7)    NULL,
    [REVISED_QTY_DUE]         INT              NULL,
    [QTY_COMPLETE]            INT              NULL,
    [OPERATION_SCRAPPED]      INT              NULL,
    [LOT_BATCH_NO]            NVARCHAR (4000)  NULL,
    [SERIAL_BEGIN]            NVARCHAR (50)    NULL,
    [SERIAL_END]              NVARCHAR (50)    NULL,
    [ENG_CHG_LEVEL]           NVARCHAR (2)     NULL,
    [STRUCTURE_ALTERNATIVE]   NVARCHAR (20)    NULL,
    [ROUTING_REVISION]        NVARCHAR (4)     NULL,
    [ROUTING_ALTERNATIVE]     NVARCHAR (20)    NULL,
    [ORDER_CODE]              NVARCHAR (4000)  NULL,
    [ORDER_CODE_DB]           NVARCHAR (3)     NULL,
    [TOTAL_STD_LEVEL_COST]    DECIMAL (18, 8)  NULL,
    [TOTAL_STD_ACCUM_COST]    DECIMAL (18, 8)  NULL,
    [TOTAL_EST_LEVEL_COST]    DECIMAL (18, 8)  NULL,
    [TOTAL_EST_ACCUM_COST]    DECIMAL (18, 8)  NULL,
    [TOTAL_ACTUAL_LEVEL_COST] DECIMAL (18, 8)  NULL,
    [TOTAL_ACTUAL_ACCUM_COST] DECIMAL (18, 8)  NULL,
    [EST_STD_LEVEL]           DECIMAL (18, 8)  NULL,
    [EST_STD_LEVEL_FACTOR]    DECIMAL (38, 20) NULL,
    [EST_STD_ACCUM]           DECIMAL (18, 8)  NULL,
    [EST_STD_ACCUM_FACTOR]    DECIMAL (38, 20) NULL,
    [ACT_STD_LEVEL]           DECIMAL (18, 8)  NULL,
    [ACT_STD_LEVEL_FACTOR]    DECIMAL (38, 20) NULL,
    [ACT_STD_ACCUM]           DECIMAL (18, 8)  NULL,
    [ACT_STD_ACCUM_FACTOR]    DECIMAL (38, 20) NULL,
    [ACT_EST_LEVEL]           DECIMAL (18, 8)  NULL,
    [ACT_EST_LEVEL_FACTOR]    DECIMAL (38, 20) NULL,
    [ACT_EST_ACCUM]           DECIMAL (18, 8)  NULL,
    [ACT_EST_ACCUM_FACTOR]    DECIMAL (38, 20) NULL,
    [PART_DESCRIPTION]        NVARCHAR (4000)  NULL,
    [PLANNER_BUYER]           NVARCHAR (20)    NULL,
    [PART_COST_GROUP_ID]      NVARCHAR (5)     NULL,
    [DEMAND_CODE]             NVARCHAR (4000)  NULL,
    [DEMAND_CODE_DB]          NVARCHAR (3)     NULL,
    [ORG_QTY_DUE]             INT              NULL,
    [ORG_START_DATE]          DATETIME2 (7)    NULL,
    [ORG_DUE_DATE]            DATETIME2 (7)    NULL,
    [NEED_DATE]               DATETIME2 (7)    NULL,
    [ACTIVITY_SEQ]            INT              NULL,
    [PROJECT_ID]              NVARCHAR (10)    NULL,
    [MRO_VISIT_ID]            INT              NULL,
    [PRIORITY_CATEGORY]       NVARCHAR (10)    NULL,
    [PART_PRODUCT_FAMILY]     NVARCHAR (5)     NULL,
    [PART_PRODUCT_CODE]       NVARCHAR (5)     NULL,
    [EFFECTIVE_SERIAL_NO]     INT              NULL,
    [CALCULATION_DATE]        DATETIME2 (7)    NULL,
    [EFFECTIVE_DATE]          DATETIME2 (7)    NULL,
    [OBJID]                   NVARCHAR (4000)  NULL,
    [OBJVERSION]              NVARCHAR (2000)  NULL,
    [Eff_Date]                DATE             NOT NULL,
    [End_Date]                DATE             NULL,
    [ActInd]                  CHAR (1)         NULL,
    [IsDeleted]               CHAR (1)         NULL,
    [BatchID]                 BIGINT           NULL,
    [ProcessLogID]            BIGINT           NULL,
    CONSTRAINT [PK_SHOP_ORDER_COST_OVERVIEW] PRIMARY KEY CLUSTERED ([PART_NO] ASC, [CONTRACT] ASC, [ORDER_NO] ASC, [RELEASE_NO] ASC, [SEQUENCE_NO] ASC, [Eff_Date] ASC) ON [DWH_IFS_ARC]
) ON [DWH_IFS_ARC];

