CREATE TABLE [IFS_ARC].[SHOP_ORDER_COST_BUCKET] (
    [ORDER_NO]                   NVARCHAR (12)   NOT NULL,
    [RELEASE_NO]                 NVARCHAR (4)    NOT NULL,
    [SEQUENCE_NO]                NVARCHAR (4)    NOT NULL,
    [PART_NO]                    NVARCHAR (25)   NOT NULL,
    [COST_BUCKET_ID]             NVARCHAR (5)    NOT NULL,
    [BUCKET_LEVEL]               INT             NOT NULL,
    [BUCKET_SEQ]                 INT             NOT NULL,
    [TOP_LEVEL_PART_NO]          NVARCHAR (25)   NOT NULL,
    [OPERATION_NO]               INT             NOT NULL,
    [COMPANY]                    NVARCHAR (20)   NOT NULL,
    [COST_SOURCE_ID]             NVARCHAR (20)   NOT NULL,
    [LEVEL_COST]                 DECIMAL (38, 8) NULL,
    [ACCUM_COST]                 DECIMAL (38, 8) NULL,
    [QTY_PER_ASSEMBLY]           INT             NULL,
    [COST_QTY_PER_ASSEMBLY]      INT             NULL,
    [CALCULATION_DATE]           DATETIME2 (7)   NULL,
    [COST_BUCKET_PUBLIC_TYPE]    NVARCHAR (4000) NULL,
    [COST_BUCKET_PUBLIC_TYPE_DB] NVARCHAR (20)   NULL,
    [STD_PLANNED_ITEM]           INT             NULL,
    [LINE_ITEM_NO]               INT             NULL,
    [COMPONENT_LINE_ITEM_NO]     INT             NULL,
    [LEVEL_SCRAP_COST]           INT             NULL,
    [ACCUM_SCRAP_COST]           INT             NULL,
    [PROJECT_COST_ELEMENT]       NVARCHAR (100)  NULL,
    [OBJID]                      NVARCHAR (4000) NULL,
    [OBJVERSION]                 NVARCHAR (2000) NULL,
    [Eff_Date]                   DATE            NOT NULL,
    [End_Date]                   DATE            NULL,
    [ActInd]                     CHAR (1)        NULL,
    [IsDeleted]                  CHAR (1)        NULL,
    [BatchID]                    BIGINT          NULL,
    [ProcessLogID]               BIGINT          NULL,
    CONSTRAINT [PK_SHOP_ORDER_COST_BUCKET] PRIMARY KEY CLUSTERED ([ORDER_NO] ASC, [RELEASE_NO] ASC, [SEQUENCE_NO] ASC, [PART_NO] ASC, [COST_BUCKET_ID] ASC, [BUCKET_LEVEL] ASC, [BUCKET_SEQ] ASC, [TOP_LEVEL_PART_NO] ASC, [OPERATION_NO] ASC, [COMPANY] ASC, [COST_SOURCE_ID] ASC) ON [DWH_IFS_ARC]
) ON [DWH_IFS_ARC];

