


CREATE VIEW [FD2].[VW_D_Product_Family] AS

SELECT 
	PF.PART_PRODUCT_FAMILY					AS Product_Family_ID
	,PF. DESCRIPTION						AS Product_Family_Description
FROM		IFS.INVENTORY_PRODUCT_FAMILY PF
WHERE		PF.ActInd='Y'

UNION ALL

SELECT '-1','UNKNOWN'