





CREATE VIEW [FD2].[VW_D_Shipment]
AS

SELECT        
	SH.TC_SHIPMENT_ID					AS Shipment_ID
	, SS.DESCRIPTION					AS Shipment_Status
	, SH.DSG_CARRIER_CODE				AS Shipment_Carrier_Code
	, SH.STATUS_CHANGE_DTTM				AS Shipment_Updated
FROM			MANH.SHIPMENT SH 
INNER JOIN		MANH.SHIPMENT_STATUS SS 
ON				SS.SHIPMENT_STATUS = SH.SHIPMENT_STATUS 
AND				SS.ActInd = 'Y'
WHERE			SH.ActInd = 'Y'

UNION ALL

SELECT        '-1', 'Unknown', NULL, NULL