CREATE TABLE [TRANS_ARC].[DPD_ROUTE] (
    [DPD_ROUTE_ID]       INT           NOT NULL,
    [DESTINATIONCOUNTRY] VARCHAR (3)   NOT NULL,
    [BEGINPOSTCODE]      VARCHAR (20)  NULL,
    [ENDPOSTCODE]        VARCHAR (20)  NULL,
    [SERVICECODES]       VARCHAR (300) NULL,
    [ROUTINGPLACES]      VARCHAR (300) NULL,
    [SENDINGDATE]        VARCHAR (20)  NULL,
    [O_SORT]             VARCHAR (20)  NULL,
    [D_DEPOT]            VARCHAR (20)  NULL,
    [GROUPINGPRIORITY]   VARCHAR (20)  NULL,
    [D_SORT]             VARCHAR (20)  NULL,
    [BARCODEID]          VARCHAR (20)  NULL,
    [BatchID]            BIGINT        NULL,
    [ProcessLogID]       BIGINT        NULL,
    CONSTRAINT [PK_DPD_ROUTE] PRIMARY KEY CLUSTERED ([DPD_ROUTE_ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [DWH_TRANS_ARC]
) ON [DWH_TRANS_ARC];



