CREATE TABLE [KEWILL_ARC].[partyn] (
    [vrfilk]       INT             NOT NULL,
    [rnropd]       BIGINT          NOT NULL,
    [artkd]        NVARCHAR (35)   NOT NULL,
    [ptykd]        NVARCHAR (20)   NOT NULL,
    [ptdati]       DATETIME2 (6)   NOT NULL,
    [vrvolg]       TINYINT         NOT NULL,
    [vrvrdt]       TINYINT         NOT NULL,
    [eindvr]       NUMERIC (13, 3) NULL,
    [vrauil]       NUMERIC (13, 3) NULL,
    [tsinnr]       BIGINT          NULL,
    [ref02]        NVARCHAR (5)    NULL,
    [brgew]        NUMERIC (14, 3) NULL,
    [ntgew]        NUMERIC (14, 3) NULL,
    [tsgron]       NUMERIC (13, 3) NULL,
    [tsgrob]       NUMERIC (13, 3) NULL,
    [tsgonn]       NUMERIC (13, 3) NULL,
    [inkprs]       NUMERIC (13, 3) NULL,
    [tsonbr]       NUMERIC (13, 3) NULL,
    [tsonnt]       NUMERIC (13, 3) NULL,
    [vratpr]       NUMERIC (13, 3) NULL,
    [tsgelb]       NUMERIC (13, 3) NULL,
    [tsgeln]       NUMERIC (13, 3) NULL,
    [tsiubr]       NUMERIC (13, 3) NULL,
    [tsiunt]       NUMERIC (13, 3) NULL,
    [tswco1]       NUMERIC (13, 3) NULL,
    [tswco2]       NUMERIC (13, 3) NULL,
    [tswco3]       NUMERIC (13, 3) NULL,
    [tswco4]       NUMERIC (13, 3) NULL,
    [tsoco1]       NUMERIC (13, 3) NULL,
    [tsoco2]       NUMERIC (13, 3) NULL,
    [tsoco3]       NUMERIC (13, 3) NULL,
    [tsoco4]       NUMERIC (13, 3) NULL,
    [tsuco1]       NUMERIC (13, 3) NULL,
    [tsuco2]       NUMERIC (13, 3) NULL,
    [tsuco3]       NUMERIC (13, 3) NULL,
    [tsuco4]       NUMERIC (13, 3) NULL,
    [tsrtyp]       NVARCHAR (10)   NULL,
    [tsrman]       NVARCHAR (20)   NULL,
    [vdscod]       NVARCHAR (3)    NULL,
    [tsdokn]       NVARCHAR (20)   NULL,
    [tspstn]       SMALLINT        NULL,
    [tskaaf]       NVARCHAR (10)   NULL,
    [vrdkdj]       DATETIME2 (6)   NULL,
    [clando]       NVARCHAR (3)    NULL,
    [vrldhk]       NVARCHAR (3)    NULL,
    [levcon]       SMALLINT        NULL,
    [ref01]        NVARCHAR (10)   NULL,
    [tsinmd]       NVARCHAR (1)    NULL,
    [tsopnr]       BIGINT          NULL,
    [tsoprg]       INT             NULL,
    [likprs]       NUMERIC (15, 2) NULL,
    [tsikvk]       NVARCHAR (3)    NULL,
    [tsppit]       NUMERIC (19, 9) NULL,
    [vrkstg]       NUMERIC (10, 2) NULL,
    [tsvkvk]       NVARCHAR (3)    NULL,
    [verzks]       NUMERIC (13, 2) NULL,
    [tsvzvk]       NVARCHAR (3)    NULL,
    [tsinin]       NUMERIC (15, 2) NULL,
    [tsinvk]       NVARCHAR (3)    NULL,
    [tsmf20]       NVARCHAR (20)   NULL,
    [Eff_Date]     DATE            NOT NULL,
    [End_Date]     DATE            NULL,
    [ActInd]       CHAR (1)        NULL,
    [IsDeleted]    CHAR (1)        NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    CONSTRAINT [PK_partyn] PRIMARY KEY CLUSTERED ([vrfilk] ASC, [rnropd] ASC, [artkd] ASC, [vrvrdt] ASC, [ptykd] ASC, [ptdati] ASC, [vrvolg] ASC, [Eff_Date] ASC) WITH (FILLFACTOR = 90) ON [DWH_KEWILL_ARC]
) ON [DWH_KEWILL_ARC];





