CREATE TABLE [KEWILL_ARC].[tsdsmd] (
    [dosvlg]       BIGINT          NOT NULL,
    [afd]          NVARCHAR (4)    NULL,
    [tsjrs2]       SMALLINT        NULL,
    [tsmds2]       TINYINT         NULL,
    [afh]          NVARCHAR (1)    NULL,
    [zendnr]       BIGINT          NULL,
    [spltnr]       TINYINT         NULL,
    [datinv]       DATETIME2 (6)   NULL,
    [kode6]        BIGINT          NULL,
    [module]       TINYINT         NULL,
    [srtdos]       NVARCHAR (1)    NULL,
    [tstwst]       TINYINT         NULL,
    [tsexdo]       BIGINT          NULL,
    [hvbnr]        NVARCHAR (15)   NULL,
    [manif]        NVARCHAR (20)   NULL,
    [refnr]        NVARCHAR (20)   NULL,
    [offvlg]       INT             NULL,
    [ref01]        NVARCHAR (10)   NULL,
    [ref02]        NVARCHAR (5)    NULL,
    [plaanl]       NVARCHAR (6)    NULL,
    [plafle]       NVARCHAR (6)    NULL,
    [conttp]       NVARCHAR (4)    NULL,
    [atlcnt]       SMALLINT        NULL,
    [contnr]       NVARCHAR (11)   NULL,
    [plher]        NVARCHAR (5)    NULL,
    [plbes]        NVARCHAR (5)    NULL,
    [vertrd]       DATETIME2 (6)   NULL,
    [aankd]        DATETIME2 (6)   NULL,
    [tsdgsg]       TINYINT         NULL,
    [tsmdsg]       TINYINT         NULL,
    [tsjrsg]       SMALLINT        NULL,
    [trplkd]       NVARCHAR (5)    NULL,
    [lllkod]       NVARCHAR (6)    NULL,
    [awbnum]       INT             NULL,
    [fcllcl]       NVARCHAR (7)    NULL,
    [bootnr]       SMALLINT        NULL,
    [zkboot]       NVARCHAR (10)   NULL,
    [autonr]       INT             NULL,
    [airlin]       NVARCHAR (3)    NULL,
    [tsrsau]       NVARCHAR (8)    NULL,
    [omverv]       NVARCHAR (25)   NULL,
    [bkbvrk]       NVARCHAR (5)    NULL,
    [konkvr]       SMALLINT        NULL,
    [tskkag]       SMALLINT        NULL,
    [krskvr]       NVARCHAR (1)    NULL,
    [valvr]        NVARCHAR (3)    NULL,
    [krsvr]        NUMERIC (12, 6) NULL,
    [tsvree]       INT             NULL,
    [konkst]       SMALLINT        NULL,
    [krskks]       NVARCHAR (1)    NULL,
    [valkst]       NVARCHAR (3)    NULL,
    [krskst]       NUMERIC (12, 6) NULL,
    [tskoee]       INT             NULL,
    [merknr]       NVARCHAR (16)   NULL,
    [collia]       NUMERIC (14, 3) NULL,
    [colkd]        NVARCHAR (2)    NULL,
    [comkod]       NVARCHAR (4)    NULL,
    [comzoe]       NVARCHAR (10)   NULL,
    [omsgd]        NVARCHAR (20)   NULL,
    [gewkod]       TINYINT         NULL,
    [brgew]        NUMERIC (14, 3) NULL,
    [ntgew]        NUMERIC (14, 3) NULL,
    [vogew]        NUMERIC (14, 3) NULL,
    [hoogte]       NUMERIC (4, 2)  NULL,
    [breedt]       NUMERIC (4, 2)  NULL,
    [lengte]       NUMERIC (4, 2)  NULL,
    [volkd]        NVARCHAR (1)    NULL,
    [volwrd]       NUMERIC (14, 3) NULL,
    [valwgd]       NVARCHAR (3)    NULL,
    [wrdgd]        NUMERIC (14, 2) NULL,
    [tarkla]       NVARCHAR (1)    NULL,
    [vrkstg]       NUMERIC (10, 2) NULL,
    [sagnr]        NVARCHAR (22)   NULL,
    [orgdok]       TINYINT         NULL,
    [kopdok]       TINYINT         NULL,
    [splvnr]       TINYINT         NULL,
    [doknr1]       TINYINT         NULL,
    [doknr2]       TINYINT         NULL,
    [doknr3]       NVARCHAR (2)    NULL,
    [doknr4]       NVARCHAR (2)    NULL,
    [tsovag]       NCHAR (1)       NULL,
    [tsrefa]       NVARCHAR (15)   NULL,
    [tslaly]       NCHAR (1)       NULL,
    [tsdmfa]       NCHAR (1)       NULL,
    [tslafl]       TINYINT         NULL,
    [tsvvjn]       NCHAR (1)       NULL,
    [tsprtr]       NCHAR (1)       NULL,
    [tarsrt]       NVARCHAR (2)    NULL,
    [tsopdg]       SMALLINT        NULL,
    [tsbrkk]       SMALLINT        NULL,
    [tslapo]       SMALLINT        NULL,
    [tslopo]       SMALLINT        NULL,
    [tsbvJN]       NVARCHAR (1)    NULL,
    [tsbvbd]       NUMERIC (10, 2) NULL,
    [tsdlhr]       SMALLINT        NULL,
    [tsseal]       NVARCHAR (8)    NULL,
    [tskaav]       NVARCHAR (7)    NULL,
    [tscodc]       NVARCHAR (3)    NULL,
    [tsdan2]       NVARCHAR (15)   NULL,
    [tsmfJN]       NCHAR (1)       NULL,
    [tswnr2]       INT             NULL,
    [tscoJN]       NCHAR (1)       NULL,
    [tshaJN]       NCHAR (1)       NULL,
    [tsmaJN]       NCHAR (1)       NULL,
    [bedrk1]       NUMERIC (10, 2) NULL,
    [bedrk2]       NUMERIC (10, 2) NULL,
    [bedrk3]       NUMERIC (10, 2) NULL,
    [bedrk4]       NUMERIC (10, 2) NULL,
    [bedrk5]       NUMERIC (10, 2) NULL,
    [bedrk6]       NUMERIC (10, 2) NULL,
    [bedrk7]       NUMERIC (10, 2) NULL,
    [bedrk8]       NUMERIC (10, 2) NULL,
    [bedrk9]       NUMERIC (10, 2) NULL,
    [kode1]        BIGINT          NULL,
    [kode2]        BIGINT          NULL,
    [kode3]        BIGINT          NULL,
    [kode4]        BIGINT          NULL,
    [kode5]        BIGINT          NULL,
    [kode7]        BIGINT          NULL,
    [kode8]        BIGINT          NULL,
    [kode9]        BIGINT          NULL,
    [kdverz]       NCHAR (1)       NULL,
    [kdrmb]        NCHAR (1)       NULL,
    [kdgrin]       NCHAR (1)       NULL,
    [kdlds]        NCHAR (1)       NULL,
    [vdscod]       NVARCHAR (3)    NULL,
    [tsdokn]       NVARCHAR (20)   NULL,
    [tspstn]       SMALLINT        NULL,
    [tskaaf]       NVARCHAR (10)   NULL,
    [doknr]        BIGINT          NULL,
    [tslsdg]       TINYINT         NULL,
    [tslsma]       TINYINT         NULL,
    [tslsjr]       SMALLINT        NULL,
    [tslddd]       TINYINT         NULL,
    [tsldmm]       TINYINT         NULL,
    [tsldyy]       INT             NULL,
    [taanlv]       TIME (4)        NULL,
    [taflev]       TIME (4)        NULL,
    [route]        NVARCHAR (20)   NULL,
    [to2]          NVARCHAR (5)    NULL,
    [by2]          NVARCHAR (3)    NULL,
    [vluch2]       NVARCHAR (11)   NULL,
    [to3]          NVARCHAR (5)    NULL,
    [by3]          NVARCHAR (3)    NULL,
    [werknr]       INT             NULL,
    [tslkdh]       NVARCHAR (3)    NULL,
    [tsvbha]       NVARCHAR (8)    NULL,
    [tsfilh]       NVARCHAR (4)    NULL,
    [mat01]        INT             NULL,
    [mat02]        INT             NULL,
    [mat03]        INT             NULL,
    [kmleeg]       INT             NULL,
    [kmbldn]       INT             NULL,
    [toturn]       NUMERIC (5, 2)  NULL,
    [totllu]       NUMERIC (5, 2)  NULL,
    [totwau]       NUMERIC (5, 2)  NULL,
    [totryu]       NUMERIC (5, 2)  NULL,
    [totmkg]       NUMERIC (14, 3) NULL,
    [totmvo]       NUMERIC (10, 3) NULL,
    [plslev]       NVARCHAR (15)   NULL,
    [tsreid]       BIGINT          NULL,
    [tsretl]       SMALLINT        NULL,
    [tsbyrd]       INT             NULL,
    [vkktot]       NUMERIC (14, 2) NULL,
    [vkotot]       NUMERIC (14, 2) NULL,
    [nkktot]       NUMERIC (14, 2) NULL,
    [nkotot]       NUMERIC (14, 2) NULL,
    [tsburt]       NVARCHAR (6)    NULL,
    [tsmf15]       NVARCHAR (15)   NULL,
    [tsord]        BIGINT          NULL,
    [tsiord]       BIGINT          NULL,
    [tsuitd]       DATETIME2 (6)   NULL,
    [tsdlos]       NVARCHAR (3)    NULL,
    [tsdlhk]       NVARCHAR (3)    NULL,
    [tsdlbs]       NVARCHAR (3)    NULL,
    [tsdexp]       NVARCHAR (3)    NULL,
    [tsdfak]       NVARCHAR (17)   NULL,
    [tsdddt]       DATETIME2 (6)   NULL,
    [regel]        INT             NULL,
    [tszenv]       INT             NULL,
    [tsrttl]       SMALLINT        NULL,
    [reisnr]       INT             NULL,
    [tsbstt]       SMALLINT        NULL,
    [exafd]        NVARCHAR (4)    NULL,
    [exper]        SMALLINT        NULL,
    [exafh]        NVARCHAR (1)    NULL,
    [exreis]       INT             NULL,
    [exzend]       INT             NULL,
    [exsplt]       SMALLINT        NULL,
    [tso161]       NVARCHAR (16)   NULL,
    [tsrido]       BIGINT          NULL,
    [tsserl]       NVARCHAR (4)    NULL,
    [tscoda]       NUMERIC (14, 2) NULL,
    [tscods]       TINYINT         NULL,
    [vlucht]       NVARCHAR (11)   NULL,
    [tsloai]       NUMERIC (14, 3) NULL,
    [fill11]       NVARCHAR (11)   NULL,
    [tsofnr]       INT             NULL,
    [tsofsn]       INT             NULL,
    [tsstts]       SMALLINT        NULL,
    [tsflcd]       NVARCHAR (10)   NULL,
    [tsvcnt]       NVARCHAR (10)   NULL,
    [tsluch]       NUMERIC (6, 2)  NULL,
    [tstcec]       NUMERIC (6, 2)  NULL,
    [tstfac]       NUMERIC (6, 2)  NULL,
    [tsdist]       INT             NULL,
    [tsdima]       NCHAR (1)       NULL,
    [tsca01]       NCHAR (1)       NULL,
    [tsca02]       NCHAR (1)       NULL,
    [tsca03]       NCHAR (1)       NULL,
    [tsca04]       NCHAR (1)       NULL,
    [tsca05]       NCHAR (1)       NULL,
    [tsca07]       NCHAR (1)       NULL,
    [tsca08]       NCHAR (1)       NULL,
    [tsca09]       NCHAR (1)       NULL,
    [tsca10]       NCHAR (1)       NULL,
    [tsca06]       NCHAR (1)       NULL,
    [tspcft]       NCHAR (1)       NULL,
    [tspcop]       NCHAR (1)       NULL,
    [tszolo]       NVARCHAR (10)   NULL,
    [tszola]       NVARCHAR (10)   NULL,
    [tszone]       NVARCHAR (10)   NULL,
    [tsdsem]       INT             NULL,
    [tsdsso]       INT             NULL,
    [Eff_Date]     DATE            NOT NULL,
    [End_Date]     DATE            NULL,
    [ActInd]       CHAR (1)        NULL,
    [IsDeleted]    CHAR (1)        NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    CONSTRAINT [PK_tsdsmd] PRIMARY KEY CLUSTERED ([dosvlg] ASC, [Eff_Date] ASC) WITH (FILLFACTOR = 90) ON [DWH_KEWILL_ARC]
) ON [DWH_KEWILL_ARC];





