CREATE TABLE [KEWILL_ARC].[tseecb] (
    [tseA00]       NVARCHAR (1)    NOT NULL,
    [tseA01]       INT             NOT NULL,
    [tseA02]       INT             NOT NULL,
    [tseA03]       NVARCHAR (20)   NOT NULL,
    [tseB00]       NVARCHAR (1)    NULL,
    [tseB01]       NVARCHAR (5)    NULL,
    [tseB02]       NVARCHAR (10)   NULL,
    [tseB03]       NVARCHAR (17)   NULL,
    [tseB04]       INT             NULL,
    [tseB05]       NVARCHAR (1)    NULL,
    [tseD00]       NVARCHAR (1)    NULL,
    [tseD01]       NUMERIC (13, 2) NULL,
    [tseD02]       BIGINT          NULL,
    [tseD03]       NVARCHAR (4)    NULL,
    [tseD04]       BIGINT          NULL,
    [tseD05]       NVARCHAR (26)   NULL,
    [tseD06]       NVARCHAR (22)   NULL,
    [tseD07]       NVARCHAR (10)   NULL,
    [tseD08]       NVARCHAR (17)   NULL,
    [tseD09]       NVARCHAR (3)    NULL,
    [tseD10]       INT             NULL,
    [tseD11]       NVARCHAR (4)    NULL,
    [tseD12]       BIGINT          NULL,
    [tseD13]       BIGINT          NULL,
    [tseD14]       NVARCHAR (25)   NULL,
    [tseD15]       NVARCHAR (20)   NULL,
    [tseE00]       NVARCHAR (1)    NULL,
    [tseE01]       NVARCHAR (3)    NULL,
    [tseE02]       NVARCHAR (3)    NULL,
    [tseE03]       SMALLINT        NULL,
    [tseE04]       SMALLINT        NULL,
    [tseE05]       NVARCHAR (10)   NULL,
    [tseE06]       NVARCHAR (10)   NULL,
    [tseE07]       NVARCHAR (14)   NULL,
    [tseE08]       INT             NULL,
    [tseE09]       NVARCHAR (1)    NULL,
    [tseE10]       NVARCHAR (1)    NULL,
    [tseE11]       NVARCHAR (1)    NULL,
    [tseE12]       NVARCHAR (35)   NULL,
    [tseE13]       NVARCHAR (35)   NULL,
    [tseE14]       NVARCHAR (35)   NULL,
    [tseE15]       NVARCHAR (15)   NULL,
    [tseE16]       NVARCHAR (26)   NULL,
    [tseE17]       NVARCHAR (22)   NULL,
    [tseE18]       NVARCHAR (1)    NULL,
    [tseE19]       NVARCHAR (4)    NULL,
    [tseE20]       BIGINT          NULL,
    [tseE21]       NVARCHAR (17)   NULL,
    [tseE22]       NVARCHAR (3)    NULL,
    [tseE23]       NVARCHAR (3)    NULL,
    [tseE24]       NVARCHAR (17)   NULL,
    [tseE25]       NUMERIC (15, 2) NULL,
    [tseE26]       NVARCHAR (3)    NULL,
    [tseE27]       NUMERIC (10, 8) NULL,
    [tseE28]       NUMERIC (14, 2) NULL,
    [tseE29]       NUMERIC (14, 2) NULL,
    [tseE30]       NUMERIC (14, 2) NULL,
    [tseE31]       NUMERIC (13, 2) NULL,
    [tseE32]       NUMERIC (5, 2)  NULL,
    [tseE33]       NUMERIC (10, 2) NULL,
    [tseE34]       NUMERIC (10, 2) NULL,
    [tseE35]       NUMERIC (10, 2) NULL,
    [tseE36]       NVARCHAR (7)    NULL,
    [tseE37]       INT             NULL,
    [tseE38]       NVARCHAR (3)    NULL,
    [tseE39]       NVARCHAR (10)   NULL,
    [tseE40]       SMALLINT        NULL,
    [tseE41]       NVARCHAR (1)    NULL,
    [tseE42]       NVARCHAR (1)    NULL,
    [tseE43]       NVARCHAR (1)    NULL,
    [tseE44]       NVARCHAR (1)    NULL,
    [tseE45]       NVARCHAR (1)    NULL,
    [tseE46]       NVARCHAR (1)    NULL,
    [tseE47]       NVARCHAR (1)    NULL,
    [tseE48]       TINYINT         NULL,
    [tseE49]       TINYINT         NULL,
    [tseF00]       NVARCHAR (1)    NULL,
    [tseF01]       NVARCHAR (1)    NULL,
    [tseF02]       NVARCHAR (26)   NULL,
    [tseF03]       NUMERIC (10, 2) NULL,
    [tseF04]       NUMERIC (10, 2) NULL,
    [tseF05]       NUMERIC (10, 2) NULL,
    [tseF06]       NUMERIC (8, 2)  NULL,
    [tsaf07]       NVARCHAR (2)    NULL,
    [tseG00]       NVARCHAR (1)    NULL,
    [tseG01]       TINYINT         NULL,
    [tseG02]       NUMERIC (10, 2) NULL,
    [tseG03]       TINYINT         NULL,
    [tseG04]       NUMERIC (10, 2) NULL,
    [tseG05]       TINYINT         NULL,
    [tseG06]       NUMERIC (10, 2) NULL,
    [tseG07]       TINYINT         NULL,
    [tseG08]       NUMERIC (10, 2) NULL,
    [tseG09]       NUMERIC (5, 2)  NULL,
    [tseG10]       NUMERIC (5, 2)  NULL,
    [tseG11]       NUMERIC (12, 1) NULL,
    [tseG12]       NUMERIC (12, 1) NULL,
    [tseG13]       NUMERIC (12, 1) NULL,
    [tseG14]       NUMERIC (9, 1)  NULL,
    [tseG15]       NVARCHAR (10)   NULL,
    [tseH00]       NVARCHAR (1)    NULL,
    [tseH01]       NVARCHAR (4)    NULL,
    [tseH02]       BIGINT          NULL,
    [tseH03]       NVARCHAR (17)   NULL,
    [tseH04]       NVARCHAR (3)    NULL,
    [tseH05]       INT             NULL,
    [tseH06]       NUMERIC (14, 4) NULL,
    [tseH07]       NUMERIC (14, 4) NULL,
    [tseH08]       NVARCHAR (14)   NULL,
    [tseH09]       INT             NULL,
    [tseH10]       NVARCHAR (3)    NULL,
    [tseH11]       NVARCHAR (3)    NULL,
    [tseH12]       NVARCHAR (3)    NULL,
    [tseH13]       NVARCHAR (5)    NULL,
    [tseH14]       NVARCHAR (5)    NULL,
    [tseH15]       NVARCHAR (5)    NULL,
    [tseH16]       NVARCHAR (5)    NULL,
    [tseH17]       NVARCHAR (1)    NULL,
    [tseH18]       NVARCHAR (3)    NULL,
    [tseJ00]       NVARCHAR (1)    NULL,
    [tseJ01]       NVARCHAR (5)    NULL,
    [tseJ02]       NVARCHAR (10)   NULL,
    [tseJ03]       NVARCHAR (17)   NULL,
    [tseJ04]       INT             NULL,
    [tseJ05]       NVARCHAR (1)    NULL,
    [tseK00]       NVARCHAR (1)    NULL,
    [tseK01]       NVARCHAR (3)    NULL,
    [tseK02]       NVARCHAR (1)    NULL,
    [tseK03]       NVARCHAR (26)   NULL,
    [tseK04]       NVARCHAR (22)   NULL,
    [tseK05]       NUMERIC (5, 2)  NULL,
    [tseK06]       NVARCHAR (4)    NULL,
    [tseK07]       NVARCHAR (2)    NULL,
    [tseK08]       NVARCHAR (9)    NULL,
    [tseK09]       BIGINT          NULL,
    [tseK10]       NUMERIC (14, 2) NULL,
    [tseK11]       NVARCHAR (3)    NULL,
    [tseK12]       NUMERIC (10, 8) NULL,
    [tseK13]       INT             NULL,
    [tseK14]       BIGINT          NULL,
    [tseK15]       NVARCHAR (4)    NULL,
    [tseK16]       NVARCHAR (4)    NULL,
    [tseK17]       NVARCHAR (4)    NULL,
    [tseK18]       NVARCHAR (4)    NULL,
    [tseK19]       NVARCHAR (4)    NULL,
    [tseK20]       NVARCHAR (10)   NULL,
    [tseK21]       NVARCHAR (10)   NULL,
    [tseK22]       NVARCHAR (15)   NULL,
    [tseK23]       NVARCHAR (15)   NULL,
    [tsaB05]       NVARCHAR (12)   NULL,
    [tsaB06]       NVARCHAR (3)    NULL,
    [tsaD01]       BIGINT          NULL,
    [tsaH01]       NVARCHAR (17)   NULL,
    [tsaH02]       NVARCHAR (3)    NULL,
    [tsaH03]       INT             NULL,
    [tsaH04]       NVARCHAR (20)   NULL,
    [tsaJ05]       NVARCHAR (12)   NULL,
    [tsaJ06]       NVARCHAR (3)    NULL,
    [tsaN00]       NVARCHAR (1)    NULL,
    [tsaN01]       NVARCHAR (3)    NULL,
    [tsaN02]       NVARCHAR (26)   NULL,
    [tsaN03]       NVARCHAR (22)   NULL,
    [tsaN04]       NVARCHAR (1)    NULL,
    [tsaN05]       NVARCHAR (4)    NULL,
    [tsaN06]       NVARCHAR (2)    NULL,
    [tsaN07]       NVARCHAR (9)    NULL,
    [tsaN08]       BIGINT          NULL,
    [tsaN09]       INT             NULL,
    [tsaN10]       SMALLINT        NULL,
    [tsaN11]       NVARCHAR (1)    NULL,
    [tsaN12]       BIGINT          NULL,
    [tsaN13]       NUMERIC (5, 2)  NULL,
    [tsaN14]       NUMERIC (5, 2)  NULL,
    [tsaN15]       NUMERIC (13, 2) NULL,
    [tsaN16]       NVARCHAR (10)   NULL,
    [tsaD15]       NVARCHAR (1)    NULL,
    [tsaD16]       NVARCHAR (17)   NULL,
    [tsaD17]       NVARCHAR (2)    NULL,
    [tsaH05]       NVARCHAR (1)    NULL,
    [tsaH06]       NVARCHAR (17)   NULL,
    [tsaH07]       BIGINT          NULL,
    [tsaN17]       NVARCHAR (4)    NULL,
    [tsaN18]       NVARCHAR (4)    NULL,
    [tsaN19]       NVARCHAR (4)    NULL,
    [tsaN20]       NVARCHAR (4)    NULL,
    [tsaN21]       NVARCHAR (4)    NULL,
    [tsaN22]       NVARCHAR (10)   NULL,
    [tsaN23]       NVARCHAR (10)   NULL,
    [tsaN24]       NVARCHAR (15)   NULL,
    [tsaN25]       NVARCHAR (15)   NULL,
    [tsdM00]       NVARCHAR (1)    NULL,
    [tsAI00]       NVARCHAR (1)    NULL,
    [tsAI01]       NUMERIC (10, 2) NULL,
    [tsAL00]       NVARCHAR (1)    NULL,
    [tsAL13]       NVARCHAR (5)    NULL,
    [tsAL14]       NVARCHAR (10)   NULL,
    [tsAL15]       INT             NULL,
    [vrfilk]       INT             NULL,
    [tslDdc]       NVARCHAR (1)    NULL,
    [tsinnr]       BIGINT          NULL,
    [tsfiA3]       NVARCHAR (1)    NULL,
    [tssnin]       INT             NULL,
    [artkd]        NVARCHAR (35)   NULL,
    [rnropd]       BIGINT          NULL,
    [Eff_Date]     DATE            NOT NULL,
    [End_Date]     DATE            NULL,
    [ActInd]       CHAR (1)        NULL,
    [IsDeleted]    CHAR (1)        NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    CONSTRAINT [PK_tseecb] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [tseA00] ASC, [tseA01] ASC, [tseA02] ASC, [tseA03] ASC) WITH (DATA_COMPRESSION = PAGE) ON [DWH_KEWILL_ARC]
) ON [DWH_KEWILL_ARC];



