CREATE TABLE [KEWILL_ARC].[tsmopd] (
    [vrfilk]       SMALLINT        NOT NULL,
    [tsinmd]       NVARCHAR (1)    NOT NULL,
    [tsopnr]       BIGINT          NOT NULL,
    [tsoprg]       INT             NOT NULL,
    [dosvlg]       BIGINT          NULL,
    [regel]        INT             NULL,
    [sub]          TINYINT         NULL,
    [status]       TINYINT         NULL,
    [vmtsrt]       TINYINT         NULL,
    [boekjj]       DATETIME2 (6)   NULL,
    [tsddmu]       DATETIME2 (6)   NULL,
    [tstimu]       TIME (4)        NULL,
    [oms]          NVARCHAR (30)   NULL,
    [rnropd]       BIGINT          NULL,
    [artkd]        NVARCHAR (35)   NULL,
    [magkd]        NVARCHAR (4)    NULL,
    [lockd]        NVARCHAR (6)    NULL,
    [comkod]       NVARCHAR (4)    NULL,
    [colkd]        NVARCHAR (2)    NULL,
    [eindvr]       NUMERIC (13, 3) NULL,
    [brgew]        NUMERIC (14, 3) NULL,
    [ntgew]        NUMERIC (14, 3) NULL,
    [tsvwck]       NVARCHAR (2)    NULL,
    [tsvwtv]       NUMERIC (13, 3) NULL,
    [tsvwbr]       NUMERIC (14, 3) NULL,
    [tsvwnt]       NUMERIC (14, 3) NULL,
    [vdscod]       NVARCHAR (3)    NULL,
    [tsdokn]       NVARCHAR (20)   NULL,
    [tspstn]       SMALLINT        NULL,
    [tskaaf]       NVARCHAR (10)   NULL,
    [ref01]        NVARCHAR (10)   NULL,
    [ref02]        NVARCHAR (5)    NULL,
    [tsdsts]       SMALLINT        NULL,
    [clando]       NVARCHAR (3)    NULL,
    [vrldhk]       NVARCHAR (3)    NULL,
    [clandb]       NVARCHAR (3)    NULL,
    [levcon]       SMALLINT        NULL,
    [tsvdac]       INT             NULL,
    [tsvdck]       NVARCHAR (2)    NULL,
    [likprs]       NUMERIC (15, 2) NULL,
    [tsikvk]       NVARCHAR (3)    NULL,
    [tsikkr]       NUMERIC (12, 6) NULL,
    [tsikve]       INT             NULL,
    [mudouw]       NUMERIC (14, 2) NULL,
    [valuta]       NVARCHAR (3)    NULL,
    [tsdwkr]       NUMERIC (12, 6) NULL,
    [tsdwve]       INT             NULL,
    [vrkstg]       NUMERIC (10, 2) NULL,
    [tsvkvk]       NVARCHAR (3)    NULL,
    [tsvkkr]       NUMERIC (12, 6) NULL,
    [tsvkve]       INT             NULL,
    [verzks]       NUMERIC (13, 2) NULL,
    [tsvzvk]       NVARCHAR (3)    NULL,
    [tsvzkr]       NUMERIC (12, 6) NULL,
    [tsvzve]       INT             NULL,
    [tsinin]       NUMERIC (15, 2) NULL,
    [tsinvk]       NVARCHAR (3)    NULL,
    [tsinkr]       NUMERIC (12, 6) NULL,
    [tsinve]       INT             NULL,
    [tsnopd]       BIGINT          NULL,
    [tsnpar]       NVARCHAR (20)   NULL,
    [tsnpda]       DATETIME2 (6)   NULL,
    [tsnvlg]       TINYINT         NULL,
    [tsnpad]       TINYINT         NULL,
    [tsnpaa]       NVARCHAR (35)   NULL,
    [tsnmag]       NVARCHAR (4)    NULL,
    [tsnlok]       NVARCHAR (6)    NULL,
    [tstek1]       NVARCHAR (1)    NULL,
    [tstek2]       NVARCHAR (1)    NULL,
    [tstek3]       NVARCHAR (3)    NULL,
    [tspart]       NVARCHAR (11)   NULL,
    [vrdkdj]       DATETIME2 (6)   NULL,
    [afd]          NVARCHAR (4)    NULL,
    [tsaant]       NUMERIC (13, 3) NULL,
    [tsvwaa]       NUMERIC (13, 3) NULL,
    [tspraa]       NUMERIC (13, 3) NULL,
    [tsprbr]       NUMERIC (13, 3) NULL,
    [tsprnt]       NUMERIC (13, 3) NULL,
    [tssnaa]       NUMERIC (13, 3) NULL,
    [tssnbr]       NUMERIC (13, 3) NULL,
    [tssnnt]       NUMERIC (13, 3) NULL,
    [asvsvm]       TINYINT         NULL,
    [asrbcb]       TINYINT         NULL,
    [asvvtk]       TINYINT         NULL,
    [asvkgb]       TINYINT         NULL,
    [asstst]       TINYINT         NULL,
    [astrac]       TINYINT         NULL,
    [assttw]       INT             NULL,
    [tskdaf]       TINYINT         NULL,
    [ts1nsl]       BIGINT          NULL,
    [ts2nsl]       BIGINT          NULL,
    [ts3nsl]       BIGINT          NULL,
    [ts4nsl]       BIGINT          NULL,
    [ts5nsl]       BIGINT          NULL,
    [tscapk]       INT             NULL,
    [tsexru]       NVARCHAR (6)    NULL,
    [tsivda]       DATETIME2 (6)   NULL,
    [tsivtd]       TIME (4)        NULL,
    [tsdfda]       DATETIME2 (6)   NULL,
    [tsdftd]       TIME (4)        NULL,
    [vrfitl]       INT             NULL,
    [tstrbd]       NUMERIC (14, 2) NULL,
    [tstrvk]       NVARCHAR (3)    NULL,
    [percpr]       NUMERIC (5, 2)  NULL,
    [btwkd]        INT             NULL,
    [atprys]       NUMERIC (13, 3) NULL,
    [tswdbd]       NUMERIC (14, 2) NULL,
    [tspryp]       NUMERIC (13, 3) NULL,
    [tsammg]       NVARCHAR (4)    NULL,
    [tsamlk]       NVARCHAR (6)    NULL,
    [tsvco1]       NUMERIC (13, 3) NULL,
    [tsvco2]       NUMERIC (13, 3) NULL,
    [tsvco3]       NUMERIC (13, 3) NULL,
    [tsvco4]       NUMERIC (13, 3) NULL,
    [tswco1]       NUMERIC (13, 3) NULL,
    [tswco2]       NUMERIC (13, 3) NULL,
    [tswco3]       NUMERIC (13, 3) NULL,
    [tswco4]       NUMERIC (13, 3) NULL,
    [tspain]       NUMERIC (13, 3) NULL,
    [tspaan]       NUMERIC (13, 3) NULL,
    [tspra1]       NUMERIC (13, 3) NULL,
    [tspra2]       NUMERIC (13, 3) NULL,
    [tspra3]       NUMERIC (13, 3) NULL,
    [tspra4]       NUMERIC (13, 3) NULL,
    [tspara]       NUMERIC (13, 3) NULL,
    [tspabr]       NUMERIC (13, 3) NULL,
    [tspant]       NUMERIC (13, 3) NULL,
    [tspar1]       NUMERIC (13, 3) NULL,
    [tspar2]       NUMERIC (13, 3) NULL,
    [tspar3]       NUMERIC (13, 3) NULL,
    [tspar4]       NUMERIC (13, 3) NULL,
    [tsinor]       INT             NULL,
    [tskrfk]       NUMERIC (13, 3) NULL,
    [tssmut]       TINYINT         NULL,
    [tsfkst]       TINYINT         NULL,
    [tsstcp]       TINYINT         NULL,
    [artgrs]       TINYINT         NULL,
    [tsskri]       TINYINT         NULL,
    [tsnsam]       NUMERIC (13, 3) NULL,
    [tsvdav]       NVARCHAR (3)    NULL,
    [tsvdvp]       NVARCHAR (3)    NULL,
    [tsagjn]       NCHAR (1)       NULL,
    [tsopwv]       TINYINT         NULL,
    [fill01]       NVARCHAR (1)    NULL,
    [tsinac]       NUMERIC (13, 3) NULL,
    [tsinck]       NVARCHAR (2)    NULL,
    [tsinte]       NUMERIC (13, 3) NULL,
    [tsinbg]       NUMERIC (14, 3) NULL,
    [tsinnt]       NUMERIC (14, 3) NULL,
    [tsina1]       NUMERIC (13, 3) NULL,
    [tsina2]       NUMERIC (13, 3) NULL,
    [tsina3]       NUMERIC (13, 3) NULL,
    [tsina4]       NUMERIC (13, 3) NULL,
    [tsback]       TINYINT         NULL,
    [tsbopr]       SMALLINT        NULL,
    [tscrdk]       TINYINT         NULL,
    [tsrman]       NVARCHAR (20)   NULL,
    [tsrtyp]       NVARCHAR (10)   NULL,
    [tsgdcd]       NVARCHAR (22)   NULL,
    [fill30]       NVARCHAR (30)   NULL,
    [tsmf20]       NVARCHAR (20)   NULL,
    [tsdsop]       NVARCHAR (20)   NULL,
    [tsfpex]       INT             NULL,
    [tsfpfi]       INT             NULL,
    [Eff_Date]     DATE            NOT NULL,
    [End_Date]     DATE            NULL,
    [ActInd]       CHAR (1)        NULL,
    [IsDeleted]    CHAR (1)        NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    CONSTRAINT [PK_tsmopd] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [tsinmd] ASC, [tsopnr] ASC, [tsoprg] ASC, [vrfilk] ASC) WITH (DATA_COMPRESSION = PAGE) ON [DWH_KEWILL_ARC]
) ON [DWH_KEWILL_ARC];



