CREATE TABLE [KEWILL_ARC].[vrarsf] (
    [rnropd]       BIGINT          NOT NULL,
    [artkd]        NVARCHAR (35)   NOT NULL,
    [vrfilk]       SMALLINT        NOT NULL,
    [minvr]        NUMERIC (13, 3) NULL,
    [maxvr]        NUMERIC (13, 3) NULL,
    [levtyd]       SMALLINT        NULL,
    [veilmg]       SMALLINT        NULL,
    [vrinlm]       SMALLINT        NULL,
    [vropim]       NCHAR (1)       NULL,
    [vrvsoi]       SMALLINT        NULL,
    [vrkpr1]       NUMERIC (12, 2) NULL,
    [vrkpr2]       NUMERIC (12, 2) NULL,
    [vrkpr3]       NUMERIC (12, 2) NULL,
    [sivrkp]       NUMERIC (12, 2) NULL,
    [sivrk2]       NUMERIC (12, 2) NULL,
    [sivrk3]       NUMERIC (12, 2) NULL,
    [kdcour]       TINYINT         NULL,
    [kdabca]       NVARCHAR (1)    NULL,
    [vrabcp]       NUMERIC (10, 6) NULL,
    [verkop]       NVARCHAR (8)    NULL,
    [inkopr]       NVARCHAR (8)    NULL,
    [vrkdpr]       NCHAR (1)       NULL,
    [vrkddl]       TINYINT         NULL,
    [rglhis]       INT             NULL,
    [vrfm10]       NVARCHAR (10)   NULL,
    [tssplv]       NCHAR (1)       NULL,
    [tsdppc]       NVARCHAR (2)    NULL,
    [tsdifp]       NUMERIC (5, 2)  NULL,
    [tsdifa]       NUMERIC (15, 2) NULL,
    [tscycm]       TINYINT         NULL,
    [tsdefa]       NCHAR (1)       NULL,
    [tsprjn]       NCHAR (1)       NULL,
    [tsleve]       BIGINT          NULL,
    [tsbsgr]       NUMERIC (13, 3) NULL,
    [magkd]        NVARCHAR (4)    NULL,
    [lockd]        NVARCHAR (6)    NULL,
    [tsvpck]       NVARCHAR (2)    NULL,
    [tsmavp]       NUMERIC (13, 3) NULL,
    [tsmpvp]       NUMERIC (5, 2)  NULL,
    [tsnrep]       NUMERIC (13, 3) NULL,
    [tsprep]       NVARCHAR (2)    NULL,
    [tsrvpp]       NUMERIC (5, 2)  NULL,
    [fill25]       NVARCHAR (25)   NULL,
    [tsccmn]       NUMERIC (13, 3) NULL,
    [tsccmv]       NUMERIC (13, 3) NULL,
    [tsccfc]       SMALLINT        NULL,
    [tsabcc]       NVARCHAR (1)    NULL,
    [tsabcn]       NVARCHAR (1)    NULL,
    [tsswpt]       NCHAR (1)       NULL,
    [tsswpl]       NCHAR (1)       NULL,
    [fill01]       NVARCHAR (1)    NULL,
    [tslsct]       DATETIME2 (6)   NULL,
    [tsswdb]       NCHAR (1)       NULL,
    [tsswlf]       NCHAR (1)       NULL,
    [tsswpf]       NCHAR (1)       NULL,
    [tsswdf]       NCHAR (1)       NULL,
    [tsswlp]       NCHAR (1)       NULL,
    [tsswpp]       NCHAR (1)       NULL,
    [tsswdp]       NCHAR (1)       NULL,
    [tsckfp]       NVARCHAR (2)    NULL,
    [tspmdt]       NCHAR (1)       NULL,
    [tspmdw]       NCHAR (1)       NULL,
    [Eff_Date]     DATE            NOT NULL,
    [End_Date]     DATE            NULL,
    [ActInd]       CHAR (1)        NULL,
    [IsDeleted]    CHAR (1)        NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    CONSTRAINT [PK_vrarsf] PRIMARY KEY CLUSTERED ([rnropd] ASC, [artkd] ASC, [vrfilk] ASC, [Eff_Date] ASC) WITH (FILLFACTOR = 90) ON [DWH_KEWILL_ARC]
) ON [DWH_KEWILL_ARC];





