CREATE TABLE [KEWILL_ARC].[vrfvrd] (
    [rnropd]       BIGINT          NOT NULL,
    [artkd]        NVARCHAR (35)   NOT NULL,
    [vrfilk]       SMALLINT        NOT NULL,
    [vrvrdt]       TINYINT         NOT NULL,
    [kstprs]       NUMERIC (12, 2) NULL,
    [sikstp]       NUMERIC (12, 2) NULL,
    [inkopv]       NUMERIC (13, 3) NULL,
    [verkpv]       NUMERIC (13, 3) NULL,
    [magopv]       NUMERIC (13, 3) NULL,
    [eindvr]       NUMERIC (13, 3) NULL,
    [vratgr]       NUMERIC (13, 3) NULL,
    [vratpr]       NUMERIC (13, 3) NULL,
    [verkrs]       NUMERIC (13, 3) NULL,
    [inkprs]       NUMERIC (13, 3) NULL,
    [atakvj]       NUMERIC (13, 3) NULL,
    [vrdnvk]       NUMERIC (13, 3) NULL,
    [wrdvrd]       NUMERIC (12, 2) NULL,
    [cumvkw]       NUMERIC (12, 2) NULL,
    [cumikw]       NUMERIC (12, 2) NULL,
    [wr1dat]       DATETIME2 (6)   NULL,
    [wkpdat]       DATETIME2 (6)   NULL,
    [wmodat]       DATETIME2 (6)   NULL,
    [wgodat]       DATETIME2 (6)   NULL,
    [wgadat]       DATETIME2 (6)   NULL,
    [atikvj]       NUMERIC (13, 3) NULL,
    [atik2j]       NUMERIC (13, 3) NULL,
    [atvkvj]       NUMERIC (13, 3) NULL,
    [atvk2j]       NUMERIC (13, 3) NULL,
    [atak2j]       NUMERIC (13, 3) NULL,
    [magkd]        NVARCHAR (4)    NULL,
    [lockd]        NVARCHAR (6)    NULL,
    [fill20]       NVARCHAR (20)   NULL,
    [vrauil]       NUMERIC (13, 3) NULL,
    [vrinor]       NUMERIC (13, 3) NULL,
    [brgew]        NUMERIC (13, 3) NULL,
    [ntgew]        NUMERIC (13, 3) NULL,
    [tsonbr]       NUMERIC (13, 3) NULL,
    [tstont]       NUMERIC (13, 3) NULL,
    [tstobr]       NUMERIC (13, 3) NULL,
    [tsgron]       NUMERIC (13, 3) NULL,
    [tsgrob]       NUMERIC (13, 3) NULL,
    [tsgonn]       NUMERIC (13, 3) NULL,
    [tsonnt]       NUMERIC (13, 3) NULL,
    [tstlnt]       NUMERIC (13, 3) NULL,
    [tsgelb]       NUMERIC (13, 3) NULL,
    [tsgeln]       NUMERIC (13, 3) NULL,
    [tsiubr]       NUMERIC (13, 3) NULL,
    [tsiunt]       NUMERIC (13, 3) NULL,
    [tsbabr]       NUMERIC (13, 3) NULL,
    [tsbant]       NUMERIC (13, 3) NULL,
    [tsdgbr]       NUMERIC (13, 3) NULL,
    [tsdgnt]       NUMERIC (13, 3) NULL,
    [tsvnbr]       NUMERIC (13, 3) NULL,
    [tsvnnt]       NUMERIC (13, 3) NULL,
    [tswco1]       NUMERIC (13, 3) NULL,
    [tswco2]       NUMERIC (13, 3) NULL,
    [tswco3]       NUMERIC (13, 3) NULL,
    [tswco4]       NUMERIC (13, 3) NULL,
    [tsoco1]       NUMERIC (13, 3) NULL,
    [tsoco2]       NUMERIC (13, 3) NULL,
    [tsoco3]       NUMERIC (13, 3) NULL,
    [tsoco4]       NUMERIC (13, 3) NULL,
    [tsuco1]       NUMERIC (13, 3) NULL,
    [tsuco2]       NUMERIC (13, 3) NULL,
    [tsuco3]       NUMERIC (13, 3) NULL,
    [tsuco4]       NUMERIC (13, 3) NULL,
    [tskrev]       NUMERIC (13, 3) NULL,
    [tskrnt]       NUMERIC (13, 3) NULL,
    [tskrbr]       NUMERIC (13, 3) NULL,
    [Eff_Date]     DATE            NOT NULL,
    [End_Date]     DATE            NULL,
    [ActInd]       CHAR (1)        NULL,
    [IsDeleted]    CHAR (1)        NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    CONSTRAINT [PK_vrfvrd] PRIMARY KEY CLUSTERED ([artkd] ASC, [Eff_Date] ASC, [rnropd] ASC, [vrfilk] ASC, [vrvrdt] ASC) ON [DWH_KEWILL_ARC]
) ON [DWH_KEWILL_ARC];

