CREATE TABLE [PROD].[CUSTOMER_PARENTS] (
    [CUSTOMER_NO]     NVARCHAR (20) NOT NULL,
    [HIERARCHY_ID]    NVARCHAR (10) NOT NULL,
    [CUSTOMER_PARENT] NVARCHAR (20) NOT NULL,
    [BatchID]         BIGINT        NULL,
    [ProcessLogID]    BIGINT        NULL,
    CONSTRAINT [PK_CUSTOMER_PARENTS] PRIMARY KEY CLUSTERED ([HIERARCHY_ID] ASC, [CUSTOMER_PARENT] ASC, [CUSTOMER_NO] ASC)
);

