CREATE TABLE [PROD].[FND_USER_ROLE] (
    [IDENTITY]     NVARCHAR (30)   NOT NULL,
    [ROLE]         NVARCHAR (30)   NOT NULL,
    [OBJID]        NVARCHAR (4000) NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    CONSTRAINT [PK_FND_USER_ROLE] PRIMARY KEY CLUSTERED ([IDENTITY] ASC, [ROLE] ASC)
);

