CREATE TABLE [PROD].[GEN_LED_VOUCHER_ROW] (
    [COMPANY]                      NVARCHAR (20)   NOT NULL,
    [VOUCHER_TYPE]                 NVARCHAR (3)    NOT NULL,
    [ACCOUNTING_YEAR]              INT             NOT NULL,
    [VOUCHER_NO]                   INT             NOT NULL,
    [ROW_NO]                       INT             NOT NULL,
    [YEAR_PERIOD]                  NVARCHAR (7)    NULL,
    [YEAR_PERIOD_KEY]              INT             NULL,
    [INTERNAL_SEQ_NUMBER]          INT             NULL,
    [POSTING_COMBINATION_ID]       INT             NULL,
    [VOUCHER_DATE]                 DATETIME2 (7)   NULL,
    [ACCOUNT]                      NVARCHAR (20)   NULL,
    [ACCOUNT_DESC]                 NVARCHAR (4000) NULL,
    [CODE_B]                       NVARCHAR (20)   NULL,
    [CODE_B_DESC]                  NVARCHAR (4000) NULL,
    [CODE_C]                       NVARCHAR (20)   NULL,
    [CODE_C_DESC]                  NVARCHAR (4000) NULL,
    [CODE_D]                       NVARCHAR (20)   NULL,
    [CODE_D_DESC]                  NVARCHAR (4000) NULL,
    [CODE_E]                       NVARCHAR (20)   NULL,
    [CODE_E_DESC]                  NVARCHAR (4000) NULL,
    [CODE_F]                       NVARCHAR (20)   NULL,
    [CODE_F_DESC]                  NVARCHAR (4000) NULL,
    [CODE_G]                       NVARCHAR (20)   NULL,
    [CODE_G_DESC]                  NVARCHAR (4000) NULL,
    [CODE_H]                       NVARCHAR (20)   NULL,
    [CODE_H_DESC]                  NVARCHAR (4000) NULL,
    [CODE_I]                       NVARCHAR (20)   NULL,
    [CODE_I_DESC]                  NVARCHAR (4000) NULL,
    [CODE_J]                       NVARCHAR (20)   NULL,
    [CODE_J_DESC]                  NVARCHAR (4000) NULL,
    [TRANS_CODE]                   NVARCHAR (100)  NULL,
    [CURRENCY_DEBET_AMOUNT]        INT             NULL,
    [CURRENCY_CREDIT_AMOUNT]       INT             NULL,
    [CURRENCY_AMOUNT]              INT             NULL,
    [DEBET_AMOUNT]                 INT             NULL,
    [CREDIT_AMOUNT]                INT             NULL,
    [AMOUNT]                       INT             NULL,
    [CORRECTION]                   NVARCHAR (1)    NULL,
    [CURRENCY_CODE]                NVARCHAR (3)    NULL,
    [QUANTITY]                     INT             NULL,
    [PROCESS_CODE]                 NVARCHAR (10)   NULL,
    [OPTIONAL_CODE]                NVARCHAR (20)   NULL,
    [PROJECT_ACTIVITY_ID]          INT             NULL,
    [PERIOD_ALLOCATION]            NVARCHAR (1)    NULL,
    [TEXT]                         NVARCHAR (200)  NULL,
    [PARTY_TYPE_ID]                NVARCHAR (20)   NULL,
    [REFERENCE_SERIE]              NVARCHAR (50)   NULL,
    [REFERENCE_NUMBER]             NVARCHAR (50)   NULL,
    [TRANSFER_ID]                  NVARCHAR (200)  NULL,
    [AUT_CODING_RULE]              NVARCHAR (20)   NULL,
    [ORG_PARENT_ROW]               INT             NULL,
    [PARENT_ROW]                   INT             NULL,
    [AUTOBOOK]                     NVARCHAR (1)    NULL,
    [AUT_CODING_SEQ]               INT             NULL,
    [AUT_CODING_PARENT_ROW]        INT             NULL,
    [INTERNAL_ACCOUNTING]          NVARCHAR (1)    NULL,
    [CURR_ACCOUNTING]              NVARCHAR (4000) NULL,
    [CURR_ACCOUNTING_DB]           NVARCHAR (1)    NULL,
    [PROJECT_ACCOUNTING]           NVARCHAR (4000) NULL,
    [PROJECT_ACCOUNTING_DB]        NVARCHAR (1)    NULL,
    [SUMMERIZED]                   NVARCHAR (4000) NULL,
    [SUMMERIZED_DB]                NVARCHAR (1)    NULL,
    [OLD_ROW_NO]                   INT             NULL,
    [OLD_PERIOD]                   INT             NULL,
    [CORRECTED]                    NVARCHAR (1)    NULL,
    [HEADER_CORRECTION]            NVARCHAR (50)   NULL,
    [THIRD_CURRENCY_DEBIT_AMOUNT]  INT             NULL,
    [THIRD_CURRENCY_CREDIT_AMOUNT] INT             NULL,
    [THIRD_CURRENCY_AMOUNT]        INT             NULL,
    [THIRD_CURRENCY_RATE]          INT             NULL,
    [ACCOUNTING_PERIOD]            INT             NULL,
    [CURRENCY_RATE]                INT             NULL,
    [CONVERSION_FACTOR]            INT             NULL,
    [MULTI_COMPANY_ID]             NVARCHAR (20)   NULL,
    [IS_MULTI_COMPANY_VOUCHER]     NVARCHAR (5)    NULL,
    [FUNCTION_GROUP]               NVARCHAR (10)   NULL,
    [MATCHING_DATE]                DATETIME2 (7)   NULL,
    [MATCHING_PERIOD]              INT             NULL,
    [MATCHING_NO]                  NVARCHAR (10)   NULL,
    [MATCHING_YEAR]                INT             NULL,
    [REFERENCE_ROW_NO]             INT             NULL,
    [AUTO_TAX_VOU_ENTRY]           NVARCHAR (20)   NULL,
    [SIMULATION_VOUCHER]           NVARCHAR (5)    NULL,
    [NCF_SETTLEMENT_DATE]          DATETIME2 (7)   NULL,
    [SEQUENCE_NO]                  INT             NULL,
    [MPCCOM_ACCOUNTING_ID]         INT             NULL,
    [ACTIVATE_CODE]                NVARCHAR (20)   NULL,
    [JOURNAL_ID]                   NVARCHAR (20)   NULL,
    [ROW_GROUP_ID]                 INT             NULL,
    [ALLOCATION_ID]                INT             NULL,
    [ALLOC_LINE_ID]                INT             NULL,
    [CREATOR_DESC]                 NVARCHAR (4000) NULL,
    [OBJID]                        NVARCHAR (4000) NULL,
    [OBJVERSION]                   NVARCHAR (2000) NULL,
    [BatchID]                      BIGINT          NULL,
    [ProcessLogID]                 BIGINT          NULL,
    CONSTRAINT [PK_GEN_LED_VOUCHER_ROW] PRIMARY KEY CLUSTERED ([ACCOUNTING_YEAR] ASC, [COMPANY] ASC, [VOUCHER_TYPE] ASC, [VOUCHER_NO] ASC, [ROW_NO] ASC)
);

