CREATE TABLE [PROD].[SALES_PART] (
    [CONTRACT]                   NVARCHAR (5)    NOT NULL,
    [CATALOG_NO]                 NVARCHAR (25)   NOT NULL,
    [PARENT_PART]                NVARCHAR (25)   NOT NULL,
    [CATALOG_DESC]               NVARCHAR (200)  NULL,
    [PART_NO]                    NVARCHAR (25)   NULL,
    [CATALOG_GROUP]              NVARCHAR (10)   NULL,
    [SALES_PRICE_GROUP_ID]       NVARCHAR (10)   NULL,
    [ENG_ATTRIBUTE]              NVARCHAR (5)    NULL,
    [NOTE_ID]                    INT             NULL,
    [PRINT_CONTROL_CODE]         NVARCHAR (10)   NULL,
    [SALES_UNIT_MEAS]            NVARCHAR (10)   NULL,
    [ACTIVEIND]                  NVARCHAR (200)  NULL,
    [ACTIVEIND_DB]               NVARCHAR (20)   NULL,
    [BONUS_BASIS_FLAG]           NVARCHAR (200)  NULL,
    [BONUS_BASIS_FLAG_DB]        NVARCHAR (20)   NULL,
    [BONUS_VALUE_FLAG]           NVARCHAR (200)  NULL,
    [BONUS_VALUE_FLAG_DB]        NVARCHAR (20)   NULL,
    [CATALOG_TYPE]               NVARCHAR (200)  NULL,
    [CATALOG_TYPE_DB]            NVARCHAR (20)   NULL,
    [CONV_FACTOR]                INT             NULL,
    [COST]                       DECIMAL (18, 2) NULL,
    [CUSTOMS_STAT_NO]            NVARCHAR (10)   NULL,
    [DATE_ENTERED]               DATETIME2 (7)   NULL,
    [DISCOUNT_GROUP]             NVARCHAR (6)    NULL,
    [LIST_PRICE]                 DECIMAL (18, 2) NULL,
    [NOTE_TEXT]                  NVARCHAR (2000) NULL,
    [PACKAGE_TYPE]               NVARCHAR (10)   NULL,
    [PRICE_CHANGE_DATE]          DATETIME2 (7)   NULL,
    [PRICE_CONV_FACTOR]          INT             NULL,
    [PRICE_UNIT_MEAS]            NVARCHAR (4)    NULL,
    [VOLUME]                     INT             NULL,
    [WEIGHT_GROSS]               INT             NULL,
    [WEIGHT_NET]                 INT             NULL,
    [COMPANY]                    NVARCHAR (20)   NULL,
    [FEE_CODE]                   NVARCHAR (20)   NULL,
    [TAXABLE]                    NVARCHAR (200)  NULL,
    [TAXABLE_DB]                 NVARCHAR (20)   NULL,
    [PROPOSED_PARCEL_QTY]        INT             NULL,
    [CLOSE_TOLERANCE]            INT             NULL,
    [CREATE_SM_OBJECT_OPTION]    NVARCHAR (200)  NULL,
    [CREATE_SM_OBJECT_OPTION_DB] NVARCHAR (20)   NULL,
    [EXPECTED_AVERAGE_PRICE]     DECIMAL (18, 2) NULL,
    [PURCHASE_PART_NO]           NVARCHAR (25)   NULL,
    [REPLACEMENT_PART_NO]        NVARCHAR (25)   NULL,
    [DATE_OF_REPLACEMENT]        DATETIME2 (7)   NULL,
    [CUST_WARRANTY_ID]           INT             NULL,
    [NON_INV_PART_TYPE]          NVARCHAR (200)  NULL,
    [NON_INV_PART_TYPE_DB]       NVARCHAR (20)   NULL,
    [INTRASTAT_CONV_FACTOR]      INT             NULL,
    [SOURCING_OPTION]            NVARCHAR (200)  NULL,
    [SOURCING_OPTION_DB]         NVARCHAR (20)   NULL,
    [RULE_ID]                    NVARCHAR (15)   NULL,
    [PALLET_TYPE]                NVARCHAR (25)   NULL,
    [PROPOSED_PALLET_QTY]        INT             NULL,
    [QUICK_REGISTERED_PART]      NVARCHAR (200)  NULL,
    [QUICK_REGISTERED_PART_DB]   NVARCHAR (20)   NULL,
    [MINIMUM_QTY]                INT             NULL,
    [DELIVERY_TYPE]              NVARCHAR (20)   NULL,
    [EXPORT_TO_EXTERNAL_APP]     NVARCHAR (200)  NULL,
    [EXPORT_TO_EXTERNAL_APP_DB]  NVARCHAR (20)   NULL,
    [ALLOW_PARTIAL_PKG_DELIV]    NVARCHAR (200)  NULL,
    [ALLOW_PARTIAL_PKG_DELIV_DB] NVARCHAR (20)   NULL,
    [TEXT_ID$]                   NVARCHAR (50)   NULL,
    [SALES_PART_REBATE_GROUP]    NVARCHAR (10)   NULL,
    [GTIN_NO]                    NVARCHAR (14)   NULL,
    [GTIN_SERIES]                NVARCHAR (200)  NULL,
    [GTIN_SERIES_DB]             NVARCHAR (20)   NULL,
    [USE_SITE_SPECIFIC]          NVARCHAR (200)  NULL,
    [USE_SITE_SPECIFIC_DB]       NVARCHAR (20)   NULL,
    [PRIMARY_CATALOG]            NVARCHAR (200)  NULL,
    [PRIMARY_CATALOG_DB]         NVARCHAR (20)   NULL,
    [AUTO_CREATED_GTIN]          NVARCHAR (5)    NULL,
    [C_SALES_CODE1]              NVARCHAR (50)   NULL,
    [C_SALES_CODE2]              NVARCHAR (50)   NULL,
    [C_SALES_CODE3]              NVARCHAR (50)   NULL,
    [C_TAX_CATEGORY]             NVARCHAR (20)   NULL,
    [C_NET_WEIGHT]               INT             NULL,
    [C_NET_VOLUME]               INT             NULL,
    [OBJID]                      NVARCHAR (100)  NULL,
    [OBJVERSION]                 BIGINT          NULL,
    [BatchID]                    BIGINT          NULL,
    [ProcessLogID]               BIGINT          NULL,
    CONSTRAINT [PK_SALES_PART] PRIMARY KEY CLUSTERED ([CONTRACT] ASC, [CATALOG_NO] ASC, [PARENT_PART] ASC)
);

