CREATE TABLE [PROD].[USER_PROFILE_ENTRY] (
    [ENTRY_CODE]   NVARCHAR (30) NOT NULL,
    [ENTRY_VALUE]  NVARCHAR (30) NOT NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    CONSTRAINT [PK_USER_PROFILE_ENTRY] PRIMARY KEY CLUSTERED ([ENTRY_CODE] ASC, [ENTRY_VALUE] ASC)
);

