CREATE TABLE [TRANS].[CARGO_ITEM] (
    [CARGO_ID]     BIGINT NOT NULL,
    [INTERFACE_ID] BIGINT NOT NULL,
    [BatchID]      BIGINT NULL,
    [ProcessLogID] BIGINT NULL,
    CONSTRAINT [PK_CARGO_ITEM] PRIMARY KEY CLUSTERED ([CARGO_ID] ASC, [INTERFACE_ID] ASC)
);

