CREATE TABLE [TRANS].[DPD_SERVICE] (
    [SERVICE_NR]       VARCHAR (20) NOT NULL,
    [SERVICE_TEXT]     VARCHAR (20) NULL,
    [SERVICE_MARK]     VARCHAR (20) NULL,
    [SERVICE_ELEMENTS] VARCHAR (50) NULL,
    [BatchID]          BIGINT       NULL,
    [ProcessLogID]     BIGINT       NULL,
    CONSTRAINT [PK_DPD_SERVICE] PRIMARY KEY CLUSTERED ([SERVICE_NR] ASC)
);

