CREATE TABLE [TRANS].[EDI_SHIPMENT] (
    [INTERFACE_ID]          BIGINT NOT NULL,
    [SHIPMENT_INTERFACE_ID] BIGINT NOT NULL,
    [BatchID]               BIGINT NULL,
    [ProcessLogID]          BIGINT NULL,
    CONSTRAINT [PK_EDI_SHIPMENT] PRIMARY KEY CLUSTERED ([INTERFACE_ID] ASC, [SHIPMENT_INTERFACE_ID] ASC)
);

