CREATE TABLE [TRANS].[FD_FORWARDER] (
    [FD_FORWARDER_CODE] VARCHAR (20) NOT NULL,
    [HUB_FORWARDER_ID]  INT          NULL,
    [HUB_SERVICE_ID]    INT          NULL,
    [BatchID]           BIGINT       NULL,
    [ProcessLogID]      BIGINT       NULL,
    CONSTRAINT [PK_FD_FORWARDER] PRIMARY KEY CLUSTERED ([FD_FORWARDER_CODE] ASC)
);

