CREATE TABLE [TRANS].[KIALA_DEPOT_ZIP] (
    [POSTAL_CODE]    VARCHAR (10) NOT NULL,
    [COUNTRY_CODE]   VARCHAR (3)  NOT NULL,
    [KIALA_DEPOT_ID] VARCHAR (20) NOT NULL,
    [PRIORITY]       INT          NOT NULL,
    [BatchID]        BIGINT       NULL,
    [ProcessLogID]   BIGINT       NULL,
    CONSTRAINT [PK_KIALA_DEPOT_ZIP] PRIMARY KEY CLUSTERED ([POSTAL_CODE] ASC, [COUNTRY_CODE] ASC, [KIALA_DEPOT_ID] ASC, [PRIORITY] ASC)
);

