CREATE TABLE [TRANS].[POSTNORD_DEPOT_ZIP] (
    [PN_COUNTRY_CODE] VARCHAR (3)  NOT NULL,
    [PN_POSTAL_CODE]  VARCHAR (10) NOT NULL,
    [PN_DEPOT_ID]     INT          NOT NULL,
    [BatchID]         BIGINT       NULL,
    [ProcessLogID]    BIGINT       NULL,
    CONSTRAINT [PK_POSTNORD_DEPOT_ZIP] PRIMARY KEY CLUSTERED ([PN_COUNTRY_CODE] ASC, [PN_POSTAL_CODE] ASC, [PN_DEPOT_ID] ASC)
);

