CREATE TABLE [TRANS].[PROJECT] (
    [PROJECT_ID]   INT            NOT NULL,
    [DSN_ID]       INT            NULL,
    [PROJECT_CODE] VARCHAR (20)   NOT NULL,
    [PROJECT_NAME] NVARCHAR (100) NULL,
    [CREATED]      DATETIME2 (7)  NULL,
    [DESCRIPTION]  VARCHAR (200)  NULL,
    [BatchID]      BIGINT         NULL,
    [ProcessLogID] BIGINT         NULL,
    CONSTRAINT [PK_PROJECT] PRIMARY KEY CLUSTERED ([PROJECT_ID] ASC)
);

