CREATE TABLE [IFS].[ACCOUNTING_GROUP] (
    [ACCOUNTING_GROUP] NVARCHAR (5)    NOT NULL,
    [OBJVERSION]       NVARCHAR (2000) NULL,
    [BatchID]          BIGINT          NULL,
    [ProcessLogID]     BIGINT          NULL,
    [Issue]            TINYINT         NULL,
    CONSTRAINT [PK_ACCOUNTING_GROUP] PRIMARY KEY CLUSTERED ([ACCOUNTING_GROUP] ASC)
);

