CREATE TABLE [IFS].[ACCOUNTING_BALANCE] (
    [COMPANY]                NVARCHAR (20)   NOT NULL,
    [ACCOUNTING_YEAR]        INT             NOT NULL,
    [ACCOUNTING_PERIOD]      INT             NOT NULL,
    [POSTING_COMBINATION_ID] INT             NOT NULL,
    [SIMULATION_VOUCHER]     NVARCHAR (5)    NOT NULL,
    [OBJVERSION]             NVARCHAR (2000) NULL,
    [BatchID]                BIGINT          NULL,
    [ProcessLogID]           BIGINT          NULL,
    [Issue]                  TINYINT         NULL,
    CONSTRAINT [PK_ACCOUNTING_BALANCE] PRIMARY KEY CLUSTERED ([COMPANY] ASC, [ACCOUNTING_YEAR] ASC, [ACCOUNTING_PERIOD] ASC, [POSTING_COMBINATION_ID] ASC, [SIMULATION_VOUCHER] ASC)
);

