CREATE TABLE [IFS].[C_KEWILL_STOCK_RECON] (
    [CONTRACT]       NVARCHAR (5)  NOT NULL,
    [CUST_NO]        NVARCHAR (50) NOT NULL,
    [PART_NO]        NVARCHAR (50) NOT NULL,
    [CUSTOMS_STATUS] NVARCHAR (50) NOT NULL,
    [LOT_BATCH_NO]   NVARCHAR (20) NOT NULL,
    [OBJVERSION]     NVARCHAR (14) NOT NULL,
    [BatchID]        BIGINT        NULL,
    [ProcessLogID]   BIGINT        NULL,
    [Issue]          TINYINT       NULL,
    CONSTRAINT [PK_C_KEWILL_STOCK_RECON] PRIMARY KEY CLUSTERED ([CONTRACT] ASC, [CUST_NO] ASC, [PART_NO] ASC, [CUSTOMS_STATUS] ASC, [LOT_BATCH_NO] ASC, [OBJVERSION] ASC)
);

