CREATE TABLE [IFS].[C_TRANSPORT_TYPE] (
    [TRANSPORT_TYPE] NVARCHAR (30)   NOT NULL,
    [OBJVERSION]     NVARCHAR (2000) NULL,
    [BatchID]        BIGINT          NULL,
    [ProcessLogID]   BIGINT          NULL,
    [Issue]          TINYINT         NULL,
    CONSTRAINT [PK_C_TRANSPORT_TYPE] PRIMARY KEY CLUSTERED ([TRANSPORT_TYPE] ASC)
);

