CREATE TABLE [IFS].[COMPANY_INVOICE_INFO] (
    [COMPANY]      NVARCHAR (20)   NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_COMPANY_INVOICE_INFO] PRIMARY KEY CLUSTERED ([COMPANY] ASC)
);

