CREATE TABLE [IFS].[CURRENCY_TYPE] (
    [COMPANY]       NVARCHAR (20)   NOT NULL,
    [CURRENCY_TYPE] NVARCHAR (10)   NOT NULL,
    [OBJVERSION]    NVARCHAR (2000) NULL,
    [BatchID]       BIGINT          NULL,
    [ProcessLogID]  BIGINT          NULL,
    [Issue]         TINYINT         NULL,
    CONSTRAINT [PK_CURRENCY_TYPE] PRIMARY KEY CLUSTERED ([COMPANY] ASC, [CURRENCY_TYPE] ASC)
);

