CREATE TABLE [IFS].[CURRENCY_RATE] (
    [COMPANY]       NVARCHAR (20) NOT NULL,
    [CURRENCY_TYPE] NVARCHAR (10) NOT NULL,
    [CURRENCY_CODE] NVARCHAR (3)  NOT NULL,
    [VALID_FROM]    DATETIME2 (7) NOT NULL,
    [OBJVERSION]    NVARCHAR (14) NULL,
    [BatchID]       BIGINT        NULL,
    [ProcessLogID]  BIGINT        NULL,
    [Issue]         TINYINT       NULL,
    CONSTRAINT [PK_CURRENCY_RATE] PRIMARY KEY CLUSTERED ([COMPANY] ASC, [CURRENCY_TYPE] ASC, [CURRENCY_CODE] ASC, [VALID_FROM] ASC)
);

