CREATE TABLE [IFS].[CUST_ORD_CUSTOMER] (
    [CUSTOMER_NO]  NVARCHAR (20)   NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_CUST_ORD_CUSTOMER] PRIMARY KEY CLUSTERED ([CUSTOMER_NO] ASC)
);

