CREATE TABLE [IFS].[CUSTOMER_ORDER_LINE] (
    [ORDER_NO]     NVARCHAR (12) NOT NULL,
    [LINE_NO]      NVARCHAR (4)  NOT NULL,
    [REL_NO]       NVARCHAR (4)  NOT NULL,
    [LINE_ITEM_NO] INT           NOT NULL,
    [OBJVERSION]   BIGINT        NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    [Issue]        TINYINT       NULL,
    CONSTRAINT [PK_CUSTOMER_ORDER_LINE] PRIMARY KEY CLUSTERED ([ORDER_NO] ASC, [LINE_NO] ASC, [REL_NO] ASC, [LINE_ITEM_NO] ASC)
);

