CREATE TABLE [IFS].[CUSTOMER_INFO] (
    [CUSTOMER_ID]  NVARCHAR (20)   NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_CUSTOMER_INFO] PRIMARY KEY CLUSTERED ([CUSTOMER_ID] ASC)
);

