CREATE TABLE [IFS].[CUST_PRICE_GROUP_DETAIL] (
    [CUST_PRICE_GROUP_ID]  NVARCHAR (10)   NOT NULL,
    [SALES_PRICE_GROUP_ID] NVARCHAR (10)   NOT NULL,
    [CURRENCY_CODE]        NVARCHAR (3)    NOT NULL,
    [COMPANY]              NVARCHAR (20)   NOT NULL,
    [OBJVERSION]           NVARCHAR (2000) NULL,
    [BatchID]              BIGINT          NULL,
    [ProcessLogID]         BIGINT          NULL,
    [Issue]                TINYINT         NULL,
    CONSTRAINT [PK_CUST_PRICE_GROUP_DETAIL] PRIMARY KEY CLUSTERED ([CUST_PRICE_GROUP_ID] ASC, [SALES_PRICE_GROUP_ID] ASC, [CURRENCY_CODE] ASC, [COMPANY] ASC)
);

