CREATE TABLE [IFS].[HISTORY_LOG_ATTRIBUTE] (
    [LOG_ID]       INT             NOT NULL,
    [COLUMN_NAME]  NVARCHAR (30)   NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_HISTORY_LOG_ATTRIBUTE] PRIMARY KEY CLUSTERED ([LOG_ID] ASC, [COLUMN_NAME] ASC)
);

