CREATE TABLE [IFS].[INVENTORY_TRANSACTION_HIST] (
    [TRANSACTION_ID] INT             NOT NULL,
    [OBJVERSION]     NVARCHAR (2000) NULL,
    [BatchID]        BIGINT          NULL,
    [ProcessLogID]   BIGINT          NULL,
    [Issue]          TINYINT         NULL,
    CONSTRAINT [PK_INVENTORY_TRANSACTION_HIST] PRIMARY KEY CLUSTERED ([TRANSACTION_ID] ASC)
);

