CREATE TABLE [IFS].[INVENTORY_LOCATION] (
    [CONTRACT]     NVARCHAR (5)    NOT NULL,
    [WAREHOUSE]    NVARCHAR (15)   NOT NULL,
    [BAY_NO]       NVARCHAR (5)    NOT NULL,
    [ROW_NO]       NVARCHAR (5)    NOT NULL,
    [TIER_NO]      NVARCHAR (5)    NOT NULL,
    [BIN_NO]       NVARCHAR (5)    NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_INVENTORY_LOCATION] PRIMARY KEY CLUSTERED ([CONTRACT] ASC, [WAREHOUSE] ASC, [BAY_NO] ASC, [ROW_NO] ASC, [TIER_NO] ASC, [BIN_NO] ASC)
);

