CREATE TABLE [IFS].[INVENTORY_PRODUCT_FAMILY] (
    [PART_PRODUCT_FAMILY] NVARCHAR (5) NOT NULL,
    [OBJVERSION]          BIGINT       NULL,
    [BatchID]             BIGINT       NULL,
    [ProcessLogID]        BIGINT       NULL,
    [Issue]               TINYINT      NULL,
    CONSTRAINT [PK_INVENTORY_PRODUCT_FAMILY_1] PRIMARY KEY CLUSTERED ([PART_PRODUCT_FAMILY] ASC)
);

