CREATE TABLE [IFS].[INVENTORY_PART_IN_STOCK] (
    [CONTRACT]         NVARCHAR (5)  NOT NULL,
    [PART_NO]          NVARCHAR (25) NOT NULL,
    [CONFIGURATION_ID] NVARCHAR (50) NOT NULL,
    [LOCATION_NO]      NVARCHAR (35) NOT NULL,
    [LOT_BATCH_NO]     NVARCHAR (20) NOT NULL,
    [SERIAL_NO]        NVARCHAR (50) NOT NULL,
    [ENG_CHG_LEVEL]    NVARCHAR (2)  NOT NULL,
    [WAIV_DEV_REJ_NO]  NVARCHAR (15) NOT NULL,
    [ACTIVITY_SEQ]     INT           NOT NULL,
    [OBJVERSION]       BIGINT        NULL,
    [BatchID]          BIGINT        NULL,
    [ProcessLogID]     BIGINT        NULL,
    [Issue]            TINYINT       NULL,
    CONSTRAINT [PK_INVENTORY_PART_IN_STOCK_1] PRIMARY KEY CLUSTERED ([CONTRACT] ASC, [PART_NO] ASC, [CONFIGURATION_ID] ASC, [LOCATION_NO] ASC, [LOT_BATCH_NO] ASC, [SERIAL_NO] ASC, [ENG_CHG_LEVEL] ASC, [WAIV_DEV_REJ_NO] ASC, [ACTIVITY_SEQ] ASC)
);

