CREATE TABLE [IFS].[LEDGER_ITEM] (
    [COMPANY]               NVARCHAR (20)   NOT NULL,
    [IDENTITY]              NVARCHAR (20)   NOT NULL,
    [PARTY_TYPE_DB]         NVARCHAR (20)   NOT NULL,
    [LEDGER_ITEM_SERIES_ID] NVARCHAR (20)   NOT NULL,
    [LEDGER_ITEM_ID]        NVARCHAR (50)   NOT NULL,
    [LEDGER_ITEM_VERSION]   INT             NOT NULL,
    [OBJVERSION]            NVARCHAR (2000) NULL,
    [BatchID]               BIGINT          NULL,
    [ProcessLogID]          BIGINT          NULL,
    [Issue]                 TINYINT         NULL,
    CONSTRAINT [PK_LEDGER_ITEM] PRIMARY KEY CLUSTERED ([IDENTITY] ASC, [COMPANY] ASC, [PARTY_TYPE_DB] ASC, [LEDGER_ITEM_SERIES_ID] ASC, [LEDGER_ITEM_ID] ASC, [LEDGER_ITEM_VERSION] ASC)
);

