CREATE TABLE [IFS].[LOT_BATCH_MASTER] (
    [PART_NO]      NVARCHAR (25)   NOT NULL,
    [LOT_BATCH_NO] NVARCHAR (20)   NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_LOT_BATCH_MASTER] PRIMARY KEY CLUSTERED ([PART_NO] ASC, [LOT_BATCH_NO] ASC)
);

