CREATE TABLE [IFS].[MANUF_STRUCTURE] (
    [CONTRACT]       NVARCHAR (5)  NOT NULL,
    [PART_NO]        NVARCHAR (25) NOT NULL,
    [ENG_CHG_LEVEL]  NVARCHAR (2)  NOT NULL,
    [BOM_TYPE_DB]    NVARCHAR (20) NOT NULL,
    [ALTERNATIVE_NO] NVARCHAR (20) NOT NULL,
    [LINE_ITEM_NO]   INT           NOT NULL,
    [OBJVERSION]     BIGINT        NULL,
    [BatchID]        BIGINT        NULL,
    [ProcessLogID]   BIGINT        NULL,
    [Issue]          TINYINT       NULL,
    CONSTRAINT [PK_MANUF_STRUCTURE] PRIMARY KEY CLUSTERED ([CONTRACT] ASC, [PART_NO] ASC, [ENG_CHG_LEVEL] ASC, [BOM_TYPE_DB] ASC, [ALTERNATIVE_NO] ASC, [LINE_ITEM_NO] ASC)
);

