CREATE TABLE [IFS].[MANUF_STRUCT_ALTERNATE] (
    [CONTRACT]       NVARCHAR (5)    NOT NULL,
    [PART_NO]        NVARCHAR (25)   NOT NULL,
    [ENG_CHG_LEVEL]  NVARCHAR (2)    NOT NULL,
    [BOM_TYPE_DB]    NVARCHAR (20)   NOT NULL,
    [ALTERNATIVE_NO] NVARCHAR (20)   NOT NULL,
    [OBJVERSION]     NVARCHAR (2000) NULL,
    [BatchID]        BIGINT          NULL,
    [ProcessLogID]   BIGINT          NULL,
    [Issue]          TINYINT         NULL,
    CONSTRAINT [PK_MANUF_STRUCT_ALTERNATE] PRIMARY KEY CLUSTERED ([CONTRACT] ASC, [PART_NO] ASC, [ENG_CHG_LEVEL] ASC, [BOM_TYPE_DB] ASC, [ALTERNATIVE_NO] ASC)
);

