CREATE TABLE [IFS].[MATERIAL_HISTORY] (
    [MATERIAL_HISTORY_ID] INT     NOT NULL,
    [OBJVERSION]          BIGINT  NULL,
    [BatchID]             BIGINT  NULL,
    [ProcessLogID]        BIGINT  NULL,
    [Issue]               TINYINT NULL,
    CONSTRAINT [PK_MATERIAL_HISTORY_1] PRIMARY KEY CLUSTERED ([MATERIAL_HISTORY_ID] ASC)
);

