CREATE TABLE [IFS].[MIXED_PAYMENT] (
    [COMPANY]          NVARCHAR (20)   NOT NULL,
    [MIXED_PAYMENT_ID] INT             NOT NULL,
    [OBJVERSION]       NVARCHAR (2000) NULL,
    [BatchID]          BIGINT          NULL,
    [ProcessLogID]     BIGINT          NULL,
    CONSTRAINT [PK_MIXED_PAYMENT] PRIMARY KEY CLUSTERED ([COMPANY] ASC, [MIXED_PAYMENT_ID] ASC)
);

