CREATE TABLE [IFS].[PRES_OBJECT_SECURITY] (
    [PO_ID]        NVARCHAR (200)  NOT NULL,
    [SEC_OBJECT]   NVARCHAR (200)  NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_PRES_OBJECT_SECURITY] PRIMARY KEY CLUSTERED ([PO_ID] ASC, [SEC_OBJECT] ASC)
);

