CREATE TABLE [IFS].[PURCHASE_ORDER_LINE_PART] (
    [ORDER_NO]     NVARCHAR (12)   NOT NULL,
    [LINE_NO]      NVARCHAR (4)    NOT NULL,
    [RELEASE_NO]   NVARCHAR (4)    NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_PURCHASE_ORDER_LINE_PART] PRIMARY KEY CLUSTERED ([ORDER_NO] ASC, [LINE_NO] ASC, [RELEASE_NO] ASC)
);

