CREATE TABLE [IFS].[PURCHASE_QUANTITY_PRICE] (
    [CONTRACT]     NVARCHAR (5)    NOT NULL,
    [PART_NO]      NVARCHAR (25)   NOT NULL,
    [VENDOR_NO]    NVARCHAR (20)   NOT NULL,
    [LINE_NO]      NVARCHAR (4)    NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_PURCHASE_QUANTITY_PRICE] PRIMARY KEY CLUSTERED ([PART_NO] ASC, [CONTRACT] ASC, [VENDOR_NO] ASC, [LINE_NO] ASC)
);

