CREATE TABLE [IFS].[PURCHASE_RECEIPT] (
    [ORDER_NO]     NVARCHAR (12)   NOT NULL,
    [LINE_NO]      NVARCHAR (4)    NOT NULL,
    [RELEASE_NO]   NVARCHAR (4)    NOT NULL,
    [RECEIPT_NO]   INT             NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_PURCHASE_RECEIPT] PRIMARY KEY CLUSTERED ([ORDER_NO] ASC, [LINE_NO] ASC, [RELEASE_NO] ASC, [RECEIPT_NO] ASC)
);

