CREATE TABLE [IFS].[ROUTING_OPERATION] (
    [CONTRACT]         NVARCHAR (5)    NOT NULL,
    [PART_NO]          NVARCHAR (25)   NOT NULL,
    [ROUTING_REVISION] NVARCHAR (4)    NOT NULL,
    [BOM_TYPE_DB]      NVARCHAR (20)   NOT NULL,
    [ALTERNATIVE_NO]   NVARCHAR (20)   NOT NULL,
    [OPERATION_ID]     INT             NOT NULL,
    [OBJVERSION]       NVARCHAR (2000) NULL,
    [BatchID]          BIGINT          NULL,
    [ProcessLogID]     BIGINT          NULL,
    [Issue]            TINYINT         NULL,
    CONSTRAINT [PK_ROUTING_OPERATION] PRIMARY KEY CLUSTERED ([PART_NO] ASC, [CONTRACT] ASC, [ROUTING_REVISION] ASC, [ALTERNATIVE_NO] ASC, [BOM_TYPE_DB] ASC, [OPERATION_ID] ASC)
);

