CREATE TABLE [IFS].[SALES_PART] (
    [CONTRACT]     NVARCHAR (5)  NOT NULL,
    [CATALOG_NO]   NVARCHAR (25) NOT NULL,
    [PARENT_PART]  NVARCHAR (25) NOT NULL,
    [OBJVERSION]   BIGINT        NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    [Issue]        TINYINT       NULL,
    CONSTRAINT [PK_SALES_PART] PRIMARY KEY CLUSTERED ([CONTRACT] ASC, [CATALOG_NO] ASC, [PARENT_PART] ASC)
);

