CREATE TABLE [IFS].[SALES_PRICE_LIST_PART] (
    [PRICE_LIST_NO]   NVARCHAR (10)   NOT NULL,
    [CATALOG_NO]      NVARCHAR (25)   NOT NULL,
    [MIN_QUANTITY]    INT             NOT NULL,
    [VALID_FROM_DATE] DATETIME2 (7)   NOT NULL,
    [OBJVERSION]      NVARCHAR (2000) NULL,
    [BatchID]         BIGINT          NULL,
    [ProcessLogID]    BIGINT          NULL,
    [Issue]           TINYINT         NULL,
    CONSTRAINT [PK_SALES_PRICE_LIST_PART] PRIMARY KEY CLUSTERED ([PRICE_LIST_NO] ASC, [CATALOG_NO] ASC, [MIN_QUANTITY] ASC, [VALID_FROM_DATE] ASC)
);

