CREATE TABLE [IFS].[SALES_PART_CROSS_REFERENCE] (
    [CUSTOMER_NO]      NVARCHAR (20)   NOT NULL,
    [CONTRACT]         NVARCHAR (5)    NOT NULL,
    [CUSTOMER_PART_NO] NVARCHAR (45)   NOT NULL,
    [OBJVERSION]       NVARCHAR (2000) NULL,
    [BatchID]          BIGINT          NULL,
    [ProcessLogID]     BIGINT          NULL,
    [Issue]            TINYINT         NULL,
    CONSTRAINT [PK_SALES_PART_CROSS_REFERENCE] PRIMARY KEY CLUSTERED ([CUSTOMER_PART_NO] ASC, [CONTRACT] ASC, [CUSTOMER_NO] ASC)
);

