CREATE TABLE [IFS].[SHOP_MATERIAL_ALLOC] (
    [ORDER_NO]     NVARCHAR (12) NOT NULL,
    [RELEASE_NO]   NVARCHAR (4)  NOT NULL,
    [SEQUENCE_NO]  NVARCHAR (4)  NOT NULL,
    [LINE_ITEM_NO] INT           NOT NULL,
    [OBJVERSION]   BIGINT        NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    [Issue]        TINYINT       NULL,
    CONSTRAINT [PK_SHOP_MATERIAL_ALLOC] PRIMARY KEY CLUSTERED ([ORDER_NO] ASC, [RELEASE_NO] ASC, [SEQUENCE_NO] ASC, [LINE_ITEM_NO] ASC)
);

