CREATE TABLE [IFS].[SUPPLIER_INFO] (
    [SUPPLIER_ID]   NVARCHAR (20) NOT NULL,
    [CREATION_DATE] DATETIME2 (7) NULL,
    [BatchID]       BIGINT        NULL,
    [ProcessLogID]  BIGINT        NULL,
    [Issue]         TINYINT       NULL,
    CONSTRAINT [PK_SUPPLIER_INFO] PRIMARY KEY CLUSTERED ([SUPPLIER_ID] ASC)
);

