CREATE TABLE [IFS].[SUPPLIER_INFO_ADDRESS] (
    [SUPPLIER_ID]  NVARCHAR (20)   NOT NULL,
    [ADDRESS_ID]   NVARCHAR (50)   NOT NULL,
    [OBJVERSION]   NVARCHAR (2000) NULL,
    [BatchID]      BIGINT          NULL,
    [ProcessLogID] BIGINT          NULL,
    [Issue]        TINYINT         NULL,
    CONSTRAINT [PK_SUPPLIER_INFO_ADDRESS] PRIMARY KEY CLUSTERED ([SUPPLIER_ID] ASC, [ADDRESS_ID] ASC)
);

