CREATE TABLE [IFS].[SUPPLIER_INFO_ADDRESS_TYPE] (
    [SUPPLIER_ID]          NVARCHAR (20)   NOT NULL,
    [ADDRESS_ID]           NVARCHAR (50)   NOT NULL,
    [ADDRESS_TYPE_CODE]    NVARCHAR (4000) NULL,
    [ADDRESS_TYPE_CODE_DB] NVARCHAR (20)   NOT NULL,
    [OBJVERSION]           NVARCHAR (2000) NULL,
    [BatchID]              BIGINT          NULL,
    [ProcessLogID]         BIGINT          NULL,
    [Issue]                TINYINT         NULL,
    CONSTRAINT [PK_SUPPLIER_INFO_ADDRESS_TYPE] PRIMARY KEY CLUSTERED ([SUPPLIER_ID] ASC, [ADDRESS_ID] ASC, [ADDRESS_TYPE_CODE_DB] ASC)
);

