CREATE TABLE [IFS].[SYSTEM_PRIVILEGE] (
    [PRIVILEGE_ID] NVARCHAR (30) NOT NULL,
    [OBJVERSION]   NVARCHAR (14) NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    [Issue]        TINYINT       NULL,
    CONSTRAINT [PK_SYSTEM_PRIVILEGE] PRIMARY KEY CLUSTERED ([PRIVILEGE_ID] ASC)
);

