CREATE TABLE [IFS].[TECHNICAL_SPECIFICATION_BOTH] (
    [TECHNICAL_SPEC_NO] INT             NOT NULL,
    [ATTRIBUTE]         NVARCHAR (15)   NOT NULL,
    [OBJVERSION]        NVARCHAR (2000) NULL,
    [BatchID]           BIGINT          NULL,
    [ProcessLogID]      BIGINT          NULL,
    [Issue]             TINYINT         NULL,
    CONSTRAINT [PK_TECHNICAL_SPECIFICATION_BOTH] PRIMARY KEY CLUSTERED ([TECHNICAL_SPEC_NO] ASC, [ATTRIBUTE] ASC)
);

