CREATE TABLE [DM].[D_WHS_Location] (
    [D_WHS_Location_Skey]                    BIGINT         IDENTITY (1, 1) NOT NULL,
    [Location_ID]                            NVARCHAR (10)  NOT NULL,
    [Location_Class_Code]                    NVARCHAR (1)   NOT NULL,
    [Location_Class_Description]             NVARCHAR (100) NULL,
    [Location_BarCode]                       NVARCHAR (15)  NOT NULL,
    [Location_Aisle]                         NVARCHAR (4)   NULL,
    [Location_Bay]                           NVARCHAR (4)   NULL,
    [Location_Level]                         NVARCHAR (4)   NULL,
    [Location_Position]                      NVARCHAR (4)   NULL,
    [Location_Display_Location]              NVARCHAR (15)  NULL,
    [Location_Pick_Sequence]                 NVARCHAR (24)  NULL,
    [Location_Work_Group]                    NVARCHAR (4)   NULL,
    [Location_Work_Area]                     NVARCHAR (4)   NULL,
    [Location_Pick_Determination_zone]       NVARCHAR (4)   NULL,
    [Location_Pick_Loc_Assignment_Zone]      NVARCHAR (12)  NULL,
    [Location_Pick_Loc_Assignment_Zone_Desc] NVARCHAR (100) NULL,
    [Location_Pull_Zone]                     NVARCHAR (4)   NULL,
    [Location_Putaway_Zone]                  NVARCHAR (4)   NULL,
    [Location_Group_Attribute_1]             NVARCHAR (24)  NULL,
    [Location_Group_Attribute_51]            NVARCHAR (24)  NULL,
    [Location_Last_Frozen_DTTM]              DATETIME2 (7)  NULL,
    [Location_Last_Count_DTTM]               DATETIME2 (7)  NULL,
    [CheckSum]                               NVARCHAR (32)  NULL,
    [CheckSumSCD1]                           NVARCHAR (32)  NULL,
    [CheckSumSCD2]                           NVARCHAR (32)  NULL,
    [IsActual]                               INT            NOT NULL,
    [IsInferred]                             INT            NULL,
    [IsDeleted]                              INT            NULL,
    [EffectiveDate]                          DATE           NOT NULL,
    [ExpiryDate]                             DATE           NULL,
    [InsertDateTime]                         DATETIME2 (7)  NULL,
    [UpdateDateTime]                         DATETIME2 (7)  NULL,
    [BatchID]                                BIGINT         NOT NULL,
    [ProcessLogID]                           BIGINT         NULL,
    CONSTRAINT [D_WHS_Location_Skey] PRIMARY KEY CLUSTERED ([D_WHS_Location_Skey] ASC) WITH (FILLFACTOR = 80)
);

