CREATE TABLE [TPX7_ARC].[VW_SHIPMENT] (
    [SHIPMENT_ID]                      INT              NOT NULL,
    [STREAM]                           VARCHAR (20)     NOT NULL,
    [SOURCE]                           VARCHAR (20)     NULL,
    [PROJECT_CODE]                     VARCHAR (20)     NOT NULL,
    [PROJECT_NAME]                     VARCHAR (50)     NULL,
    [PROJECT_GROUP_CODE]               VARCHAR (20)     NULL,
    [PROJECT_GROUP_NAME]               VARCHAR (50)     NULL,
    [PU_ADDRESS_ID]                    INT              NOT NULL,
    [DY_ADDRESS_ID]                    INT              NOT NULL,
    [PU_ADDRESS_NAME]                  VARCHAR (50)     NOT NULL,
    [DY_ADDRESS_NAME]                  VARCHAR (50)     NOT NULL,
    [PU_ADDRESS_LINE_1]                VARCHAR (200)    NOT NULL,
    [DY_ADDRESS_LINE_1]                VARCHAR (200)    NOT NULL,
    [PU_ADDRESS_LINE_2]                VARCHAR (200)    NOT NULL,
    [DY_ADDRESS_LINE_2]                VARCHAR (200)    NOT NULL,
    [PU_COUNTRY_CODE]                  VARCHAR (3)      NOT NULL,
    [PU_COUNTRY_NAME]                  VARCHAR (50)     NULL,
    [DY_COUNTRY_CODE]                  VARCHAR (3)      NOT NULL,
    [DY_COUNTRY_NAME]                  VARCHAR (50)     NULL,
    [REPORTING_COUNTRY_CODE]           VARCHAR (3)      NOT NULL,
    [REPORTING_COUNTRY_NAME]           VARCHAR (50)     NULL,
    [IS_RETURN]                        INT              NOT NULL,
    [PU_RESTRICTION]                   VARCHAR (20)     NOT NULL,
    [DY_RESTRICTION]                   VARCHAR (20)     NOT NULL,
    [COLLI_NR]                         INT              NOT NULL,
    [WEIGHT]                           DECIMAL (10, 2)  NOT NULL,
    [VOLUME]                           DECIMAL (14, 8)  NOT NULL,
    [DOCUMENTS_ONLY]                   VARCHAR (1)      NOT NULL,
    [FORWARDER_CODE]                   VARCHAR (3)      NULL,
    [FORWARDER_NAME]                   VARCHAR (50)     NULL,
    [SELLING_RATE_CODE]                VARCHAR (20)     NULL,
    [BUYING_RATE_CODE]                 VARCHAR (20)     NULL,
    [SELLING_CURRENCY_CODE]            VARCHAR (3)      NULL,
    [BUYING_CURRENCY_CODE]             VARCHAR (3)      NULL,
    [SELLING_RATE]                     DECIMAL (24, 8)  NULL,
    [BUYING_RATE]                      DECIMAL (24, 8)  NULL,
    [FORWARDER_REFERENCE]              VARCHAR (50)     NULL,
    [INCOTERM_CODE]                    VARCHAR (20)     NULL,
    [POD_SIGNED_BY]                    VARCHAR (50)     NULL,
    [EXCEPTION_COUNT]                  INT              NOT NULL,
    [CONSIGNEE_REFERENCE]              VARCHAR (256)    NULL,
    [REMARKS]                          TEXT             NULL,
    [INPUT_MODE]                       VARCHAR (20)     NOT NULL,
    [SHIPPER_SHIPMENT_REF]             VARCHAR (256)    NULL,
    [SERVICE_CODE]                     VARCHAR (20)     NULL,
    [AREA]                             DECIMAL (8, 4)   NULL,
    [BASE_CHARGE]                      DECIMAL (24, 8)  NULL,
    [BILL_TO_RECEIVER_ADDRESS_ID]      INT              NULL,
    [BILL_TO_SENDER_ADDRESS_ID]        INT              NULL,
    [BOOKED_BY]                        DECIMAL (9)      NULL,
    [BOOKED_ON]                        DATETIME         NULL,
    [CHARGE_FACTOR]                    VARCHAR (20)     NULL,
    [CHARGEABLE_WEIGHT]                DECIMAL (12, 4)  NULL,
    [COD_CURRENCY_CODE_]               VARCHAR (3)      NULL,
    [COD_VALUE_]                       DECIMAL (24, 8)  NULL,
    [COMPUTED_LOADING_LENGTH]          DECIMAL (18, 4)  NULL,
    [CONNOTE_NR]                       VARCHAR (100)    NULL,
    [COST_CENTRE_ID]                   INT              NULL,
    [CREATED_BY]                       DECIMAL (9)      NULL,
    [CREATED_ON]                       DATETIME         NULL,
    [CUSTOMER_INVOICE_CURRENCY_]       VARCHAR (3)      NULL,
    [CUSTOMER_INVOICE_REFERENCE_]      VARCHAR (256)    NULL,
    [CUSTOMER_INVOICE_VALUE_]          DECIMAL (24, 8)  NULL,
    [CUSTOMER_ORDER_NR_]               VARCHAR (256)    NULL,
    [CUSTOMS_CURRENCY_]                VARCHAR (3)      NULL,
    [CUSTOMS_DOCUMENTS]                VARCHAR (32)     NULL,
    [CUSTOMS_STATUS_]                  VARCHAR (256)    NULL,
    [CUSTOMS_VALUE_]                   DECIMAL (24, 8)  NULL,
    [DANGEROUS_GOODS_]                 VARCHAR (256)    NULL,
    [DEFAULT_CARRIER]                  VARCHAR (20)     NULL,
    [DELETED_BY]                       DECIMAL (9)      NULL,
    [DELETED_ON]                       DATETIME         NULL,
    [DESCRIPTION_2_]                   VARCHAR (256)    NULL,
    [DESCRIPTION_3_]                   VARCHAR (256)    NULL,
    [DESCRIPTION_4_]                   VARCHAR (256)    NULL,
    [DY_CITY]                          VARCHAR (128)    NULL,
    [DY_CONTACT_NAME]                  VARCHAR (256)    NULL,
    [DY_POSTAL_CODE]                   VARCHAR (128)    NULL,
    [DY_REMARKS]                       VARCHAR (200)    NULL,
    [DY_STATE]                         VARCHAR (128)    NULL,
    [DY_TELEPHONE]                     VARCHAR (20)     NULL,
    [DY_TIME_BEGIN]                    VARCHAR (10)     NULL,
    [DY_TIME_END]                      VARCHAR (10)     NULL,
    [EXTRA_STOP_COUNT_]                VARCHAR (32)     NULL,
    [FORM_TYPE]                        VARCHAR (3)      NULL,
    [FORWARDER_CHARGE]                 DECIMAL (24, 8)  NULL,
    [FUEL_SURCHARGE]                   DECIMAL (24, 8)  NULL,
    [GL_ACCOUNT_ID]                    INT              NULL,
    [GOODS_CONDITION]                  VARCHAR (20)     NULL,
    [IB_OB]                            VARCHAR (10)     NULL,
    [INCOTERM_2_CODE]                  VARCHAR (20)     NULL,
    [INCOTERM_CITY]                    VARCHAR (128)    NULL,
    [INTERFACE_ID]                     BIGINT           NULL,
    [INTERFACE_STATUS]                 TINYINT          NULL,
    [INVOICE_PACKING_LIST_]            VARCHAR (256)    NULL,
    [LOADING_LENGTH]                   DECIMAL (8, 2)   NULL,
    [MANUAL_BOOKING]                   BIT              NULL,
    [MULTIPLIER_LOADING_LENGTH_WEIGHT] DECIMAL (9, 2)   NULL,
    [MULTIPLIER_VOLUME_WEIGHT]         DECIMAL (9, 2)   NULL,
    [OPTION_CODE_1_]                   VARCHAR (64)     NULL,
    [OPTION_CODE_2_]                   VARCHAR (64)     NULL,
    [OPTION_CODE_3_]                   VARCHAR (64)     NULL,
    [OPTION_CODE_4_]                   VARCHAR (64)     NULL,
    [OTHER_SURCHARGE]                  DECIMAL (24, 8)  NULL,
    [PICKUP_BY]                        DECIMAL (9)      NULL,
    [PICKUP_ON]                        DATETIME         NULL,
    [POD_BY]                           DECIMAL (9)      NULL,
    [POD_ON]                           DATETIME         NULL,
    [PORT_OF_DISCHARGE_]               VARCHAR (256)    NULL,
    [PORT_OF_DISCHARGE_IS_DY_ADDRESS_] VARCHAR (1)      NULL,
    [PORT_OF_LOADING_]                 VARCHAR (256)    NULL,
    [PORT_OF_LOADING_IS_PU_ADDRESS_]   VARCHAR (1)      NULL,
    [PU_CITY]                          VARCHAR (128)    NULL,
    [PU_CONTACT_NAME]                  VARCHAR (256)    NULL,
    [PU_POSTAL_CODE]                   VARCHAR (128)    NULL,
    [PU_REMARKS]                       VARCHAR (200)    NULL,
    [PU_STATE]                         VARCHAR (128)    NULL,
    [PU_TELEPHONE]                     VARCHAR (20)     NULL,
    [PU_TIME_BEGIN]                    VARCHAR (10)     NULL,
    [PU_TIME_END]                      VARCHAR (10)     NULL,
    [RATED_BY]                         INT              NULL,
    [RATED_ON]                         DATETIME         NULL,
    [SA_DELIVERY]                      BIT              NULL,
    [SA_PICKUP]                        BIT              NULL,
    [SECURE_KEY]                       UNIQUEIDENTIFIER NOT NULL,
    [SERVICE_CHARGE]                   DECIMAL (24, 8)  NULL,
    [SERVICE_LEVEL_CODE]               VARCHAR (20)     NULL,
    [SERVICE_NAME]                     VARCHAR (50)     NULL,
    [SERVICE_REGION_CODE_]             VARCHAR (64)     NULL,
    [SERVICE_SELECTION_METHOD]         VARCHAR (20)     NULL,
    [SHIP_AUTHORIZATION_]              VARCHAR (256)    NULL,
    [SHIPMENT_LEG_ID]                  INT              NULL,
    [SHIPMENT_TYPE_NR]                 VARCHAR (32)     NULL,
    [UOM_DIMENSION]                    VARCHAR (3)      NOT NULL,
    [UOM_VOLUME]                       VARCHAR (3)      NOT NULL,
    [UOM_WEIGHT]                       VARCHAR (3)      NOT NULL,
    [VEHICLE_TYPE_CODE_]               VARCHAR (256)    NULL,
    [VENDOR_NUMBER]                    VARCHAR (20)     NULL,
    [SLA_BASE_CHARGE]                  DECIMAL (24, 8)  NULL,
    [SLA_CURRENCY_CODE]                VARCHAR (3)      NULL,
    [SLA_RATE]                         DECIMAL (24, 8)  NULL,
    [SLA_RATE_CODE]                    VARCHAR (20)     NULL,
    [DY_EMAIL]                         VARCHAR (200)    NULL,
    [CLIENT_CLIENT_ACCOUNT_NR]         VARCHAR (20)     NULL,
    [BUYING_BASE_CHARGE]               DECIMAL (24, 8)  NULL,
    [BUYING_CHARGE_FACTOR]             VARCHAR (20)     NULL,
    [BUYING_SLA_BASE_CHARGE]           DECIMAL (24, 8)  NULL,
    [BUYING_SLA_CURRENCY_CODE]         VARCHAR (3)      NULL,
    [BUYING_SLA_RATE]                  DECIMAL (24, 8)  NULL,
    [BUYING_SLA_RATE_CODE]             VARCHAR (20)     NULL,
    [CONSIGNMENT_NUMBER]               NVARCHAR (50)    NULL,
    [INSURED_VALUE]                    DECIMAL (24, 8)  NULL,
    [INSURED_VALUE_CURRENCY_CODE]      VARCHAR (3)      NULL,
    [MANIFEST_ACTUAL_TS]               DATETIME         NULL,
    [MANIFEST_ID]                      INT              NULL,
    [SHIP_CONFIRM]                     BIT              NOT NULL,
    [REQUESTED_PU_TS]                  DATETIME         NOT NULL,
    [REQUESTED_DY_TS]                  DATETIME         NULL,
    [SLA_PU_TS]                        DATETIME         NULL,
    [SLA_DY_TS]                        DATETIME         NULL,
    [EXPECTED_PU_TS]                   DATETIME         NULL,
    [EXPECTED_DY_TS]                   DATETIME         NULL,
    [ACTUAL_PU_TS]                     DATETIME         NULL,
    [PICKUP_MONTH]                     INT              NULL,
    [PICKUP_YEAR]                      INT              NULL,
    [ACTUAL_DY_TS]                     DATETIME         NULL,
    [DOSSIER_NUMBER]                   NVARCHAR (50)    NULL,
    [LOAD_NUMBER]                      NVARCHAR (50)    NULL,
    [PRE_PLAN_CODE]                    NVARCHAR (50)    NULL,
    [RUN_NUMBER]                       NVARCHAR (50)    NULL,
    [WEBSHOP_ORDER_NUMBER]             NVARCHAR (50)    NULL,
    [STATUS]                           VARCHAR (10)     NOT NULL,
    [PERFORMANCE]                      VARCHAR (20)     NULL,
    [DELIVERED]                        INT              NOT NULL,
    [ONTIME]                           INT              NOT NULL,
    [INTRANSIT]                        INT              NOT NULL,
    [Eff_Date]                         DATE             NOT NULL,
    [End_Date]                         DATE             NULL,
    [ActInd]                           CHAR (1)         NULL,
    [IsDeleted]                        CHAR (1)         NULL,
    [BatchID]                          BIGINT           NULL,
    [ProcessLogID]                     BIGINT           NULL,
    CONSTRAINT [PK_SHIPMENT] PRIMARY KEY CLUSTERED ([Eff_Date] ASC, [SHIPMENT_ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [DWH_TPX7_ARC]
) ON [DWH_TPX7_ARC];



