

CREATE VIEW [RV].[Cross_Reference] 
AS
SELECT CR.CUSTOMER_NO CUSTOMER_NO
      ,CG.DESCRIPTION NAME
	  ,CR.CONTRACT SITE
      ,CR.CATALOG_NO SALES_PART_NO
	  ,SP.CATALOG_DESC SALES_PART_DESCRIPTION
      ,CR.CUSTOMER_UNIT_MEAS Sales_UoM
	  ,CR.CONV_FACTOR CONV_FACTOR
	  ,CR.CUSTOMER_PART_NO CUSTOMER_PART
	  ,CR.CATALOG_DESC CUSTOMER_PART_DESCRIPTION   
      ,CR.SELF_BILLING SELF_BILLING
  FROM [$(DWH)].IFS.SALES_PART_CROSS_REFERENCE CR
  LEFT JOIN [$(DWH)].IFS.CUSTOMER_GROUP CG
  ON
  CR.CUSTOMER_NO=CG.CUST_GRP
  AND CG.ActInd='Y'
  LEFT JOIN [$(DWH)].IFS.SALES_PART SP
  ON
  CR.CATALOG_NO =SP.CATALOG_NO
  AND SP.ActInd='Y'
  WHERE CR.ActInd='Y'