CREATE TABLE [DM].[D_Shipment_Details] (
    [D_Shipment_Details_Skey]                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [Shipper_Ref_ID]                          NVARCHAR (256) NULL,
    [Customer_Ref_ID]                         NVARCHAR (256) NULL,
    [Shipment_ID]                             INT            NOT NULL,
    [Carrier]                                 VARCHAR (50)   NULL,
    [Is Delivered]                            INT            NOT NULL,
    [Is Ontime]                               INT            NULL,
    [Is Intransit]                            INT            NULL,
    [Delivery Status]                         VARCHAR (10)   NULL,
    [Delivery Performance]                    VARCHAR (20)   NULL,
    [Rate Code]                               VARCHAR (20)   NULL,
    [Incoterm]                                VARCHAR (20)   NULL,
    [Delivery Postal Code]                    VARCHAR (128)  NULL,
    [Shipment Create Date]                    DATETIME2 (7)  NULL,
    [Parcel Collection Date]                  DATETIME2 (7)  NULL,
    [Parcel Delivered at Pickup Date]         DATETIME2 (7)  NULL,
    [Parcel Delivered at Customer Date]       DATETIME2 (7)  NULL,
    [Parcel Delivered at FD Date]             DATETIME2 (7)  NULL,
    [Parcel Last Delivery Date]               DATETIME2 (7)  NULL,
    [First Attempt Date]                      DATETIME2 (7)  NULL,
    [Carrier Billing Date]                    DATETIME2 (7)  NULL,
    [OTIF Calculation]                        DATETIME2 (7)  NULL,
    [LT_OTIF]                                 INT            NULL,
    [OLPN LT Create to Delivered]             INT            NULL,
    [OLPN LT Ship Confirmed to Delivered]     INT            NULL,
    [OLPN LT Ship Confirmed to First Attempt] INT            NULL,
    [OLPN LT Ship Confirmed Pickup]           INT            NULL,
    CONSTRAINT [PK_D_Shipment_Details] PRIMARY KEY CLUSTERED ([D_Shipment_Details_Skey] ASC) WITH (FILLFACTOR = 80)
);

