CREATE TABLE [DM].[F_Outbound] (
    [DateKey]                              BIGINT          NOT NULL,
    [D_Order_Type_Skey]                    BIGINT          NOT NULL,
    [D_Facility_Skey]                      BIGINT          NOT NULL,
    [D_Country_Skey]                       BIGINT          NOT NULL,
    [D_Transporter_Skey]                   BIGINT          NOT NULL,
    [D_Shipment_Skey]                      BIGINT          NOT NULL,
    [D_Order_Skey]                         BIGINT          NOT NULL,
    [D_OLPN_Skey]                          BIGINT          NOT NULL,
    [D_SKU_Skey]                           BIGINT          NOT NULL,
    [D_Lot_Skey]                           BIGINT          NOT NULL,
    [D_Customer_Skey]                      BIGINT          NOT NULL,
    [D_Product_Family_Skey]                BIGINT          NOT NULL,
    [D_Container_Skey]                     BIGINT          NOT NULL,
    [Number_Of_Orders_Shipped]             INT             NULL,
    [Number_Of_IFS_Order_Lines_Shipped]    INT             NULL,
    [Number_Of_WMS_Order_Lines_Shipped]    INT             NULL,
    [Number_Of_Parcels_Shipped]            INT             NULL,
    [Number_Of_Units_Shipped]              NUMERIC (16, 4) NULL,
    [Number_Of_Units_Cancelled]            NUMERIC (16, 4) NULL,
    [Number_Of_IFS_Order_Lines_Cancelled]  INT             NULL,
    [Number_Of_Orders_Not_Shipped_on_time] INT             NULL,
    [Number_Of_Picklines]                  INT             NULL,
    [InsertDateTime]                       DATETIME2 (7)   NULL,
    [UpdateDateTime]                       DATETIME2 (7)   NULL,
    [BatchID]                              BIGINT          NOT NULL,
    [ProcessLogID]                         BIGINT          NULL
);

