CREATE TABLE [IFS].[INV_ACCOUNTING_ROW] (
    [COMPANY]                   NVARCHAR (20)   NOT NULL,
    [IDENTITY]                  NVARCHAR (20)   NULL,
    [PARTY_TYPE]                NVARCHAR (4000) NULL,
    [PARTY_TYPE_DB]             NVARCHAR (20)   NULL,
    [INVOICE_ID]                INT             NOT NULL,
    [ITEM_ID]                   INT             NOT NULL,
    [ROW_ID]                    INT             NOT NULL,
    [TAX_ID]                    INT             NULL,
    [CURR_CODE]                 NVARCHAR (3)    NULL,
    [RATE]                      INT             NULL,
    [DIV_FACTOR]                INT             NULL,
    [CURR_AMOUNT]               DECIMAL (18, 2) NULL,
    [DOM_AMOUNT]                DECIMAL (18, 2) NULL,
    [CURR_AMOUNT_CREDIT]        DECIMAL (18, 2) NULL,
    [CURR_AMOUNT_DEBIT]         DECIMAL (18, 2) NULL,
    [DOM_AMOUNT_CREDIT]         DECIMAL (18, 2) NULL,
    [DOM_AMOUNT_DEBIT]          DECIMAL (18, 2) NULL,
    [THIRD_AMOUNT]              DECIMAL (18, 2) NULL,
    [DB_AMOUNT]                 NVARCHAR (2000) NULL,
    [CODE_A]                    NVARCHAR (10)   NULL,
    [CODE_B]                    NVARCHAR (10)   NULL,
    [CODE_C]                    NVARCHAR (10)   NULL,
    [CODE_D]                    NVARCHAR (10)   NULL,
    [CODE_E]                    NVARCHAR (10)   NULL,
    [CODE_F]                    NVARCHAR (10)   NULL,
    [CODE_G]                    NVARCHAR (10)   NULL,
    [CODE_H]                    NVARCHAR (10)   NULL,
    [CODE_I]                    NVARCHAR (10)   NULL,
    [CODE_J]                    NVARCHAR (10)   NULL,
    [PROJECT_ACTIVITY_ID]       INT             NULL,
    [DB_ACCOUNT_STRING]         NVARCHAR (2000) NULL,
    [VOUCHER_TYPE]              NVARCHAR (3)    NULL,
    [VOUCHER_NO]                INT             NULL,
    [ACCOUNTING_YEAR]           INT             NULL,
    [ACCOUNTING_PERIOD]         INT             NULL,
    [YEAR_PERIOD_KEY]           INT             NULL,
    [VOUCHER_DATE]              DATETIME2 (7)   NULL,
    [QUANTITY]                  INT             NULL,
    [TEXT]                      NVARCHAR (2000) NULL,
    [AUTO_POSTING_PROC_CODE]    NVARCHAR (10)   NULL,
    [POSTING_TYPE]              NVARCHAR (10)   NULL,
    [ERROR_FLAG]                NVARCHAR (5)    NULL,
    [OPTIONAL_CODE]             NVARCHAR (20)   NULL,
    [VOUCHER_COMPANY]           NVARCHAR (20)   NULL,
    [ADD_INTERNAL]              NVARCHAR (5)    NULL,
    [INTERNAL_SEQ]              INT             NULL,
    [PERIOD_ALLOC_SEQ]          INT             NULL,
    [LINE_REF]                  INT             NULL,
    [VAT_FINAL_POSTING_ITEM_ID] INT             NULL,
    [ORDER_NO]                  NVARCHAR (12)   NULL,
    [RECEIPT_REF]               NVARCHAR (50)   NULL,
    [POST_PROP_ROW_ID]          INT             NULL,
    [EXT_INV_VOUCHER_TEXT]      NVARCHAR (2000) NULL,
    [CORRECTED_VOUCHER_TYPE]    NVARCHAR (10)   NULL,
    [SUB_CONTRACT_NO]           NVARCHAR (15)   NULL,
    [VALUATION_NO]              INT             NULL,
    [REFERENCE]                 NVARCHAR (800)  NULL,
    [OBJID]                     NVARCHAR (4000) NULL,
    [OBJVERSION]                NVARCHAR (2000) NULL,
    [BatchID]                   BIGINT          NULL,
    [ProcessLogID]              BIGINT          NULL
);



