CREATE TABLE [IFS].[PART_CATALOG_INVENT_ATTRIB] (
    [PART_NO]                      NVARCHAR (25)   NOT NULL,
    [UN_NO]                        NVARCHAR (4)    NULL,
    [FLASH_POINT]                  NVARCHAR (10)   NULL,
    [COLD_SENSITIVE]               NVARCHAR (4000) NULL,
    [COLD_SENSITIVE_DB]            NVARCHAR (25)   NULL,
    [EM_S_NO]                      NVARCHAR (10)   NULL,
    [MARINE_POLLUTANT]             NVARCHAR (4000) NULL,
    [MARINE_POLLUTANT_DB]          NVARCHAR (25)   NULL,
    [ITEM_NO]                      NVARCHAR (6)    NULL,
    [HSE_CONTRACT]                 NVARCHAR (5)    NULL,
    [PROPER_SHIPPING_NAME_ID]      NVARCHAR (10)   NULL,
    [PACKAGING_GROUP_ID]           NVARCHAR (10)   NULL,
    [TUNNEL_CODE]                  NVARCHAR (10)   NULL,
    [PACKAGING_MATERIAL_ID]        NVARCHAR (10)   NULL,
    [ADDITIONAL_SHIP_DESC_ID]      NVARCHAR (10)   NULL,
    [MODIFIED_DATE]                DATETIME2 (7)   NULL,
    [NOTE_ID]                      INT             NULL,
    [IMDG_SPECIAL_PROVISION]       NVARCHAR (100)  NULL,
    [ADR_SPECIAL_PROVISION]        NVARCHAR (100)  NULL,
    [IATA_SPECIAL_PROVISION]       NVARCHAR (100)  NULL,
    [N_O_S]                        NVARCHAR (4000) NULL,
    [N_O_S_DB]                     NVARCHAR (5)    NULL,
    [ADR_ENVIRONMENTAL_HAZARD]     NVARCHAR (4000) NULL,
    [ADR_ENVIRONMENTAL_HAZARD_DB]  NVARCHAR (5)    NULL,
    [IATA_ENVIRONMENTAL_HAZARD]    NVARCHAR (4000) NULL,
    [IATA_ENVIRONMENTAL_HAZARD_DB] NVARCHAR (5)    NULL,
    [IMDG_CLASS_ID]                NVARCHAR (10)   NULL,
    [IMDG_LIMITED_QUANTITY]        NVARCHAR (10)   NULL,
    [ADR_COMMENT_ID]               NVARCHAR (10)   NULL,
    [IMDG_SUBSIDIARY_RISK_1_ID]    NVARCHAR (10)   NULL,
    [IMDG_SUBSIDIARY_RISK_2_ID]    NVARCHAR (10)   NULL,
    [ADR_LIMITED_QUANTITY]         NVARCHAR (10)   NULL,
    [IATA_LIMITED_QUANTITY]        NVARCHAR (10)   NULL,
    [IATA_COMMENT_ID]              NVARCHAR (10)   NULL,
    [ADR_SUBSIDIARY_RISK_1_ID]     NVARCHAR (10)   NULL,
    [ADR_RID_CLASS_ID]             NVARCHAR (10)   NULL,
    [ADR_SUBSIDIARY_RISK_2_ID]     NVARCHAR (10)   NULL,
    [IATA_SUBSIDIARY_RISK_2_ID]    NVARCHAR (10)   NULL,
    [IATA_SUBSIDIARY_RISK_1_ID]    NVARCHAR (10)   NULL,
    [IATA_DGR_CLASS_ID]            NVARCHAR (10)   NULL,
    [SEGREGATION_CODE]             NVARCHAR (10)   NULL,
    [IMDG_COMMENT_ID]              NVARCHAR (10)   NULL,
    [TEMPLATE_PART]                NVARCHAR (4000) NULL,
    [TEMPLATE_PART_DB]             NVARCHAR (5)    NULL,
    [OBJID]                        NVARCHAR (4000) NULL,
    [OBJVERSION]                   NVARCHAR (2000) NULL,
    [BatchID]                      BIGINT          NULL,
    [ProcessLogID]                 BIGINT          NULL
);

