CREATE TABLE [IFS].[SHOP_MATERIAL_ALLOC] (
    [ORDER_NO]                NVARCHAR (12)   NULL,
    [RELEASE_NO]              NVARCHAR (4)    NULL,
    [SEQUENCE_NO]             NVARCHAR (4)    NULL,
    [LINE_ITEM_NO]            INT             NULL,
    [PART_NO]                 NVARCHAR (25)   NULL,
    [CONTRACT]                NVARCHAR (5)    NULL,
    [ISSUE_TO_LOC]            NVARCHAR (35)   NULL,
    [NOTE_ID]                 INT             NULL,
    [OPERATION_NO]            INT             NULL,
    [STRUCTURE_LINE_NO]       INT             NULL,
    [CREATE_DATE]             DATETIME2 (7)   NULL,
    [DATE_REQUIRED]           DATETIME2 (7)   NULL,
    [LAST_ACTIVITY_DATE]      DATETIME2 (7)   NULL,
    [LAST_ISSUE_DATE]         DATETIME2 (7)   NULL,
    [LEADTIME_OFFSET]         INT             NULL,
    [PRIORITY_NO]             INT             NULL,
    [QTY_ASSIGNED]            DECIMAL (18, 4) NULL,
    [QTY_ISSUED]              DECIMAL (18, 4) NULL,
    [QTY_ON_ORDER]            DECIMAL (18, 4) NULL,
    [QTY_PER_ASSEMBLY]        DECIMAL (18, 4) NULL,
    [SHRINKAGE_FACTOR]        DECIMAL (18, 4) NULL,
    [COMPONENT_SCRAP]         DECIMAL (18, 4) NULL,
    [QTY_REQUIRED]            DECIMAL (18, 4) NULL,
    [SUPPLY_CODE]             NVARCHAR (200)  NULL,
    [SUPPLY_CODE_DB]          NVARCHAR (20)   NULL,
    [NOTE_TEXT]               NVARCHAR (2000) NULL,
    [ORDER_CODE]              NVARCHAR (200)  NULL,
    [ORDER_CODE_DB]           NVARCHAR (20)   NULL,
    [GENERATE_DEMAND_QTY]     DECIMAL (18, 4) NULL,
    [QTY_SHORT]               DECIMAL (18, 4) NULL,
    [CONSUMPTION_ITEM]        NVARCHAR (200)  NULL,
    [CONSUMPTION_ITEM_DB]     NVARCHAR (20)   NULL,
    [PRINT_UNIT]              NVARCHAR (30)   NULL,
    [ACTIVITY_SEQ]            INT             NULL,
    [DRAW_POS_NO]             NVARCHAR (10)   NULL,
    [CONFIGURATION_ID]        NVARCHAR (50)   NULL,
    [CONDITION_CODE]          NVARCHAR (10)   NULL,
    [PART_OWNERSHIP]          NVARCHAR (200)  NULL,
    [PART_OWNERSHIP_DB]       NVARCHAR (20)   NULL,
    [OWNING_CUSTOMER_NO]      NVARCHAR (20)   NULL,
    [OWNING_VENDOR_NO]        NVARCHAR (20)   NULL,
    [VIM_STRUCTURE_SOURCE_DB] NVARCHAR (20)   NULL,
    [VIM_STRUCTURE_SOURCE]    NVARCHAR (80)   NULL,
    [PARTIAL_PART_REQUIRED]   NVARCHAR (1)    NULL,
    [PROJECT_ID]              NVARCHAR (10)   NULL,
    [CATCH_QTY_ISSUED]        DECIMAL (18, 4) NULL,
    [REPLICATE_CHANGES]       NVARCHAR (5)    NULL,
    [REPLACED_QTY]            INT             NULL,
    [REPLACES_QPA_FACTOR]     INT             NULL,
    [REPLACES_LINE_ITEM_NO]   INT             NULL,
    [QTY_SCRAPPED_COMPONENT]  INT             NULL,
    [POSITION_PART_NO]        NVARCHAR (25)   NULL,
    [STD_PLANNED_ITEM]        INT             NULL,
    [STATE]                   NVARCHAR (2000) NULL,
    [OBJID]                   NVARCHAR (100)  NULL,
    [OBJVERSION]              BIGINT          NULL,
    [BatchID]                 BIGINT          NULL,
    [ProcessLogID]            BIGINT          NULL
);





