CREATE TABLE [DM].[D_Cash_Flows] (
    [D_Cash_Flows_Skey] BIGINT          IDENTITY (1, 1) NOT NULL,
    [DateKey]           DATE            NULL,
    [Cash_ID]           NVARCHAR (32)   NOT NULL,
    [Company]           NVARCHAR (20)   NOT NULL,
    [Identity_Name]     NVARCHAR (4000) NULL,
    [Party_Type_DB]     NVARCHAR (20)   NULL,
    [Identity_ID]       NVARCHAR (20)   NULL,
    [Categorie]         VARCHAR (22)    NULL,
    [Short_Name]        NVARCHAR (4000) NULL,
    [Grootboek]         NVARCHAR (4000) NULL,
    [Amount]            DECIMAL (20, 2) NULL,
    [Uit_In]            VARCHAR (9)     NULL,
    [Omschrijving]      NVARCHAR (200)  NULL,
    [Pay_Flow]          VARCHAR (6)     NULL,
    [CheckSum]          NVARCHAR (32)   NULL,
    [CheckSumSCD1]      NVARCHAR (32)   NULL,
    [CheckSumSCD2]      NVARCHAR (32)   NULL,
    [IsActual]          INT             NOT NULL,
    [IsInferred]        INT             NULL,
    [IsDeleted]         INT             NULL,
    [EffectiveDate]     DATE            NOT NULL,
    [ExpiryDate]        DATE            NULL,
    [InsertDateTime]    DATETIME2 (7)   NULL,
    [UpdateDateTime]    DATETIME2 (7)   NULL,
    [BatchID]           BIGINT          NOT NULL,
    [ProcessLogID]      BIGINT          NULL,
    CONSTRAINT [PK_D_Cash_Flows] PRIMARY KEY CLUSTERED ([D_Cash_Flows_Skey] ASC) WITH (FILLFACTOR = 80)
);

