CREATE TABLE [DM].[D_Invoice] (
    [D_Invoice_Skey]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [Company]               NVARCHAR (20)   NOT NULL,
    [Supplier_ID]           NVARCHAR (20)   NULL,
    [Invoice_ID]            INT             NOT NULL,
    [Series_ID]             NVARCHAR (20)   NULL,
    [Invoice_Number]        NVARCHAR (50)   NULL,
    [Invoice_Date]          DATETIME2 (7)   NULL,
    [Arrival_Date]          DATETIME2 (7)   NULL,
    [Delivery_Date]         DATETIME2 (7)   NULL,
    [Due_Date]              DATETIME2 (7)   NULL,
    [Pay_Term_Base_Date]    DATETIME2 (7)   NULL,
    [Pay_Term]              INT             NULL,
    [PL_Pay_Date]           DATETIME2 (7)   NULL,
    [Voucher_ID]            INT             NULL,
    [Voucher_Type]          NVARCHAR (7)    NULL,
    [Accounting_Year]       INT             NULL,
    [PO_Ref_Number]         NVARCHAR (50)   NULL,
    [Amount]                DECIMAL (18, 2) NULL,
    [Domenestic_Amount]     DECIMAL (18, 2) NULL,
    [VAT_Amount]            DECIMAL (18, 2) NULL,
    [VAT_Domenestic_Amount] DECIMAL (18, 2) NULL,
    [Invoice_Type]          NVARCHAR (20)   NULL,
    [NCF_Reference]         NVARCHAR (50)   NULL,
    [Invoice_Status]        NVARCHAR (30)   NULL,
    [CheckSum]              NVARCHAR (32)   NULL,
    [CheckSumSCD1]          NVARCHAR (32)   NULL,
    [CheckSumSCD2]          NVARCHAR (32)   NULL,
    [IsActual]              INT             NOT NULL,
    [IsInferred]            INT             NULL,
    [IsDeleted]             INT             NULL,
    [EffectiveDate]         DATE            NOT NULL,
    [ExpiryDate]            DATE            NULL,
    [InsertDateTime]        DATETIME2 (7)   NULL,
    [UpdateDateTime]        DATETIME2 (7)   NULL,
    [BatchID]               BIGINT          NOT NULL,
    [ProcessLogID]          BIGINT          NULL,
    CONSTRAINT [PK_D_Invoice] PRIMARY KEY CLUSTERED ([D_Invoice_Skey] ASC) WITH (FILLFACTOR = 80)
);

