CREATE TABLE [DM].[D_Pack_QC] (
    [D_Pack_QC_Skey]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [OLPN_ID]           NVARCHAR (50)   NOT NULL,
    [Order_ID]          NVARCHAR (50)   NOT NULL,
    [Lane_ID]           SMALLINT        NULL,
    [QC_Action]         VARCHAR (7)     NULL,
    [user]              NVARCHAR (50)   NULL,
    [TimeIn]            DATETIME        NULL,
    [TimeOut]           DATETIME        NULL,
    [DatumQCScan]       DATE            NULL,
    [TijdQCScan]        TIME (7)        NULL,
    [Status]            NVARCHAR (50)   NULL,
    [ExpirationIssue]   TINYINT         NULL,
    [iLPNStatusIssue]   TINYINT         NULL,
    [iLPNLocationIssue] TINYINT         NULL,
    [OverpackIssue]     TINYINT         NULL,
    [UnknownIssue]      TINYINT         NULL,
    [ItemIssue]         TINYINT         NULL,
    [WeightIssue]       BIT             NULL,
    [Special_Instr]     NVARCHAR (500)  NULL,
    [MinWeight]         DECIMAL (18, 4) NULL,
    [MaxWeight]         DECIMAL (18, 4) NULL,
    [Weight]            DECIMAL (18, 4) NULL,
    [CheckSum]          NVARCHAR (32)   NULL,
    [CheckSumSCD1]      NVARCHAR (32)   NULL,
    [CheckSumSCD2]      NVARCHAR (32)   NULL,
    [IsActual]          INT             NOT NULL,
    [IsInferred]        INT             NULL,
    [IsDeleted]         INT             NULL,
    [EffectiveDate]     DATE            NULL,
    [ExpiryDate]        DATE            NULL,
    [InsertDateTime]    DATETIME2 (7)   NULL,
    [UpdateDateTime]    DATETIME2 (7)   NULL,
    [BatchID]           BIGINT          NOT NULL,
    [ProcessLogID]      BIGINT          NULL,
    CONSTRAINT [PK_D_Pack_QC] PRIMARY KEY CLUSTERED ([D_Pack_QC_Skey] ASC) WITH (FILLFACTOR = 80)
);

