CREATE TABLE [DM].[D_Work_Orders] (
    [D_Work_Order_Skey]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [Wo_Number]          NVARCHAR (12)  NOT NULL,
    [Line_No]            NUMERIC (9)    NOT NULL,
    [Work_Ord_Detail_Id] NUMERIC (9)    NOT NULL,
    [Status]             NVARCHAR (10)  NULL,
    [Status_Code]        NUMERIC (2)    NULL,
    [Order_Type]         NVARCHAR (10)  NULL,
    [TI_Number]          NUMERIC (3)    NULL,
    [SKU_Name]           NVARCHAR (100) NOT NULL,
    [SKU_Number]         INT            NOT NULL,
    [SKU_Description]    NVARCHAR (65)  NOT NULL,
    [FU_SKU]             NVARCHAR (1)   NULL,
    [Requested_QTY]      NUMERIC (9, 2) NULL,
    [Completed_QTY]      NUMERIC (9, 2) NULL,
    [To_Be_Picked]       NUMERIC (9, 2) NULL,
    [Picked_QTY]         NUMERIC (9, 2) NULL,
    [In_Work_QTY]        NUMERIC (9, 2) NULL,
    [Scheduled_Date]     DATETIME2 (7)  NULL,
    [Scheduled_Time]     NVARCHAR (12)  NULL,
    [Comment]            NVARCHAR (255) NULL,
    [Mod_Date_Time]      DATETIME2 (7)  NULL,
    [Create_Date_Time]   DATETIME2 (7)  NULL,
    [Wave_Number]        NVARCHAR (12)  NULL,
    [CheckSum]           NVARCHAR (32)  NULL,
    [CheckSumSCD1]       NVARCHAR (32)  NULL,
    [CheckSumSCD2]       NVARCHAR (32)  NULL,
    [IsActual]           INT            NOT NULL,
    [IsInferred]         INT            NULL,
    [IsDeleted]          INT            NULL,
    [EffectiveDate]      DATE           NOT NULL,
    [ExpiryDate]         DATE           NULL,
    [InsertDateTime]     DATETIME2 (7)  NULL,
    [UpdateDateTime]     DATETIME2 (7)  NULL,
    [BatchID]            BIGINT         NOT NULL,
    [ProcessLogID]       BIGINT         NULL,
    CONSTRAINT [PK_D_Work_Orders] PRIMARY KEY CLUSTERED ([D_Work_Order_Skey] ASC) WITH (FILLFACTOR = 80)
);

