CREATE TABLE [DM].[F_Accounting_Row] (
    [Company]                  NVARCHAR (20)   NOT NULL,
    [Party_ID]                 NVARCHAR (20)   NULL,
    [Party_Type]               NVARCHAR (4000) NULL,
    [D_Invoice_Skey]           INT             NOT NULL,
    [Item_ID]                  INT             NOT NULL,
    [Row_ID]                   INT             NOT NULL,
    [Currency_Code]            NVARCHAR (7)    NULL,
    [Amount]                   DECIMAL (18, 2) NULL,
    [Domenestic_Amount]        DECIMAL (18, 2) NULL,
    [Credit_Amount]            DECIMAL (18, 2) NULL,
    [Debit_Amount]             DECIMAL (18, 2) NULL,
    [Domenestic_Credit_Amount] DECIMAL (18, 2) NULL,
    [Domenestic_Debit_Amount]  DECIMAL (18, 2) NULL,
    [D_Account_Skey]           NVARCHAR (10)   NULL,
    [Code_J]                   NVARCHAR (10)   NULL,
    [Voucher_Type]             NVARCHAR (7)    NULL,
    [Voucher_No]               INT             NULL,
    [Accounting_Year]          INT             NULL,
    [Accounting_Period]        INT             NULL,
    [Year_Period]              INT             NULL,
    [Voucher_Date]             DATETIME2 (7)   NULL,
    [Quantity]                 INT             NULL,
    [Posting_Type]             NVARCHAR (10)   NULL,
    [BTW_Code]                 NVARCHAR (20)   NULL,
    [Voucher_Company]          NVARCHAR (20)   NULL,
    [Booking_Reference]        NVARCHAR (800)  NULL,
    [InsertDateTime]           DATETIME2 (7)   NULL,
    [UpdateDateTime]           DATETIME2 (7)   NULL,
    [BatchID]                  BIGINT          NOT NULL,
    [ProcessLogID]             BIGINT          NULL
);

