CREATE TABLE [DM].[F_Obsolete_Report] (
    [DateKey]                            DATE            NOT NULL,
    [Contract]                           NVARCHAR (5)    NULL,
    [RN]                                 BIGINT          NOT NULL,
    [SKU_Name]                           NVARCHAR (25)   NOT NULL,
    [Lot_Code]                           NVARCHAR (20)   NULL,
    [SKU_Description]                    NVARCHAR (65)   NULL,
    [Inventory_Netto_QTY]                FLOAT (53)      NULL,
    [Percentage]                         FLOAT (53)      NULL,
    [Sum_Netto_Qty]                      FLOAT (53)      NULL,
    [Inventory_Cost_Price]               DECIMAL (22, 5) NULL,
    [Inventory_Netto_Value]              DECIMAL (29, 2) NULL,
    [Order_Type]                         VARCHAR (2)     NULL,
    [Criteria]                           INT             NULL,
    [Days_to_Expire]                     INT             NULL,
    [Expiration_Date]                    DATE            NULL,
    [Lock_Date]                          DATE            NULL,
    [Days_Until_Lockdate]                INT             NULL,
    [Locken]                             VARCHAR (6)     NULL,
    [Number_Of_Units_PMND]               FLOAT (53)      NULL,
    [Number_Of_Units_PD]                 FLOAT (53)      NULL,
    [Days_To_Sell_Stock]                 FLOAT (53)      NULL,
    [Days_To_Sell_Stock_SUM]             FLOAT (53)      NULL,
    [Projection_OOS]                     DATE            NULL,
    [Lock_VS_Projection_OOS]             DATE            NULL,
    [Calc_Date]                          DATE            NULL,
    [Last_batch_vs_lock_date_next_batch] INT             NULL,
    [Expected_Obsolete]                  VARCHAR (7)     NULL,
    [Expected_Obsolete_Stock]            FLOAT (53)      NULL,
    [Value_Obsolete_Stock]               FLOAT (53)      NULL,
    [InsertDateTime]                     DATETIME2 (7)   NULL,
    [UpdateDateTime]                     DATETIME2 (7)   NULL,
    [BatchID]                            BIGINT          NOT NULL,
    [ProcessLogID]                       BIGINT          NULL
);



