CREATE TABLE [DM].[F_Shipped_new] (
    [DateKey]                DATE          NULL,
    [Order_Shipment_ID]      NVARCHAR (50) NULL,
    [Order_IFS_ID]           NVARCHAR (50) NULL,
    [Order_ID]               NVARCHAR (50) NOT NULL,
    [TPX_OLPN_ID]            VARCHAR (256) NULL,
    [Rate_Code]              VARCHAR (20)  NULL,
    [Forwarder_Code]         VARCHAR (3)   NULL,
    [Forwarder_Name]         VARCHAR (50)  NULL,
    [Forwarder_Reference]    VARCHAR (50)  NULL,
    [Service_Level_Code]     VARCHAR (20)  NULL,
    [Forwarder_Service_Code] VARCHAR (20)  NULL,
    [Status]                 VARCHAR (10)  NOT NULL,
    [TPX_Ontime]             INT           NOT NULL,
    [TPX_Delivered]          INT           NOT NULL,
    [TPX_iNTRANSIT]          INT           NOT NULL,
    [TPX_Dossier_Number]     NVARCHAR (50) NULL,
    [Expected_Deliver_Date]  DATETIME2 (7) NULL,
    [Actual_Deliver_Date]    DATETIME2 (7) NULL,
    [Requested_Deliver_Date] DATETIME2 (7) NULL,
    [Manh_Order_Create_Date] DATETIME2 (7) NULL,
    [Manh_Planned_Ship_Date] DATE          NULL,
    [Manh_Order_Lines]       INT           NULL,
    [Manh_Num_Of_Parcels]    INT           NULL,
    [IFS_Order_Lines]        INT           NULL,
    [InsertDateTime]         DATETIME2 (7) NULL,
    [UpdateDateTime]         DATETIME2 (7) NULL,
    [BatchID]                BIGINT        NOT NULL,
    [ProcessLogID]           BIGINT        NULL
);

