CREATE TABLE [DM].[F_Shipment] (
    [DateKey]                DATE          NULL,
    [D_Shipment_Skey]        BIGINT        NOT NULL,
    [Order_IFS_ID]           NVARCHAR (50) NOT NULL,
    [D_Order_Skey]           BIGINT        NOT NULL,
    [D_OLPN_Skey]            BIGINT        NOT NULL,
    [Rate_Code]              VARCHAR (20)  NOT NULL,
    [Forwarder_Code]         VARCHAR (3)   NOT NULL,
    [Forwarder_Name]         VARCHAR (50)  NOT NULL,
    [Forwarder_Reference]    VARCHAR (50)  NOT NULL,
    [Service_Level_Code]     VARCHAR (20)  NOT NULL,
    [Forwarder_Service_Code] VARCHAR (20)  NULL,
    [Status]                 VARCHAR (10)  NOT NULL,
    [TPX_Ontime]             INT           NOT NULL,
    [TPX_Delivered]          INT           NOT NULL,
    [TPX_iNTRANSIT]          INT           NOT NULL,
    [TPX_Dossier_Number]     NVARCHAR (50) NOT NULL,
    [Expected_Deliver_Date]  DATETIME2 (7) NULL,
    [First_Attempt_Date]     DATETIME2 (7) NULL,
    [First_Customer_Contact] DATETIME2 (7) NULL,
    [Actual_Deliver_Date]    DATETIME2 (7) NULL,
    [Requested_Deliver_Date] DATETIME2 (7) NULL,
    [Manh_Order_Create_Date] DATETIME2 (7) NULL,
    [Manh_Planned_Ship_Date] DATE          NULL,
    [Manh_Order_Lines]       INT           NOT NULL,
    [Manh_Num_Of_Parcels]    INT           NOT NULL,
    [IFS_Order_Lines]        INT           NOT NULL,
    [InsertDateTime]         DATETIME2 (7) NULL,
    [UpdateDateTime]         DATETIME2 (7) NULL,
    [BatchID]                BIGINT        NOT NULL,
    [ProcessLogID]           BIGINT        NULL
);

