CREATE TABLE [TPX7].[VW_SHIPMENT_PACKAGE] (
    [SHIPMENT_ID]                 INT             NOT NULL,
    [LINE_NR]                     DECIMAL (4)     NOT NULL,
    [PACKAGE_TYPE]                VARCHAR (20)    NOT NULL,
    [DESCRIPTION]                 VARCHAR (100)   NULL,
    [QUANTITY]                    INT             NOT NULL,
    [WEIGHT]                      DECIMAL (10, 2) NOT NULL,
    [VOLUME]                      DECIMAL (14, 8) NOT NULL,
    [LENGTH]                      DECIMAL (10, 2) NOT NULL,
    [WIDTH]                       DECIMAL (10, 2) NOT NULL,
    [HEIGHT]                      DECIMAL (10, 2) NOT NULL,
    [BARCODE]                     VARCHAR (50)    NULL,
    [BRN]                         VARCHAR (10)    NULL,
    [BUSINESS_UNIT_ID]            VARCHAR (20)    NULL,
    [CONSIGNEE_SHIPMENTLINE_REF]  VARCHAR (30)    NULL,
    [CUSTOMS_VALUE]               DECIMAL (24, 8) NULL,
    [CUSTOMS_VALUE_CURRENCY_CODE] VARCHAR (3)     NULL,
    [FORM_LINE_NR]                INT             NULL,
    [FORWARDER_SHIPMENTLINE_REF]  VARCHAR (30)    NULL,
    [GIRTH]                       DECIMAL (10, 2) NULL,
    [LABEL]                       VARCHAR (50)    NULL,
    [MANUFACTURE]                 VARCHAR (20)    NULL,
    [REFERENCE_2]                 VARCHAR (100)   NULL,
    [RETURNABLE]                  VARCHAR (1)     NULL,
    [SHIPPER_SHIPMENTLINE_REF]    VARCHAR (30)    NULL,
    [SHIPPER_SHIPMENTLINE_REF2]   VARCHAR (30)    NULL,
    [STACKABLE_ITEMS]             VARCHAR (1)     NULL,
    [SUPPLIER_REFERENCE]          VARCHAR (100)   NULL,
    [UOM_DIMENSION]               VARCHAR (3)     NOT NULL,
    [UOM_VOLUME]                  VARCHAR (3)     NOT NULL,
    [UOM_WEIGHT]                  VARCHAR (3)     NOT NULL,
    [VOLUME_WEIGHT]               DECIMAL (14, 6) NULL,
    [STATUS]                      VARCHAR (20)    NULL,
    [ACTUAL_PU_TS]                DATETIME        NULL,
    [ACTUAL_DY_TS]                DATETIME        NULL,
    [POD_SIGNED_BY]               VARCHAR (50)    NULL,
    [Eff_Date]                    DATE            NOT NULL,
    [End_Date]                    DATE            NULL,
    [ActInd]                      CHAR (1)        NULL,
    [IsDeleted]                   CHAR (1)        NULL,
    [BatchID]                     BIGINT          NULL,
    [ProcessLogID]                BIGINT          NULL,
    CONSTRAINT [PK_SHIPMENT_PACKAGE] PRIMARY KEY CLUSTERED ([SHIPMENT_ID] ASC, [LINE_NR] ASC, [Eff_Date] ASC) ON [DWH_TPX7]
) ON [DWH_TPX7];





