CREATE TABLE [MANH].[APPOINTMENT_TYPE] (
    [APPOINTMENT_TYPE] NVARCHAR (3)  NOT NULL,
    [DESCRIPTION]      NVARCHAR (50) NOT NULL,
    [BatchID]          BIGINT        NULL,
    [ProcessLogID]     BIGINT        NULL,
    CONSTRAINT [PK_MANH_APPOINTMENT_TYPE] PRIMARY KEY CLUSTERED ([APPOINTMENT_TYPE] ASC)
);

