CREATE TABLE [MANH].[ASN_TYPE] (
    [ASN_TYPE]     SMALLINT      NOT NULL,
    [DESCRIPTION]  NVARCHAR (50) NOT NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    CONSTRAINT [PK_MANH_ASN_TYPE] PRIMARY KEY CLUSTERED ([ASN_TYPE] ASC)
);

