CREATE TABLE [MANH].[ASN_STATUS] (
    [ASN_STATUS]   SMALLINT      NOT NULL,
    [DESCRIPTION]  NVARCHAR (50) NOT NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    CONSTRAINT [PK_MANH_ASN_STATUS] PRIMARY KEY CLUSTERED ([ASN_STATUS] ASC)
);

