CREATE TABLE [MANH].[CL_MESSAGE_STATUS] (
    [STATUS_ID]    BIGINT        NOT NULL,
    [STATUS_NAME]  NVARCHAR (64) NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    CONSTRAINT [PK_MANH_CL_MESSAGE_STATUS] PRIMARY KEY CLUSTERED ([STATUS_ID] ASC)
);

