CREATE TABLE [MANH].[ER_USER_PROFILE] (
    [LOGIN_USER_ID]              NVARCHAR (50)   NULL,
    [MENU_ID]                    INT             NULL,
    [EMPLYE_ID]                  NVARCHAR (10)   NULL,
    [RESTR_TASK_GRP_TO_DFLT]     NVARCHAR (1)    NULL,
    [RESTR_MENU_MODE_TO_DFLT]    NVARCHAR (1)    NULL,
    [DFLT_RF_MENU_MODE]          NVARCHAR (1)    NULL,
    [LANG_ID]                    NVARCHAR (3)    NULL,
    [DATE_MASK]                  NVARCHAR (11)   NULL,
    [LAST_TASK]                  NVARCHAR (10)   NULL,
    [LAST_LOCN]                  NVARCHAR (10)   NULL,
    [LAST_WORK_GRP]              NVARCHAR (4)    NULL,
    [LAST_WORK_AREA]             NVARCHAR (4)    NULL,
    [ALLOW_TASK_INT_CHG]         NVARCHAR (1)    NULL,
    [NBR_OF_TASK_TO_DSP]         INT             NULL,
    [TASK_DSP_MODE]              NVARCHAR (1)    NULL,
    [DB_USER_ID]                 NVARCHAR (30)   NULL,
    [DB_PSWD]                    NVARCHAR (90)   NULL,
    [DB_CONNECT_STRING]          NVARCHAR (30)   NULL,
    [PRTR_REQSTR]                NVARCHAR (20)   NULL,
    [IDLE_TIME_BEF_SHTDWN]       INT             NULL,
    [RF_MENU_ID]                 INT             NULL,
    [USER_ID]                    NVARCHAR (15)   NULL,
    [CREATE_DATE_TIME]           DATETIME2 (7)   NULL,
    [MOD_DATE_TIME]              DATETIME2 (7)   NULL,
    [PAGE_SIZE]                  INT             NULL,
    [VOCOLLECT_WORK_TYPE]        INT             NULL,
    [CURR_TASK_GRP]              NVARCHAR (3)    NULL,
    [CURR_VOCOLLECT_PTS_CASE]    NVARCHAR (20)   NULL,
    [CURR_VOCOLLECT_REASON_CODE] NVARCHAR (2)    NULL,
    [TASK_GRP_JUMP_FLAG]         NVARCHAR (1)    NULL,
    [AUTO_3PL_LOGIN_FLAG]        NVARCHAR (1)    NULL,
    [SECURITY_CONTEXT_ID]        INT             NULL,
    [SEC_USER_NAME]              NVARCHAR (128)  NULL,
    [VOCOLLECT_PUTAWAY_FLAG]     INT             NULL,
    [VOCOLLECT_REPLEN_FLAG]      INT             NULL,
    [VOCOLLECT_PACKING_FLAG]     INT             NULL,
    [CLS_TIMEZONE_ID]            INT             NULL,
    [DAL_CONNECTION_STRING]      NVARCHAR (255)  NULL,
    [USER_PROFILE_ID]            INT             NULL,
    [WM_VERSION_ID]              INT             NULL,
    [USER_SECURITY_CONTEXT_ID]   INT             NULL,
    [DFLT_TASK_INT]              INT             NULL,
    [CREATED_DTTM]               DATETIME2 (7)   NULL,
    [LAST_UPDATED_DTTM]          DATETIME2 (7)   NULL,
    [ACTION]                     NVARCHAR (2)    NULL,
    [ESIGN_USER_ID]              NVARCHAR (15)   NULL,
    [DB_SID]                     INT             NULL,
    [TRANSACTION_ID]             INT             NULL,
    [EREC_CREATE_DATE_TIME]      DATETIME2 (7)   NULL,
    [DB_USERNAME]                NVARCHAR (30)   NULL,
    [CLIENT_MACHINE_NAME]        NVARCHAR (64)   NULL,
    [CLIENT_OS_USER]             NVARCHAR (30)   NULL,
    [CLIENT_MODULE]              NVARCHAR (12)   NULL,
    [CLIENT_SQL]                 NVARCHAR (1000) NULL,
    [ER_USER_PROFILE_ID]         INT             NULL,
    [BatchID]                    BIGINT          NULL,
    [ProcessLogID]               BIGINT          NULL
);

