CREATE TABLE [MANH].[EVENT_PARM] (
    [EVENT_PARM_ID]     INT           NOT NULL,
    [WHSE]              NVARCHAR (3)  NULL,
    [REC_TYPE]          NVARCHAR (3)  NULL,
    [EVENT_TYPE]        NVARCHAR (3)  NULL,
    [CREATE_DATE_TIME]  DATETIME2 (7) NULL,
    [MOD_DATE_TIME]     DATETIME2 (7) NULL,
    [USER_ID]           NVARCHAR (15) NULL,
    [EVENT_PARM_DESC]   NVARCHAR (40) NULL,
    [WM_VERSION_ID]     INT           NOT NULL,
    [CREATED_DTTM]      DATE          NOT NULL,
    [LAST_UPDATED_DTTM] DATE          NULL,
    [BatchID]           BIGINT        NULL,
    [ProcessLogID]      BIGINT        NULL,
    CONSTRAINT [PK_MANH_VENT_PARM] PRIMARY KEY CLUSTERED ([EVENT_PARM_ID] ASC)
);

