CREATE TABLE [MANH].[FACILITY_TYPE] (
    [FACILITY_TYPE] NVARCHAR (3)  NOT NULL,
    [DESCRIPTION]   NVARCHAR (50) NOT NULL,
    [BIT_VALUE]     INT           NOT NULL,
    [BatchID]       BIGINT        NULL,
    [ProcessLogID]  BIGINT        NULL,
    CONSTRAINT [PK_MANH_FACILITY_TYPE] PRIMARY KEY CLUSTERED ([FACILITY_TYPE] ASC)
);

