CREATE TABLE [MANH].[ILM_APPOINTMENT_STATUS] (
    [APPT_STATUS_CODE]  SMALLINT      NOT NULL,
    [DESCRIPTION]       NVARCHAR (50) NOT NULL,
    [BatchID]           BIGINT        NULL,
    [ProcessLogID]      BIGINT        NULL,
    [CREATED_DTTM]      DATETIME2 (7) NULL,
    [LAST_UPDATED_DTTM] DATETIME2 (7) NULL,
    CONSTRAINT [PK_MANH_ILM_APPOINTMENT_STATUS] PRIMARY KEY CLUSTERED ([APPT_STATUS_CODE] ASC)
);



