CREATE TABLE [MANH].[ILM_APPOINTMENT_OBJECTS] (
    [ID]             INT      NOT NULL,
    [APPT_OBJ_TYPE]  SMALLINT NOT NULL,
    [APPT_OBJ_ID]    INT      NOT NULL,
    [COMPANY_ID]     INT      NOT NULL,
    [APPOINTMENT_ID] INT      NOT NULL,
    [STOP_SEQ]       SMALLINT NULL,
    [BatchID]        BIGINT   NULL,
    [ProcessLogID]   BIGINT   NULL,
    CONSTRAINT [PK_MANH_ILM_APPOINTMENT_OBJECTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

