CREATE TABLE [MANH].[ITEM_CBO] (
    [ITEM_ID]                        INT             NOT NULL,
    [COMPANY_ID]                     INT             NOT NULL,
    [ITEM_NAME]                      NVARCHAR (100)  NOT NULL,
    [DESCRIPTION]                    NVARCHAR (65)   NOT NULL,
    [PROTECTION_LEVEL_ID]            INT             NULL,
    [COMMODITY_CLASS_ID]             INT             NULL,
    [COMMODITY_CODE_ID]              BIGINT          NULL,
    [PRODUCT_CLASS_ID]               INT             NULL,
    [UN_NUMBER_ID]                   BIGINT          NULL,
    [BASE_STORAGE_UOM_ID]            INT             NULL,
    [ITEM_SEASON]                    NVARCHAR (16)   NULL,
    [ITEM_SEASON_YEAR]               NVARCHAR (4)    NULL,
    [ITEM_STYLE]                     NVARCHAR (50)   NULL,
    [ITEM_STYLE_SFX]                 NVARCHAR (8)    NULL,
    [ITEM_COLOR]                     NVARCHAR (50)   NULL,
    [ITEM_COLOR_SFX]                 NVARCHAR (8)    NULL,
    [ITEM_SECOND_DIM]                NVARCHAR (50)   NULL,
    [ITEM_QUALITY]                   NCHAR (4)       NULL,
    [ITEM_SIZE_DESC]                 NVARCHAR (50)   NULL,
    [ITEM_BAR_CODE]                  NVARCHAR (50)   NULL,
    [ITEM_DESC_SHORT]                NVARCHAR (50)   NULL,
    [ITEM_UPC_GTIN]                  NVARCHAR (25)   NULL,
    [UNIT_WEIGHT]                    NUMERIC (16, 4) NULL,
    [WEIGHT_UOM_ID]                  INT             NULL,
    [UNIT_VOLUME]                    NUMERIC (16, 4) NULL,
    [VOLUME_UOM_ID]                  INT             NULL,
    [UNIT_HEIGHT]                    NUMERIC (16, 4) NULL,
    [UNIT_WIDTH]                     NUMERIC (16, 4) NULL,
    [UNIT_LENGTH]                    NUMERIC (16, 4) NULL,
    [DIMENSION_UOM_ID]               INT             NULL,
    [VARIABLE_WEIGHT]                SMALLINT        NULL,
    [DATABASE_QTY_UOM_ID]            INT             NULL,
    [DISPLAY_QTY_UOM_ID]             INT             NULL,
    [STATUS_CODE]                    SMALLINT        NULL,
    [ITEM_IMAGE_FILENAME]            NVARCHAR (50)   NULL,
    [AUDIT_CREATED_SOURCE]           NVARCHAR (100)  NULL,
    [AUDIT_CREATED_SOURCE_TYPE]      SMALLINT        NOT NULL,
    [AUDIT_CREATED_DTTM]             DATETIME2 (7)   NOT NULL,
    [AUDIT_LAST_UPDATED_SOURCE]      NVARCHAR (100)  NULL,
    [AUDIT_LAST_UPDATED_SOURCE_TYPE] SMALLINT        NULL,
    [AUDIT_LAST_UPDATED_DTTM]        DATETIME2 (7)   NULL,
    [MARK_FOR_DELETION]              SMALLINT        NOT NULL,
    [CATCH_WEIGHT_ITEM]              NVARCHAR (1)    NULL,
    [COMMODITY_LEVEL_DESC]           NVARCHAR (100)  NULL,
    [CHANNEL_TYPE_ID]                INT             NULL,
    [COLOR_DESC]                     NVARCHAR (50)   NULL,
    [VERSION]                        BIGINT          NULL,
    [ITEM_QUALITY_CODE]              INT             NULL,
    [PROD_TYPE]                      NVARCHAR (3)    NULL,
    [STD_BUNDL_QTY]                  NUMERIC (9, 2)  NULL,
    [STAB_CODE]                      NVARCHAR (4)    NULL,
    [ITEM_ORIENTATION]               NVARCHAR (1)    NOT NULL,
    [PROTN_FACTOR]                   NVARCHAR (3)    NULL,
    [CAVITY_LEN]                     NUMERIC (7, 2)  NULL,
    [CAVITY_WD]                      NUMERIC (7, 2)  NULL,
    [CAVITY_HT]                      NUMERIC (7, 2)  NULL,
    [INCREMENTAL_LEN]                NUMERIC (16, 4) NULL,
    [INCREMENTAL_WD]                 NUMERIC (16, 4) NULL,
    [INCREMENTAL_HT]                 NUMERIC (16, 4) NULL,
    [STACKABLE_ITEM]                 NVARCHAR (1)    NULL,
    [MAX_NEST_NUMBER]                SMALLINT        NULL,
    [STCC_CODE_ID]                   INT             NULL,
    [SITC_CODE_ID]                   INT             NULL,
    [SCHEDULE_B_CODE_ID]             INT             NULL,
    [SOLD_ONLINE]                    SMALLINT        NOT NULL,
    [SOLD_IN_STORES]                 SMALLINT        NOT NULL,
    [PICKUP_AT_STORE]                SMALLINT        NOT NULL,
    [SHIP_TO_STORE]                  SMALLINT        NOT NULL,
    [URL]                            NVARCHAR (255)  NULL,
    [IS_RETURNABLE]                  SMALLINT        NOT NULL,
    [BatchID]                        BIGINT          NULL,
    [ProcessLogID]                   BIGINT          NULL,
    [BRAND]                          NVARCHAR (15)   NULL,
    [COLOR_SEQ]                      INT             NULL,
    [COMMERCE_ATTRIBUTE1]            NVARCHAR (50)   NULL,
    [COMMERCE_ATTRIBUTE2]            NVARCHAR (50)   NULL,
    [COMMERCE_DATE_ATTRIBUTE1]       DATETIME2 (7)   NULL,
    [COMMERCE_NUM_ATTRIBUTE1]        NUMERIC (13, 4) NULL,
    [COMMERCE_NUM_ATTRIBUTE2]        NUMERIC (13, 4) NULL,
    [CREATED_DTTM]                   DATETIME2 (7)   NULL,
    [CUBISCAN_LAST_UPDATED_DTTM]     DATETIME2 (7)   NULL,
    [IS_EXCHANGEABLE]                INT             NULL,
    [ITEM_DISPOSITION]               NVARCHAR (15)   NULL,
    [LAST_UPDATED_DTTM]              DATETIME2 (7)   NULL,
    [LONG_DESCRIPTION]               NVARCHAR (500)  NULL,
    [MIN_SHIP_INNER_UOM_ID]          NVARCHAR (3)    NULL,
    [PRICE_STATUS]                   NVARCHAR (15)   NULL,
    [REF_FIELD1]                     NVARCHAR (25)   NULL,
    [REF_FIELD10]                    NVARCHAR (25)   NULL,
    [REF_FIELD2]                     NVARCHAR (25)   NULL,
    [REF_FIELD3]                     NVARCHAR (25)   NULL,
    [REF_FIELD4]                     NVARCHAR (25)   NULL,
    [REF_FIELD5]                     NVARCHAR (25)   NULL,
    [REF_FIELD6]                     NVARCHAR (25)   NULL,
    [REF_FIELD7]                     NVARCHAR (25)   NULL,
    [REF_FIELD8]                     NVARCHAR (25)   NULL,
    [REF_FIELD9]                     NVARCHAR (25)   NULL,
    [REF_NUM1]                       NUMERIC (13, 5) NULL,
    [REF_NUM2]                       NUMERIC (13, 5) NULL,
    [REF_NUM3]                       NUMERIC (13, 5) NULL,
    [REF_NUM4]                       NUMERIC (13, 5) NULL,
    [REF_NUM5]                       NUMERIC (13, 5) NULL,
    [SELL_THROUGH]                   NUMERIC (13, 4) NULL,
    [SIZE_SEQ]                       INT             NULL,
    CONSTRAINT [PK_MANH_ITEM_CBO] PRIMARY KEY CLUSTERED ([ITEM_ID] ASC)
);



