CREATE TABLE [MANH].[LANGUAGE] (
    [LANGUAGE_ID]       SMALLINT      NOT NULL,
    [DESCRIPTION]       NVARCHAR (50) NOT NULL,
    [LANGUAGE_SUFFIX]   NVARCHAR (8)  NOT NULL,
    [BatchID]           BIGINT        NULL,
    [ProcessLogID]      BIGINT        NULL,
    [CREATED_DTTM]      DATETIME2 (7) NULL,
    [LAST_UPDATED_DTTM] DATETIME2 (7) NULL,
    CONSTRAINT [PK_MANH_LANGUAGE] PRIMARY KEY CLUSTERED ([LANGUAGE_ID] ASC)
);



