CREATE TABLE [MANH].[LPN_FACILITY_STATUS] (
    [LPN_FACILITY_STATUS]        SMALLINT      NOT NULL,
    [INBOUND_OUTBOUND_INDICATOR] NVARCHAR (1)  NOT NULL,
    [DESCRIPTION]                NVARCHAR (50) NOT NULL,
    [BatchID]                    BIGINT        NULL,
    [ProcessLogID]               BIGINT        NULL,
    CONSTRAINT [PK_MANH_LPN_FACILITY_STATUS] PRIMARY KEY CLUSTERED ([INBOUND_OUTBOUND_INDICATOR] ASC, [LPN_FACILITY_STATUS] ASC)
);

