CREATE TABLE [MANH].[LRF_PRINT_STATUS] (
    [STAT_CODE]    INT           NOT NULL,
    [DESCRIPTION]  NVARCHAR (50) NOT NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    CONSTRAINT [PK_MANH_LRF_PRINT_STATUS] PRIMARY KEY CLUSTERED ([STAT_CODE] ASC)
);

