CREATE TABLE [MANH].[MOVE_TYPE] (
    [MOVE_TYPE]         INT            NOT NULL,
    [DESCRIPTION]       NVARCHAR (50)  NOT NULL,
    [MOVE_TYPE_CODE]    NVARCHAR (3)   NOT NULL,
    [COMMENTS]          NVARCHAR (255) NULL,
    [CREATED_DTTM]      DATETIME2 (7)  NOT NULL,
    [LAST_UPDATED_DTTM] DATETIME2 (7)  NOT NULL,
    [BatchID]           BIGINT         NULL,
    [ProcessLogID]      BIGINT         NULL,
    CONSTRAINT [PK_MANH_MOVE_TYPE] PRIMARY KEY CLUSTERED ([MOVE_TYPE] ASC)
);

