CREATE TABLE [MANH].[MOVEMENT_TYPE] (
    [MOVEMENT_TYPE] NVARCHAR (2)  NOT NULL,
    [DESCRIPTION]   NVARCHAR (50) NULL,
    [BatchID]       BIGINT        NULL,
    [ProcessLogID]  BIGINT        NULL,
    CONSTRAINT [PK_MANH_MOVEMENT_TYPE] PRIMARY KEY CLUSTERED ([MOVEMENT_TYPE] ASC)
);

