CREATE TABLE [MANH].[MSG_TYPE] (
    [MSG_TYPE]     NVARCHAR (30) NOT NULL,
    [DESCRIPTION]  NVARCHAR (50) NULL,
    [BatchID]      BIGINT        NULL,
    [ProcessLogID] BIGINT        NULL,
    CONSTRAINT [PK_MANH_MSG_TYPE] PRIMARY KEY CLUSTERED ([MSG_TYPE] ASC)
);

