CREATE TABLE [MANH].[ORDER_WMS_STATUS] (
    [STATUS_CODE]  INT            NOT NULL,
    [DESCRIPTION]  NVARCHAR (100) NOT NULL,
    [BatchID]      BIGINT         NULL,
    [ProcessLogID] BIGINT         NULL,
    CONSTRAINT [PK_MANH_ORDER_WMS_STATUS] PRIMARY KEY CLUSTERED ([STATUS_CODE] ASC)
);

