CREATE TABLE [MANH].[OUTPT_LPN_DETAIL] (
    [ASSORT_NBR]                NVARCHAR (12)   NULL,
    [BUSINESS_PARTNER]          NVARCHAR (40)   NULL,
    [CONSUMPTION_PRIORITY_DTTM] DATETIME2 (7)   NULL,
    [CREATED_DTTM]              DATETIME2 (7)   NOT NULL,
    [CREATED_SOURCE]            NVARCHAR (25)   NULL,
    [CREATED_SOURCE_TYPE]       INT             NOT NULL,
    [GTIN]                      NVARCHAR (25)   NULL,
    [INVC_BATCH_NBR]            INT             NOT NULL,
    [INVENTORY_TYPE]            NVARCHAR (1)    NULL,
    [ITEM_ATTR_1]               NVARCHAR (10)   NULL,
    [ITEM_ATTR_2]               NVARCHAR (10)   NULL,
    [ITEM_ATTR_3]               NVARCHAR (10)   NULL,
    [ITEM_ATTR_4]               NVARCHAR (10)   NULL,
    [ITEM_ATTR_5]               NVARCHAR (10)   NULL,
    [ITEM_ID]                   INT             NULL,
    [LAST_UPDATED_DTTM]         DATETIME2 (7)   NOT NULL,
    [LAST_UPDATED_SOURCE]       NVARCHAR (25)   NULL,
    [LAST_UPDATED_SOURCE_TYPE]  INT             NOT NULL,
    [LPN_DETAIL_ID]             INT             NOT NULL,
    [MANUFACTURED_DTTM]         DATETIME2 (7)   NULL,
    [BATCH_NBR]                 NVARCHAR (15)   NULL,
    [MANUFACTURED_PLANT]        NVARCHAR (3)    NULL,
    [CNTRY_OF_ORGN]             NVARCHAR (4)    NULL,
    [OUTPT_LPN_DETAIL_ID]       INT             NOT NULL,
    [PRODUCT_STATUS]            NVARCHAR (3)    NULL,
    [PROC_DTTM]                 DATETIME2 (7)   NOT NULL,
    [PROC_STAT_CODE]            INT             NOT NULL,
    [QTY_UOM]                   NVARCHAR (50)   NULL,
    [REC_PROC_INDIC]            NVARCHAR (1)    NULL,
    [SIZE_VALUE]                DECIMAL (16, 4) NULL,
    [TC_COMPANY_ID]             INT             NOT NULL,
    [TC_LPN_ID]                 NVARCHAR (50)   NOT NULL,
    [VERSION_NBR]               INT             NOT NULL,
    [DISTRIBUTION_ORDER_DTL_ID] INT             NULL,
    [ITEM_COLOR]                NVARCHAR (50)   NULL,
    [ITEM_COLOR_SFX]            NVARCHAR (8)    NULL,
    [ITEM_SEASON]               NVARCHAR (16)   NULL,
    [ITEM_SEASON_YEAR]          NVARCHAR (4)    NULL,
    [ITEM_SECOND_DIM]           NVARCHAR (50)   NULL,
    [ITEM_SIZE_DESC]            NVARCHAR (50)   NULL,
    [ITEM_QUALITY]              NVARCHAR (1)    NULL,
    [ITEM_STYLE]                NVARCHAR (50)   NULL,
    [ITEM_STYLE_SFX]            NVARCHAR (8)    NULL,
    [SIZE_RANGE_CODE]           NVARCHAR (50)   NULL,
    [SIZE_REL_POSN_IN_TABLE]    NVARCHAR (2)    NULL,
    [VENDOR_ITEM_NBR]           NVARCHAR (20)   NULL,
    [MINOR_ORDER_NBR]           NVARCHAR (50)   NULL,
    [MINOR_PO_NBR]              NVARCHAR (30)   NULL,
    [ITEM_NAME]                 NVARCHAR (100)  NULL,
    [TC_ORDER_LINE_ID]          NVARCHAR (30)   NULL,
    [DISTRO_NUMBER]             NVARCHAR (50)   NULL,
    [BatchID]                   BIGINT          NULL,
    [ProcessLogID]              BIGINT          NULL,
    CONSTRAINT [PK_MANH_OUTPT_LPN_DETAIL] PRIMARY KEY CLUSTERED ([OUTPT_LPN_DETAIL_ID] ASC)
);

