CREATE TABLE [MANH].[OUTPT_ORDERS] (
    [ACCT_RCVBL_ACCT_NBR]           NVARCHAR (10)   NULL,
    [ACCT_RCVBL_CODE]               NVARCHAR (2)    NULL,
    [ADDR_CODE]                     NVARCHAR (8)    NULL,
    [BACKORDERED_QUANTITY]          DECIMAL (13, 2) NULL,
    [BATCH_CTRL_NBR]                NVARCHAR (10)   NOT NULL,
    [BILLING_METHOD]                INT             NULL,
    [BILL_ACCT_NBR]                 NVARCHAR (23)   NULL,
    [BILL_FACILITY_ALIAS_ID]        NVARCHAR (16)   NULL,
    [BILL_FACILITY_ID]              INT             NULL,
    [BILL_OF_LADING_NUMBER]         NVARCHAR (30)   NULL,
    [BILL_TO_ADDRESS_1]             NVARCHAR (75)   NULL,
    [BILL_TO_ADDRESS_2]             NVARCHAR (75)   NULL,
    [BILL_TO_ADDRESS_3]             NVARCHAR (75)   NULL,
    [BILL_TO_CITY]                  NVARCHAR (50)   NULL,
    [BILL_TO_CONTACT]               NVARCHAR (50)   NULL,
    [BILL_TO_CONTACT_NAME]          NVARCHAR (50)   NULL,
    [BILL_TO_COUNTRY_CODE]          NVARCHAR (2)    NULL,
    [BILL_TO_COUNTY]                NVARCHAR (40)   NULL,
    [BILL_TO_EMAIL]                 NVARCHAR (256)  NULL,
    [BILL_TO_FACILITY_NAME]         NVARCHAR (50)   NULL,
    [BILL_TO_FAX_NUMBER]            NVARCHAR (30)   NULL,
    [BILL_TO_NAME]                  NVARCHAR (91)   NULL,
    [BILL_TO_PHONE_NUMBER]          NVARCHAR (32)   NULL,
    [BILL_TO_POSTAL_CODE]           NVARCHAR (10)   NULL,
    [BILL_TO_STATE_PROV]            NVARCHAR (3)    NULL,
    [BILL_TO_TITLE]                 NVARCHAR (50)   NULL,
    [BOL_BREAK_ATTR]                NVARCHAR (3)    NULL,
    [BOL_TYPE]                      NVARCHAR (4)    NULL,
    [BUSINESS_PARTNER]              NVARCHAR (40)   NULL,
    [CREATED_DTTM]                  DATETIME2 (7)   NOT NULL,
    [CREATED_SOURCE]                NVARCHAR (25)   NULL,
    [CREATED_SOURCE_TYPE]           INT             NOT NULL,
    [CURRENCY]                      NVARCHAR (40)   NULL,
    [D_ADDRESS_1]                   NVARCHAR (75)   NULL,
    [D_ADDRESS_2]                   NVARCHAR (75)   NULL,
    [D_ADDRESS_3]                   NVARCHAR (75)   NULL,
    [D_CITY]                        NVARCHAR (40)   NULL,
    [D_CONTACT]                     NVARCHAR (50)   NULL,
    [D_COUNTRY_CODE]                NVARCHAR (2)    NULL,
    [D_COUNTY]                      NVARCHAR (40)   NULL,
    [D_DOCK_DOOR_ID]                INT             NULL,
    [D_DOCK_ID]                     NVARCHAR (8)    NULL,
    [D_EMAIL]                       NVARCHAR (256)  NULL,
    [D_FACILITY_ALIAS_ID]           NVARCHAR (16)   NULL,
    [D_FACILITY_ID]                 INT             NULL,
    [D_FACILITY_NAME]               NVARCHAR (50)   NULL,
    [D_FAX_NUMBER]                  NVARCHAR (30)   NULL,
    [D_NAME]                        NVARCHAR (91)   NULL,
    [D_PHONE_NUMBER]                NVARCHAR (32)   NULL,
    [D_POSTAL_CODE]                 NVARCHAR (10)   NULL,
    [D_STATE_PROV]                  NVARCHAR (3)    NULL,
    [DC_CTR_NBR]                    NVARCHAR (32)   NULL,
    [DELIVERY_START_DTTM]           DATETIME2 (7)   NULL,
    [DISTRIBUTION_SHIP_VIA]         NVARCHAR (30)   NULL,
    [DO_TYPE]                       INT             NULL,
    [DSG_SHIP_VIA]                  INT             NULL,
    [ORIGINAL_SHIP_VIA]             NVARCHAR (30)   NULL,
    [EXT_PURCHASE_ORDER]            NVARCHAR (50)   NULL,
    [FREIGHT_CLASS]                 DECIMAL (5, 1)  NULL,
    [FREIGHT_FORWARDER_ACCT_NBR]    NVARCHAR (40)   NULL,
    [GLOBAL_LOCN_NBR]               NVARCHAR (52)   NULL,
    [HANDLING_CHARGES]              DECIMAL (13, 4) NULL,
    [INCOTERM_FACILITY_ALIAS_ID]    NVARCHAR (16)   NULL,
    [INCOTERM_FACILITY_ID]          INT             NULL,
    [INCOTERM_ID]                   INT             NULL,
    [INCOTERM_LOC_AVA_DTTM]         DATETIME2 (7)   NULL,
    [INCOTERM_LOC_AVA_TIME_ZONE_ID] INT             NULL,
    [INCOTERM_NAME]                 NVARCHAR (50)   NULL,
    [INSUR_CHRG]                    DECIMAL (11, 2) NULL,
    [INVC_BATCH_NBR]                INT             NOT NULL,
    [IS_BACK_ORDERED]               NVARCHAR (4)    NOT NULL,
    [LAST_UPDATED_DTTM]             DATETIME2 (7)   NOT NULL,
    [LAST_UPDATED_SOURCE]           NVARCHAR (25)   NULL,
    [LAST_UPDATED_SOURCE_TYPE]      INT             NOT NULL,
    [MAJOR_MINOR_ORDER]             NVARCHAR (4)    NULL,
    [MAJOR_ORDER_CTRL_NBR]          NVARCHAR (40)   NULL,
    [MAJOR_ORDER_GRP_ATTR]          NVARCHAR (50)   NULL,
    [MANIFEST_ID]                   NVARCHAR (30)   NULL,
    [MERCHANDIZING_DEPARTMENT]      NVARCHAR (50)   NULL,
    [MISC_CHARGES]                  DECIMAL (13, 4) NULL,
    [MONETARY_VALUE]                DECIMAL (13, 4) NULL,
    [MOVEMENT_OPTION]               INT             NULL,
    [MV_CURRENCY]                   NVARCHAR (40)   NULL,
    [NON_MACHINEABLE]               INT             NULL,
    [O_ADDRESS_1]                   NVARCHAR (75)   NULL,
    [O_ADDRESS_2]                   NVARCHAR (75)   NULL,
    [O_ADDRESS_3]                   NVARCHAR (75)   NULL,
    [O_CITY]                        NVARCHAR (40)   NULL,
    [O_CONTACT]                     NVARCHAR (50)   NULL,
    [O_COUNTRY_CODE]                NVARCHAR (2)    NULL,
    [O_COUNTY]                      NVARCHAR (40)   NULL,
    [O_DOCK_DOOR_ID]                INT             NULL,
    [O_DOCK_ID]                     NVARCHAR (8)    NULL,
    [O_EMAIL]                       NVARCHAR (50)   NULL,
    [O_FACILITY_ALIAS_ID]           NVARCHAR (16)   NULL,
    [O_FACILITY_ID]                 INT             NULL,
    [O_FACILITY_NAME]               NVARCHAR (50)   NULL,
    [O_FAX_NUMBER]                  NVARCHAR (30)   NULL,
    [O_POSTAL_CODE]                 NVARCHAR (10)   NULL,
    [O_STATE_PROV]                  NVARCHAR (3)    NULL,
    [ORDER_DATE_DTTM]               DATETIME2 (7)   NULL,
    [ORDER_WEIGHT]                  DECIMAL (13, 4) NULL,
    [OUTPT_ORDERS_ID]               INT             NOT NULL,
    [ORG_SHIP_FACILITY_ALIAS_ID]    NVARCHAR (16)   NULL,
    [ORG_SHIP_FACILITY_ID]          INT             NULL,
    [ORIGINAL_ASSIGNED_SHIP_VIA]    NVARCHAR (30)   NULL,
    [ORIGIN_SHIP_THRU_FACILITY_ID]  INT             NULL,
    [ORIGIN_SHIP_THRU_FAC_ALIAS_ID] NVARCHAR (16)   NULL,
    [PICKUP_END_DTTM]               DATETIME2 (7)   NULL,
    [PICKUP_START_DTTM]             DATETIME2 (7)   NULL,
    [PLANNED_SHIP_DATE]             DATETIME2 (7)   NULL,
    [PRE_PACK_FLAG]                 INT             NOT NULL,
    [PRIORITY]                      INT             NULL,
    [PRO_NUMBER]                    NVARCHAR (50)   NULL,
    [PROC_DTTM]                     DATETIME2 (7)   NOT NULL,
    [PROC_STAT_CODE]                INT             NOT NULL,
    [REC_XPANS_FIELD]               NVARCHAR (20)   NULL,
    [RTE_ID]                        NVARCHAR (16)   NULL,
    [RTE_SHIPMENT_SEQ]              NUMERIC (9)     NULL,
    [SCHED_DELIVERY_DTTM]           DATETIME2 (7)   NULL,
    [SHIPMENT_ID]                   INT             NULL,
    [SHIP_DATE]                     DATETIME2 (7)   NULL,
    [SHIP_GROUP_ID]                 NVARCHAR (15)   NULL,
    [SHIP_GROUP_SEQUENCE]           INT             NOT NULL,
    [SHPNG_CHRG]                    DECIMAL (11, 2) NOT NULL,
    [ORDER_STATUS]                  INT             NOT NULL,
    [DO_STATUS]                     INT             NOT NULL,
    [STORE_NBR]                     NVARCHAR (16)   NULL,
    [STORE_TYPE]                    NVARCHAR (2)    NULL,
    [TAX_CHARGES]                   DECIMAL (13, 4) NULL,
    [TC_COMPANY_ID]                 INT             NOT NULL,
    [TC_ORDER_ID]                   NVARCHAR (50)   NOT NULL,
    [TC_SHIPMENT_ID]                NVARCHAR (50)   NULL,
    [TOTAL_NBR_OF_LPN]              INT             NOT NULL,
    [TOTAL_NBR_OF_PLT]              INT             NOT NULL,
    [TOTAL_NBR_OF_UNITS]            INT             NOT NULL,
    [VERSION_NBR]                   INT             NOT NULL,
    [LINE_HAUL_SHIP_VIA]            NVARCHAR (16)   NULL,
    [PLAN_D_FACILITY_ALIAS_ID]      NVARCHAR (16)   NULL,
    [PLAN_D_FACILITY_ID]            INT             NULL,
    [PLAN_LEG_D_ALIAS_ID]           NVARCHAR (16)   NULL,
    [PLAN_LEG_D_ID]                 INT             NULL,
    [PLAN_LEG_O_ALIAS_ID]           NVARCHAR (16)   NULL,
    [PLAN_LEG_O_ID]                 INT             NULL,
    [PLAN_O_FACILITY_ALIAS_ID]      NVARCHAR (16)   NULL,
    [PLAN_O_FACILITY_ID]            INT             NULL,
    [SPL_INSTR_CODE_1]              NVARCHAR (15)   NULL,
    [SPL_INSTR_CODE_10]             NVARCHAR (15)   NULL,
    [SPL_INSTR_CODE_2]              NVARCHAR (15)   NULL,
    [SPL_INSTR_CODE_3]              NVARCHAR (15)   NULL,
    [SPL_INSTR_CODE_4]              NVARCHAR (15)   NULL,
    [SPL_INSTR_CODE_5]              NVARCHAR (15)   NULL,
    [SPL_INSTR_CODE_6]              NVARCHAR (15)   NULL,
    [SPL_INSTR_CODE_7]              NVARCHAR (15)   NULL,
    [SPL_INSTR_CODE_8]              NVARCHAR (15)   NULL,
    [SPL_INSTR_CODE_9]              NVARCHAR (15)   NULL,
    [PRE_BILL_STATUS]               INT             NOT NULL,
    [PRTL_SHIP_CONF_FLAG]           INT             NULL,
    [PRTL_SHIP_CONF_STATUS]         INT             NULL,
    [PRE_BILLED_FLAG]               INT             NULL,
    [TAX_ID]                        NVARCHAR (15)   NULL,
    [ALLOW_PRE_BILLING]             INT             NULL,
    [O_PHONE_NUMBER]                NVARCHAR (32)   NULL,
    [PURCHASE_ORDER_NBR]            NVARCHAR (50)   NULL,
    [MARK_FOR]                      NVARCHAR (100)  NULL,
    [ORDER_TYPE]                    NVARCHAR (20)   NULL,
    [DISTRO_NUMBER]                 NVARCHAR (50)   NULL,
    [REF_SHIPMENT_NBR]              NVARCHAR (50)   NULL,
    [REF_STOP_SEQ]                  INT             NULL,
    [PO_TYPE_ATTR]                  NVARCHAR (20)   NULL,
    [BatchID]                       BIGINT          NULL,
    [ProcessLogID]                  BIGINT          NULL,
    CONSTRAINT [PK_MANH_OUTPT_ORDERS] PRIMARY KEY CLUSTERED ([OUTPT_ORDERS_ID] ASC)
);

