CREATE TABLE [MANH].[PARAM_GROUP] (
    [PARAM_GROUP_ID]    NVARCHAR (10) NOT NULL,
    [PARAM_GROUP_NAME]  NVARCHAR (50) NULL,
    [CREATED_DTTM]      DATETIME2 (7) NOT NULL,
    [LAST_UPDATED_DTTM] DATETIME2 (7) NOT NULL,
    [BatchID]           BIGINT        NULL,
    [ProcessLogID]      BIGINT        NULL,
    CONSTRAINT [PK_MANH_PARAM_GROUP] PRIMARY KEY CLUSTERED ([PARAM_GROUP_ID] ASC)
);

