CREATE TABLE [MANH].[PURCHASE_ORDERS_STATUS] (
    [PURCHASE_ORDERS_STATUS] INT           NOT NULL,
    [DESCRIPTION]            NVARCHAR (60) NOT NULL,
    [NOTE]                   NVARCHAR (40) NULL,
    [BatchID]                BIGINT        NULL,
    [ProcessLogID]           BIGINT        NULL,
    CONSTRAINT [PK_MANH_PURCHASE_ORDERS_STATUS] PRIMARY KEY CLUSTERED ([PURCHASE_ORDERS_STATUS] ASC)
);

