CREATE TABLE [MANH].[SERVICE_LEVEL] (
    [TC_COMPANY_ID]              INT             NOT NULL,
    [SERVICE_LEVEL]              NVARCHAR (8)    NULL,
    [DESCRIPTION]                NVARCHAR (50)   NOT NULL,
    [COMMENTS]                   NVARCHAR (1000) NULL,
    [MARK_FOR_DELETION]          INT             NOT NULL,
    [CREATED_SOURCE_TYPE]        INT             NOT NULL,
    [CREATED_SOURCE]             NVARCHAR (50)   NOT NULL,
    [CREATED_DTTM]               DATETIME2 (7)   NOT NULL,
    [LAST_UPDATED_SOURCE_TYPE]   INT             NOT NULL,
    [LAST_UPDATED_SOURCE]        NVARCHAR (50)   NULL,
    [LAST_UPDATED_DTTM]          DATETIME2 (7)   NOT NULL,
    [DEFAULT_MOT_ID]             INT             NULL,
    [SERVICE_LEVEL_ID]           INT             NOT NULL,
    [MAX_PARCEL_WEIGHT]          DECIMAL (13, 4) NULL,
    [MAX_PARCEL_DIMENSION]       DECIMAL (13, 2) NULL,
    [MAX_PARCEL_CUBE]            INT             NULL,
    [MAX_PARCEL_GIRTH]           DECIMAL (13, 2) NULL,
    [MIN_PARCEL_CWT_WEIGHT]      INT             NULL,
    [MIN_PARCEL_AVG_CWT_WEIGHT]  INT             NULL,
    [MIN_PARCEL_WEIGHT]          DECIMAL (13, 4) NULL,
    [MIN_PARCEL_CUBE]            INT             NULL,
    [RATING_LEVEL_ID]            INT             NULL,
    [EXECUTION_LEVEL_ID]         INT             NULL,
    [SERVICE_LEVEL_INDICATOR]    NVARCHAR (15)   NULL,
    [CLASS_OF_MAIL]              NVARCHAR (25)   NULL,
    [PRINT_DESC]                 NVARCHAR (25)   NULL,
    [IS_RATE_LPN_AT_MANIFEST]    INT             NULL,
    [TRACKING_NBR_SEQ_ID]        INT             NULL,
    [SERVICE_LEVEL_ICON]         NVARCHAR (15)   NULL,
    [SERVICE_LEVEL_RANK]         INT             NULL,
    [MAX_LENGTH_GIRTH]           DECIMAL (13, 2) NULL,
    [CARRIER_PKG_IDENTIFIER]     NVARCHAR (50)   NULL,
    [FRT_SERV]                   NVARCHAR (50)   NULL,
    [INV_BULK_RATE_FLAG]         NVARCHAR (50)   NULL,
    [CARRIER_PACKAGE_ID]         NVARCHAR (50)   NULL,
    [PARCEL_SERV_MODE]           NVARCHAR (50)   NULL,
    [FLAT_RATE_WEIGHT_THRESHOLD] DECIMAL (13, 4) NULL,
    [CUSTOM_SERVICE_ATTRIB]      NVARCHAR (10)   NULL,
    [HAS_HAZMAT]                 INT             NOT NULL,
    [EPI_SERVICE_LEVEL_CODE]     NVARCHAR (100)  NULL,
    [BatchID]                    BIGINT          NULL,
    [ProcessLogID]               BIGINT          NULL,
    CONSTRAINT [PK_MANH_SERVICE_LEVEL] PRIMARY KEY CLUSTERED ([SERVICE_LEVEL_ID] ASC)
);

