CREATE TABLE [MANH].[TASK_HDR] (
    [TASK_ID]                INT            NOT NULL,
    [WHSE]                   NVARCHAR (3)   NULL,
    [TASK_DESC]              NVARCHAR (40)  NULL,
    [INVN_TYPE]              NVARCHAR (1)   NULL,
    [INVN_NEED_TYPE]         SMALLINT       NOT NULL,
    [DFLT_TASK_PRTY]         INT            NOT NULL,
    [CURR_TASK_PRTY]         INT            NOT NULL,
    [XPECTD_DURTN]           INT            NOT NULL,
    [ACTL_DURTN]             INT            NOT NULL,
    [ERLST_START_DATE_TIME]  DATETIME2 (7)  NULL,
    [LTST_START_DATE_TIME]   DATETIME2 (7)  NULL,
    [LTST_CMPL_DATE_TIME]    DATETIME2 (7)  NULL,
    [BEGIN_AREA]             NVARCHAR (4)   NULL,
    [BEGIN_ZONE]             NVARCHAR (4)   NULL,
    [BEGIN_AISLE]            NVARCHAR (4)   NULL,
    [END_AREA]               NVARCHAR (4)   NULL,
    [END_ZONE]               NVARCHAR (4)   NULL,
    [END_AISLE]              NVARCHAR (4)   NULL,
    [START_CURR_WORK_GRP]    NVARCHAR (4)   NULL,
    [START_CURR_WORK_AREA]   NVARCHAR (4)   NULL,
    [END_CURR_WORK_GRP]      NVARCHAR (4)   NULL,
    [END_CURR_WORK_AREA]     NVARCHAR (4)   NULL,
    [START_DEST_WORK_GRP]    NVARCHAR (4)   NULL,
    [START_DEST_WORK_AREA]   NVARCHAR (4)   NULL,
    [END_DEST_WORK_GRP]      NVARCHAR (4)   NULL,
    [END_DEST_WORK_AREA]     NVARCHAR (4)   NULL,
    [TASK_TYPE]              NVARCHAR (2)   NULL,
    [TASK_GENRTN_REF_CODE]   NVARCHAR (3)   NULL,
    [TASK_GENRTN_REF_NBR]    NVARCHAR (40)  NULL,
    [NEED_ID]                NVARCHAR (10)  NULL,
    [TASK_BATCH]             NVARCHAR (6)   NULL,
    [STAT_CODE]              SMALLINT       NOT NULL,
    [CREATE_DATE_TIME]       DATETIME2 (7)  NULL,
    [MOD_DATE_TIME]          DATETIME2 (7)  NULL,
    [USER_ID]                NVARCHAR (15)  NULL,
    [RLS_DATE_TIME]          DATETIME2 (7)  NULL,
    [TASK_CMPL_REF_CODE]     NVARCHAR (3)   NULL,
    [TASK_CMPL_REF_NBR]      NVARCHAR (40)  NULL,
    [OWNER_USER_ID]          NVARCHAR (15)  NULL,
    [ONE_USER_PER_GRP]       NVARCHAR (1)   NULL,
    [NEXT_TASK_ID]           INT            NOT NULL,
    [EXCEPTION_CODE]         NVARCHAR (2)   NULL,
    [CURR_LOCN_ID]           NVARCHAR (10)  NULL,
    [TASK_PARM_ID]           INT            NULL,
    [RULE_ID]                INT            NULL,
    [VOCOLLECT_ASSIGN_ID]    INT            NOT NULL,
    [CURR_USER_ID]           NVARCHAR (15)  NULL,
    [MHE_FLAG]               NVARCHAR (1)   NULL,
    [PICK_TO_TOTE_FLAG]      NVARCHAR (1)   NULL,
    [MHE_ORD_STATE]          NVARCHAR (2)   NULL,
    [PRT_TASK_LIST_FLAG]     NVARCHAR (1)   NULL,
    [RPT_PRTR_REQSTR]        NVARCHAR (255) NULL,
    [ORIG_TASK_ID]           INT            NULL,
    [DOC_ID]                 NVARCHAR (14)  NULL,
    [VOCO_INTRNL_REVERSE_ID] NVARCHAR (9)   NULL,
    [TASK_HDR_ID]            INT            NOT NULL,
    [WM_VERSION_ID]          INT            NOT NULL,
    [ITEM_ID]                BIGINT         NULL,
    [LOCN_HDR_ID]            INT            NOT NULL,
    [TASK_RULE_PARM_ID]      INT            NOT NULL,
    [BatchID]                BIGINT         NULL,
    [ProcessLogID]           BIGINT         NULL,
    CONSTRAINT [PK_MANH_TASK_HDR] PRIMARY KEY CLUSTERED ([TASK_HDR_ID] ASC)
);

