CREATE TABLE [MANH].[UCL_USER] (
    [UCL_USER_ID]                 BIGINT         NOT NULL,
    [COMPANY_ID]                  INT            NOT NULL,
    [USER_NAME]                   NVARCHAR (50)  NOT NULL,
    [USER_PASSWORD]               NVARCHAR (255) NOT NULL,
    [IS_ACTIVE]                   SMALLINT       NOT NULL,
    [CREATED_SOURCE_TYPE_ID]      SMALLINT       NOT NULL,
    [CREATED_SOURCE]              NVARCHAR (50)  NOT NULL,
    [CREATED_DTTM]                DATETIME2 (7)  NOT NULL,
    [LAST_UPDATED_SOURCE_TYPE_ID] SMALLINT       NOT NULL,
    [LAST_UPDATED_SOURCE]         NVARCHAR (50)  NOT NULL,
    [LAST_UPDATED_DTTM]           DATETIME2 (7)  NOT NULL,
    [USER_TYPE_ID]                SMALLINT       NOT NULL,
    [LOCALE_ID]                   SMALLINT       NOT NULL,
    [LOCATION_ID]                 BIGINT         NOT NULL,
    [USER_FIRST_NAME]             NVARCHAR (50)  NULL,
    [USER_MIDDLE_NAME]            NVARCHAR (50)  NULL,
    [USER_LAST_NAME]              NVARCHAR (50)  NULL,
    [USER_PREFIX]                 NVARCHAR (16)  NULL,
    [USER_TITLE]                  NVARCHAR (50)  NULL,
    [TELEPHONE_NUMBER]            NVARCHAR (32)  NULL,
    [FAX_NUMBER]                  NVARCHAR (32)  NULL,
    [ADDRESS_1]                   NVARCHAR (75)  NULL,
    [ADDRESS_2]                   NVARCHAR (75)  NULL,
    [CITY]                        NVARCHAR (50)  NULL,
    [STATE_PROV_CODE]             NVARCHAR (4)   NULL,
    [POSTAL_CODE]                 NVARCHAR (10)  NULL,
    [COUNTRY_CODE]                NVARCHAR (4)   NULL,
    [USER_EMAIL_1]                NVARCHAR (75)  NULL,
    [USER_EMAIL_2]                NVARCHAR (75)  NULL,
    [COMM_METHOD_ID_DURING_BH_1]  SMALLINT       NULL,
    [COMM_METHOD_ID_DURING_BH_2]  SMALLINT       NULL,
    [COMM_METHOD_ID_AFTER_BH_1]   SMALLINT       NULL,
    [COMM_METHOD_ID_AFTER_BH_2]   SMALLINT       NULL,
    [COMMON_NAME]                 NVARCHAR (100) NOT NULL,
    [LAST_PASSWORD_CHANGE_DTTM]   DATETIME2 (7)  NULL,
    [LOGGED_IN]                   INT            NULL,
    [LAST_LOGIN_DTTM]             DATETIME2 (7)  NULL,
    [DEFAULT_BUSINESS_UNIT_ID]    INT            NOT NULL,
    [DEFAULT_WHSE_REGION_ID]      INT            NOT NULL,
    [CHANNEL_ID]                  BIGINT         NULL,
    [HIBERNATE_VERSION]           BIGINT         NULL,
    [NUMBER_OF_INVALID_LOGINS]    SMALLINT       NULL,
    [TAX_ID_NBR]                  NVARCHAR (15)  NULL,
    [EMP_START_DATE]              DATETIME2 (7)  NULL,
    [BIRTH_DATE]                  DATETIME2 (7)  NULL,
    [GENDER_ID]                   NVARCHAR (1)   NULL,
    [BatchID]                     BIGINT         NULL,
    [ProcessLogID]                BIGINT         NULL,
    [ISPASSWORDMANAGEDINTERNALLY] INT            NULL,
    [PASSWORD_RESET_DATE_TIME]    DATETIME2 (7)  NULL,
    [PASSWORD_TOKEN]              NVARCHAR (255) NULL,
    CONSTRAINT [PK_MANH_UCL_USER] PRIMARY KEY CLUSTERED ([UCL_USER_ID] ASC)
);



