CREATE TABLE [MANH].[USER_TYPE] (
    [USER_TYPE_ID]      SMALLINT      NOT NULL,
    [DESCRIPTION]       NVARCHAR (50) NOT NULL,
    [ABBREVIATION]      NVARCHAR (4)  NOT NULL,
    [BatchID]           BIGINT        NULL,
    [ProcessLogID]      BIGINT        NULL,
    [CREATED_DTTM]      DATETIME2 (7) NULL,
    [LAST_UPDATED_DTTM] DATETIME2 (7) NULL,
    CONSTRAINT [PK_MANH_USER_TYPE] PRIMARY KEY CLUSTERED ([USER_TYPE_ID] ASC)
);



