CREATE TABLE [MANH].[WAVE_WORK_TYPE_STATS] (
    [WAVE_PARM_ID]            INT             NOT NULL,
    [WORK_TYPE]               NVARCHAR (3)    NOT NULL,
    [WHSE]                    NVARCHAR (3)    NULL,
    [WAVE_NBR]                NVARCHAR (12)   NULL,
    [SAMS_CAPCTY]             DECIMAL (11, 4) NOT NULL,
    [SAMS_SCHED]              DECIMAL (11, 4) NOT NULL,
    [SAMS_CMPL]               DECIMAL (11, 4) NOT NULL,
    [UNITS_CAPCTY]            DECIMAL (9, 2)  NOT NULL,
    [UNITS_SCHED]             DECIMAL (9, 2)  NOT NULL,
    [UNITS_CMPL]              DECIMAL (9, 2)  NOT NULL,
    [PIKS_CAPCTY]             INT             NOT NULL,
    [PIKS_SCHED]              INT             NOT NULL,
    [PIKS_CMPL]               INT             NOT NULL,
    [LINES_CAPCTY]            INT             NOT NULL,
    [LINES_SCHED]             INT             NOT NULL,
    [LINES_CMPL]              INT             NOT NULL,
    [DLRS_CAPCTY]             DECIMAL (11, 2) NOT NULL,
    [DLRS_SCHED]              DECIMAL (11, 2) NOT NULL,
    [DLRS_CMPL]               DECIMAL (11, 2) NOT NULL,
    [PKTS_SCHED]              INT             NOT NULL,
    [PKTS_CMPL]               INT             NOT NULL,
    [CREATE_DATE_TIME]        DATETIME2 (7)   NULL,
    [MOD_DATE_TIME]           DATETIME2 (7)   NULL,
    [USER_ID]                 NVARCHAR (15)   NULL,
    [SKU_CAPCTY]              INT             NOT NULL,
    [CASE_CAPCTY]             INT             NOT NULL,
    [COMP_UNITS_CAPCTY]       INT             NOT NULL,
    [COMP_CASE_CAPCTY]        INT             NOT NULL,
    [FG_HOURS_CAPCTY]         INT             NOT NULL,
    [SKU_SCHED]               INT             NOT NULL,
    [SKU_CMPL]                INT             NOT NULL,
    [CASE_SCHED]              INT             NOT NULL,
    [CASE_CMPL]               INT             NOT NULL,
    [COMP_UNITS_SCHED]        INT             NOT NULL,
    [COMP_UNITS_CMPL]         INT             NOT NULL,
    [COMP_CASE_SCHED]         INT             NOT NULL,
    [COMP_CASE_CMPL]          INT             NOT NULL,
    [FG_HOURS_SCHED]          INT             NOT NULL,
    [FG_HOURS_CMPL]           INT             NOT NULL,
    [CARTON_CAPCTY]           INT             NOT NULL,
    [CARTON_SCHED]            INT             NOT NULL,
    [CARTON_CMPL]             INT             NOT NULL,
    [WAVE_WORK_TYPE_STATS_ID] INT             NOT NULL,
    [SHIP_WAVE_PARM_ID]       INT             NULL,
    [WM_VERSION_ID]           INT             NOT NULL,
    [CREATED_DTTM]            DATETIME2 (7)   NOT NULL,
    [LAST_UPDATED_DTTM]       DATETIME2 (7)   NULL,
    [BatchID]                 BIGINT          NULL,
    [ProcessLogID]            BIGINT          NULL,
    CONSTRAINT [PK_MANH_WAVE_WORK_TYPE_STATS] PRIMARY KEY CLUSTERED ([WAVE_WORK_TYPE_STATS_ID] ASC)
);

