CREATE TABLE [WEB].[FormRelationShipRadar] (
    [FormRelationShipRadar_ID]                 BIGINT         NOT NULL,
    [FormRelationShipRadar_Country]            NVARCHAR (100) NULL,
    [FormRelationShipRadar_Date]               DATE           NULL,
    [FormRelationShipRadar_CustomerQuadrant]   NVARCHAR (5)   NULL,
    [FormRelationShipRadar_WOWMoments]         INT            NULL,
    [FormRelationShipRadar_WOWMoment1]         NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_WOWMoment2]         NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_WOWMoment3]         NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_WOWMoment4]         NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_WOWMoment5]         NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_Development]        NVARCHAR (15)  NULL,
    [FormRelationShipRadar_DevelopmentComment] NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_OnAlert]            NVARCHAR (5)   NULL,
    [FormRelationShipRadar_OnAlertComment]     NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_MonthComment]       NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_ExperienceFocus]    NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_ExperienceComment]  NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_Actions]            NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_LearningPoints]     NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_ForeverProud]       NVARCHAR (MAX) NULL,
    [FormRelationShipRadar_State]              NVARCHAR (20)  NULL,
    [FormRelationShipRadar_UpdatedBy]          NVARCHAR (256) NULL,
    [FormRelationShipRadar_UpdatedDate]        DATETIME2 (7)  NULL,
    [FormRelationShipRadar_CreatedBy]          NVARCHAR (256) NULL,
    [FormRelationShipRadar_CreatedDate]        DATETIME2 (7)  NULL,
    [BatchID]                                  BIGINT         NULL,
    [ProcessLogID]                             BIGINT         NULL,
    CONSTRAINT [PK_FormRelationShipRadar] PRIMARY KEY CLUSTERED ([FormRelationShipRadar_ID] ASC)
);

