CREATE TABLE [IFS].[ACCOUNTING_BALANCE] (
    [COMPANY]                       NVARCHAR (20)   NOT NULL,
    [ACCOUNTING_YEAR]               INT             NOT NULL,
    [ACCOUNTING_PERIOD]             INT             NOT NULL,
    [YEAR_PERIOD_KEY]               INT             NULL,
    [POSTING_COMBINATION_ID]        INT             NOT NULL,
    [SIMULATION_VOUCHER]            NVARCHAR (5)    NOT NULL,
    [YEAR_PERIOD]                   NVARCHAR (7)    NULL,
    [ACCOUNT]                       NVARCHAR (20)   NULL,
    [CODE_B]                        NVARCHAR (20)   NULL,
    [CODE_C]                        NVARCHAR (20)   NULL,
    [CODE_D]                        NVARCHAR (20)   NULL,
    [CODE_E]                        NVARCHAR (20)   NULL,
    [CODE_F]                        NVARCHAR (20)   NULL,
    [CODE_G]                        NVARCHAR (20)   NULL,
    [CODE_H]                        NVARCHAR (20)   NULL,
    [CODE_I]                        NVARCHAR (20)   NULL,
    [CODE_J]                        NVARCHAR (20)   NULL,
    [DEBET_BALANCE]                 DECIMAL (18, 2) NULL,
    [CREDIT_BALANCE]                DECIMAL (18, 2) NULL,
    [AMOUNT_BALANCE]                DECIMAL (18, 2) NULL,
    [CURR_DEBET_BALANCE]            DECIMAL (18, 2) NULL,
    [CURR_CREDIT_BALANCE]           DECIMAL (18, 2) NULL,
    [CURR_AMOUNT_BALANCE]           DECIMAL (18, 2) NULL,
    [QTY_BALANCE]                   DECIMAL (18, 2) NULL,
    [THIRD_CURRENCY_DEBIT_BALANCE]  DECIMAL (18, 2) NULL,
    [THIRD_CURRENCY_CREDIT_BALANCE] DECIMAL (18, 2) NULL,
    [THIRD_CURRENCY_AMOUNT_BALANCE] DECIMAL (18, 2) NULL,
    [CURRENCY_AMOUNT]               NVARCHAR (2000) NULL,
    [AMOUNT]                        NVARCHAR (2000) NULL,
    [THIRD_CURRENCY_AMOUNT]         NVARCHAR (2000) NULL,
    [QUANTITY]                      NVARCHAR (2000) NULL,
    [OBJID]                         NVARCHAR (4000) NULL,
    [OBJVERSION]                    NVARCHAR (2000) NULL,
    [Eff_Date]                      DATE            NOT NULL,
    [End_Date]                      DATE            NULL,
    [ActInd]                        CHAR (1)        NULL,
    [IsDeleted]                     CHAR (1)        NULL,
    [BatchID]                       BIGINT          NULL,
    [ProcessLogID]                  BIGINT          NULL,
    CONSTRAINT [PK_ACCOUNTING_BALANCE] PRIMARY KEY CLUSTERED ([COMPANY] ASC, [ACCOUNTING_YEAR] ASC, [ACCOUNTING_PERIOD] ASC, [POSTING_COMBINATION_ID] ASC, [SIMULATION_VOUCHER] ASC, [Eff_Date] ASC) ON [DWH_IFS]
) ON [DWH_IFS];

