CREATE TABLE [IFS].[COMPANY_INVOICE_INFO] (
    [COMPANY]                       NVARCHAR (20)   NOT NULL,
    [GROSS_CALC]                    NVARCHAR (5)    NULL,
    [PAGE_FOOTING]                  NVARCHAR (2000) NULL,
    [DEF_INSTANT_INV_TYPE]          NVARCHAR (20)   NULL,
    [DEF_MAN_CUST_INV_TYPE]         NVARCHAR (20)   NULL,
    [DEF_MAN_SUPP_INV_TYPE]         NVARCHAR (20)   NULL,
    [DEF_AUTO_INVOICE_TYPE]         NVARCHAR (20)   NULL,
    [INV_FEE_VAT_CODE]              NVARCHAR (20)   NULL,
    [BASE_PLANNED_PAY_DATE]         NVARCHAR (4000) NULL,
    [BASE_PLANNED_PAY_DATE_DB]      NVARCHAR (20)   NULL,
    [SEP_INV_AUTH]                  NVARCHAR (5)    NULL,
    [INV_SUPP_NOT_EQUAL_SUPP]       NVARCHAR (200)  NULL,
    [INV_SUPP_NOT_EQUAL_SUPP_DB]    NVARCHAR (30)   NULL,
    [VAT_NO]                        NVARCHAR (50)   NULL,
    [VOUCHER_AT_INV_ENTRY]          NVARCHAR (5)    NULL,
    [SAME_VOUCHER_NO]               NVARCHAR (5)    NULL,
    [AMOUNT_METHOD]                 NVARCHAR (4000) NULL,
    [AMOUNT_METHOD_DB]              NVARCHAR (20)   NULL,
    [GROSS_UP]                      NVARCHAR (5)    NULL,
    [AUTOMATIC_POST]                NVARCHAR (5)    NULL,
    [DEF_REC_INSTANT_INV_TYPE]      NVARCHAR (20)   NULL,
    [DEF_REC_MAN_SUPP_INV_TYPE]     NVARCHAR (20)   NULL,
    [NCF_REFERENCE_METHOD]          NVARCHAR (4000) NULL,
    [NCF_REFERENCE_METHOD_DB]       NVARCHAR (20)   NULL,
    [NCF_REFERENCE_METHOD_SUPP]     NVARCHAR (4000) NULL,
    [NCF_REFERENCE_METHOD_SUPP_DB]  NVARCHAR (20)   NULL,
    [PERCENT_TOLERANCE]             INT             NULL,
    [AMOUNT_TOLERANCE]              INT             NULL,
    [TAX_CORRESPONDENCE]            NVARCHAR (5)    NULL,
    [SALES_TAX_CALC_METHOD]         NVARCHAR (4000) NULL,
    [SALES_TAX_CALC_METHOD_DB]      NVARCHAR (50)   NULL,
    [TYPE1099_REQUIRED]             NVARCHAR (5)    NULL,
    [TAX_REGIME]                    NVARCHAR (4000) NULL,
    [TAX_REGIME_DB]                 NVARCHAR (20)   NULL,
    [TAX_ID_TYPE]                   NVARCHAR (10)   NULL,
    [LIABILITY_TYPE]                NVARCHAR (20)   NULL,
    [INTERNAL_INCOME_TYPE]          INT             NULL,
    [INCOME_TYPE_ID]                NVARCHAR (4000) NULL,
    [CURRENCY_CODE]                 NVARCHAR (4000) NULL,
    [COUNTRY_CODE]                  NVARCHAR (4000) NULL,
    [NUMBERING_CUST_INV_DATE_ORDER] NVARCHAR (5)    NULL,
    [DEF_ADV_CO_DR_INV_TYPE]        NVARCHAR (20)   NULL,
    [DEF_ADV_CO_CR_INV_TYPE]        NVARCHAR (20)   NULL,
    [DISPLAY_DATE]                  NVARCHAR (5)    NULL,
    [TAX_AMOUNT_LIMIT]              NVARCHAR (5)    NULL,
    [AUTHORIZATION_LEVEL]           NVARCHAR (4000) NULL,
    [AUTHORIZATION_LEVEL_DB]        NVARCHAR (20)   NULL,
    [USE_POSTING_PROPOSAL]          NVARCHAR (5)    NULL,
    [TOLERANCE_ACC_TO_POST_CTRL]    NVARCHAR (5)    NULL,
    [DEFAULT_TAX_WITHHOLDING_CODE]  NVARCHAR (60)   NULL,
    [USE_TAX_INVOICE]               NVARCHAR (5)    NULL,
    [POST_PREL_TAX_WITHH]           NVARCHAR (5)    NULL,
    [DEF_RECADV_INV_TYPE]           NVARCHAR (20)   NULL,
    [TAX_ROUNDING_LEVEL]            NVARCHAR (4000) NULL,
    [TAX_ROUNDING_LEVEL_DB]         NVARCHAR (20)   NULL,
    [CREDIT_LIMIT]                  INT             NULL,
    [PRINT_ADV_PAY_ON_CU_INV]       NVARCHAR (5)    NULL,
    [DEF_CORR_INST_INV_TYPE]        NVARCHAR (20)   NULL,
    [DEF_CO_PREPAY_DEB_INV_TYPE]    NVARCHAR (20)   NULL,
    [DEF_CO_PREPAY_CRE_INV_TYPE]    NVARCHAR (20)   NULL,
    [DEF_CO_COR_INV_TYPE]           NVARCHAR (20)   NULL,
    [DEF_COL_COR_INV_TYPE]          NVARCHAR (20)   NULL,
    [DEF_PROJ_COR_INV_TYPE]         NVARCHAR (20)   NULL,
    [DEF_PROJ_CRE_INV_TYPE]         NVARCHAR (20)   NULL,
    [SUPP_INV_NO_UNIQUENESS]        NVARCHAR (200)  NULL,
    [SUPP_INV_NO_UNIQUENESS_DB]     NVARCHAR (20)   NULL,
    [CORR_INV_BASE_AMT]             NVARCHAR (5)    NULL,
    [DOCUMENT_CLASS]                NVARCHAR (12)   NULL,
    [DOCUMENT_PREFIX]               NVARCHAR (50)   NULL,
    [ATTACH_DOC_CLASS]              NVARCHAR (12)   NULL,
    [ATTACH_DOC_PREFIX]             NVARCHAR (50)   NULL,
    [CO_REBATE_CRE_INV_TYPE]        NVARCHAR (20)   NULL,
    [C_USE_TAX_ID_TAX_OFFICE]       NVARCHAR (5)    NULL,
    [ACC_CURR_DIFF]                 INT             NULL,
    [OBJID]                         NVARCHAR (4000) NULL,
    [OBJVERSION]                    NVARCHAR (2000) NULL,
    [Eff_Date]                      DATE            NOT NULL,
    [End_Date]                      DATE            NULL,
    [ActInd]                        CHAR (1)        NULL,
    [IsDeleted]                     CHAR (1)        NULL,
    [BatchID]                       BIGINT          NULL,
    [ProcessLogID]                  BIGINT          NULL,
    CONSTRAINT [PK_COMPANY_INVOICE_INFO] PRIMARY KEY CLUSTERED ([COMPANY] ASC, [Eff_Date] ASC)
);

