CREATE TABLE [IFS].[CUSTOMER_ORDER_LINE] (
    [ORDER_NO]                       NVARCHAR (12)   NOT NULL,
    [LINE_NO]                        NVARCHAR (4)    NOT NULL,
    [REL_NO]                         NVARCHAR (4)    NOT NULL,
    [LINE_ITEM_NO]                   INT             NOT NULL,
    [CONTRACT]                       NVARCHAR (5)    NULL,
    [CATALOG_NO]                     NVARCHAR (25)   NULL,
    [NOTE_ID]                        INT             NULL,
    [ORDER_CODE]                     NVARCHAR (3)    NULL,
    [PART_NO]                        NVARCHAR (25)   NULL,
    [PRE_ACCOUNTING_ID]              INT             NULL,
    [SALES_UNIT_MEAS]                NVARCHAR (10)   NULL,
    [BASE_SALE_UNIT_PRICE]           DECIMAL (18, 2) NULL,
    [BONUS_BASIS]                    INT             NULL,
    [BONUS_VALUE]                    INT             NULL,
    [BUY_QTY_DUE]                    DECIMAL (18, 2) NULL,
    [CATALOG_DESC]                   NVARCHAR (200)  NULL,
    [CATALOG_TYPE]                   NVARCHAR (200)  NULL,
    [CATALOG_TYPE_DB]                NVARCHAR (20)   NULL,
    [CONV_FACTOR]                    INT             NULL,
    [COST]                           DECIMAL (18, 2) NULL,
    [CURRENCY_RATE]                  DECIMAL (18)    NULL,
    [DATE_ENTERED]                   DATETIME2 (7)   NULL,
    [DISCOUNT]                       INT             NULL,
    [LINE_TOTAL_QTY]                 INT             NULL,
    [LINE_TOTAL_WEIGHT]              INT             NULL,
    [NOTE_TEXT]                      NVARCHAR (2000) NULL,
    [ORDER_DISCOUNT]                 INT             NULL,
    [PLANNED_DELIVERY_DATE]          DATETIME2 (7)   NULL,
    [PLANNED_DUE_DATE]               DATETIME2 (7)   NULL,
    [SUPPLY_SITE_DUE_DATE]           DATETIME2 (7)   NULL,
    [PRICE_CONV_FACTOR]              INT             NULL,
    [PROMISED_DELIVERY_DATE]         DATETIME2 (7)   NULL,
    [QTY_ASSIGNED]                   INT             NULL,
    [QTY_INVOICED]                   INT             NULL,
    [QTY_ON_ORDER]                   INT             NULL,
    [QTY_PICKED]                     INT             NULL,
    [QTY_RETURNED]                   INT             NULL,
    [QTY_SHIPDIFF]                   INT             NULL,
    [QTY_SHIPPED]                    INT             NULL,
    [QTY_TO_SHIP]                    INT             NULL,
    [QTY_SHORT]                      INT             NULL,
    [REAL_SHIP_DATE]                 DATETIME2 (7)   NULL,
    [REVISED_QTY_DUE]                INT             NULL,
    [SALE_UNIT_PRICE]                DECIMAL (18, 2) NULL,
    [SUPPLY_CODE]                    NVARCHAR (200)  NULL,
    [SUPPLY_CODE_DB]                 NVARCHAR (20)   NULL,
    [WANTED_DELIVERY_DATE]           DATETIME2 (7)   NULL,
    [DELIVERY_TYPE]                  NVARCHAR (20)   NULL,
    [VENDOR_NO]                      NVARCHAR (20)   NULL,
    [FEE_CODE]                       NVARCHAR (200)  NULL,
    [CUSTOMER_PART_NO]               NVARCHAR (45)   NULL,
    [CUSTOMER_PART_CONV_FACTOR]      INT             NULL,
    [CUSTOMER_PART_UNIT_MEAS]        NVARCHAR (10)   NULL,
    [CUSTOMER_PART_BUY_QTY]          INT             NULL,
    [PLANNED_SHIP_DATE]              DATETIME2 (7)   NULL,
    [PLANNED_SHIP_PERIOD]            NVARCHAR (10)   NULL,
    [CUSTOMER_NO]                    NVARCHAR (20)   NULL,
    [CONSIGNMENT_STOCK]              NVARCHAR (200)  NULL,
    [CONSIGNMENT_STOCK_DB]           NVARCHAR (20)   NULL,
    [CLOSE_TOLERANCE]                INT             NULL,
    [PRICE_LIST_NO]                  NVARCHAR (10)   NULL,
    [CHARGED_ITEM]                   NVARCHAR (200)  NULL,
    [CHARGED_ITEM_DB]                NVARCHAR (20)   NULL,
    [DEMAND_ORDER_REF1]              NVARCHAR (12)   NULL,
    [DEMAND_ORDER_REF2]              NVARCHAR (4)    NULL,
    [DEMAND_ORDER_REF3]              NVARCHAR (4)    NULL,
    [DEMAND_ORDER_REF4]              INT             NULL,
    [DEMAND_CODE]                    NVARCHAR (200)  NULL,
    [DEMAND_CODE_DB]                 NVARCHAR (20)   NULL,
    [DOP_CONNECTION]                 NVARCHAR (200)  NULL,
    [DOP_CONNECTION_DB]              NVARCHAR (20)   NULL,
    [CREATE_SM_OBJECT_OPTION]        NVARCHAR (200)  NULL,
    [CREATE_SM_OBJECT_OPTION_DB]     NVARCHAR (20)   NULL,
    [DEFAULT_ADDR_FLAG]              NVARCHAR (200)  NULL,
    [DEFAULT_ADDR_FLAG_DB]           NVARCHAR (20)   NULL,
    [ADDR_FLAG]                      NVARCHAR (200)  NULL,
    [ADDR_FLAG_DB]                   NVARCHAR (20)   NULL,
    [SHIP_ADDR_NO]                   NVARCHAR (50)   NULL,
    [ROUTE_ID]                       NVARCHAR (12)   NULL,
    [FORWARD_AGENT_ID]               NVARCHAR (20)   NULL,
    [SHIP_VIA_CODE]                  NVARCHAR (3)    NULL,
    [DELIVERY_TERMS]                 NVARCHAR (3)    NULL,
    [DELIVERY_LEADTIME]              INT             NULL,
    [DISTRICT_CODE]                  NVARCHAR (10)   NULL,
    [REGION_CODE]                    NVARCHAR (10)   NULL,
    [DESIRED_QTY]                    DECIMAL (18)    NULL,
    [PURCHASE_PART_NO]               NVARCHAR (25)   NULL,
    [STAGED_BILLING]                 NVARCHAR (200)  NULL,
    [STAGED_BILLING_DB]              NVARCHAR (20)   NULL,
    [VAT]                            NVARCHAR (200)  NULL,
    [VAT_DB]                         NVARCHAR (20)   NULL,
    [ORIGINAL_PART_NO]               NVARCHAR (25)   NULL,
    [SUP_SM_CONTRACT]                NVARCHAR (5)    NULL,
    [SUP_SM_OBJECT]                  NVARCHAR (40)   NULL,
    [SM_CONNECTION]                  NVARCHAR (200)  NULL,
    [SM_CONNECTION_DB]               NVARCHAR (20)   NULL,
    [PART_PRICE]                     DECIMAL (18, 2) NULL,
    [CALC_CHAR_PRICE]                INT             NULL,
    [CHAR_PRICE]                     INT             NULL,
    [PRICE_SOURCE]                   NVARCHAR (200)  NULL,
    [PRICE_SOURCE_DB]                NVARCHAR (20)   NULL,
    [PRICE_FREEZE]                   NVARCHAR (200)  NULL,
    [PRICE_FREEZE_DB]                NVARCHAR (20)   NULL,
    [DOCK_CODE]                      NVARCHAR (35)   NULL,
    [SUB_DOCK_CODE]                  NVARCHAR (35)   NULL,
    [REF_ID]                         NVARCHAR (35)   NULL,
    [LOCATION_NO]                    NVARCHAR (35)   NULL,
    [CONFIGURATION_ID]               NVARCHAR (50)   NULL,
    [PRICE_EFFECTIVITY_DATE]         DATETIME2 (7)   NULL,
    [CONFIGURED_LINE_PRICE_ID]       INT             NULL,
    [LATEST_RELEASE_DATE]            DATETIME2 (7)   NULL,
    [CTP_PLANNED]                    NVARCHAR (200)  NULL,
    [CTP_PLANNED_DB]                 NVARCHAR (20)   NULL,
    [JOB_ID]                         NVARCHAR (10)   NULL,
    [CUST_WARRANTY_ID]               INT             NULL,
    [PRICE_SOURCE_ID]                NVARCHAR (25)   NULL,
    [INTRASTAT_EXEMPT]               NVARCHAR (200)  NULL,
    [INTRASTAT_EXEMPT_DB]            NVARCHAR (20)   NULL,
    [PRICE_UNIT_MEAS]                NVARCHAR (10)   NULL,
    [CONDITION_CODE]                 NVARCHAR (10)   NULL,
    [ADDITIONAL_DISCOUNT]            INT             NULL,
    [PART_OWNERSHIP]                 NVARCHAR (200)  NULL,
    [PART_OWNERSHIP_DB]              NVARCHAR (20)   NULL,
    [OWNING_CUSTOMER_NO]             NVARCHAR (20)   NULL,
    [EXCHANGE_ITEM]                  NVARCHAR (200)  NULL,
    [EXCHANGE_ITEM_DB]               NVARCHAR (20)   NULL,
    [SUPPLY_SITE_RESERVE_TYPE]       NVARCHAR (200)  NULL,
    [SUPPLY_SITE_RESERVE_TYPE_DB]    NVARCHAR (20)   NULL,
    [ORIGINATING_REL_NO]             NVARCHAR (4)    NULL,
    [ORIGINATING_LINE_ITEM_NO]       INT             NULL,
    [RELEASE_PLANNING]               NVARCHAR (200)  NULL,
    [RELEASE_PLANNING_DB]            NVARCHAR (20)   NULL,
    [REPLICATE_CHANGES]              NVARCHAR (5)    NULL,
    [CHANGE_REQUEST]                 NVARCHAR (5)    NULL,
    [SUPPLIER_SHIP_VIA_TRANSIT]      NVARCHAR (3)    NULL,
    [SUPPLIER_SHIP_VIA_TRANSIT_DESC] NVARCHAR (35)   NULL,
    [SUPPLY_SITE]                    NVARCHAR (5)    NULL,
    [SHIPMENT_CONNECTED]             NVARCHAR (200)  NULL,
    [SHIPMENT_CONNECTED_DB]          NVARCHAR (20)   NULL,
    [SELF_BILLING]                   NVARCHAR (200)  NULL,
    [SELF_BILLING_DB]                NVARCHAR (20)   NULL,
    [ACTIVITY_SEQ]                   INT             NULL,
    [PROJECT_ID]                     NVARCHAR (10)   NULL,
    [SERVER_DATA_CHANGE]             INT             NULL,
    [DELIVER_TO_CUSTOMER_NO]         NVARCHAR (20)   NULL,
    [CONTACT]                        NVARCHAR (90)   NULL,
    [INPUT_QTY]                      INT             NULL,
    [INPUT_UNIT_MEAS]                NVARCHAR (30)   NULL,
    [INPUT_CONV_FACTOR]              INT             NULL,
    [INPUT_VARIABLE_VALUES]          NVARCHAR (2000) NULL,
    [DOP_NEW_QTY_DEMAND]             NVARCHAR (2000) NULL,
    [SHIPMENT_CREATION]              NVARCHAR (200)  NULL,
    [SHIPMENT_CREATION_DB]           NVARCHAR (25)   NULL,
    [MANUFACTURING_DEPARTMENT]       NVARCHAR (2000) NULL,
    [DELIVERY_SEQUENCE]              INT             NULL,
    [CANCEL_REASON]                  NVARCHAR (10)   NULL,
    [DELIVERY_CONFIRMED]             NVARCHAR (200)  NULL,
    [DELIVERY_CONFIRMED_DB]          NVARCHAR (20)   NULL,
    [CUSTOMER_PO_LINE_NO]            NVARCHAR (4)    NULL,
    [CUSTOMER_PO_REL_NO]             NVARCHAR (4)    NULL,
    [UPDATE_PEGGED_ORDERS]           NVARCHAR (5)    NULL,
    [QTY_CONFIRMEDDIFF]              INT             NULL,
    [BLOCKED_FOR_INVOICING]          NVARCHAR (200)  NULL,
    [BLOCKED_FOR_INVOICING_DB]       NVARCHAR (20)   NULL,
    [PROVISIONAL_PRICE]              NVARCHAR (200)  NULL,
    [PROVISIONAL_PRICE_DB]           NVARCHAR (20)   NULL,
    [RECEIVING_ADVICE_TYPE]          NVARCHAR (200)  NULL,
    [RECEIVING_ADVICE_TYPE_DB]       NVARCHAR (20)   NULL,
    [DEFAULT_CHARGES]                NVARCHAR (50)   NULL,
    [FIRST_ACTUAL_SHIP_DATE]         DATETIME2 (7)   NULL,
    [VAT_NO]                         NVARCHAR (50)   NULL,
    [PRICE_SOURCE_NET_PRICE]         NVARCHAR (200)  NULL,
    [PRICE_SOURCE_NET_PRICE_DB]      NVARCHAR (5)    NULL,
    [TARGET_DATE]                    DATETIME2 (7)   NULL,
    [ALLOCATION_ID]                  INT             NULL,
    [DEL_TERMS_LOCATION]             NVARCHAR (100)  NULL,
    [CLASSIFICATION_PART_NO]         NVARCHAR (25)   NULL,
    [CLASSIFICATION_UNIT_MEAS]       NVARCHAR (10)   NULL,
    [CLASSIFICATION_STANDARD]        NVARCHAR (25)   NULL,
    [REBATE_BUILDER]                 NVARCHAR (200)  NULL,
    [REBATE_BUILDER_DB]              NVARCHAR (20)   NULL,
    [LINE_TOTAL_WEIGHT_GROSS]        INT             NULL,
    [ZONE_DEFINITION_ID]             NVARCHAR (15)   NULL,
    [ZONE_ID]                        NVARCHAR (15)   NULL,
    [FREIGHT_PRICE_LIST_NO]          NVARCHAR (10)   NULL,
    [ADJUSTED_WEIGHT_NET]            INT             NULL,
    [ADJUSTED_WEIGHT_GROSS]          INT             NULL,
    [ADJUSTED_VOLUME]                INT             NULL,
    [FREIGHT_FREE]                   NVARCHAR (200)  NULL,
    [FREIGHT_FREE_DB]                NVARCHAR (20)   NULL,
    [PART_LEVEL]                     NVARCHAR (200)  NULL,
    [PART_LEVEL_DB]                  NVARCHAR (30)   NULL,
    [PART_LEVEL_ID]                  NVARCHAR (200)  NULL,
    [CUSTOMER_LEVEL]                 NVARCHAR (200)  NULL,
    [CUSTOMER_LEVEL_DB]              NVARCHAR (30)   NULL,
    [CUSTOMER_LEVEL_ID]              NVARCHAR (200)  NULL,
    [LOAD_ID]                        INT             NULL,
    [CUSTOMS_VALUE]                  DECIMAL (18)    NULL,
    [ABNORMAL_DEMAND]                NVARCHAR (200)  NULL,
    [ABNORMAL_DEMAND_DB]             NVARCHAR (20)   NULL,
    [COMPANY]                        NVARCHAR (20)   NULL,
    [QTY_PER_ASSEMBLY]               INT             NULL,
    [NEW_COMP_AFTER_DELIVERY]        NVARCHAR (5)    NULL,
    [CASE_CREDIT]                    DECIMAL (18, 2) NULL,
    [OBJID]                          NVARCHAR (100)  NULL,
    [OBJVERSION]                     BIGINT          NULL,
    [OBJSTATE]                       NVARCHAR (20)   NULL,
    [OBJEVENTS]                      NVARCHAR (4000) NULL,
    [STATE]                          NVARCHAR (4000) NULL,
    [Eff_Date]                       DATE            NOT NULL,
    [End_Date]                       DATE            NULL,
    [ActInd]                         CHAR (1)        NULL,
    [IsDeleted]                      CHAR (1)        NULL,
    [BatchID]                        BIGINT          NULL,
    [ProcessLogID]                   BIGINT          NULL,
    CONSTRAINT [PK_CUSTOMER_ORDER_LINE] PRIMARY KEY CLUSTERED ([ORDER_NO] ASC, [LINE_NO] ASC, [REL_NO] ASC, [LINE_ITEM_NO] ASC, [Eff_Date] ASC) ON [DWH_IFS]
) ON [DWH_IFS];

















