CREATE TABLE [IFS].[INVENTORY_PART_IN_STOCK] (
    [CONTRACT]                NVARCHAR (5)   NOT NULL,
    [PART_NO]                 NVARCHAR (25)  NOT NULL,
    [CONFIGURATION_ID]        NVARCHAR (50)  NOT NULL,
    [LOCATION_NO]             NVARCHAR (35)  NOT NULL,
    [LOT_BATCH_NO]            NVARCHAR (20)  NOT NULL,
    [SERIAL_NO]               NVARCHAR (50)  NOT NULL,
    [ENG_CHG_LEVEL]           NVARCHAR (2)   NOT NULL,
    [WAIV_DEV_REJ_NO]         NVARCHAR (15)  NOT NULL,
    [ACTIVITY_SEQ]            INT            NOT NULL,
    [AVG_UNIT_TRANSIT_COST]   INT            NULL,
    [COUNT_VARIANCE]          INT            NULL,
    [EXPIRATION_DATE]         DATETIME2 (7)  NULL,
    [FREEZE_FLAG]             NVARCHAR (200) NULL,
    [FREEZE_FLAG_DB]          NVARCHAR (20)  NULL,
    [LAST_ACTIVITY_DATE]      DATETIME2 (7)  NULL,
    [LAST_COUNT_DATE]         DATETIME2 (7)  NULL,
    [LOCATION_TYPE]           NVARCHAR (200) NULL,
    [LOCATION_TYPE_DB]        NVARCHAR (20)  NULL,
    [QTY_IN_TRANSIT]          INT            NULL,
    [QTY_ONHAND]              INT            NULL,
    [QTY_RESERVED]            INT            NULL,
    [RECEIPT_DATE]            DATETIME2 (7)  NULL,
    [SOURCE]                  NVARCHAR (25)  NULL,
    [WAREHOUSE]               NVARCHAR (15)  NULL,
    [BAY_NO]                  NVARCHAR (5)   NULL,
    [ROW_NO]                  NVARCHAR (5)   NULL,
    [TIER_NO]                 NVARCHAR (5)   NULL,
    [BIN_NO]                  NVARCHAR (5)   NULL,
    [AVAILABILITY_CONTROL_ID] NVARCHAR (25)  NULL,
    [CREATE_DATE]             DATETIME2 (7)  NULL,
    [ROTABLE_PART_POOL_ID]    NVARCHAR (20)  NULL,
    [PROJECT_ID]              NVARCHAR (10)  NULL,
    [CATCH_QTY_IN_TRANSIT]    INT            NULL,
    [CATCH_QTY_ONHAND]        INT            NULL,
    [OBJID]                   NVARCHAR (100) NULL,
    [OBJVERSION]              BIGINT         NULL,
    [Eff_Date]                DATE           NOT NULL,
    [End_Date]                DATE           NULL,
    [ActInd]                  CHAR (1)       NULL,
    [IsDeleted]               CHAR (1)       NULL,
    [BatchID]                 BIGINT         NULL,
    [ProcessLogID]            BIGINT         NULL,
    CONSTRAINT [PK_INVENTORY_PART_IN_STOCK] PRIMARY KEY CLUSTERED ([CONTRACT] ASC, [PART_NO] ASC, [CONFIGURATION_ID] ASC, [LOCATION_NO] ASC, [LOT_BATCH_NO] ASC, [SERIAL_NO] ASC, [ENG_CHG_LEVEL] ASC, [WAIV_DEV_REJ_NO] ASC, [ACTIVITY_SEQ] ASC, [Eff_Date] ASC)
);

