CREATE TABLE [IFS].[INVOICE_UTILITY_INV_HEAD_PUB] (
    [COMPANY]              NVARCHAR (20)   NOT NULL,
    [PARTY_TYPE]           NVARCHAR (4000) NULL,
    [PARTY_TYPE_DB]        NVARCHAR (20)   NULL,
    [INVOICE_ID]           INT             NOT NULL,
    [SERIES_ID]            NVARCHAR (20)   NULL,
    [IDENTITY]             NVARCHAR (20)   NULL,
    [DELIVERY_IDENTITY]    NVARCHAR (200)  NULL,
    [NAME]                 NVARCHAR (4000) NULL,
    [INVOICE_NO]           NVARCHAR (50)   NULL,
    [INVOICE_TYPE]         NVARCHAR (20)   NULL,
    [INVOICE_DATE]         DATETIME2 (7)   NULL,
    [DUE_DATE]             DATETIME2 (7)   NULL,
    [DELIVERY_DATE]        DATETIME2 (7)   NULL,
    [ARRIVAL_DATE]         DATETIME2 (7)   NULL,
    [CURRENCY]             NVARCHAR (3)    NULL,
    [CURR_RATE]            INT             NULL,
    [DIV_FACTOR]           INT             NULL,
    [NET_AMOUNT]           DECIMAL (18, 2) NULL,
    [VAT_AMOUNT]           DECIMAL (18, 2) NULL,
    [DOM_NET_AMOUNT]       DECIMAL (18, 2) NULL,
    [DOM_VAT_AMOUNT]       DECIMAL (18, 2) NULL,
    [NET_DOM_AMOUNT]       DECIMAL (18, 2) NULL,
    [VAT_DOM_AMOUNT]       DECIMAL (18, 2) NULL,
    [NET_CURR_AMOUNT]      DECIMAL (18, 2) NULL,
    [VAT_CURR_AMOUNT]      DECIMAL (18, 2) NULL,
    [PAY_TERM_ID]          NVARCHAR (20)   NULL,
    [PAY_TERM_DESCRIPTION] NVARCHAR (4000) NULL,
    [PAYMENT_ADDRESS_ID]   NVARCHAR (50)   NULL,
    [WAY_PAY_ID]           NVARCHAR (20)   NULL,
    [CASH]                 NVARCHAR (5)    NULL,
    [COLLECT]              NVARCHAR (5)    NULL,
    [INT_ALLOWED]          NVARCHAR (5)    NULL,
    [NATIONAL_BANK_CODE]   NVARCHAR (20)   NULL,
    [DELIVERY_ADDRESS_ID]  NVARCHAR (50)   NULL,
    [INVOICE_ADDRESS_ID]   NVARCHAR (50)   NULL,
    [HEAD_DATA]            NVARCHAR (2000) NULL,
    [SERIES_REFERENCE]     NVARCHAR (20)   NULL,
    [NUMBER_REFERENCE]     NVARCHAR (50)   NULL,
    [CREATORS_REFERENCE]   NVARCHAR (100)  NULL,
    [CREATOR]              NVARCHAR (30)   NULL,
    [CODE_A]               NVARCHAR (10)   NULL,
    [CODE_B]               NVARCHAR (10)   NULL,
    [CODE_C]               NVARCHAR (10)   NULL,
    [CODE_D]               NVARCHAR (10)   NULL,
    [CODE_E]               NVARCHAR (10)   NULL,
    [CODE_F]               NVARCHAR (10)   NULL,
    [CODE_G]               NVARCHAR (10)   NULL,
    [CODE_H]               NVARCHAR (10)   NULL,
    [CODE_I]               NVARCHAR (10)   NULL,
    [CODE_J]               NVARCHAR (10)   NULL,
    [PROJECT_ID]           NVARCHAR (4000) NULL,
    [PROJECT_ACTIVITY_ID]  INT             NULL,
    [PRE_ACC_CODE_STRING]  NVARCHAR (2000) NULL,
    [AFF_BASE_LEDG_POST]   NVARCHAR (5)    NULL,
    [AFF_LINE_POST]        NVARCHAR (5)    NULL,
    [PRELIM_CODE]          NVARCHAR (20)   NULL,
    [VOUCHER_DATE_REF]     DATETIME2 (7)   NULL,
    [VOUCHER_TYPE_REF]     NVARCHAR (3)    NULL,
    [VOUCHER_NO_REF]       INT             NULL,
    [ACCOUNTING_YEAR_REF]  INT             NULL,
    [C1]                   NVARCHAR (100)  NULL,
    [C2]                   NVARCHAR (100)  NULL,
    [C3]                   NVARCHAR (100)  NULL,
    [C4]                   NVARCHAR (100)  NULL,
    [C5]                   NVARCHAR (100)  NULL,
    [C6]                   NVARCHAR (100)  NULL,
    [C7]                   NVARCHAR (100)  NULL,
    [C8]                   NVARCHAR (100)  NULL,
    [C9]                   NVARCHAR (100)  NULL,
    [C10]                  NVARCHAR (100)  NULL,
    [N1]                   BIGINT          NULL,
    [N2]                   BIGINT          NULL,
    [N3]                   BIGINT          NULL,
    [D1]                   DATETIME2 (7)   NULL,
    [D2]                   DATETIME2 (7)   NULL,
    [D3]                   DATETIME2 (7)   NULL,
    [CHK_HANDLING_CODE]    NVARCHAR (20)   NULL,
    [PO_REF_NUMBER]        NVARCHAR (4000) NULL,
    [PAYER_IDENTITY]       NVARCHAR (20)   NULL,
    [DEDUCTION_GROUP]      NVARCHAR (20)   NULL,
    [NCF_REFERENCE]        NVARCHAR (50)   NULL,
    [CLIENT_STATE]         NVARCHAR (4000) NULL,
    [INVOICE_VERSION]      INT             NULL,
    [BRANCH]               NVARCHAR (20)   NULL,
    [PAY_TERM_BASE_DATE]   DATETIME2 (7)   NULL,
    [ADV_INV]              NVARCHAR (5)    NULL,
    [NOTES]                NVARCHAR (4000) NULL,
    [MEDIA_CODE]           NVARCHAR (30)   NULL,
    [SEND_STATUS]          NVARCHAR (4000) NULL,
    [OBJSTATE]             NVARCHAR (30)   NULL,
    [OBJID]                NVARCHAR (4000) NULL,
    [OBJVERSION]           NVARCHAR (2000) NULL,
    [Eff_Date]             DATE            NOT NULL,
    [End_Date]             DATE            NULL,
    [ActInd]               CHAR (1)        NULL,
    [IsDeleted]            CHAR (1)        NULL,
    [BatchID]              BIGINT          NULL,
    [ProcessLogID]         BIGINT          NULL,
    CONSTRAINT [PK_INVOICE_UTILITY_INV_HEAD_PUB] PRIMARY KEY CLUSTERED ([INVOICE_ID] ASC, [COMPANY] ASC, [Eff_Date] ASC) ON [DWH_IFS]
) ON [DWH_IFS];

