CREATE TABLE [IFS].[OPERATION_HISTORY] (
    [TRANSACTION_ID]           INT             NOT NULL,
    [ACCOUNTING_ID]            INT             NULL,
    [WORK_CENTER_NO]           NVARCHAR (5)    NULL,
    [TRANSACTION]              NVARCHAR (4000) NULL,
    [EMPNO]                    NVARCHAR (11)   NULL,
    [DATED]                    DATETIME2 (7)   NULL,
    [DATE_APPLIED]             DATETIME2 (7)   NULL,
    [SETUP_TIME]               DECIMAL (18, 2) NULL,
    [MANUFACTURING_TIME]       DECIMAL (18, 6) NULL,
    [QTY_COMPLETE]             INT             NULL,
    [QTY_SCRAPPED]             INT             NULL,
    [INV_TRANSACTION_ID]       INT             NULL,
    [MANUFACTURING_COST]       INT             NULL,
    [OH_1_COST]                INT             NULL,
    [OH_2_COST]                INT             NULL,
    [SOURCE]                   NVARCHAR (25)   NULL,
    [LABOR_COST]               INT             NULL,
    [LABOR_SETUP_TIME]         INT             NULL,
    [LABOR_TIME]               INT             NULL,
    [LABOR_CLASS_NO]           NVARCHAR (10)   NULL,
    [REVERSED_FLAG]            NVARCHAR (4000) NULL,
    [REVERSED_FLAG_DB]         NVARCHAR (20)   NULL,
    [OPER_STATUS_CODE]         NVARCHAR (4000) NULL,
    [OPER_STATUS_CODE_DB]      NVARCHAR (20)   NULL,
    [ORDER_TYPE]               NVARCHAR (4000) NULL,
    [ORDER_TYPE_DB]            NVARCHAR (20)   NULL,
    [ORDER_NO]                 NVARCHAR (12)   NULL,
    [RELEASE_NO]               NVARCHAR (4)    NULL,
    [SEQUENCE_NO]              NVARCHAR (4)    NULL,
    [OPERATION_NO]             INT             NULL,
    [CONTRACT]                 NVARCHAR (5)    NULL,
    [PART_NO]                  NVARCHAR (25)   NULL,
    [OUTSIDE_QTY_SHIPPED]      INT             NULL,
    [PURCH_ORDER_NO]           NVARCHAR (12)   NULL,
    [PURCH_LINE_NO]            NVARCHAR (4)    NULL,
    [PURCH_RELEASE_NO]         NVARCHAR (4)    NULL,
    [PURCH_RECEIPT_NO]         INT             NULL,
    [INVOICE_NO]               NVARCHAR (50)   NULL,
    [VENDOR_NO]                NVARCHAR (20)   NULL,
    [TRANSACTION_CODE]         NVARCHAR (30)   NULL,
    [MODIFY_DATE_APPLIED_DATE] DATETIME2 (7)   NULL,
    [MODIFY_DATE_APPLIED_USER] NVARCHAR (30)   NULL,
    [CLOCKING_SEQ]             INT             NULL,
    [USER_ID]                  NVARCHAR (30)   NULL,
    [CREW_SIZE]                INT             NULL,
    [REPORT_POINT_ID]          NVARCHAR (10)   NULL,
    [OBJID]                    NVARCHAR (4000) NULL,
    [OBJVERSION]               NVARCHAR (2000) NULL,
    [Eff_Date]                 DATE            NOT NULL,
    [End_Date]                 DATE            NULL,
    [ActInd]                   CHAR (1)        NULL,
    [IsDeleted]                CHAR (1)        NULL,
    [BatchID]                  BIGINT          NULL,
    [ProcessLogID]             BIGINT          NULL,
    CONSTRAINT [PK_OPERATION_HISTORY] PRIMARY KEY CLUSTERED ([TRANSACTION_ID] ASC, [Eff_Date] ASC) ON [DWH_IFS]
) ON [DWH_IFS];

