CREATE TABLE [IFS].[PAYMENT] (
    [COMPANY]                    NVARCHAR (20)   NOT NULL,
    [SERIES_ID]                  NVARCHAR (20)   NOT NULL,
    [PAYMENT_ID]                 INT             NOT NULL,
    [PAY_DATE]                   DATETIME2 (7)   NULL,
    [VOUCHER_DATE]               DATETIME2 (7)   NULL,
    [ACCOUNTING_YEAR]            INT             NULL,
    [ACCOUNTING_PERIOD]          INT             NULL,
    [YEAR_PERIOD_KEY]            INT             NULL,
    [VOUCHER_TYPE]               NVARCHAR (3)    NULL,
    [USER_GROUP]                 NVARCHAR (30)   NULL,
    [USERID]                     NVARCHAR (30)   NULL,
    [VOUCHER_NO]                 INT             NULL,
    [PAYMENT_TYPE_CODE]          NVARCHAR (4000) NULL,
    [PAYMENT_TYPE_CODE_DB]       NVARCHAR (20)   NULL,
    [IS_NOTE]                    NVARCHAR (4000) NULL,
    [PAYMENT_ROLLBACK_STATUS]    NVARCHAR (4000) NULL,
    [PAYMENT_ROLLBACK_STATUS_DB] NVARCHAR (20)   NULL,
    [REG_DATE]                   DATETIME2 (7)   NULL,
    [JOURNAL_NO]                 INT             NULL,
    [PAYMENT_LEDGER_TYPE]        NVARCHAR (4000) NULL,
    [PAYMENT_LEDGER_TYPE_DB]     NVARCHAR (20)   NULL,
    [PARENT_COMPANY]             NVARCHAR (20)   NULL,
    [PARENT_PAYMENT_ID]          INT             NULL,
    [PARENT_SERIES_ID]           NVARCHAR (20)   NULL,
    [SHORT_NAME]                 NVARCHAR (4000) NULL,
    [TAX_CURR_RATE]              DECIMAL (18, 6) NULL,
    [OBJID]                      NVARCHAR (4000) NULL,
    [OBJVERSION]                 NVARCHAR (2000) NULL,
    [Eff_Date]                   DATE            NOT NULL,
    [End_Date]                   DATE            NULL,
    [ActInd]                     CHAR (1)        NULL,
    [IsDeleted]                  CHAR (1)        NULL,
    [BatchID]                    BIGINT          NULL,
    [ProcessLogID]               BIGINT          NULL,
    CONSTRAINT [PK_PAYMENT] PRIMARY KEY CLUSTERED ([COMPANY] ASC, [SERIES_ID] ASC, [PAYMENT_ID] ASC, [Eff_Date] ASC) ON [DWH_IFS]
) ON [DWH_IFS];

