CREATE TABLE [IFS].[PURCHASE_ORDER_LINE](
	[ORDER_NO] [nvarchar](12) NOT NULL,
	[LINE_NO] [nvarchar](4) NOT NULL,
	[RELEASE_NO] [nvarchar](4) NOT NULL,
	[BLANKET_LINE] [int] NULL,
	[ADDITIONAL_COST_AMOUNT] [int] NULL,
	[BUY_QTY_DUE] [int] NULL,
	[BUY_UNIT_PRICE] [decimal](18, 2) NULL,
	[CLOSE_TOLERANCE] [int] NULL,
	[CONV_FACTOR] [int] NULL,
	[CURRENCY_RATE] [int] NULL,
	[DATE_ENTERED] [datetime2](7) NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[DISCOUNT] [int] NULL,
	[FBUY_UNIT_PRICE] [decimal](18, 2) NULL,
	[LAST_ACTIVITY_DATE] [datetime2](7) NULL,
	[NOTE_TEXT] [nvarchar](2000) NULL,
	[PLANNED_DELIVERY_DATE] [datetime2](7) NULL,
	[PROMISED_DELIVERY_DATE] [datetime2](7) NULL,
	[WANTED_DELIVERY_DATE] [datetime2](7) NULL,
	[NOTE_ID] [int] NULL,
	[PLANNED_RECEIPT_DATE] [datetime2](7) NULL,
	[CLOSE_CODE] [nvarchar](4000) NULL,
	[CLOSE_CODE_DB] [nvarchar](1) NULL,
	[PRE_ACCOUNTING_ID] [int] NULL,
	[CONTRACT] [nvarchar](5) NULL,
	[BUY_UNIT_MEAS] [nvarchar](10) NULL,
	[BLANKET_ORDER] [nvarchar](12) NULL,
	[PRICE_CONV_FACTOR] [int] NULL,
	[DEMAND_CODE] [nvarchar](4000) NULL,
	[DEMAND_CODE_DB] [nvarchar](3) NULL,
	[CURRENCY_CODE] [nvarchar](3) NULL,
	[INSPECTION_CODE] [nvarchar](20) NULL,
	[DELIVERY_CONTROL_CODE] [nvarchar](4) NULL,
	[LAST_ORD_CONF_REMINDER] [datetime2](7) NULL,
	[LAST_DELIVERY_REMINDER] [datetime2](7) NULL,
	[ORD_CONF_REM_NUM] [int] NULL,
	[DELIVERY_REM_NUM] [int] NULL,
	[ORD_CONF_REMINDER] [nvarchar](4000) NULL,
	[ORD_CONF_REMINDER_DB] [nvarchar](20) NULL,
	[DELIVERY_REMINDER] [nvarchar](4000) NULL,
	[DELIVERY_REMINDER_DB] [nvarchar](20) NULL,
	[REPLACES_ORDER_NO] [nvarchar](12) NULL,
	[REPLACES_LINE_NO] [nvarchar](4) NULL,
	[REPLACES_RELEASE_NO] [nvarchar](4) NULL,
	[REPLACES_RECEIPT_NO] [int] NULL,
	[RECEIVE_CASE] [nvarchar](4000) NULL,
	[RECEIVE_CASE_DB] [nvarchar](20) NULL,
	[PROCESS_TYPE] [nvarchar](3) NULL,
	[PURCHASE_PAYMENT_TYPE] [nvarchar](4000) NULL,
	[PURCHASE_PAYMENT_TYPE_DB] [nvarchar](20) NULL,
	[PROJECT_ID] [nvarchar](10) NULL,
	[ACTIVITY_SEQ] [int] NULL,
	[AUTOMATIC_INVOICE] [nvarchar](4000) NULL,
	[AUTOMATIC_INVOICE_DB] [nvarchar](20) NULL,
	[DEMAND_OPERATION_NO] [nvarchar](12) NULL,
	[DEMAND_ORDER_CODE] [nvarchar](1) NULL,
	[DEMAND_ORDER_NO] [nvarchar](12) NULL,
	[DEMAND_ORDER_TYPE] [nvarchar](3) NULL,
	[DEMAND_RELEASE] [nvarchar](12) NULL,
	[DEMAND_SEQUENCE_NO] [nvarchar](4) NULL,
	[CURRENCY_TYPE] [nvarchar](10) NULL,
	[DESPATCH_QTY] [int] NULL,
	[DESPATCH_DATE] [datetime2](7) NULL,
	[DELNOTE_NO] [nvarchar](50) NULL,
	[ASSORTMENT] [nvarchar](20) NULL,
	[TECHNICAL_COORDINATOR_ID] [nvarchar](20) NULL,
	[TAX_EXEMPT] [nvarchar](4000) NULL,
	[TAX_EXEMPT_DB] [nvarchar](5) NULL,
	[TAX_AMOUNT] [decimal](18, 2) NULL,
	[ORIGINAL_QTY] [int] NULL,
	[DEFECT_PART_KEY_REF] [nvarchar](60) NULL,
	[ADDR_FLAG] [nvarchar](4000) NULL,
	[ADDR_FLAG_DB] [nvarchar](20) NULL,
	[DEFAULT_ADDR_FLAG] [nvarchar](4000) NULL,
	[DEFAULT_ADDR_FLAG_DB] [nvarchar](20) NULL,
	[DESTINATION_ID] [nvarchar](30) NULL,
	[SHIP_VIA_CODE] [nvarchar](3) NULL,
	[DELIVERY_TERMS] [nvarchar](3) NULL,
	[ADDRESS_ID] [nvarchar](50) NULL,
	[COMPANY] [nvarchar](20) NULL,
	[FORWARDER_ID] [nvarchar](20) NULL,
	[PAY_TAX] [nvarchar](4000) NULL,
	[PAY_TAX_DB] [nvarchar](5) NULL,
	[INTERNAL_DEST_DESC] [nvarchar](2000) NULL,
	[PURCHASE_SITE] [nvarchar](5) NULL,
	[FREEZE_FLAG] [nvarchar](4000) NULL,
	[FREEZE_FLAG_DB] [nvarchar](20) NULL,
	[INVOICING_SUPPLIER] [nvarchar](20) NULL,
	[INTRASTAT_EXEMPT] [nvarchar](4000) NULL,
	[INTRASTAT_EXEMPT_DB] [nvarchar](20) NULL,
	[FEE_CODE] [nvarchar](20) NULL,
	[CANCEL_REASON] [nvarchar](10) NULL,
	[TAXABLE] [nvarchar](4000) NULL,
	[TAXABLE_DB] [nvarchar](5) NULL,
	[INVENTORY_PART] [nvarchar](4000) NULL,
	[INVENTORY_PART_DB] [nvarchar](20) NULL,
	[PART_NO] [nvarchar](25) NULL,
	[REQUISITION_NO] [nvarchar](12) NULL,
	[DEL_TERMS_LOCATION] [nvarchar](100) NULL,
	[OVER_DELIVERY_TOLERANCE] [int] NULL,
	[OBJID] [nvarchar](4000) NULL,
	[OBJVERSION] [nvarchar](2000) NULL,
	[OBJSTATE] [nvarchar](20) NULL,
	[OBJEVENTS] [nvarchar](4000) NULL,
	[STATE] [nvarchar](4000) NULL,
	[Eff_Date] [date] NOT NULL,
	[End_Date] [date] NULL,
	[ActInd] [char](1) NULL,
	[IsDeleted] [char](1) NULL,
	[BatchID] [bigint] NULL,
	[ProcessLogID] [bigint] NULL,
 CONSTRAINT [PK_PURCHASE_ORDER_LINE] PRIMARY KEY CLUSTERED 
(
	[ORDER_NO] ASC,
	[LINE_NO] ASC,
	[RELEASE_NO] ASC,
	[Eff_Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [DWH_IFS]
) ON [DWH_IFS]
GO


