CREATE TABLE [IFS].[PURCHASE_PART_SUPPLIER] (
    [CONTRACT]                    NVARCHAR (5)    NOT NULL,
    [PART_NO]                     NVARCHAR (25)   NOT NULL,
    [VENDOR_NO]                   NVARCHAR (20)   NOT NULL,
    [BUY_UNIT_MEAS]               NVARCHAR (10)   NULL,
    [CURRENCY_CODE]               NVARCHAR (3)    NULL,
    [INSPECTION_CODE]             NVARCHAR (20)   NULL,
    [NOTE_ID]                     INT             NULL,
    [STATUS_CODE]                 NVARCHAR (2)    NULL,
    [ADDITIONAL_COST_AMOUNT]      INT             NULL,
    [CONV_FACTOR]                 INT             NULL,
    [CUM_RCPTS_QTY]               INT             NULL,
    [DISCOUNT]                    INT             NULL,
    [INTERNAL_CONTROL_TIME]       INT             NULL,
    [LIST_PRICE]                  DECIMAL (18, 2) NULL,
    [MINIMUM_QTY]                 INT             NULL,
    [PRICE_CONV_FACTOR]           INT             NULL,
    [PRICE_UNIT_MEAS]             NVARCHAR (10)   NULL,
    [PRIMARY_VENDOR]              NVARCHAR (4000) NULL,
    [PRIMARY_VENDOR_DB]           NVARCHAR (1)    NULL,
    [SAMPLE_PERCENT]              INT             NULL,
    [SAMPLE_QTY]                  INT             NULL,
    [VENDOR_MANUF_LEADTIME]       INT             NULL,
    [VENDOR_PART_NO]              NVARCHAR (80)   NULL,
    [LEADTIME_AUTO]               NVARCHAR (4000) NULL,
    [LEADTIME_AUTO_DB]            NVARCHAR (1)    NULL,
    [RECEIVE_CASE]                NVARCHAR (4000) NULL,
    [RECEIVE_CASE_DB]             NVARCHAR (20)   NULL,
    [VENDOR_PART_DESCRIPTION]     NVARCHAR (200)  NULL,
    [STD_MULTIPLE_QTY]            INT             NULL,
    [DELIVERY_PATTERN_ID]         NVARCHAR (5)    NULL,
    [STANDARD_PACK_SIZE]          INT             NULL,
    [ASSORTMENT]                  NVARCHAR (20)   NULL,
    [SUPPLY_CONFIGURATION]        NVARCHAR (4000) NULL,
    [SUPPLY_CONFIGURATION_DB]     NVARCHAR (20)   NULL,
    [ORDERS_PRICE_OPTION]         NVARCHAR (4000) NULL,
    [ORDERS_PRICE_OPTION_DB]      NVARCHAR (20)   NULL,
    [CONTACT]                     NVARCHAR (100)  NULL,
    [WARRANTY_ID]                 INT             NULL,
    [EXTERNAL_SERVICE_ALLOWED]    NVARCHAR (4000) NULL,
    [EXTERNAL_SERVICE_ALLOWED_DB] NVARCHAR (5)    NULL,
    [PART_OWNERSHIP]              NVARCHAR (4000) NULL,
    [PART_OWNERSHIP_DB]           NVARCHAR (20)   NULL,
    [DIST_ORDER_RECEIPT_TYPE]     NVARCHAR (4000) NULL,
    [DIST_ORDER_RECEIPT_TYPE_DB]  NVARCHAR (20)   NULL,
    [DIST_ORDER_COORDINATOR]      NVARCHAR (20)   NULL,
    [MULTISITE_PLANNED_PART]      NVARCHAR (4000) NULL,
    [MULTISITE_PLANNED_PART_DB]   NVARCHAR (20)   NULL,
    [QUICK_REGISTERED_PART]       NVARCHAR (4000) NULL,
    [QUICK_REGISTERED_PART_DB]    NVARCHAR (20)   NULL,
    [FEE_CODE]                    NVARCHAR (20)   NULL,
    [PURCHASE_PAYMENT_TYPE]       NVARCHAR (4000) NULL,
    [PURCHASE_PAYMENT_TYPE_DB]    NVARCHAR (20)   NULL,
    [TEMPLATE_ID]                 NVARCHAR (5)    NULL,
    [QTY_CALC_ROUNDING]           INT             NULL,
    [GTIN_NO]                     NVARCHAR (35)   NULL,
    [C_CONSOLID_MAIN_PART]        NVARCHAR (10)   NULL,
    [C_CONSOLID_CHAR]             NVARCHAR (25)   NULL,
    [OBJID]                       NVARCHAR (4000) NULL,
    [OBJVERSION]                  NVARCHAR (2000) NULL,
    [Eff_Date]                    DATE            NOT NULL,
    [End_Date]                    DATE            NULL,
    [ActInd]                      CHAR (1)        NULL,
    [IsDeleted]                   CHAR (1)        NULL,
    [BatchID]                     BIGINT          NULL,
    [ProcessLogID]                BIGINT          NULL,
    CONSTRAINT [PK_PURCHASE_PART_SUPPLIER] PRIMARY KEY CLUSTERED ([PART_NO] ASC, [CONTRACT] ASC, [VENDOR_NO] ASC, [Eff_Date] ASC) ON [DWH_IFS]
) ON [DWH_IFS];







