CREATE TABLE [IFS].[PURCHASE_ORDER_LINE_ALL](
	[ORDER_NO] [nvarchar](12) NOT NULL,
	[LINE_NO] [nvarchar](4) NOT NULL,
	[RELEASE_NO] [nvarchar](4) NOT NULL,
	[BLANKET_ORDER] [nvarchar](12) NULL,
	[BLANKET_LINE] [int] NULL,
	[ASSORTMENT] [nvarchar](20) NULL,
	[BUYER_CODE] [nvarchar](4000) NULL,
	[BUY_UNIT_MEAS] [nvarchar](10) NULL,
	[CONTRACT] [nvarchar](5) NULL,
	[CURRENCY_CODE] [nvarchar](3) NULL,
	[DEMAND_OPERATION_NO] [nvarchar](12) NULL,
	[DEMAND_ORDER_CODE] [nvarchar](1) NULL,
	[DEMAND_ORDER_NO] [nvarchar](12) NULL,
	[DEMAND_ORDER_TYPE] [nvarchar](3) NULL,
	[DEMAND_RELEASE] [nvarchar](12) NULL,
	[DEMAND_SEQUENCE_NO] [nvarchar](4) NULL,
	[ENG_CHG_LEVEL] [nvarchar](2) NULL,
	[INSPECTION_CODE] [nvarchar](20) NULL,
	[NOTE_ID] [int] NULL,
	[ORDER_CODE] [nvarchar](3) NULL,
	[PART_NO] [nvarchar](25) NULL,
	[PRE_ACCOUNTING_ID] [int] NULL,
	[PRICE_UNIT_MEAS] [nvarchar](10) NULL,
	[QC_CODE] [nvarchar](20) NULL,
	[REQUISITION_NO] [nvarchar](12) NULL,
	[REQ_LINE] [nvarchar](4) NULL,
	[REQ_RELEASE] [nvarchar](4) NULL,
	[UNIT_MEAS] [nvarchar](10) NULL,
	[ADDITIONAL_COST_AMOUNT] [decimal](18, 2) NULL,
	[BUY_QTY_DUE] [int] NULL,
	[BUY_UNIT_PRICE] [decimal](18, 2) NULL,
	[CLOSE_CODE] [nvarchar](4000) NULL,
	[CLOSE_CODE_DB] [nvarchar](1) NULL,
	[CLOSE_TOLERANCE] [int] NULL,
	[CONV_FACTOR] [int] NULL,
	[CURRENCY_RATE] [int] NULL,
	[DATE_ENTERED] [datetime2](7) NULL,
	[DEMAND_CODE] [nvarchar](4000) NULL,
	[DEMAND_CODE_DB] [nvarchar](3) NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[DISCOUNT] [int] NULL,
	[FBUY_UNIT_PRICE] [decimal](18, 2) NULL,
	[LAST_ACTIVITY_DATE] [datetime2](7) NULL,
	[NOTE_TEXT] [nvarchar](2000) NULL,
	[ORIGINAL_QTY] [int] NULL,
	[PLANNED_DELIVERY_DATE] [datetime2](7) NULL,
	[PLANNED_RECEIPT_DATE] [datetime2](7) NULL,
	[PRICE_CONV_FACTOR] [int] NULL,
	[PROMISED_DELIVERY_DATE] [datetime2](7) NULL,
	[QTY_ON_ORDER] [int] NULL,
	[REVISED_QTY] [int] NULL,
	[SAMPLE_PERCENT] [decimal](18, 4) NULL,
	[SAMPLE_QTY] [int] NULL,
	[WANTED_DELIVERY_DATE] [datetime2](7) NULL,
	[DELIVERY_CONTROL_CODE] [nvarchar](4) NULL,
	[STAT_GRP] [nvarchar](4000) NULL,
	[HIDE_PRICE] [nvarchar](4000) NULL,
	[HIDE_PRICE_DB] [nvarchar](1) NULL,
	[VENDOR_NO] [nvarchar](20) NULL,
	[REPLACES_ORDER_NO] [nvarchar](12) NULL,
	[REPLACES_LINE_NO] [nvarchar](4) NULL,
	[REPLACES_RELEASE_NO] [nvarchar](4) NULL,
	[REPLACES_RECEIPT_NO] [int] NULL,
	[AUTHORIZE_CODE] [nvarchar](20) NULL,
	[DIM_QUALITY] [nvarchar](4000) NULL,
	[TYPE_DESIGNATION] [nvarchar](4000) NULL,
	[RECEIVE_CASE] [nvarchar](4000) NULL,
	[RECEIVE_CASE_DB] [nvarchar](20) NULL,
	[QTY_TO_INSPECT] [int] NULL,
	[PROCESS_TYPE] [nvarchar](3) NULL,
	[PROJECT_ID] [nvarchar](10) NULL,
	[ACTIVITY_SEQ] [int] NULL,
	[PURCHASE_PAYMENT_TYPE] [nvarchar](4000) NULL,
	[PURCHASE_PAYMENT_TYPE_DB] [nvarchar](20) NULL,
	[AUTOMATIC_INVOICE] [nvarchar](4000) NULL,
	[AUTOMATIC_INVOICE_DB] [nvarchar](20) NULL,
	[ORD_CONF_REMINDER] [nvarchar](4000) NULL,
	[ORD_CONF_REMINDER_DB] [nvarchar](20) NULL,
	[DELIVERY_REMINDER] [nvarchar](4000) NULL,
	[DELIVERY_REMINDER_DB] [nvarchar](20) NULL,
	[LAST_ORD_CONF_REMINDER] [datetime2](7) NULL,
	[LAST_DELIVERY_REMINDER] [datetime2](7) NULL,
	[ORD_CONF_REM_NUM] [int] NULL,
	[DELIVERY_REM_NUM] [int] NULL,
	[DESPATCH_QTY] [int] NULL,
	[DESPATCH_DATE] [datetime2](7) NULL,
	[DELNOTE_NO] [nvarchar](50) NULL,
	[TECHNICAL_COORDINATOR_ID] [nvarchar](20) NULL,
	[REQUISITIONER_CODE] [nvarchar](4000) NULL,
	[CONFIGURATION_ID] [nvarchar](50) NULL,
	[PURCHASE_MODIFIED] [nvarchar](4000) NULL,
	[PURCHASE_MODIFIED_DB] [nvarchar](10) NULL,
	[TAXABLE] [nvarchar](4000) NULL,
	[TAXABLE_DB] [nvarchar](5) NULL,
	[TAX_EXEMPT] [nvarchar](4000) NULL,
	[TAX_EXEMPT_DB] [nvarchar](5) NULL,
	[PAY_TAX] [nvarchar](4000) NULL,
	[PAY_TAX_DB] [nvarchar](5) NULL,
	[FEE_CODE] [nvarchar](20) NULL,
	[TAX_AMOUNT] [decimal](18, 2) NULL,
	[TAX_SHIP_ADDRESS] [nvarchar](4000) NULL,
	[CONDITION_CODE] [nvarchar](10) NULL,
	[SERIAL_NO] [nvarchar](50) NULL,
	[LOT_BATCH_NO] [nvarchar](20) NULL,
	[SERVICE_TYPE] [nvarchar](20) NULL,
	[IS_EXCHANGE_PART] [nvarchar](5) NULL,
	[ORIGINAL_PART_NO] [nvarchar](25) NULL,
	[PART_OWNERSHIP_DB] [nvarchar](20) NULL,
	[PART_OWNERSHIP] [nvarchar](4000) NULL,
	[OWNING_CUSTOMER_NO] [nvarchar](20) NULL,
	[CORE_DEPOSIT] [int] NULL,
	[CORE_DEPOSIT_BASE] [int] NULL,
	[EXCHANGE_ITEM_DB] [nvarchar](20) NULL,
	[EXCHANGE_ITEM] [nvarchar](4000) NULL,
	[DEFAULT_ADDR_FLAG] [nvarchar](20) NULL,
	[ADDRESS_ID] [nvarchar](50) NULL,
	[ADDR_FLAG] [nvarchar](20) NULL,
	[DESTINATION_ID] [nvarchar](30) NULL,
	[SHIP_VIA_CODE] [nvarchar](3) NULL,
	[DELIVERY_TERMS] [nvarchar](3) NULL,
	[FORWARDER_ID] [nvarchar](20) NULL,
	[REFERENCE_ID] [nvarchar](35) NULL,
	[DOCK_CODE] [nvarchar](35) NULL,
	[SUB_DOCK_CODE] [nvarchar](35) NULL,
	[LOCATION_NO] [nvarchar](35) NULL,
	[PURCHASE_SITE] [nvarchar](5) NULL,
	[MANUFACTURER_ID] [nvarchar](20) NULL,
	[MANUFACTURER_PART_NO] [nvarchar](80) NULL,
	[DELIVER_TO_CUSTOMER_NO] [nvarchar](20) NULL,
	[EAN_LOCATION_DEL_ADDR] [nvarchar](100) NULL,
	[INVOICING_SUPPLIER] [nvarchar](20) NULL,
	[INTRASTAT_EXEMPT] [nvarchar](4000) NULL,
	[INTRASTAT_EXEMPT_DB] [nvarchar](20) NULL,
	[INPUT_QTY] [int] NULL,
	[INPUT_UNIT_MEAS] [nvarchar](50) NULL,
	[INPUT_CONV_FACTOR] [int] NULL,
	[INPUT_VARIABLE_VALUES] [nvarchar](50) NULL,
	[OBJID] [nvarchar](4000) NULL,
	[OBJVERSION] [nvarchar](2000) NULL,
	[OBJSTATE] [nvarchar](20) NULL,
	[OBJEVENTS] [nvarchar](4000) NULL,
	[STATE] [nvarchar](4000) NULL,
	[CANCEL_REASON] [nvarchar](10) NULL,
	[ROWTYPE] [nvarchar](30) NULL,
	[OVER_DELIVERY_TOLERANCE] [int] NULL,
	[DEL_TERMS_LOCATION] [nvarchar](100) NULL,
	[INTERNAL_CONTROL_TIME] [int] NULL,
	[WEIGHT_NET] [decimal](18, 4) NULL,
	[VOLUME_NET] [decimal](18, 4) NULL,
	[Eff_Date] [date] NOT NULL,
	[End_Date] [date] NULL,
	[ActInd] [char](1) NULL,
	[IsDeleted] [char](1) NULL,
	[BatchID] [bigint] NULL,
	[ProcessLogID] [bigint] NULL,
 CONSTRAINT [PK_PURCHASE_ORDER_LINE_ALL] PRIMARY KEY CLUSTERED 
(
	[ORDER_NO] ASC,
	[LINE_NO] ASC,
	[RELEASE_NO] ASC,
	[Eff_Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [DWH_IFS]
) ON [DWH_IFS]
GO


