CREATE TABLE [IFS].[PURCHASE_RECEIPT] (
    [ORDER_NO]                NVARCHAR (12)   NOT NULL,
    [LINE_NO]                 NVARCHAR (4)    NOT NULL,
    [RELEASE_NO]              NVARCHAR (4)    NOT NULL,
    [RECEIPT_NO]              INT             NOT NULL,
    [RECEIPT_REFERENCE]       NVARCHAR (50)   NULL,
    [NOTE_TEXT]               NVARCHAR (2000) NULL,
    [QTY_ARRIVED]             INT             NULL,
    [QTY_INSPECTED]           INT             NULL,
    [QTY_TO_INSPECT]          INT             NULL,
    [ARRIVAL_DATE]            DATETIME2 (7)   NULL,
    [RECEIVER]                NVARCHAR (30)   NULL,
    [QTY_INVOICED]            INT             NULL,
    [QC_CODE]                 NVARCHAR (20)   NULL,
    [NO_OF_INSPECTIONS]       INT             NULL,
    [RECEIVE_CASE]            NVARCHAR (4000) NULL,
    [RECEIVE_CASE_DB]         NVARCHAR (20)   NULL,
    [QTY_CONSIGNMENT]         INT             NULL,
    [AUTOMATIC_INVOICE]       NVARCHAR (4000) NULL,
    [AUTOMATIC_INVOICE_DB]    NVARCHAR (20)   NULL,
    [NOTE_ID]                 INT             NULL,
    [PRINTED_ARRIVAL_FLAG]    NVARCHAR (4000) NULL,
    [PRINTED_ARRIVAL_FLAG_DB] NVARCHAR (1)    NULL,
    [PRINTED_RETURN_FLAG]     NVARCHAR (4000) NULL,
    [PRINTED_RETURN_FLAG_DB]  NVARCHAR (1)    NULL,
    [ADD_COST_INCLUDED]       NVARCHAR (4000) NULL,
    [ADD_COST_INCLUDED_DB]    NVARCHAR (10)   NULL,
    [APPROVED_DATE]           DATETIME2 (7)   NULL,
    [FINALLY_INVOICED_DATE]   DATETIME2 (7)   NULL,
    [AIRWAY_BILL_NO]          NVARCHAR (50)   NULL,
    [C_MRN]                   NVARCHAR (25)   NULL,
    [C_ATB]                   NVARCHAR (25)   NULL,
    [C_ATB_POSITION]          INT             NULL,
    [C_CMS_INBOUND_SENT]      NVARCHAR (5)    NULL,
    [C_DATE_INBOUND_SENT]     DATETIME2 (7)   NULL,
    [OBJID]                   NVARCHAR (4000) NULL,
    [OBJVERSION]              NVARCHAR (2000) NULL,
    [OBJSTATE]                NVARCHAR (20)   NULL,
    [OBJEVENTS]               NVARCHAR (4000) NULL,
    [STATE]                   NVARCHAR (4000) NULL,
    [Eff_Date]                DATE            NOT NULL,
    [End_Date]                DATE            NULL,
    [ActInd]                  CHAR (1)        NULL,
    [IsDeleted]               CHAR (1)        NULL,
    [BatchID]                 BIGINT          NULL,
    [ProcessLogID]            BIGINT          NULL,
    CONSTRAINT [PK_PURCHASE_RECEIPT] PRIMARY KEY CLUSTERED ([ORDER_NO] ASC, [LINE_NO] ASC, [RELEASE_NO] ASC, [RECEIPT_NO] ASC, [Eff_Date] ASC)
);

