
CREATE VIEW CL_MESSAGE_PLUS
AS

SELECT
  CAST('Unknown' AS NVARCHAR(50))						AS TYPE
  , CAST(-1 AS BIGINT)									AS MSG_ID
  , CAST('' AS NVARCHAR(9))								AS LPN
  , CAST('' AS NVARCHAR(12))							AS WAVE
  , CAST('' AS NVARCHAR(9))								AS ORDER_ID
  , CAST('' AS NVARCHAR(6))								AS DIVERT
  , CAST('' AS NVARCHAR(6))								AS WEIGHT
  , CAST('' AS NVARCHAR(10))							AS LINE_ITEM_ID
  , CAST('' AS NVARCHAR(10))							AS PICK_LOCATION
  , CAST('' AS NVARCHAR(14))							AS ITEM_NAME
  , CAST('' AS NVARCHAR(6))								AS QUANTITY
  , CAST('' AS NVARCHAR(8))								AS ILPN
  , CAST('' AS NVARCHAR(20))							AS PICKER
  , CAST('' AS NVARCHAR(20))							AS STATE
  , CAST('' AS DATETIME2(7))							AS CREATE_DATE

UNION ALL

SELECT
  CAST('Container Status' AS NVARCHAR(50))				AS TYPE
  , CAST(CM.MSG_ID AS BIGINT)							AS MSG_ID
  , CAST(SUBSTRING(CM.DATA,26,9) AS NVARCHAR(9))		AS LPN
  , CAST(SUBSTRING(CM.DATA,36,12) AS NVARCHAR(12))		AS WAVE
  , CAST(SUBSTRING(CM.DATA,47,9) AS NVARCHAR(9))		AS ORDER_ID
  , CAST(SUBSTRING(CM.DATA,56,6) AS NVARCHAR(6))		AS DIVERT
  , CAST(SUBSTRING(CM.DATA,62,6) AS NVARCHAR(6))		AS WEIGHT
  , NULL												AS LINE_ITEM_ID
  , NULL												AS PICK_LOCATION
  , NULL												AS ITEM_NAME
  , NULL												AS QUANTITY
  , NULL												AS ILPN
  , NULL												AS PICKER
  , CAST(SUBSTRING(CM.DATA,69,14) AS NVARCHAR(20))		AS STATE
  , CAST(CM.WHEN_CREATED AS DATETIME2(7))				AS CREATE_DATE
FROM MANH.CL_MESSAGE CM
WHERE CM.SOURCE_ID = 'Container Status'

UNION ALL

SELECT
  CAST('Line Item Status' AS NVARCHAR(50))				AS TYPE
  , CAST(CM.MSG_ID AS BIGINT)							AS MSG_ID
  , CAST(SUBSTRING(CM.DATA,27,9) AS NVARCHAR(9))		AS LPN
  , CAST(SUBSTRING(CM.DATA,36,12) AS NVARCHAR(12))		AS WAVE
  , CAST(SUBSTRING(CM.DATA,48,9) AS NVARCHAR(9))		AS ORDER_ID
  , NULL												AS DIVERT
  , NULL												AS WEIGHT
  , CAST(SUBSTRING(CM.DATA,57,10) AS NVARCHAR(10))		AS LINE_ITEM_ID
  , CAST(SUBSTRING(CM.DATA,87,10) AS NVARCHAR(10))		AS PICK_LOCATION
  , CAST(SUBSTRING(CM.DATA,97,14) AS NVARCHAR(14))		AS ITEM_NAME
  , CAST(SUBSTRING(CM.DATA,111,6) AS NVARCHAR(6))		AS QUANTITY
  , CAST(SUBSTRING(CM.DATA,117,8) AS NVARCHAR(8))		AS ILPN
  , CAST(SUBSTRING(CM.DATA,125,20) AS NVARCHAR(20))		AS PICKER
  , CAST(SUBSTRING(CM.DATA,67,20) AS NVARCHAR(20))		AS STATE
  , CAST(CM.WHEN_CREATED AS DATETIME2(7))				AS CREATE_DATE
FROM MANH.CL_MESSAGE CM
WHERE CM.SOURCE_ID = 'Line Item Status'