
CREATE VIEW dbo.ORDERS_SHIP_DATE
AS


-- Added Wave information I1802 0022
WITH CTE_IFS AS (
	SELECT 
		MAX(SUBSTRING(OL.TC_ORDER_LINE_ID, 1,11))	AS IFS_Order_ID
		, MAX(OL.WAVE_NBR)							AS Wave_Nbr
		, MAX(WP.CREATE_DATE_TIME)					AS Wave_Date
		, COUNT(DISTINCT LP.TC_LPN_ID)				AS Number_Of_Parcels
		, MAX(LP.TC_SHIPMENT_ID)					AS TC_SHIPMENT_ID
		, OL.ORDER_ID								AS ORDER_ID
	FROM			MANH.ORDERS OD
	INNER JOIN		DWH.MANH.ORDER_LINE_ITEM OL
	ON				OL.ORDER_ID = OD.ORDER_ID
	AND				OL.ActInd = 'Y'
	LEFT JOIN		DWH.MANH.LPN_OUTBOUND LP
	ON				LP.ORDER_ID = OL.ORDER_ID
	AND				LP.ActInd = 'Y'
	AND				LP.LPN_FACILITY_STATUS <> 99
	LEFT JOIN		DWH.MANH.WAVE_PARM WP
	ON				WP.WAVE_NBR = OL.WAVE_NBR
	AND				WP.ActInd = 'Y'
	GROUP BY 
		OL.ORDER_ID
)
, CTE_CAL AS (
	SELECT
	  CA.DateKey
	  , CA.FullDate
	  , CA.IndWorkday
	FROM		[$(Datamart)].DM.D_Calendar CA
	WHERE		CA.IsActual = 1
	AND			CA.IndWorkday = 1
), CTE_LATE AS(
	SELECT
		OD.TC_ORDER_ID
		, OD.ORDER_ID
		, OD.DSG_SHIP_VIA
		, CC.CARRIER_CODE
		, OD.CREATED_DTTM
		, CAST(DATEADD(minute, CAST(SUBSTRING(SC.MISC_FLAGS, 3, 2) AS INT),(DATEADD(HOUR, CAST(LEFT(SC.MISC_FLAGS, 2) AS INT), '00:00:00.000'))) AS TIME) AS CuttOff
		, (SELECT C1.FullDate FROM (
			SELECT
			  CC.FullDate
			  , RANK() OVER (ORDER BY CC.FullDate) AS RN
			FROM CTE_CAL CC
			WHERE CC.FullDate >= CAST(OD.CREATED_DTTM AS DATE)
			) C1 WHERE C1.RN = 
			CASE WHEN DATEDIFF(
				SECOND,DATEADD(minute, CAST(SUBSTRING(SC.MISC_FLAGS, 3, 2) AS INT)
				,DATEADD(HOUR, CAST(LEFT(SC.MISC_FLAGS, 2) AS INT)
				, CAST(CAST((SELECT C4.FullDate FROM (SELECT C3.FullDate, RANK() OVER (ORDER BY C3.FullDate) AS RN FROM CTE_CAL C3 WHERE C3.FullDate >= CAST(OD.CREATED_DTTM AS DATE) AND C3.IndWorkday = 1) C4 WHERE C4.RN = 1) AS DATE) AS DATETIME))
			),OD.CREATED_DTTM) > 0 
			THEN 1 ELSE 0 END + 
			CASE WHEN CC.CARRIER_CODE = 'LHFPLS' THEN 1 ELSE 0 END + 1) AS SHIPDATE3
	FROM			MANH.ORDERS OD
	INNER JOIN		DWH.MANH.SHIP_VIA SV 
	ON				SV.SHIP_VIA = OD.DSG_SHIP_VIA 
	AND				SV.ActInd = 'Y'
	LEFT JOIN		DWH.MANH.SYS_CODE SC 
	ON				SC.CODE_ID = OD.DSG_SHIP_VIA 
	AND				SC.REC_TYPE = 'C' 
	AND				SC.CODE_TYPE = 'CBC' 
	AND				SC.ActInd = 'Y'
	LEFT JOIN		DWH.MANH.CARRIER_CODE CC 
	ON				CC.CARRIER_ID = SV.CARRIER_ID 
	AND				CC.ActInd = 'Y'
	WHERE			OD.ORDER_TYPE='OF'
	AND				OD.IS_CANCELLED = 0
)

SELECT
  CAST(CL.TC_ORDER_ID AS NVARCHAR(50))	AS TC_Order_ID
  , CAST(CL.CREATED_DTTM AS DATETIME2)	AS Order_Create_Date
  , CAST(CL.CuttOff AS TIME)			AS Order_Cuttoff_Time
  , CAST(CI.Wave_Date AS DATETIME2)		AS Order_Wave_Date
  , CAST(CL.SHIPDATE3 AS DATE)			AS Order_Planned_Ship_Date
FROM			CTE_LATE CL
INNER JOIN		CTE_IFS CI
ON				CI.ORDER_ID = CL.ORDER_ID
/*
WITH CTE_CAL AS (
	SELECT
	  CA.DateKey
	  , CA.FullDate
	  , CA.IndWorkday
	FROM		Datamart.DM.D_Calendar CA
	WHERE		CA.IsActual = 1
	AND			CA.IndWorkday = 1
), CTE_LATE AS(
	SELECT
		OD.TC_ORDER_ID
		, OD.DSG_SHIP_VIA
		, CC.CARRIER_CODE
		, OD.CREATED_DTTM
		, (SELECT C1.FullDate FROM (
			SELECT
			  CC.FullDate
			  , RANK() OVER (ORDER BY CC.FullDate) AS RN
			FROM CTE_CAL CC
			WHERE CC.FullDate >= CAST(OD.CREATED_DTTM AS DATE)
			) C1 WHERE C1.RN = 
			CASE WHEN DATEDIFF(SECOND,DATEADD(minute, CAST(SUBSTRING(SC.MISC_FLAGS, 3, 2) AS INT),DATEADD(HOUR, CAST(LEFT(SC.MISC_FLAGS, 2) AS INT), CAST(CAST(OD.CREATED_DTTM AS DATE) AS DATETIME))),OD.CREATED_DTTM) > 0 
			THEN 1 ELSE 0 END + 
			CASE WHEN CC.CARRIER_CODE = 'LHFPLS' THEN 1 ELSE 0 END + 1) AS SHIPDATE3
	FROM			MANH.ORDERS OD
	INNER JOIN		DWH.MANH.SHIP_VIA SV 
	ON				SV.SHIP_VIA = OD.DSG_SHIP_VIA 
	AND				SV.ActInd = 'Y'
	LEFT JOIN		DWH.MANH.SYS_CODE SC 
	ON				SC.CODE_ID = OD.DSG_SHIP_VIA 
	AND				SC.REC_TYPE = 'C' 
	AND				SC.CODE_TYPE = 'CBC' 
	AND				SC.ActInd = 'Y'
	LEFT JOIN		DWH.MANH.CARRIER_CODE CC 
	ON				CC.CARRIER_ID = SV.CARRIER_ID 
	AND				CC.ActInd = 'Y'
	WHERE			OD.ORDER_TYPE='OF'
	AND				OD.IS_CANCELLED = 0
)

SELECT
  CAST(CL.TC_ORDER_ID AS NVARCHAR(50))	AS TC_Order_ID
  , CAST(CL.SHIPDATE3 AS DATE)			AS Order_Planned_Ship_Date
FROM CTE_LATE CL
*/